/* GENERATED by port/tools/gen_asm_stubs.py - do not edit. */
/* Link stubs for the public code labels of the historical TASM modules that no
 * translation (port/asm/<module>.c) owns yet. Each logs once and returns 0. */
#include "ke_stub.h"

/* m_0982c_0995c: owned by port/asm/m_0982c_0995c.c */

KE_ASM_STUB(measure_pit_channel0, "m_09f64_0a0d2")
KE_ASM_STUB(set_pit_channel0_reload, "m_09f64_0a0d2")
KE_ASM_STUB(pit_channel0_interrupt, "m_09f64_0a0d2")

/* m_0a284_0a51f: owned by port/asm/m_0a284_0a51f.c */

/* m_0a958_0a966: owned by port/asm/m_0a958_0a966.c */

/* m_11258_11494: owned by port/asm/m_11258_11494.c */

/* m_11494_11530: owned by port/asm/m_11494_11530.c */

KE_ASM_STUB(load_protracker_module, "m_11530_11df8")
KE_ASM_STUB(stop_protracker_module, "m_11530_11df8")

/* m_11df8_12288: owned by port/asm/m_11df8_12288.c */

KE_ASM_STUB(render_sprite_record_kind_5_entry, "m_12288_12680")
KE_ASM_STUB(render_sprite_record_kind_5_draw, "m_12288_12680")
KE_ASM_STUB(restore_sprite_background_record, "m_12288_12680")

/* m_12680_12683: owned by port/asm/m_12680_12683.c */

KE_ASM_STUB(render_sprite_record_kind_3_entry, "m_12684_1296e")
KE_ASM_STUB(render_sprite_record_kind_3_draw, "m_12684_1296e")
KE_ASM_STUB(restore_sprite_background_from_record, "m_12684_1296e")

/* m_12970_12973: owned by port/asm/m_12970_12973.c */

KE_ASM_STUB(render_transparent_sprite_record_entry, "m_12974_12a9c")
KE_ASM_STUB(draw_transparent_sprite_rows, "m_12974_12a9c")
KE_ASM_STUB(restore_sprite_rectangle, "m_12974_12a9c")

KE_ASM_STUB(process_sprite_update_list, "m_12a9c_12f30")
KE_ASM_STUB(process_sprite_update_list_entry, "m_12a9c_12f30")
KE_ASM_STUB(replay_sprite_update_list, "m_12a9c_12f30")
KE_ASM_STUB(replay_sprite_update_list_entry, "m_12a9c_12f30")
KE_ASM_STUB(draw_bob_sprite, "m_12a9c_12f30")
KE_ASM_STUB(draw_bob_sprite_entry, "m_12a9c_12f30")
KE_ASM_STUB(clip_and_dispatch_sprite_record, "m_12a9c_12f30")

KE_ASM_STUB(copy_chunky_scanline_to_vga, "m_12f30_12f9c")
KE_ASM_STUB(copy_chunky_scanline_to_vga_entry, "m_12f30_12f9c")

KE_ASM_STUB(copy_screen_span, "m_12f9c_13324")
KE_ASM_STUB(copy_screen_span_entry, "m_12f9c_13324")
KE_ASM_STUB(copy_clipped_screen_rectangle, "m_12f9c_13324")

KE_ASM_STUB(read_vga_pixel, "m_13324_13712")
KE_ASM_STUB(read_vga_pixel_entry, "m_13324_13712")
KE_ASM_STUB(write_vga_pixel, "m_13324_13712")
KE_ASM_STUB(write_vga_pixel_entry, "m_13324_13712")
KE_ASM_STUB(fill_vga_span, "m_13324_13712")
KE_ASM_STUB(fill_vga_span_entry, "m_13324_13712")
KE_ASM_STUB(fill_clipped_vga_rectangle, "m_13324_13712")

KE_ASM_STUB(fill_planar_video_rows, "m_13712_137a8")

/* m_137a8_13944: owned by port/asm/m_137a8_13944.c */

/* m_13944_13a48: owned by port/asm/m_13944_13a48.c */

/* m_13a48_13a95: owned by port/asm/m_13a48_13a95.c */

