/* TU f_4085..f_4ce1 [0x4085, 0x4cf2): generated by tools/tu.py */
#include <string.h>
typedef struct { int at_00, at_04, at_08, at_0c, at_10, at_14, at_18, at_1c; int at_20, at_24, at_28, at_2c, at_30, at_34, at_38, at_3c; int at_40, at_44, at_48, at_4c, at_50, at_54, at_58, at_5c; int at_60, at_64, at_68, at_6c, at_70, at_74, at_78; } State;
typedef struct { unsigned char b[18]; } Rec12;
typedef struct { unsigned char b[40]; } Rec28;
typedef struct { int value, pad; } Pair8;
typedef struct { int v[4]; } Row16;
extern State *g_dee4;
extern unsigned char g_e142;
extern unsigned char *g_dda4;
extern unsigned char *g_e2ec;
extern int g_ddbc;
extern int g_ddc0;
extern int g_ddb8;
extern int g_df34;
extern int g_e24c;
extern int g_e250;
extern int g_e22c;
extern int g_e230;
extern int g_8db4;
extern void (*g_8db8)(void);
extern int g_8e20;
extern int *g_dddc;
extern unsigned char g_a990[];
extern void (*g_6160[])(void);
void f_8004(int *, int);
int f_b17e(void *, void *);
int f_b5df(void *, void *);
void f_4291(void);
extern short g_7474;
extern int *g_60f0[];
void f_c20d(int);
extern unsigned char *g_de5c;
void f_4394(void);
void f_5771(void);
extern short g_e4c4;
extern short g_e4c6;
void f_10502(int, int);
void f_4602(void);
extern char g_5ec0[];
void f_7e62(int, int, int, int, int, int, int);
extern void f_8fce(int, int);
extern void f_13a48(void *, int, int, int);
extern void f_9053(void);
extern void f_58b0(void);
extern int g_ddac;
extern int g_dda8;
extern Rec12 *g_ddb4;
extern Rec12 g_df78[];
extern int g_8e1c;
extern int g_8e24;
extern void *g_ddd4;
extern int g_ddc4;
extern int g_ddcc;
extern Rec28 *g_dd94;
extern Rec28 g_a848[];
extern int f_592c(void);
extern void f_1085a(int);
extern void f_a574(int);
extern void f_c3ab(void);
extern void f_6a1d(unsigned char, int, int, int);
extern void f_6327(void);
extern void f_1040c(int, int);
extern void f_10487(int, int);
extern int g_dee0;
extern int g_e4d0;
extern int g_67b0;
extern int g_e270;
extern int g_df3c;
extern int g_8e48;
extern int g_e4c8;
extern int g_dd40;
extern int g_df24;
extern int g_df2c;
extern int g_df20;
extern int g_dd48;
extern int g_dd4c;
extern int g_ddc8;
extern short g_747c;
extern unsigned short g_7c00;
extern unsigned short g_7bfe;
extern Row16 g_6cbb[];
extern int g_68f8;
extern int g_6940;
extern int g_6944;
extern int g_6948;
extern int g_694c;
extern int g_6958;
extern int g_695c;
extern int g_6960;
extern int g_6964;
extern int g_8dc8;
extern int g_8ddc;
extern Pair8 g_6218[];

void f_4085(void)
{
    int unused;

    g_e24c = g_dee4->at_00;
    g_e250 = g_dee4->at_04;
    f_8004(&g_e24c, g_dee4->at_78);
    g_dda4 = g_a990;
    for (g_ddbc = 0; g_ddbc < g_ddc0; ++g_ddbc) {
        *(int *)g_dda4 = *(int *)g_dda4;
        ++*(int *)(g_dda4 + 4);
        if (g_e142 != 0)
            ++*(int *)(g_dda4 + 4);
        g_8db4 = f_b17e(g_dda4 + 8, g_dda4 + 0xc) + g_df34;
        if (*(int *)g_dda4 > 0x140 || *(int *)g_dda4 < 0 ||
            *(int *)(g_dda4 + 4) > 0xd8 || *(int *)(g_dda4 + 4) < 0) {
            f_4291();
            continue;
        }
        if (*(int *)(g_dda4 + 4) < 0xc3) {
            g_e22c = *(int *)g_dda4;
            g_e230 = *(int *)(g_dda4 + 4);
            f_8004(&g_e22c, g_8db4);
            if (f_b5df(&g_e24c, &g_e22c) != 0) {
                g_ddb8 = ((unsigned char *)g_dda4)[0x10] + 1;
                g_8e20 = ((unsigned char *)g_dda4)[0x11];
                if (g_8e20 >= 0x1c)
                    g_8e20 -= 0x1c;
                g_8db8 = g_6160[g_8e20];
                g_8db8();
                g_dddc[5] += 2 << g_dee4->at_24;
                f_4291();
                continue;
            }
        }
        *(int *)g_e2ec = g_8db4;
        *(short *)(g_e2ec + 4) = *(short *)g_dda4;
        *(short *)(g_e2ec + 6) = *(short *)(g_dda4 + 4);
        *(short *)(g_e2ec + 8) = 0;
        g_e2ec += 0xa;
        g_dda4 += 0x12;
    }
}

void f_4291(void)
{
    --g_ddc0;
    if (g_ddbc != g_ddc0)
        memcpy((void *)g_dda4, (void *)(g_dda4 + 0x12), (g_ddc0 - g_ddbc) * 0x12);
    --g_ddbc;
}

void f_42e1(unsigned char a, unsigned char b, int c, int d)
{
    if (g_ddc0 < 0x18 && a < 0x1c) {
        g_dda4 = g_a990;
        g_dda4 += g_ddc0 * 0x12;
        if (g_7474 == -1)
            g_ddc0 = 0x1388;
        *(int *)g_dda4 = c;
        *(int *)(g_dda4 + 4) = d;
        *(int *)(g_dda4 + 0xc) = (int)g_60f0[a];
        *(int *)(g_dda4 + 8) = 0;
        *(unsigned char *)(g_dda4 + 0x10) = b;
        *(unsigned char *)(g_dda4 + 0x11) = a;
        f_c20d(0x1e);
        ++g_ddc0;
    }
}

void f_4394(void)
{
    if (g_ddb8 > 0)
        f_c20d(0x29);
    *g_de5c |= 0x20;
    g_dee4->at_58 = 3;
    g_8e20 = g_dee4->at_1c + g_ddb8;
    if (g_8e20 > 12) g_8e20 = 12;
    if (g_8e20 < 0) g_8e20 = 0;
    g_dee4->at_5c = g_8e20;
}

void f_4413(void)
{
    int b;
    int a;
    if (g_dee4->at_28 > 0) a = 1; else a = 0;
    if ((*g_de5c & 8) == 0) b = 1; else b = 0;
    if (b | a) {
        f_c20d(0x27);
        if (--g_dee4->at_28 < 0)
            f_5771();
    }
}

void f_4480(void)
{
    f_c20d(0x4c);
    g_dee4->at_24 += g_ddb8;
}

void f_44a9(void)
{
    f_c20d(0x5b);
    if ((*g_de5c & 8) == 0) {
        if ((*g_de5c & 0x10) == 0) {
            *g_de5c |= 0x10;
            g_dee4->at_00 = g_dee4->at_10 + g_dee4->at_0c - g_e4c6;
            g_dee4->at_04 = g_e4c4;
            f_10502(g_dee4->at_00, g_dee4->at_04);
            g_dee4->at_38 = g_ddb8 << 6;
        } else {
            g_dee4->at_38 += g_ddb8 << 6;
        }
    }
}

void f_4551(void)
{
    g_ddb8 = -g_ddb8;
    f_4602();
}

void f_456d(void)
{
    f_c20d(0x1f);
    f_7e62(0, 0, 0, 0, g_df34, (int)g_5ec0, 13);
}

void f_45a6(void)
{
    f_c20d(0x3c);
    g_dddc[1] += g_ddb8 * 0x71;
}

void f_45d0(void) {
    f_c20d(0x3c);
    f_8fce(g_dee4->at_00, g_dee4->at_04);
}

void f_4602(void) {
    f_c20d(0x5c);
    g_ddb4 = g_df78;
    for (g_ddac = 0; g_ddac < g_dda8; ++g_ddac) {
        g_8e20 = g_ddb4->b[0x10] + g_ddb8;
        if (g_8e20 > 5) g_8e20 = 5;
        if (g_8e20 < 0) g_8e20 = 0;
        g_ddb4->b[0x10] = (unsigned char)g_8e20;
        ++g_ddb4;
    }
}

void f_469b(void) {
    f_c20d(0x56);
    g_de5c[1] |= 8;
    f_13a48(g_ddd4, 0, 0x100, 0x20);
    g_dee4->at_30 += g_ddb8 << 7;
}

void f_46e7(void) {
    f_c20d(0x4c);
    g_8e1c = 3;
    g_ddb4 = g_df78;
    for (g_ddac = 0; g_ddac < g_dda8; ++g_ddac) {
        f_9053();
        g_ddb4++;
    }
}

void f_4745(void) {
    g_ddb8 = -g_ddb8;
    f_46e7();
}

void f_4761(void) {
    f_c20d(0x33);
    g_de5c[1] &= 0xfe;
    g_de5c[0] |= 8;
    g_dee4->at_34 = g_ddb8 << 10;
    g_de5c[1] &= 0xfe;
    if (g_de5c[0] & 0x10) {
        g_de5c[0] &= 0xef;
        g_dee4->at_00 = g_dee4->at_10 + g_dee4->at_0c - (short)g_e4c6;
        g_dee4->at_04 = (short)g_e4c4;
        f_10502(g_dee4->at_00, g_dee4->at_04);
    }
}

void f_4802(void) {
    f_c20d(0x68);
    if (!(g_de5c[1] & 4)) {
        g_dee4->at_04 = g_dee4->at_18;
        g_de5c[1] |= 4;
        f_58b0();
    }
}

void f_4847(void) {
    f_c20d(0x5b);
    if (!(g_de5c[0] & 8)) {
        g_de5c[1] |= 1;
        g_dee4->at_3c += g_ddb8 << 5;
    }
}

void f_4886(void) {
    f_c20d(0x3c);
    if (!g_dee4->at_28) {
        g_dee4->at_44 = 0;
        g_dee4->at_40 = 3;
    }
    g_dee4->at_28 += g_ddb8;
}

void f_48d2(void) {
    f_c20d(0x3c);
    g_de5c[0] |= 0x80;
    g_dee4->at_60 = 0xf;
    g_dee4->at_64 = 0xf;
    g_dee4->at_68 = 1;
    g_dee4->at_6c = 2;
    g_dee4->at_70 = -2;
}

void f_4931(void) {
    f_c20d(0x3c);
    g_de5c[1] |= 0x10;
}

void f_4955(void) {
    f_c20d(0x67);
    g_de5c[1] |= 0x20;
    g_dee4->at_2c += g_ddb8 << 9;
    g_ddb4 = g_df78;
    for (g_ddac = 0; g_ddac < g_dda8; ++g_ddac) {
        g_ddb4->b[0x11] |= 2;
        ++g_ddb4;
    }
}

void f_49c7(void) {
    f_c20d(0x1f);
    g_de5c[1] |= 2;
    g_dee4->at_74 = g_dee4->at_00;
}

void f_49fb(void) {
    f_c20d(0x3c);
    g_de5c[0] |= 0x80;
    g_dee4->at_60 = 0xf;
    g_dee4->at_64 = 0xf;
    g_dee4->at_68 = 5;
    g_dee4->at_6c = 2;
    g_dee4->at_70 = -2;
}

void f_4a5a(void) {
    g_8e20 = (g_8e24 >> 2) & 0x1f;
    if (g_8e20 < 0x1c) {
    } else {
        g_8e20 -= 0x1c;
    }
    if (g_8e20 == 1) g_8e20 = 0xf;
    if (g_8e20 == 0x15) g_8e20 = 0x13;
    g_8db8 = g_6160[g_8e20];
    g_8db8();
}

void f_4aca(void) {
    f_c20d(0x28);
    g_ddb8 = -g_ddb8;
    f_4394();
}

void f_4af0(void) {
    f_c20d(0x3c);
    g_de5c[0] |= 0x80;
    g_dee4->at_60 = 4;
    g_dee4->at_64 = 4;
    g_dee4->at_68 = 1;
    g_dee4->at_6c = 0;
    g_dee4->at_70 = -5;
}

void f_4b4f(void) {
    f_c20d(0x3c);
    g_de5c[0] |= 0x80;
    g_dee4->at_60 = 6;
    g_dee4->at_64 = 6;
    g_dee4->at_68 = 1;
    g_dee4->at_6c = 1;
    g_dee4->at_70 = -4;
}

void f_4bae(void) {
    f_c20d(0x3c);
    g_de5c[0] |= 0x80;
    g_dee4->at_60 = 4;
    g_dee4->at_64 = 4;
    g_dee4->at_68 = 5;
    g_dee4->at_6c = 0;
    g_dee4->at_70 = -5;
}

void f_4c0d(void) {
    f_c20d(0x3c);
    g_de5c[0] |= 0x80;
    g_dee4->at_60 = 6;
    g_dee4->at_64 = 6;
    g_dee4->at_68 = 3;
    g_dee4->at_6c = 1;
    g_dee4->at_70 = -4;
}

void f_4c6c(void) {
    f_c20d(0x57);
    g_dd94 = g_a848;
    for (g_ddc4 = 0; g_ddc4 < g_ddcc; ++g_ddc4) {
        g_dd94->b[0x24] |= 2;
        *(int *)&g_dd94->b[0x20] = 0;
        ++g_dd94;
    }
}

void f_4cd0(void) { }

void f_4ce1(void) {
}

/* Owned _DATA: animation/frame records (284 32-bit values). */
int g_5c7c = 0;
int g_5c80[284] = {
    9634, 127, 0, -1, 9990, 127,
    0, -1, 10496, 127, 0, -1,
    10830, 127, 0, -1, 11956, 127,
    0, -1, 12260, 127, 0, -1,
    12558, 127, 0, -1, 12670, 127,
    0, -1, 12870, 127, 0, -1,
    13018, 127, 0, -1, 13308, 127,
    0, -1, 13502, 127, 0, -1,
    13882, 127, 0, -1, 14104, 127,
    0, -1, 15452, 127, 0, -1,
    16358, 127, 0, -1, 20076, 127,
    0, -1, 20562, 127, 0, -1,
    21010, 127, 0, -1, 21374, 127,
    0, -1, 2, 0, 150, 0,
    326, 0, 560, 0, 858, 0,
    1268, 0, 0, -6, 1802, 0,
    1950, 0, 2126, 0, 2360, 0,
    2658, 0, 3068, 0, 0, -6,
    3602, 0, 3750, 0, 3926, 0,
    4160, 0, 4458, 0, 4868, 0,
    0, -6, 5402, 3, 5522, 3,
    5692, 3, 5898, 3, 6158, 3,
    6484, 3, 6158, 3, 5898, 3,
    5692, 3, 5522, 3, 0, -10,
    6876, 10, 7116, 10, 7352, 10,
    7632, 10, 7922, 10, 0, -5,
    8236, 4, 8334, 4, 0, -2,
    14334, 8, 14716, 8, 15072, 8,
    0, -3, 15766, 4, 16000, 4,
    0, -2, 16802, 6, 17132, 6,
    17466, 6, 17790, 6, 18108, 6,
    17790, 6, 17466, 6, 17132, 6,
    0, -8, 18418, 5, 18718, 5,
    19034, 5, 19368, 5, 19716, 5,
    19368, 5, 19034, 5, 18718, 5,
    0, -8, 21600, 5, 21882, 5,
    22180, 5, 22496, 5, 22826, 5,
    22496, 5, 22180, 5, 21882, 5,
    0, -8, 11124, 10, 11540, 10,
    0, -2, 23168, 6, 23426, 6,
    23686, 6, 23936, 6, 24170, 6,
    23936, 6, 23686, 6, 23426, 6,
    0, -8, 24402, 3, 24936, 3,
    25490, 3, 0, -3, 26048, 3,
    26152, 3, 26302, 3, 26468, 3,
    26684, 3, 26958, 3, 26684, 3,
    26468, 3, 26302, 3, 26152, 3,
    0, -10
};

/* 28 state animation records, each pointing into g_5c80. */
int *g_60f0[28] = {
    g_5c80 + 194, g_5c80 + 64, g_5c80 + 56, g_5c80 + 162,
    g_5c80 + 236, g_5c80 + 76, g_5c80 + 12, g_5c80 + 48,
    g_5c80 + 176, g_5c80 + 0, g_5c80 + 72, g_5c80 + 68,
    g_5c80 + 60, g_5c80 + 170, g_5c80 + 20, g_5c80 + 4,
    g_5c80 + 40, g_5c80 + 230, g_5c80 + 16, g_5c80 + 52,
    g_5c80 + 44, g_5c80 + 8, g_5c80 + 212, g_5c80 + 24,
    g_5c80 + 32, g_5c80 + 28, g_5c80 + 36, g_5c80 + 254
};

/* State action dispatch table, in index order. */
void (*g_6160[28])(void) = {
    f_4394, f_4413, f_4480, f_44a9,
    f_4551, f_456d, f_45a6, f_45d0,
    f_4602, f_469b, f_46e7, f_4745,
    f_4761, f_4802, f_4847, f_4886,
    f_48d2, f_4931, f_4955, f_49c7,
    f_49fb, f_4a5a, f_4aca, f_4af0,
    f_4b4f, f_4bae, f_4c0d, f_4c6c
};
