/* TU f_5f71..f_95ee [0x5f71, 0x963b): generated by tools/tu.py */
#include <string.h>
typedef struct { int at_00, at_04, at_08, at_0c, at_10, at_14, at_18, at_1c; int at_20, at_24, at_28, at_2c, at_30, at_34, at_38, at_3c; int at_40, at_44, at_48, at_4c, at_50, at_54, at_58, at_5c; int at_60, at_64, at_68, at_6c, at_70, at_74, at_78; } State;
typedef struct { unsigned char b[18]; } Rec12;
typedef struct { int at_00, at_04, at_08, at_0c, at_10, at_14, at_18, at_1c, at_20; unsigned char flags, tail[3]; } Rec28;
typedef struct { int value, pad; } Pair8;
typedef struct { int v[4]; } Row16;
typedef struct { int pad[5]; int at_14; } Rec20;
typedef struct { unsigned char : 2; unsigned char f : 6; } BF1_2_6;
typedef struct { unsigned char b[2]; } S2;
typedef unsigned int size_t;
typedef struct { unsigned f : 2; } BF4_0_2;
typedef struct { int a, b, c; short d; int e; } S18;
struct Frame { unsigned img; int time; };
struct Spr { int a, b, c, d; int e; int speed; struct Frame *f; unsigned b0 : 1, anim : 4, f5 : 1, f6 : 1, f7 : 1, f8 : 1; };
struct Iter24 { int first, second, start, count, step, unused; };
struct Iter48 { int pad0, pad4, box, pad12, pad16; char *at20; int pad24, pad28, pad32, pad36, pad40, pad44; };
struct f85a4_edge { unsigned char active; unsigned char result; int x; int y; };
struct f85a4_local { struct f85a4_edge rows[4]; };
extern void f_c20d(int);
extern void f_8fce(int, int);
extern void f_13a48(void *, int, int, int);
extern void f_9053(void);
extern void f_10502(int, int);
extern void f_58b0(void);
extern void f_4394(void);
extern int f_592c(void);
extern void f_1085a(int);
extern void f_a574(int);
extern void f_c3ab(void);
extern void f_6a1d(unsigned char, int, int, int);
extern void f_6327(void);
void f_8066(int *rect, unsigned char *info);
extern int f_b17e(int *, int *);
void f_8004(int *rect, unsigned char *info);
extern int f_b5df(void *, void *);
extern void f_4413(void);
extern void f_42e1(unsigned char, unsigned char, int, int);
extern void f_7e62(int, int, int, int, int, int, int);
extern int f_dd01();
typedef struct { unsigned b0:1, b1:1, b2:1; } Flags;
extern unsigned char g_5ef0[];
extern unsigned char g_5e6c[];
extern unsigned char *g_388a;
extern unsigned char *g_38fe;
extern int g_7c08;
extern int g_dda4;
extern int g_ddbc;
extern int g_ddc0;
extern char g_a990[];
extern char g_e13a;
extern unsigned char g_e13b, g_e46b;
#define DDA4 ((unsigned char *)g_dda4)
#define DDB4 ((unsigned char *)g_ddb4)

/* Initialized tables reconstructed from obj3. */
Pair8 g_61d0[9] = {
    { 2, 4 }, { 172, 4 }, { 378, 4 }, { 638, 4 },
    { 964, 4 }, { 1356, 4 }, { 2018, 4 }, { 2316, 4 },
    { 0, -8 },
};
Pair8 g_6218[14] = {
    { 2662, 0 }, { 3046, 0 }, { 3482, 0 }, { 3972, 0 },
    { 4512, 0 }, { 5102, 0 }, { 5754, 0 }, { 6466, 0 },
    { 7238, 0 }, { 8082, 0 }, { 8974, 0 }, { 9926, 0 },
    { 10964, 0 }, { 0, -13 },
};
Pair8 g_6288[14] = {
    { 12036, 0 }, { 12036, 0 }, { 12530, 0 }, { 12530, 0 },
    { 13202, 0 }, { 13202, 0 }, { 13976, 0 }, { 13976, 0 },
    { 15072, 0 }, { 15072, 0 }, { 16254, 0 }, { 16254, 0 },
    { 17558, 0 }, { 0, -13 },
};
Pair8 g_62f8[14] = {
    { 18958, 0 }, { 18958, 0 }, { 19470, 0 }, { 19470, 0 },
    { 20118, 0 }, { 20118, 0 }, { 20894, 0 }, { 20894, 0 },
    { 21782, 0 }, { 21782, 0 }, { 22870, 0 }, { 22870, 0 },
    { 24086, 0 }, { 0, -13 },
};
Pair8 g_6368[2] = {
    { 25398, 0 }, { 25516, 0 },
};
Pair8 g_6378[12] = {
    { 25660, 0 }, { 25832, 0 }, { 26038, 0 }, { 26286, 0 },
    { 26604, 0 }, { 26966, 0 }, { 27368, 0 }, { 27818, 0 },
    { 28310, 0 }, { 28830, 0 }, { 29388, 0 }, { 0, -13 },
};
Pair8 g_63d8[119] = {
    { 1356, 4 }, { 964, 4 }, { 638, 4 }, { 378, 4 },
    { 172, 4 }, { 2, 4 }, { 0, -6 }, { 31592, 5 },
    { 31956, 5 }, { 32320, 5 }, { 32684, 5 }, { 33048, 5 },
    { 33412, 5 }, { 33776, 5 }, { 34140, 5 }, { 34504, 5 },
    { 34868, 5 }, { 35232, 5 }, { 35596, 5 }, { 35596, 5 },
    { 35596, 5 }, { 35596, 5 }, { 35596, 5 }, { 35596, 5 },
    { 35596, 5 }, { 35596, 5 }, { 35232, 5 }, { 34868, 5 },
    { 34504, 5 }, { 34140, 5 }, { 33776, 5 }, { 33412, 5 },
    { 33048, 5 }, { 32684, 5 }, { 32320, 5 }, { 31956, 5 },
    { 31592, 5 }, { 0, -30 }, { 31592, 2 }, { 31956, 2 },
    { 32320, 2 }, { 32684, 2 }, { 33048, 2 }, { 33412, 2 },
    { 33776, 2 }, { 34140, 2 }, { 34504, 2 }, { 34868, 2 },
    { 35232, 2 }, { 35596, 2 }, { 35596, 2 }, { 35596, 2 },
    { 35596, 2 }, { 35596, 2 }, { 35596, 2 }, { 35596, 2 },
    { 35596, 2 }, { 35232, 2 }, { 34868, 2 }, { 34504, 2 },
    { 34140, 2 }, { 33776, 2 }, { 33412, 2 }, { 33048, 2 },
    { 32684, 2 }, { 32320, 2 }, { 31956, 2 }, { 31592, 2 },
    { 0, -30 }, { 2, 6 }, { 1240, 6 }, { 0, -2 },
    { 2664, 15 }, { 3316, 15 }, { 4102, 15 }, { 3316, 15 },
    { 0, -4 }, { 4758, 3 }, { 4758, 3 }, { 4758, 3 },
    { 4758, 3 }, { 5404, 3 }, { 6192, 3 }, { 35960, 3 },
    { 37020, 3 }, { 35960, 3 }, { 6192, 3 }, { 5404, 3 },
    { 0, -11 }, { 7124, 8 }, { 7636, 8 }, { 8152, 8 },
    { 0, -3 }, { 8698, 15 }, { 9498, 15 }, { 10262, 15 },
    { 9498, 15 }, { 0, -4 }, { 11070, 10 }, { 11548, 10 },
    { 11990, 10 }, { 11548, 10 }, { 0, -4 }, { 12468, 10 },
    { 12958, 10 }, { 13460, 10 }, { 13940, 10 }, { 14374, 10 },
    { 14842, 10 }, { 0, -6 }, { 15318, 10 }, { 15848, 10 },
    { 16262, 10 }, { 16792, 10 }, { 17206, 10 }, { 17736, 10 },
    { 18150, 10 }, { 18680, 10 }, { 0, -8 },
};
Pair8 *g_6790[8] = {
    &g_63d8[69], &g_63d8[72], &g_63d8[77], &g_63d8[89], &g_63d8[93], &g_63d8[98], &g_63d8[103], &g_63d8[110]
};
int g_67b0 = 0;
Pair8 g_67b4[21] = {
    { 2, 3 }, { 96, 3 }, { 276, 3 }, { 478, 3 },
    { 774, 3 }, { 1094, 3 }, { 1486, 3 }, { 1956, 3 },
    { 2518, 3 }, { 3206, 3 }, { 3934, 3 }, { 4702, 3 },
    { 5470, 3 }, { 6238, 3 }, { 7054, 3 }, { 7874, 3 },
    { 8700, 3 }, { 9502, 3 }, { 10296, 3 }, { 11056, 3 },
    { 11806, 3 },
};
int g_685c = 0;
int g_6860 = -21;
Pair8 g_6864[3] = {
    { 13112, 4 }, { 13480, 4 }, { 0, -2 },
};
Pair8 g_687c[1] = {
    { 12500, 4 },
};
Row16 g_6884[7] = {
    { 12500, 4, 0, -2 },
    { 200, 8, 3, 100 },
    { 250, 10, 4, 100 },
    { 275, 12, 4, 95 },
    { 300, 13, 5, 90 },
    { 325, 14, 5, 85 },
    { 350, 16, 5, 75 },
};
int g_68f4 = 0;

void f_5f71(int, int, int, int);
extern void f_5aaf(void);
extern void f_1040c(int, int);
extern void f_10487(int, int);
extern State *g_dee4;
extern char *g_dee0;
extern unsigned char *g_e2ec;
extern unsigned char *g_de5c;
extern int g_ddac;
extern int g_dda8;
extern int g_ddb8;
extern int g_e4d0;
extern int g_67b0;
extern int g_e270;
extern int g_df3c;
extern int g_8e48;
extern char *g_df2c;
extern int g_e4c8;
extern unsigned char *g_dd40;
extern int g_df24;
extern char *g_df34;
extern int g_df20;
extern int g_dd48;
extern unsigned char *g_dd4c;
extern int g_ddc8;
extern int g_df40;
extern int g_e24c[];
extern int g_e250;
extern int g_e22c[];
extern int g_e230;
extern int g_e23c[];
extern int g_e240;
extern int g_e244;
extern int g_e248;
extern unsigned char g_e142;
extern unsigned char g_e143;
extern int g_dd78;
extern int g_ddd0;
extern unsigned char g_ddb0[];
extern int g_dd9c;
extern int g_8e04;
extern unsigned char g_8e10[];
extern Pair8 *g_6790[];
extern unsigned char g_a988[];
extern unsigned char *g_dddc;
extern short g_747c;
extern unsigned short g_7c00;
extern unsigned short g_7bfe;
extern Row16 g_6cbb[];
extern int g_68f8;
extern int g_6940;
extern int g_6944;
extern int g_6948;
extern int g_694c;
extern int g_6958;
extern int g_695c;
extern int g_6960;
extern int g_6964;
extern char *g_ddb4;
extern char g_df78[];
extern int g_8e1c;
extern int g_8e20;
extern int g_8e24;
extern int g_8dc8;
extern int g_8ddc;
extern int (*g_8db8)(void);
extern int (*g_6160[])(void);
extern void *g_ddd4;
extern int g_ddc4;
extern int g_ddcc;
extern Rec28 *g_dd94;
extern Rec28 g_a848[];
extern short g_e4c6;
extern short g_e4c4;
void f_6156(void);
void f_61a6(void);
extern unsigned char g_25ec[];
extern unsigned char g_5e68[];
extern unsigned char g_6098[];
extern int g_8db4;
extern unsigned char g_a518[];
extern unsigned char g_a608[];
extern unsigned g_dd50;
extern int g_dd60;
extern int g_dd64;
extern int g_dd68;
extern int g_dd70;
extern S2 *g_dd80;
extern unsigned char *g_dd90;
extern int g_dda0;
extern int g_e254;
extern int g_e258;
extern void f_3918(int, int, int, int);
extern void f_3ac0(int, int, int);
extern void f_3e0f(int, int);
extern void f_69cd(void);
extern void f_c26a(int, int);
void *memcpy(void *, const void *, size_t);
extern short g_742c;
extern short g_746c;
extern short g_7b14;
extern short g_7b18;
extern short g_7b20;
extern short g_7b22;
extern short g_7b34;
extern int g_7c08;
extern int g_9468;
extern int g_9470;
extern int g_947c;
extern int g_9484;
extern int g_9490;
extern int g_94a8;
extern unsigned char g_ab40[];
extern unsigned char g_bf40[];
extern unsigned char g_d340[];
extern int g_e35a;
extern int g_e37a;
extern unsigned char g_e48b;
extern unsigned char g_e48e;
extern void f_111de(unsigned, unsigned);
extern void f_12f9c(int, int, int, int, int);
extern void f_13b72(void);
extern void f_6e13(void);
extern int f_6e2e(void);
extern int f_6ee8(void);
extern void f_6f66(void);
extern void f_7032(void);
extern void f_704d(void);
extern void f_7068(void);
extern void f_7112(void);
extern void f_7184(void);
extern void f_73c0(void);
extern void f_7532(void);
extern void f_798c(void);
extern void f_7bd5(void);
extern void f_9d40(unsigned char);
extern void f_a810(void *, int);
extern void f_c8c0(int, int, short, int, int);
extern void f_c9ce(int, int);
extern int f_dd53(int, int);
extern void f_ea9f(void *, int, int, int);
extern void f_ed38(void);
extern int g_7b0c;
extern void f_ec76(void *);
extern unsigned char g_e13e;
extern unsigned char g_e13b;
extern unsigned char g_e46b;
extern int g_94a0;
extern int g_94a4;
extern int g_9494;
extern int g_94ac;
extern int g_946c;
extern int g_948c;
extern int g_949c;
extern int g_94b4;
extern int g_9498;
extern int g_9474;
extern int g_e36a;
extern int g_e366;
extern short g_7b24;
extern short g_7b26;
extern short g_7b16;
extern short g_7b1a;
extern short g_e4a8;
extern short g_e4c2;
extern void f_10369(void);
extern void f_103b9(void);
void f_80d8(void);
void f_843a(void);
extern unsigned char g_91ac[];
extern unsigned char f_13324(int, int);
extern int g_9488;
extern int g_9480;
extern int g_94b0;
extern int g_dd84;
extern int g_dd88;
extern char *g_9478;
extern struct Spr *g_dd6c;
extern void f_7551(void);
extern void f_7bf4(void);
extern void f_85a4(void);
extern void f_100fa(int, int, int, int);
extern void f_10137(void);
void *memmove(void *, const void *, size_t);
void f_788d(void);
void f_7e12(void);
void f_8585(void);
void f_8f7e(void);
extern short g_e4ba;
extern short g_e4bc;
extern int f_135e8(int, int, int, int, int, int);
extern int g_68f4;
extern void f_78dd(int, int, int, int, int, int, int);
extern unsigned char g_8e4c[];
extern int f_b76c(S18, int, int, S18, int, int, int, int, int, int);
extern struct Spr g_94b8[];
extern int g_df38;
extern unsigned char *g_ddd8;
extern int g_2e9c[];
extern void f_12cbd(unsigned char *, int, int);
extern unsigned char *g_e158;
extern short g_e15c;
extern short g_e15e;
extern short g_e160;
extern short g_e162;
extern struct Iter24 *g_e150;
extern int g_e148;
extern int g_e14c;
extern int g_e154;
void f_95ee(void);
void f_82cc(void);
void f_8345(void);
void f_83b1(void);
extern unsigned char g_7b36;
extern int g_ddc0;
extern unsigned char g_e48d;
extern unsigned char g_e48f;
extern short g_7b3d;
extern int g_e1b8;
extern short g_e1bc;
extern short g_e1c0;
extern unsigned char g_5dc0[];
extern unsigned char g_5df8[];
extern unsigned char g_5e30[];
extern int g_dd58;
extern int g_dd5c;
extern int g_e234;
extern int g_e238;
extern int g_e25c[];
extern int g_e260;
extern short g_e4b0;
extern short g_e4b4;
extern int f_91a3(int, int);

void f_4cf2(void)
{
    int *v_4;
    int *v_8;
    int v_c;
    v_4 = (int *)(g_388a + 4);
    v_8 = (int *)g_38fe;
    v_c = (*(v_4 - 1));
    g_dee4->at_08 = g_dee4->at_00;
    if (g_de5c[0] & 2) {
    if (--g_dee4->at_50 <= 0) {
    g_dee4->at_50 = 4;
    if ((g_dee4->at_1c + 8) <= ++g_dee4->at_54) {
    if (v_c) {
L_4d74:;
    v_c = (v_c ^ (*v_4++));
    if (v_4 < v_8) goto L_4d74;
    if (v_c) {
    v_c = 0;
    g_7c08 = 0;
    g_dda8 = 5000;
    }
    }
L_4da9:;
    g_de5c[0] &= 0xfd;
    f_10502(g_dee4->at_00, g_dee4->at_04);
    }
    }
    } else {
    if (g_de5c[0] & 1) {
    if (--g_dee4->at_48 <= 0) {
    g_dee4->at_48 = 4;
    g_dee4->at_4c++;
    g_8e20 = (g_dee4->at_4c - 12);
    if (g_8e20 >= 0) {
    if (((Pair8 *)((unsigned char *)g_63d8 + 4))[g_8e20].value < 0) {
    g_dee4->at_4c--;
    g_e13a = 255;
    } else {
    g_de5c[1] &= 0xfe;
    g_de5c[1] &= 0xfb;
    g_de5c[0] &= 0xbf;
    }
    }
    }
    } else {
    if (g_de5c[0] & 0x20) {
    if (--g_dee4->at_58 == 0) {
    g_dee4->at_58 = 3;
    if (g_dee4->at_1c > g_dee4->at_5c) {
    g_dee4->at_1c--;
    f_57fa();
    } else {
    if (g_dee4->at_1c < g_dee4->at_5c) {
    g_dee4->at_1c++;
    f_57fa();
    } else {
    g_de5c[0] &= 0xdf;
    }
    }
    }
    }
L_4ec7:;
    if (g_de5c[1] & 8) {
    g_8e20 = --g_dee4->at_30;
    if (g_8e20 < 32) {
    f_13a48(g_ddd4, 0, 256, g_8e20);
    }
L_4f06:;
    if (g_8e20 <= 0) {
    g_de5c[1] &= 0xf7;
    }
    }
L_4f18:;
    if (g_de5c[1] & 0x20) {
    if (--g_dee4->at_2c <= 0) {
    g_de5c[1] &= 0xdf;
    g_ddb4 = g_df78;
    g_ddac = 0;
L_4f4e:;
    for (; g_ddac < g_dda8; g_ddac++) {
    if ((*(int *)(DDB4 + 4)) > 2432) {
    DDB4[0x11] &= 0xfd;
    }
L_4f7c:;
    (*(unsigned char **)&g_ddb4) += 18;
    }
    }
    }
L_4f85:;
    if (g_e13b) {
    if (g_de5c[1] & 1) goto L_5377;
    } else {
    if (!(g_de5c[0] & 8)) goto L_5241;
    if (--g_dee4->at_34 <= 0) {
    g_de5c[0] &= 0xf7;
    g_de5c[0] &= 0xfb;
    f_10502(g_dee4->at_00, g_dee4->at_04);
    } else {
    if (g_dee4->at_34 < 140) {
    ((Flags *)g_de5c)->b2 = (g_dee4->at_34 >> 3) & 1;
    }
    }
    }
L_501a:;
    g_8e20 = 0;
    g_ddb4 = g_df78;
    g_ddac = 0;
L_5038:;
    for (; g_ddac < g_dda8; g_ddac++) {
    if (!(DDB4[0x11] & 1)) {
    if ((*(int *)(DDB4 + 4)) > g_8e20) goto L_506c;
    }
    goto L_508b;
L_506c:;
    g_8e20 = ((int)(*(int *)(DDB4 + 4)) >> (int)4);
    g_8e1c = ((int)(*(int *)DDB4) >> (int)4);
L_508b:;
    (*(unsigned char **)&g_ddb4) += 18;
    }
L_5094:;
    g_ddb4 = g_df78;
    if ((*(int *)(DDB4 + 0xc)) < 0) {
    g_dda4 = (int)g_a990;
    g_ddbc = 0;
L_50c1:;
    for (; g_ddbc < g_ddc0; g_ddbc++) {
    unsigned char v_10;
    v_10 = DDA4[0x11];
    if (v_10 >= 11) {
    if (v_10 <= 11) goto L_5128;
    if (v_10 >= 18) {
    if (v_10 <= 18) goto L_5128;
    if (v_10 == 22) goto L_5128;
    goto L_512a;
    }
L_5106:;
    if (v_10 == 14) goto L_5128;
    goto L_512a;
    } else {
    if (v_10 >= 3) {
    if (v_10 <= 4) goto L_5128;
    if (v_10 == 9) goto L_5128;
    goto L_512a;
    } else {
    if (v_10 != 1) goto L_512a;
    }
    }
L_5128:;
    goto L_5153;
L_512a:;
    if ((*(int *)(DDA4 + 4)) > g_8e20) {
    g_8e20 = (*(int *)(DDA4 + 4));
    g_8e1c = (*(int *)DDA4);
    }
L_5153:;
    g_dda4 += 18;
    }
    }
L_515f:;
    if (g_dee4->at_04 < 188) {
    g_dee4->at_04 += 5;
    if (g_dee4->at_04 > 188) {
    g_dee4->at_04 = 188;
    }
    }
L_5190:;
    if (g_dee4->at_00 < g_8e1c) {
    g_dee4->at_00 += 8;
    if (g_dee4->at_00 > g_8e1c) {
    g_dee4->at_00 = g_8e1c;
    }
    } else {
    if (g_dee4->at_00 > g_8e1c) {
    g_dee4->at_00 -= 8;
    if (g_dee4->at_00 < g_8e1c) {
    g_dee4->at_00 = g_8e1c;
    }
    }
    }
L_51f8:;
    if (g_dee4->at_00 < g_dee4->at_0c) {
    g_dee4->at_00 = g_dee4->at_0c;
    }
L_521a:;
    if (g_dee4->at_00 > g_dee4->at_10) {
    g_dee4->at_00 = g_dee4->at_10;
    }
    goto L_5377;
L_5241:;
    if (g_de5c[1] & 1) {
    if (--g_dee4->at_3c <= 0) {
    g_de5c[1] &= 0xfe;
    f_10502(g_dee4->at_00, g_dee4->at_04);
    }
    } else {
    if (g_de5c[0] & 0x10) {
    if (--g_dee4->at_38 <= 0) {
    g_de5c[0] &= 0xef;
    g_de5c[0] &= 0xfb;
    g_dee4->at_00 = ((g_dee4->at_10 + g_dee4->at_0c) - (short)g_e4c6);
    g_dee4->at_04 = (short)g_e4c4;
    f_10502(g_dee4->at_00, g_dee4->at_04);
    } else {
    g_dee4->at_00 = ((g_dee4->at_10 + g_dee4->at_0c) - (short)g_e4c6);
    g_dee4->at_04 = (short)g_e4c4;
    if (g_dee4->at_38 < 32) {
    ((Flags *)g_de5c)->b2 = (g_dee4->at_38 >> 2) & 1;
    }
    }
    } else {
    g_dee4->at_00 = (short)g_e4c6;
    g_dee4->at_04 = (short)g_e4c4;
    }
    }
    }
    }
L_5377:;
    f_5381();
}

void f_5381(void)
{
    if ((*(unsigned char *)(g_de5c + 1) & 2) == 0) goto L_53e3;
    *(int *)g_e2ec = (int)(g_dee0 + 0x7536);
    *(short *)(g_e2ec + 4) = *(short *)((unsigned char *)(unsigned char *)g_dee4 + 0x74);
    *(short *)(g_e2ec + 6) = *(short *)((unsigned char *)(unsigned char *)g_dee4 + 4);
    *(short *)(g_e2ec + 8) = 0;
    g_e2ec += 0xa;
L_53e3:;
    if ((*(unsigned char *)g_de5c & 1) == 0) goto L_542d;
    g_8e20 = *(int *)((unsigned char *)(unsigned char *)g_dee4 + 0x4c);
    if (g_8e20 >= 0xc) goto L_5415;
    g_8e20 = 0xc - g_8e20;
    goto L_5478;
L_5415:;
    g_8dc8 = *(int *)((unsigned char *)g_6378 + (g_8e20 << 3));
    goto L_54aa;
L_542d:;
    if ((*(unsigned char *)g_de5c & 2) == 0) goto L_546b;
    g_8e20 = *(int *)((unsigned char *)(unsigned char *)g_dee4 + 0x54);
    if (g_8e20 < 8) goto L_5456;
    g_8e20 -= 8;
    goto L_5478;
L_5456:;
    g_8dc8 = *(int *)((unsigned char *)g_61d0 + (g_8e20 << 3));
    goto L_54aa;
L_546b:;
    g_8e20 = *(int *)((unsigned char *)(unsigned char *)g_dee4 + 0x1c);
L_5478:;
    if ((*(unsigned char *)g_de5c & 0x80) == 0) goto L_5497;
    g_8dc8 = *(int *)((unsigned char *)g_6288 + (g_8e20 << 3));
    goto L_54aa;
L_5497:;
    g_8dc8 = *(int *)((unsigned char *)g_6218 + (g_8e20 << 3));
L_54aa:;
    if ((*(unsigned char *)g_de5c & 4) != 0) goto L_5703;
    *(int *)g_e2ec = (int)(g_8dc8 + g_dee0);
    *(short *)(g_e2ec + 4) = *(short *)g_dee4;
    *(short *)(g_e2ec + 6) = *(short *)((unsigned char *)(unsigned char *)g_dee4 + 4);
    *(short *)(g_e2ec + 8) = 0;
    g_e2ec += 0xa;
    *(int *)((unsigned char *)(unsigned char *)g_dee4 + 0x78) = *(int *)(g_e2ec + -0xa);
    if ((*(unsigned char *)g_de5c & 0x40) == 0) goto L_557c;
    g_8ddc = *(int *)((unsigned char *)g_6368 + (g_8e20 << 3));
    *(int *)g_e2ec = (int)(g_8ddc + g_dee0);
    *(short *)(g_e2ec + 4) = *(short *)g_dee4;
    *(short *)(g_e2ec + 6) = *(short *)((unsigned char *)(unsigned char *)g_dee4 + 4);
    *(short *)(g_e2ec + 8) = 0;
    g_e2ec += 0xa;
L_557c:;
    if ((*(unsigned char *)(g_de5c + 1) & 4) == 0) goto L_55ea;
    g_8ddc = *(int *)(g_5ef0 + (((g_8e24 >> 2) & 1) << 3));
    *(int *)g_e2ec = (int)(g_df34 + g_8ddc);
    *(short *)(g_e2ec + 4) = *(short *)g_dee4;
    *(short *)(g_e2ec + 6) = *(short *)((unsigned char *)(unsigned char *)g_dee4 + 4);
    *(short *)(g_e2ec + 8) = 0;
    g_e2ec += 0xa;
L_55ea:;
    if (*(int *)((unsigned char *)(unsigned char *)g_dee4 + 0x28) > 0) goto L_55ff;
    if ((*(unsigned char *)g_de5c & 8) == 0) goto L_5609;
L_55ff:;
    if ((*(unsigned char *)g_de5c & 1) == 0) goto L_560e;
L_5609:;
    goto L_5703;
L_560e:;
    if (--*(int *)((unsigned char *)(unsigned char *)g_dee4 + 0x40) > 0) goto L_5670;
    g_8e1c = *(int *)(g_5e6c + (++*(int *)((unsigned char *)(unsigned char *)g_dee4 + 0x44) << 3));
    if (g_8e1c >= 0) goto L_5662;
    *(int *)((unsigned char *)(unsigned char *)g_dee4 + 0x44) += g_8e1c;
    g_8e1c = *(int *)(g_5e6c + (*(int *)((unsigned char *)(unsigned char *)g_dee4 + 0x44) << 3));
L_5662:;
    *(int *)((unsigned char *)(unsigned char *)g_dee4 + 0x40) = g_8e1c;
L_5670:;
    if (*(int *)((unsigned char *)(unsigned char *)g_dee4 + 0x28) != 1) goto L_5693;
    g_8ddc = *(int *)(g_5e68 + (*(int *)((unsigned char *)(unsigned char *)g_dee4 + 0x44) << 3));
    goto L_56a9;
L_5693:;
    g_8ddc = *(int *)(g_6098 + (*(int *)((unsigned char *)(unsigned char *)g_dee4 + 0x44) << 3));
L_56a9:;
    *(int *)g_e2ec = (int)(g_8ddc + g_df34);
    *(short *)(g_e2ec + 4) = (unsigned short)((*(int *)g_dee4 - (*(int *)((unsigned char *)(unsigned char *)g_dee4 + 0x20) >> 1)) + 4);
    *(short *)(g_e2ec + 6) = *(short *)((unsigned char *)(unsigned char *)g_dee4 + 4);
    *(short *)(g_e2ec + 8) = 0;
    g_e2ec += 0xa;
L_5703:;
    if ((*(unsigned char *)(g_de5c + 1) & 1) == 0) goto L_576c;
    g_8ddc = *(int *)((unsigned char *)g_62f8 + (g_8e20 << 3));
    *(int *)g_e2ec = (int)(g_8ddc + g_dee0);
    *(short *)(g_e2ec + 4) = *(short *)g_dee4;
    *(short *)(g_e2ec + 6) = *(short *)((unsigned char *)(unsigned char *)g_dee4 + 4);
    *(short *)(g_e2ec + 8) = 0;
    g_e2ec += 0xa;
L_576c:;
}

void f_5771(void) {
    if (!(g_de5c[0] & 1)) {
        f_c20d(0xb);
        g_de5c[0] |= 1;
        g_dee4->at_48 = 4;
        g_dee4->at_4c = 0xd - g_dee4->at_1c;
    }
}

void f_57bf(void) {
    f_c20d(0x26);
    g_de5c[0] |= 2;
    g_dee4->at_50 = 4;
    g_dee4->at_54 = 0;
}

void f_57fa(void) {
    g_dee4->at_20 = f_592c() - 2;
    g_8e20 = g_dee4->at_20 >> 1;
    g_dee4->at_0c = g_8e20 + 0x10;
    g_dee4->at_10 = 0x130 - g_8e20;
    f_1040c(g_dee4->at_0c, g_dee4->at_10);
    g_8e20 = g_dee4->at_00;
    if (g_de5c[0] & 0x10)
        g_8e20 = g_dee4->at_10 + g_dee4->at_0c - g_8e20;
    f_10502(g_8e20, g_e4c4);
}

void f_58b0(void) {
    if (g_de5c[1] & 4) g_8e20 = 0x18;
    else g_8e20 = 0xbc;
    g_dee4->at_14 = g_8e20;
    g_dee4->at_18 = 0xbc;
    f_10487(g_dee4->at_14, g_dee4->at_18);
    f_10502(g_e4c6, g_dee4->at_04);
}

int f_592c(void) {
    char *address;
    address = g_dee0 + g_6218[g_dee4->at_1c].value;
    return *(short *)(address + 2);
}

void f_5966(void)
{
    if (g_e142 == 0) goto L_59a4;
    if ((g_dd78 - g_ddcc) <= 0) goto L_5a9c;
    g_8e20 = 0x16;
    *(int *)g_8e10 = (int)&g_63d8[38];
    goto L_59b8;
L_59a4:;
    g_8e20 = 0x37;
    *(int *)g_8e10 = (int)&g_63d8[7];
L_59b8:;
    if (g_ddd0 != g_8e20) goto L_59e6;
    f_7e62(0x90, 0x10, 0, 0, (int)g_df2c, *(int *)g_8e10, 1);
L_59e6:;
    --g_ddd0;
    if (g_ddd0 > 0) goto L_5a9c;
    g_ddd0 = *(int *)g_ddb0;
    if (g_dd9c < 8) goto L_5a13;
    g_dd9c -= 8;
L_5a13:;
    g_8e04 = *(unsigned char *)(g_a988 + g_dd9c++);
    if (g_e142 == 0) goto L_5a6b;
    g_8e04 = f_dd01() & 7;
    f_42e1(1, 0, 0xa0, 0x20);
    if (g_8e04 != 5) goto L_5a6b;
    g_8e04 = 0;
L_5a6b:;
    if ((unsigned)g_8e04 <= 7) goto L_5a7e;
    g_8e04 = 7;
L_5a7e:;
    f_5f71(0xa0, 0x10, (unsigned)f_dd01() >> 7, g_8e04);
L_5a9c:;
    if (g_ddcc == 0) goto L_5aaa;
    f_5aaf();
L_5aaa:;
}

void f_5aaf(void)
{
    *(int *)g_e24c = *(int *)g_dee4;
    g_e250 = *(int *)((unsigned char *)(unsigned char *)g_dee4 + 4);
    f_8066(g_e24c, (unsigned char *)*(int *)((unsigned char *)(unsigned char *)g_dee4 + 0x78));
    *(int *)g_e22c = *(int *)((unsigned char *)(unsigned char *)g_dee4 + 0x74);
    g_e230 = *(int *)((unsigned char *)(unsigned char *)g_dee4 + 4);
    f_8066(g_e22c, (unsigned char *)(g_dee0 + 0x7536));
    g_dd94 = g_a848;
    g_ddc4 = 0;
L_5b31:;
    if (g_ddc4 < g_ddcc) goto L_5b4b;
    return;
L_5b43:;
    ++g_ddc4;
    goto L_5b31;
L_5b4b:;
    *(int *)g_dd94 += *(int *)(((unsigned char *)g_dd94 + 8));
    *(int *)(((unsigned char *)g_dd94 + 4)) += *(int *)(((unsigned char *)g_dd94 + 0xc));
    if (--*(int *)(((unsigned char *)g_dd94 + 0x14)) > 0) goto L_5bf1;
    *(int *)(((unsigned char *)g_dd94 + 0x14)) = (unsigned)f_dd01() >> 7;
    if ((*(signed char *)&g_8e24 & 0x20) == 0) goto L_5bad;
    *(int *)(((unsigned char *)g_dd94 + 8)) = -*(int *)(((unsigned char *)g_dd94 + 8));
    goto L_5bc8;
L_5bad:;
    if ((*(signed char *)&g_8e24 & 8) == 0) goto L_5bc8;
    *(int *)(((unsigned char *)g_dd94 + 0xc)) = -*(int *)(((unsigned char *)g_dd94 + 0xc));
L_5bc8:;
    if (g_e142 == 0) goto L_5bf1;
    f_42e1(1, 0, *(int *)g_dd94, *(int *)(((unsigned char *)g_dd94 + 4)));
L_5bf1:;
    *(int *)(((unsigned char *)g_dd94 + 0x10)) = (int)(g_df2c + f_b17e(((unsigned char *)g_dd94 + 0x18), ((unsigned char *)g_dd94 + 0x1c)));
    *(int *)g_e23c = *(int *)g_dd94;
    g_e240 = *(int *)(((unsigned char *)g_dd94 + 4));
    f_8004(g_e23c, (void *)*(int *)(((unsigned char *)g_dd94 + 0x10)));
    if ((*(unsigned char *)(((unsigned char *)g_dd94 + 0x24)) & 2) == 0) goto L_5c64;
    if (*(int *)(((unsigned char *)g_dd94 + 0x20)) <= 0) goto L_5d86;
L_5c64:;
    if (*(int *)g_e23c > 0x10) goto L_5c8a;
    if (*(int *)(((unsigned char *)g_dd94 + 8)) >= 0) goto L_5c8a;
    *(int *)(((unsigned char *)g_dd94 + 8)) = -*(int *)(((unsigned char *)g_dd94 + 8));
L_5c8a:;
    if (g_e244 < 0x130) goto L_5cb3;
    if (*(int *)(((unsigned char *)g_dd94 + 8)) <= 0) goto L_5cb3;
    *(int *)(((unsigned char *)g_dd94 + 8)) = -*(int *)(((unsigned char *)g_dd94 + 8));
L_5cb3:;
    if (g_e240 > 0x18) goto L_5cd9;
    if (*(int *)(((unsigned char *)g_dd94 + 0xc)) >= 0) goto L_5cd9;
    *(int *)(((unsigned char *)g_dd94 + 0xc)) = -*(int *)(((unsigned char *)g_dd94 + 0xc));
L_5cd9:;
    if (g_e142 == 0) goto L_5cee;
    g_8e04 = 0x98;
    goto L_5cf8;
L_5cee:;
    g_8e04 = 0xc8;
L_5cf8:;
    if ((unsigned)g_e248 < g_8e04) goto L_5d22;
    if (*(int *)(((unsigned char *)g_dd94 + 0xc)) <= 0) goto L_5d22;
    *(int *)(((unsigned char *)g_dd94 + 0xc)) = -*(int *)(((unsigned char *)g_dd94 + 0xc));
L_5d22:;
    if (f_b5df(g_e24c, g_e23c) == 0) goto L_5d63;
    if ((*(unsigned char *)(((unsigned char *)g_dd94 + 0x24)) & 1) == 0) goto L_5d61;
    if ((*(unsigned char *)g_de5c & 8) != 0) goto L_5d54;
    f_4413();
L_5d54:;
    if (*(int *)((unsigned char *)(unsigned char *)g_dee4 + 0x28) >= 0) goto L_5d86;
    goto L_5d63;
L_5d61:;
    goto L_5d86;
L_5d63:;
    if ((*(unsigned char *)(g_de5c + 1) & 2) == 0) goto L_5dd5;
    if (f_b5df(g_e22c, g_e23c) == 0) goto L_5dd5;
L_5d86:;
    f_7e62((*(int *)g_e23c + g_e244) >> 1, ((g_e240 + g_e248) + 0xa) >> 1, *(int *)(((unsigned char *)g_dd94 + 8)), *(int *)(((unsigned char *)g_dd94 + 0xc)), (int)g_df2c, (int)g_25ec, 1);
    f_5e2d();
    goto L_5b43;
L_5dd5:;
    *(int *)g_e2ec = *(int *)(((unsigned char *)g_dd94 + 0x10));
    *(short *)(g_e2ec + 4) = *(short *)g_dd94;
    *(short *)(g_e2ec + 6) = *(short *)(((unsigned char *)g_dd94 + 4));
    *(short *)(g_e2ec + 8) = 0;
    g_e2ec += 0xa;
    (*(unsigned char **)&g_dd94) += 0x28;
    goto L_5b43;
}

void f_5e2d(void) {
    int choice;
    if (g_e142) {
        if (g_dd78 > 0) --g_dd78;
        choice = f_dd01(0, 7) - 2;
        switch (choice) {
            case 5:
                g_ddb8 = 1;
                f_42e1(0xf, 0, g_dd94->at_00, g_dd94->at_04);
                break;
            case 3:
                f_42e1(0x1b, 0, g_dd94->at_00, g_dd94->at_04);
                break;
            case 0: case 1: case 2:
                f_42e1(1, 0, g_dd94->at_00, g_dd94->at_04);
                break;
            case 4:
                break;
        }
    }
    *(int *)(g_dddc + 0x14) += 3 << g_dee4->at_24;
    f_c20d(0x25);
    --g_ddcc;
    if (g_ddc4 != g_ddcc)
        memcpy(g_dd94, g_dd94 + 1, (g_ddcc - g_ddc4) * 0x28);
    --g_ddc4;
}

void f_5f71(int arg1, int arg2, int arg3, int arg4) {
    if (g_ddcc >= 8) return;
    g_dd94 = g_a848;
    g_dd94 += g_ddcc;
    g_dd94->at_00 = arg1;
    g_dd94->at_04 = arg2;
    g_dd94->at_08 = -1;
    g_dd94->at_0c = 1;
    if (f_dd01() & 0x100)
        g_dd94->at_08 = -g_dd94->at_08;
    g_dd94->at_14 = arg3;
    g_dd94->at_18 = 0;
    g_dd94->at_1c = (int)g_6790[arg4];
    g_dd94->at_1c -= 8;
    g_dd94->at_10 = (int)(g_df2c + 2);
    g_dd94->at_20 = (int)g_e143 / 20 + 2;
    g_dd94->flags &= 0xfd;
    if (arg4 != 2) g_dd94->flags &= 0xfe;
    else g_dd94->flags |= 1;
    f_c20d(0x22);
    ++g_ddcc;
}

void f_608a(void) {
    g_ddd4 = (void *)g_e4d0;
    g_dd40 = g_e4d0;
    f_1085a(g_68f8);
    g_e4d0 -= g_e4c8 - 0x300;
    g_df24 = g_e4d0;
    f_1085a(g_6940);
}

void f_60e5(void) {
    g_df34 = g_e4d0;
    f_1085a(g_6944);
    g_df2c = g_e4d0;
    f_1085a(g_6948);
    g_dee0 = g_e4d0;
    f_1085a(g_694c);
    g_df20 = g_e4d0;
    f_1085a(g_6958);
}

void f_6156(void) {
    g_dd48 = g_e4d0;
    g_dd40 = g_dd48 + 0xfa00;
    f_a574(g_6960);
    g_dd4c = g_e4d0;
    f_1085a(g_695c);
}

void f_61a6(void) {
    g_df40 = g_e4d0;
    g_e270 = (int)g_6cbb;
    f_c3ab();
    for (g_8e20 = 0; g_8e20 < 0x6e; ++g_8e20)
        g_6cbb[g_8e20].v[0] -= g_67b0;
    g_df3c = g_e4d0;
    g_8e48 = g_df3c;
    if (g_747c == -1) f_1085a(g_6964);
    for (g_8e20 = 0; g_8e20 < 0x6e; ++g_8e20)
        g_6cbb[g_8e20].v[0] += g_8e48;
    g_67b0 = g_8e48;
    g_e4d0 = g_df40;
}

void f_6278(void) {
    if (g_dee4->at_60 == 0 && (g_de5c[0] & 0x80)) {
        if (g_ddc8 < g_dee4->at_68) {
            if (g_7c00 == g_7bfe || !(g_7bfe & 2)) {
                if (!(g_de5c[0] & 8)) goto skip_call;
            }
            f_6a1d((unsigned char)g_dee4->at_6c, g_dee4->at_70,
                   g_dee4->at_00, g_dee4->at_04);
            g_dee4->at_60 = g_dee4->at_64;
        }
        skip_call:
        goto done_event;
    } else {
        --g_dee4->at_60;
    }
    done_event:
    if (g_ddc8 != 0) f_6327();
}

void f_6327(void)
{
    int v_4;
    int v_8;
    int v_c;
    int v_10;
    int v_14;
    g_dd90 = g_a518;
    for (g_dda0 = 0; g_dda0 < g_ddc8; ++g_dda0) {
        *(int *)(g_dd90 + 4) += *(int *)(g_dd90 + 8);
        g_8db4 = *(int *)(g_dd90 + 0xc);
        *(int *)g_e24c = *(int *)g_dd90;
        g_e250 = *(int *)(g_dd90 + 4);
        f_8004(g_e24c, (unsigned char *)g_8db4);
        if (g_e254 <= 0x140) {
            if (*(int *)g_e24c >= 0) goto L_63c3;
        }
        goto L_63cf;
L_63c3:;
        if (g_e258 > 0xdc) {
L_63cf:;
        } else {
            if (g_e250 >= 0x14) goto L_6464;
        }
        if ((*(int *)(g_dd90 + 0x10) & 3) == 2) {
            f_7e62((*(int *)g_e24c + g_e254) >> 1, (g_e250 + g_e258) >> 1, 0, 0, (int)g_df2c, (int)g_25ec, 1);
            f_c20d(0x57);
        } else {
            f_7e62((*(int *)g_e24c + g_e254) >> 1, 0x18, 0, 0, (int)g_df34, (int)g_6098, 1);
        }
        f_69cd();
        continue;
L_6464:;
        g_dd94 = g_a848;
        for (g_ddc4 = 0; g_ddc4 < g_ddcc; ++g_ddc4) {
            *(int *)g_e22c = *(int *)g_dd94;
            g_e230 = *(int *)(((unsigned char *)g_dd94 + 4));
            f_8066(g_e22c, (unsigned char *)*(int *)((unsigned char *)((unsigned char *)g_dd94 + 0x10)));
            if (f_b5df(g_e24c, g_e22c) != 0) {
                *(unsigned char *)(((unsigned char *)g_dd94 + 0x24)) |= 2;
                if ((*(int *)(g_dd90 + 0x10) & 3) == 2) {
                    *(int *)(((unsigned char *)g_dd94 + 0x20)) = 0;
                    goto L_6527;
                }
                if ((*(int *)(g_dd90 + 0x10) & 3) == 1) {
                    *(int *)(((unsigned char *)g_dd94 + 0x20)) -= 4;
                    goto L_6527;
                }
                --*(int *)(((unsigned char *)g_dd94 + 0x20));
L_6527:;
                if (*(int *)(((unsigned char *)g_dd94 + 0x20)) <= 0) {
                    *(int *)(((unsigned char *)g_dd94 + 0xc)) += *(int *)(g_dd90 + 8) >> 1;
                }
                if ((*(int *)(g_dd90 + 0x10) & 3) != 2) {
                    f_7e62((*(int *)g_e24c + g_e254) >> 1, (g_e250 + g_e258) >> 1, 0, 0, (int)g_df34, (int)g_5e68, 1);
                    f_69cd();
                    goto L_69c3;
                }
            }
            (*(unsigned char **)&g_dd94) += 0x28;
        }
        v_14 = 0;
        v_4 = (g_e250 + g_e258) >> 1;
        if (v_4 >= 0x18) {
            if (v_4 <= 0x98) goto L_65cc;
        }
        goto L_6975;
L_65cc:;
        if (g_e254 >= 0x10) {
            if (*(int *)g_e24c <= 0x130) goto L_65e6;
        }
        goto L_6975;
L_65e6:;
        g_dd80 = (S2 *)g_a608;
        v_8 = (*(int *)g_e24c - 0x10) >> 4;
        v_c = (g_e254 - 0x10) >> 4;
        v_10 = ((v_4 - 0x18) >> 3) * 0x12;
        if (v_8 < 0) {
            v_8 = 0;
        }
        if (v_c > 0x11) {
            v_c = 0x11;
        }
        if (v_10 > 0x10e) {
            v_10 = 0x10e;
        }
        g_dd80 += v_10;
        for (v_4 = v_8; v_4 <= v_c; v_4++) {
            g_dd50 = *(unsigned char *)(((unsigned char *)g_dd80) + ((v_4 * 2) + 1));
            if (g_dd50 == 0xf8) {
                *(int *)g_dd90 += g_dd68 - g_dd60;
                *(int *)(g_dd90 + 4) += (g_dd70 - g_dd64) - 8;
                v_4 = v_c;
                goto L_6963;
            }
            if (g_dd50 == 0xf9) {
                *(int *)g_dd90 += g_dd60 - g_dd68;
                *(int *)(g_dd90 + 4) += (g_dd64 - g_dd70) - 8;
                v_4 = v_c;
                goto L_6963;
            }
            if (g_dd50 != 0) {
                if ((*(int *)(g_dd90 + 0x10) & 3) == 2) goto L_671f;
            }
            goto L_673e;
L_671f:;
            f_3918(v_4, v_10, 0, *(int *)(g_dd90 + 8));
            goto L_6963;
L_673e:;
            if (g_dd50 >= 1) {
                if (g_dd50 <= 0x90) goto L_6758;
            }
            goto L_67fe;
L_6758:;
            if (g_dd50 >= 1) {
                if (g_dd50 <= 0x10) goto L_677e;
            }
            if (g_dd50 >= 0x31) {
                if (g_dd50 <= 0x40) goto L_677e;
            }
            goto L_6780;
L_677e:;
            goto L_6794;
L_6780:;
            if (g_dd50 >= 0x61) {
                if (g_dd50 <= 0x70) goto L_6794;
            }
            goto L_67b0;
L_6794:;
            f_3918(v_4, v_10, 0, *(int *)(g_dd90 + 8));
            goto L_67e3;
L_67b0:;
            g_dd50 -= 0x10;
            *(unsigned char *)(((unsigned char *)g_dd80) + ((v_4 * 2) + 1)) = *(unsigned char *)&g_dd50;
            f_3ac0(v_4, v_10, g_dd50);
L_67e3:;
            f_c26a(0xc, 0x19);
            *(int *)g_8e10 = (int)g_5e68;
            goto L_691c;
L_67fe:;
            if (g_dd50 >= 0x91) {
                if (g_dd50 <= 0x100) goto L_681b;
            }
            goto L_6963;
L_681b:;
            if (g_dd50 >= 0xf5) {
                if (g_dd50 <= 0xf7) goto L_6835;
            }
            goto L_685f;
L_6835:;
            f_c26a(0x2e, 0x32);
            g_ddb8 = -1;
            f_4394();
            *(int *)g_8e10 = (int)g_6098;
            goto L_691c;
L_685f:;
            if (g_dd50 >= 0xfa) {
                if (g_dd50 <= 0x100) goto L_687c;
            }
            goto L_6906;
L_687c:;
            f_c26a(1, 9);
            if (--((BF1_2_6 *)(((unsigned char *)g_dd80) + (v_4 * 2)))->f == 0) {
                *(int *)((unsigned char *)g_dddc + 0x14) += 2 << *(int *)((unsigned char *)g_dee4 + 0x24);
                f_3e0f(g_dd50, v_4 + v_10);
                f_3918(v_4, v_10, 0, *(int *)(g_dd90 + 8));
            }
            *(int *)g_8e10 = (int)g_5e68;
            goto L_691c;
L_6906:;
            f_c26a(0x2a, 0x2d);
            *(int *)g_8e10 = (int)g_6098;
L_691c:;
            f_7e62((v_4 << 4) + 0x18, ((v_10 / 0x12) << 3) + 0x1c, 0, 0, (int)g_df34, *(int *)g_8e10, 1);
            v_14 = -1;
            continue;
L_6963:;
        }
        if (v_14 == 0) goto L_6975;
        f_69cd();
        goto L_69c3;
L_6975:;
        *(int *)g_e2ec = *(int *)(g_dd90 + 0xc);
        *(short *)(g_e2ec + 4) = *(short *)g_dd90;
        *(short *)(g_e2ec + 6) = *(short *)(g_dd90 + 4);
        *(short *)(g_e2ec + 8) = 0;
        g_e2ec += 0xa;
        g_dd90 += 0x14;
L_69c3:;
    }
}

void f_69cd(void)
{
    --g_ddc8;
    if (g_dda0 != g_ddc8)
        memcpy(g_dd90, g_dd90 + 20, (g_ddc8 - g_dda0) * 20);
    --g_dda0;
}

void f_6a1d(unsigned char a0, int a1, int a2, int a3)
{
    unsigned char v_4;
    if (g_ddc8 >= 0xc) goto L_6afd;
    g_dd90 = g_a518;
    g_dd90 += g_ddc8 * 0x14;
    *(int *)g_dd90 = a2;
    *(int *)(g_dd90 + 4) = a3;
    *(int *)(g_dd90 + 8) = a1;
    v_4 = a0;
    if (v_4 < 1) goto L_6a8a;
    if (v_4 <= 1) goto L_6aa6;
    if (v_4 == 2) goto L_6abc;
    goto L_6ad0;
L_6a8a:;
    if (v_4 != 0) goto L_6ad0;
    g_8e20 = 0x21e6;
    f_c20d(0x5a);
    goto L_6ad0;
L_6aa6:;
    g_8e20 = 0x2280;
    f_c20d(0x58);
    goto L_6ad0;
L_6abc:;
    g_8e20 = 0x2342;
    f_c20d(0x66);
L_6ad0:;
    *(int *)(g_dd90 + 0xc) = (int)(g_df34 + g_8e20);
    ((BF4_0_2 *)(g_dd90 + 0x10))->f = a0;
    ++g_ddc8;
L_6afd:;
}

int f_6b02(void)
{
    g_9468 = 0x118;
    g_9484 = 0;
    g_947c = g_e37a;
    g_e37a = 0xa6;
    f_ea9f((void *)g_dd40, 0, 0x3f, 8);
    g_e4d0 = g_7c08;
    f_6156();
    f_61a6();
    *(unsigned char *)&g_7b34 &= 0xf8;
    f_c8c0((int)g_d340, 0x100, 4, (int)g_ab40, (int)g_bf40);
    f_7112();
    f_7032();
    f_704d();
    f_7068();
    f_9d40(0);
    f_9d40(0);
    f_a810((void *)g_dd48, g_7b18);
    f_12f9c(g_7b18, 0, g_7b20, 0, g_e35a);
    f_12f9c(g_7b18, 0, g_7b22, 0, g_e35a);
    g_7b14 = g_7b18;
    f_6f66();
    f_798c();
    f_73c0();
    f_ea9f((void *)g_dd40, 0x3f, 0, 1);
L_6c3d:;
    f_9d40(3);
    f_7184();
    f_13b72();
    f_798c();
    f_7532();
    f_73c0();
    f_7bd5();
    f_c9ce(0, 0);
    if (g_746c == 0) goto L_6c91;
    f_111de(g_746c, 0);
L_6c91:;
    f_ed38();
    if (g_94a8 <= 0) goto L_6cac;
    if (g_9490 > 0) goto L_6db7;
L_6cac:;
    --g_9468;
    --g_9470;
    if (g_9470 > 0) goto L_6db7;
    if (g_94a8 > 0) goto L_6d4d;
    if (g_742c != 0) goto L_6ce6;
    f_c20d(0x6b);
L_6ce6:;
    g_9470 = 0;
L_6cf0:;
    if (g_9470 < 2) goto L_6d03;
    goto L_6d41;
L_6cfb:;
    ++g_9470;
    goto L_6cf0;
L_6d03:;
    f_7e62(f_dd53(-0x1e, 0x1e) + 0x106, f_dd53(-0x1e, 0x1e) + 0x56, 0, 0, (int)g_dd4c, (int)g_67b4, 1);
    goto L_6cfb;
L_6d41:;
    g_9470 = 8;
    goto L_6db7;
L_6d4d:;
    if (g_742c != 0) goto L_6d61;
    f_c20d(0x6a);
L_6d61:;
    f_7e62(f_dd53(-0x10, 0x10) + (g_e4c6 + 4), (g_e4c4 + 8) + f_dd53(-0x10, 0x10), 0, 0, (int)g_dd4c, (int)g_67b4, 1);
    g_9470 = 0x19;
L_6db7:;
    if (g_94a8 > 0) goto L_6dc9;
    if (g_9468 <= 0) goto L_6dcb;
L_6dc9:;
    goto L_6dda;
L_6dcb:;
    f_6e13();
    return f_6ee8();
L_6dda:;
    if (g_9468 <= 0) goto L_6dfe;
    if (g_e48b == g_e48e) goto L_6df9;
    if (g_e48e == 1) goto L_6dfe;
L_6df9:;
    goto L_6c3d;
L_6dfe:;
    f_6e13();
    return f_6e2e();
}

void f_6e13(void) { g_e37a = g_947c; }

int f_6e2e(void)
{
    f_c20d(0xb);
    g_7b0c = 2;
    g_8e1c = 0;
L_6e58:;
    if (g_8e1c < 0x3f) goto L_6e6e;
    goto L_6ecf;
L_6e66:;
    ++g_8e1c;
    goto L_6e58;
L_6e6e:;
    g_8e20 = 0;
L_6e78:;
    if (g_8e20 < 0x300) goto L_6e8f;
    goto L_6eb1;
L_6e86:;
    g_8e20 += 3;
    goto L_6e78;
L_6e8f:;
    if (++*(unsigned char *)(unsigned char *)(g_dd40 + g_8e20) <= 0x3f) goto L_6eaf;
    *(unsigned char *)(unsigned char *)(g_dd40 + g_8e20) = 0x3f;
L_6eaf:;
    goto L_6e86;
L_6eb1:;
    f_ec76((void *)g_dd40);
    f_9d40(3);
    goto L_6e66;
L_6ecf:;
    g_7b0c = 1;
    return 0;
}

int f_6ee8(void)
{
    f_c20d(0x26);
    if (g_e13b == 0)
        *(int *)((unsigned char *)g_dddc + 20) += (5000 / g_94a0) * g_9490 + 5000;
    g_7b0c = 3;
    f_ea9f(g_dd40, 0, -63, -1);
    g_7b0c = 1;
    return 1;
}

void f_6f66(void)
{
    int v_4;
    int v_8;
    int v_c;
    v_8 = 0;
L_6f79:;
    if (v_8 < 0xa6) goto L_6f8f;
    return;
L_6f87:;
    v_8++;
    goto L_6f79;
L_6f8f:;
    v_4 = 0xa0;
L_6f96:;
    if (v_4 < 0x140) goto L_6faa;
    goto L_7028;
L_6fa4:;
    v_4 += 2;
    goto L_6f96;
L_6faa:;
    v_c = (unsigned char)f_13324(v_4, v_8);
    if (v_c < 0x18) goto L_6fcc;
    if (v_c <= 0x27) goto L_6fce;
L_6fcc:;
    goto L_6fdf;
L_6fce:;
    *(int *)(g_91ac + (v_8 << 2)) = v_4;
    goto L_7028;
L_6fdf:;
    if (v_c < 0x50) goto L_6feb;
    if (v_c <= 0x58) goto L_6fed;
L_6feb:;
    goto L_6ffe;
L_6fed:;
    *(int *)(g_91ac + (v_8 << 2)) = v_4;
    goto L_7028;
L_6ffe:;
    if (v_c < 0x90) goto L_7010;
    if (v_c <= 0xa7) goto L_7012;
L_7010:;
    goto L_7023;
L_7012:;
    *(int *)(g_91ac + (v_8 << 2)) = v_4;
    goto L_7028;
L_7023:;
    goto L_6fa4;
L_7028:;
    goto L_6f87;
}

void f_7032(void) { g_9488 = 0; }

void f_704d(void) { g_dd84 = 0; }

void f_7068(void)
{
    g_94a4 = *(int *)((unsigned char *)g_6884 + (g_e13e << 4));
    g_94a8 = g_94a4;
    g_9494 = g_94a8;
    g_94ac = *(int *)((unsigned char *)g_6884 + 4 + ((g_e13e << 2) << 2));
    g_946c = *(int *)((unsigned char *)g_6884 + 8 + ((g_e13e << 2) << 2));
    g_948c = g_946c;
    g_949c = *(int *)((unsigned char *)g_6884 + 12 + ((g_e13e << 2) << 2));
    g_94b4 = 0;
    g_9498 = 7;
    g_9474 = 0xf;
}

void f_7112(void)
{
    f_100fa(4, 16, 4, 0x95);
    f_10502(4, 0x52);
    for (g_8e20 = 0; g_8e20 < 4; ++g_8e20)
        f_10137();
    g_94a0 = 100;
    g_9490 = g_94a0;
    g_94b0 = g_9490;
}

void f_7184(void)
{
    if (g_9490 > 0) goto L_71cb;
    g_9490 = 0;
    f_100fa(g_e4ba, g_e4bc, g_e4ba, g_e4bc);
L_71cb:;
    if (g_9490 == g_94b0) goto L_72c0;
    g_94b0 = g_9490;
    g_e37a = g_947c;
    f_135e8(g_7b16, ((g_9490 * 0x6f) / g_94a0) + 0x1c, 0xb3, 0x8b, 0xb9, 0);
    f_135e8(g_7b14, ((g_9490 * 0x6f) / g_94a0) + 0x1c, 0xb3, 0x8b, 0xb9, 0);
    g_e37a = 0xa6;
    g_8e20 = 0;
L_7272:;
    if (g_8e20 < 0x300) goto L_7289;
    goto L_72ac;
L_7280:;
    g_8e20 += 3;
    goto L_7272;
L_7289:;
    if ((*(unsigned char *)(unsigned char *)(g_dd40 + g_8e20) += 3) <= 0x3f) goto L_72aa;
    *(unsigned char *)(unsigned char *)(g_dd40 + g_8e20) = 0x3f;
L_72aa:;
    goto L_7280;
L_72ac:;
    g_9484 = 1;
    f_c20d(0x69);
L_72c0:;
    if (g_94a8 == g_9494) goto L_738f;
    if (g_94a8 >= 0) goto L_72ee;
    g_94a8 = 0;
    g_94b4 = 0x1388;
L_72ee:;
    g_9494 = g_94a8;
    g_e37a = g_947c;
    f_135e8(g_7b16, ((g_94a8 * 0x6f) / g_94a4) + 0xb4, 0xb3, 0x123, 0xb9, 0);
    f_135e8(g_7b14, ((g_94a8 * 0x6f) / g_94a4) + 0xb4, 0xb3, 0x123, 0xb9, 0);
    g_e37a = 0xa6;
    g_9484 += 8;
    f_c20d(0x25);
L_738f:;
    if (g_9484 <= 0) goto L_73bb;
    f_13a48((void *)g_dd40, 0, 0x100, -g_9484);
    --g_9484;
L_73bb:;
}

void f_73c0(void)
{
    if (g_9490 <= 0) goto bottom;
    if (g_68f4 != 0) goto reset_gate;
    if (g_7bfe == 3) goto reset_gate;
    goto first_compare;
reset_gate:
    goto reset_flag;
first_compare:
    if (g_7bfe == g_7c00) goto second_gate;
    if ((g_7bfe & 1) == 1) goto first_side;
second_gate:
    goto second_side;
first_side:
    f_c20d(0x66);
    f_78dd(0, 4, g_e4c6, g_e4c4, 0x40, 0, (int)g_6864);
    g_e4ba -= 7;
    g_68f4 = 1;
    goto second_exit;
second_side:
    if (g_7bfe == g_7c00) goto second_skip;
    if (g_7bfe & 2) goto second_actions;
second_skip:
    goto second_exit;
second_actions:
    f_c20d(0x66);
    f_78dd(0, 1, g_e4c6, g_e4c4, 0x60, 0x18, (int)g_6864);
    f_78dd(0, 1, g_e4c6, g_e4c4, 0x60, -0x18, (int)g_6864);
    g_e4ba -= 7;
    g_68f4 = 1;
second_exit:
    goto bottom;
reset_flag:
    g_68f4 = 0;
bottom:
    *(int *)g_e2ec = (int)(g_dd4c + 0x35d6);
    *(short *)(g_e2ec + 4) = g_e4c6;
    *(short *)(g_e2ec + 6) = g_e4c4;
    *(short *)(g_e2ec + 8) = 0;
    g_e2ec += 10;
}

void f_7532(void) { if (g_9488) f_7551(); }

void f_7551(void)
{
    S18 *v_4;
    S18 *v_8;
    g_9478 = g_8e4c;
    g_9480 = 0;
L_7571:;
    if (g_9480 < g_9488) goto L_758b;
    return;
L_7583:;
    ++g_9480;
    goto L_7571;
L_758b:;
    *(int *)(g_9478 + 4) += *(int *)(g_9478 + 0xc);
    *(int *)(g_9478 + 8) += *(int *)(g_9478 + 0x10);
    f_b17e(g_9478 + 0x18, g_9478 + 0x1c);
    v_8 = (S18 *)(*(int *)*(unsigned char * *)(g_9478 + 0x1c) + *(unsigned char * *)(g_9478 + 0x14));
    if ((*(int *)(g_9478 + 4) >> 4) > 0x150) goto L_7600;
    if ((*(int *)(g_9478 + 4) >> 4) >= -0x10) goto L_7602;
L_7600:;
    goto L_7614;
L_7602:;
    if ((*(int *)(g_9478 + 8) >> 4) <= 0xd8) goto L_7616;
L_7614:;
    goto L_7626;
L_7616:;
    if ((*(int *)(g_9478 + 8) >> 4) >= -0x10) goto L_7630;
L_7626:;
    f_788d();
    goto L_7583;
L_7630:;
    if (*(int *)g_9478 != 0) goto L_7771;
    v_4 = (S18 *)(g_dd4c + 0x395c);
    if (f_b76c(*v_4, 0xf6, 0x46,
               *v_8,
               *(int *)(g_9478 + 4) >> 4, *(int *)(g_9478 + 8) >> 4,
               0xa, 0, 0xa, 0) != -1) goto L_7701;
    g_94a8 -= *(int *)(g_9478 + 0x20);
    f_7e62(*(int *)(g_9478 + 4) >> 4, *(int *)(g_9478 + 8) >> 4, *(int *)(g_9478 + 0xc) >> 6, *(int *)(g_9478 + 0x10) >> 6, (int)g_dd4c, (int)g_67b4, 1);
    f_788d();
    goto L_7583;
L_7701:;
    if (((*(int *)(g_9478 + 4) >> 4) + 5) <= *(int *)(g_91ac + ((*(int *)(g_9478 + 8) >> 4) << 2))) goto L_776c;
    f_c20d(0x57);
    f_7e62(*(int *)(g_9478 + 4) >> 4, *(int *)(g_9478 + 8) >> 4, 0, 0, (int)g_dd4c, (int)g_67b4, 1);
    f_788d();
    goto L_7583;
L_776c:;
    goto L_7835;
L_7771:;
    v_4 = (S18 *)(g_dd4c + 0x35d6);
    if (f_b76c(*v_4,
               g_e4c6, g_e4c4,
               *v_8,
               (*(int *)(g_9478 + 4) >> 4) + 8, *(int *)(g_9478 + 8) >> 4,
               4, 4, 4, 4) != -1) goto L_7835;
    if (g_9490 <= 0) goto L_77f9;
    g_9490 -= *(int *)(g_9478 + 0x20);
L_77f9:;
    f_7e62(*(int *)(g_9478 + 4) >> 4, *(int *)(g_9478 + 8) >> 4, 0, 0, (int)g_dd4c, (int)g_67b4, 1);
    f_788d();
    goto L_7583;
L_7835:;
    *(int *)g_e2ec = v_8;
    *(short *)(g_e2ec + 4) = (unsigned short)(*(int *)(g_9478 + 4) >> 4);
    *(short *)(g_e2ec + 6) = (unsigned short)(*(int *)(g_9478 + 8) >> 4);
    *(short *)(g_e2ec + 8) = 0;
    g_e2ec += 0xa;
    g_9478 += 0x24;
    goto L_7583;
}

void f_788d(void)
{
    --g_9488;
    if (g_9480 != g_9488)
        memcpy(g_9478, g_9478 + 0x24, (g_9488 - g_9480) * 0x24);
    --g_9480;
}

void f_78dd(int a, int b, int x, int y, int c, int d, int e)
{
    if (g_9488 < 0x18) {
        g_9478 = g_8e4c;
        g_9478 += g_9488 * 0x24;
        *(int *)(g_9478 + 0) = a;
        *(int *)(g_9478 + 0x20) = b;
        *(int *)(g_9478 + 4) = x << 4;
        *(int *)(g_9478 + 8) = y << 4;
        *(int *)(g_9478 + 12) = c;
        *(int *)(g_9478 + 16) = d;
        *(int *)(g_9478 + 24) = 0;
        *(int *)(g_9478 + 28) = e - 8;
        *(int *)(g_9478 + 20) = (int)g_dd4c;
        ++g_9488;
    }
}

void f_798c(void)
{
    int v_4;
    int v_8;
    int v_c;
    int v_10;
    int v_14;
    v_4 = 0xf6;
    v_8 = 0x56;
    v_14 = 0;
    if (g_94a8 <= 0) goto L_7b95;
    --g_94b4;
    if (g_94b4 > 0) goto L_7af8;
    *(int *)g_e2ec = (int)(g_dd4c + 0x43b6);
    *(short *)(g_e2ec + 4) = 0xf6;
    *(short *)(g_e2ec + 6) = 0x46;
    *(short *)(g_e2ec + 8) = 0;
    g_e2ec += 0xa;
    v_14 = 1;
    --g_9498;
    if (g_9498 > 0) goto L_7af8;
    g_9498 = 7;
    v_c = ((g_e4c6 - v_4) << 4) / 0x28;
    v_10 = ((f_dd53(-0x1e, 0x1e) + (g_e4c4 - v_8)) << 4) / 0x28;
    f_78dd(1, g_94ac, v_4, v_8, v_c, v_10, (int)g_687c);
    if (g_9490 <= 0) goto L_7aaf;
    f_c20d(0x58);
L_7aaf:;
    --g_948c;
    if (g_948c > 0) goto L_7af8;
    g_949c -= 2;
    g_94b4 = g_949c;
    g_948c = g_946c;
    --g_9474;
    if (g_9474 > 0) goto L_7af8;
    ++g_946c;
    g_9474 = 0xf;
L_7af8:;
    if (v_14 != 0) goto L_7b93;
    if (g_94b4 < 0xf) goto L_7b1b;
    if ((g_949c - 0x14) >= g_94b4) goto L_7b58;
L_7b1b:;
    *(int *)g_e2ec = (int)(g_dd4c + 0x3e70);
    *(short *)(g_e2ec + 4) = 0xf6;
    *(short *)(g_e2ec + 6) = 0x46;
    *(short *)(g_e2ec + 8) = 0;
    g_e2ec += 0xa;
    goto L_7b93;
L_7b58:;
    *(int *)g_e2ec = (int)(g_dd4c + 0x395c);
    *(short *)(g_e2ec + 4) = 0xf6;
    *(short *)(g_e2ec + 6) = 0x46;
    *(short *)(g_e2ec + 8) = 0;
    g_e2ec += 0xa;
L_7b93:;
    return;
L_7b95:;
    *(int *)g_e2ec = (int)(g_dd4c + 0x43b6);
    *(short *)(g_e2ec + 4) = 0xf6;
    *(short *)(g_e2ec + 6) = 0x46;
    *(short *)(g_e2ec + 8) = 0;
    g_e2ec += 0xa;
}

void f_7bd5(void) { if (g_dd84) f_7bf4(); }

void f_7bf4(void)
{
    g_dd6c = g_94b8;
    for (g_dd88 = 0; g_dd88 < g_dd84; g_dd88++) {
        if (g_dd6c->f5) {
            g_dd6c->a = *(int *)g_dee4;
            g_dd6c->b = *(int *)((unsigned char *)g_dee4 + 4);
            goto L_7ca4;
        }
        if (g_dd6c->anim == 0) {
            g_dd6c->a += g_dd6c->c;
            g_dd6c->b += g_dd6c->d;
            goto L_7ca4;
        }
        g_dd6c->anim--;
L_7ca4:
        if (--g_dd6c->speed > 0) goto L_7d2a;
        g_8e20 = (++g_dd6c->f)->time;
        if (g_8e20 >= 0) goto L_7d1c;
        if (g_dd6c->f6) *g_de5c |= 0x40;
        if (g_dd6c->f8) {
            f_7e12();
            continue;
        }
        g_dd6c->f += g_8e20;
        g_8e20 = g_dd6c->f->time;
L_7d1c:
        g_dd6c->speed = g_8e20;
L_7d2a:
        g_8db4 = g_dd6c->e + g_dd6c->f->img;
        if (g_dd6c->f7) {
            g_e24c[0] = g_dd6c->a;
            g_e250 = g_dd6c->b;
            f_8004(g_e24c, (unsigned char *)g_8db4);
            if (g_dd6c->a > 0x150) goto L_7d96;
            if (g_dd6c->a >= -0x10) goto L_7d98;
L_7d96:
            goto L_7da6;
L_7d98:
            if (g_dd6c->b <= 0xd8) goto L_7da8;
L_7da6:
            goto L_7db3;
L_7da8:
            if (g_dd6c->b >= -0x10) goto L_7dbd;
L_7db3:
            f_7e12();
            continue;
        }
L_7dbd:
        *(int *)g_e2ec = g_8db4;
        *(short *)(g_e2ec + 4) = g_dd6c->a;
        *(short *)(g_e2ec + 6) = g_dd6c->b;
        *(short *)(g_e2ec + 8) = 0;
        g_e2ec += 10;
        g_dd6c++;
    }
}

void f_7e12(void)
{
    --g_dd84;
    if (g_dd88 != g_dd84)
        memcpy((unsigned char *)g_dd6c, (unsigned char *)g_dd6c + 0x20, (g_dd84 - g_dd88) * 0x20);
    --g_dd88;
}

void f_7e62(int a, int b, int c, int d, int e, int f, int flags)
{
    if (g_dd84 < 0x32) {
        g_dd6c = g_94b8;
        g_dd6c += g_dd84;
        g_dd6c->a = a;
        g_dd6c->b = b;
        g_dd6c->c = c;
        g_dd6c->d = d;
        if (flags & 0x10) {
            g_dd6c->speed = 0x3e80;
            g_dd6c->f = f;
        } else {
            g_dd6c->speed = 0;
            g_dd6c->f = f - 8;
        }
        g_dd6c->e = e;
        g_dd6c->anim = flags >> 4;
        g_dd6c->f5 = flags >> 3;
        g_dd6c->f6 = flags >> 2;
        g_dd6c->f7 = flags >> 1;
        g_dd6c->f8 = flags;
        g_dd84++;
    }
}

void f_7f8a(void)
{
    int x;
    int y;
    unsigned char *p;
    y = 16;
    while (y < g_e36a) {
        x = 0;
        while (x < g_e366) {
            p = g_ddd8 + g_2e9c[2 * g_df38];
            f_12cbd(p, x, y);
            x += *(short *)(p + 2);
        }
        y += *(short *)(p + 4);
    }
}

void f_8004(int *rect, unsigned char *info)
{
    g_e158 = info;
    f_95ee();
    rect[0] += g_e15c;
    rect[1] += g_e15e;
    rect[2] = rect[0] + g_e160 - 2;
    rect[3] = rect[1] + g_e162 - 2;
}

void f_8066(int *rect, unsigned char *info)
{
    g_e158 = info;
    f_95ee();
    rect[0] += g_e15c + 3;
    rect[1] += g_e15e + 3;
    rect[2] = rect[0] - 3 + g_e160 - 5;
    rect[3] = rect[1] - 3 + g_e162 - 5;
}

void f_80d8(void)
{
    if (g_e46b & 0x20) {
        if (g_7bfe != g_7c00) {
            if (g_7bfe == 1) {
                f_10369();
                g_e4a8 -= 2;
                g_e4c2 -= 2;
                f_103b9();
            } else if (g_7bfe == 2) {
                f_10369();
                g_e4a8 += 2;
                g_e4c2 += 2;
                f_103b9();
            }
        }
    }
}

void f_814b(void)
{
    if ((g_7b36 & 1) == 0) goto L_8206;
    if (g_e48f < 0x41) goto L_8176;
    if (g_e48f <= 0x5a) goto L_8178;
L_8176:;
    goto L_8181;
L_8178:;
    if ((g_e48e & 0x80) == 0) goto L_8183;
L_8181:;
    goto L_81a0;
L_8183:;
    f_42e1((unsigned char)(g_e48f - 0x41), 0, 0xa0, 0x64);
L_81a0:;
    if (g_e48f != 0x25) goto L_81b2;
    if ((g_e48e & 0x80) == 0) goto L_81b4;
L_81b2:;
    goto L_81cc;
L_81b4:;
    f_42e1(0xf, 0, 0xa0, 0x64);
L_81cc:;
    if (g_e48f != 0x2e) goto L_81de;
    if ((g_e48e & 0x80) == 0) goto L_81e0;
L_81de:;
    goto L_8206;
L_81e0:;
    *(unsigned char *)g_de5c &= 0xf7;
    *(unsigned char *)(g_de5c + 1) &= 0xfb;
    *(unsigned char *)g_de5c &= 0xbf;
    *(unsigned char *)g_de5c &= 0x7f;
    f_58b0();
L_8206:;
    if ((g_7b36 & 2) == 0) goto L_8295;
    if (g_e48e != 0x1b) goto L_823e;
    g_e143 = 0x3c;
    g_ddc0 = 0;
    g_dd78 = 0;
    g_e48f = 0;
L_823e:;
    if (g_e48d == 0x20) goto L_8250;
    if (g_e48f == 0x20) goto L_8252;
L_8250:;
    goto L_8266;
L_8252:;
    g_ddc0 = 0;
    g_dd78 = 0;
L_8266:;
    if (g_e48d == 0x2a) goto L_8278;
    if (g_e48f == 0x2a) goto L_827a;
L_8278:;
    goto L_8295;
L_827a:;
    g_e143 += 9;
    g_ddc0 = 0;
    g_dd78 = 0;
L_8295:;
    if ((g_7b36 & 4) == 0) goto L_82b2;
    *(unsigned char *)g_de5c |= 8;
    *(int *)((unsigned char *)g_dee4 + 0x34) = 3;
L_82b2:;
    if ((g_7b36 & 8) == 0) goto L_82c7;
    *(int *)(g_dddc + 4) = 0x63;
L_82c7:;
}

void f_82cc(void)
{
    struct Iter24 *p = g_e150;
    int i = 0;
    for (; i < g_e148; i++) {
        p->count = (p->second - p->first) / p->step;
        p->start = p->first - p->count;
        p++;
    }
    g_e14c = 0;
}

void f_8345(void)
{
    struct Iter24 *p;
    int i;
    ++g_e14c;
    p = g_e150;
    i = 0;
    for (; i < g_e148; i++) {
        if (g_e14c >= p->step)
            p->start = p->second;
        else
            p->start += p->count;
        p++;
    }
}

void f_83b1(void)
{
    struct Iter48 *p = (struct Iter48 *)g_e150;
    int i = 0;
    for (; i < (g_e148 >> 1); i++) {
        *(int *)g_e2ec = (int)(p->at20 + g_e154);
        *(short *)(g_e2ec + 4) = (short)(p->box >> 4);
        *(short *)(g_e2ec + 6) = (short)(p->pad32 >> 4);
        *(short *)(g_e2ec + 8) = 0;
        g_e2ec += 10;
        ++p;
    }
}

void f_843a(void)
{
    f_c8c0((int)g_d340, 0x100, 4, (int)g_ab40, (int)g_bf40);
    g_7b14 = g_7b20;
    g_7b16 = g_7b22;
    g_7b18 = g_7b24;
    g_7b1a = g_7b26;
}

void f_84a0(int a0)
{
    g_7b3d = 0;
    g_7b34 = (g_7b34 & 0xfffe) & 0xfffd;
L_84c5:;
    f_9d40(3);
    g_e1bc = 0;
    g_e1b8 = (int)g_e2ec;
L_84e6:;
    g_e2ec = (unsigned char *)g_e1b8;
    f_13b72();
    f_8345();
    f_83b1();
    ++g_e1bc;
    if (g_e1bc < g_e1c0) goto L_84e6;
    f_c9ce(0, 0);
    f_ed38();
    if (g_e48d == g_e48f) goto L_853c;
    if (g_e48f == 0x20) goto L_8556;
L_853c:;
    if (g_7bfe == g_7c00) goto L_8554;
    if ((*(unsigned char *)&g_7bfe & 7) != 0) goto L_8556;
L_8554:;
    goto L_8558;
L_8556:;
    goto L_8570;
L_8558:;
    if (g_e48b == g_e48e) goto L_856e;
    if (g_e48e == 1) goto L_8570;
L_856e:;
    goto L_8572;
L_8570:;
    return;
L_8572:;
    if (g_e14c < a0) goto L_84c5;
}

void f_8585(void) { if (g_dda8) f_85a4(); }

void f_85a4(void)
{
    unsigned char v_4;
    unsigned char v_8;
    unsigned char v_c;
    unsigned char v_10;
    int v_14;
    struct f85a4_local v_40;
    *(int *)g_e24c = *(int *)g_dee4;
    g_e250 = *(int *)((unsigned char *)g_dee4 + 4);
    f_8004(g_e24c, (unsigned char *)*(int *)((unsigned char *)(unsigned char *)g_dee4 + 0x78));
    g_e250 += 3;
    g_e258 = g_e250 + 0xa;
    *(int *)g_e24c += 2;
    g_e254 -= 2;
    *(int *)g_e23c = *(int *)((unsigned char *)g_dee4 + 0x74);
    f_8004(g_e23c, (unsigned char *)(g_dee0 + 0x7536));
    g_ddb4 = g_df78;
    g_ddac = 0;
L_863b:;
    if (g_ddac < g_dda8) goto L_8655;
    return;
L_864d:;
    ++g_ddac;
    goto L_863b;
L_8655:;
    g_8e20 = *(unsigned char *)(g_ddb4 + 0x10);
    if ((*(unsigned char *)(g_ddb4 + 0x11) & 2) == 0) goto L_86a7;
    g_8ddc = *(int *)(g_5e30 + (g_8e20 << 3));
    if ((*(unsigned char *)(g_de5c + 1) & 0x20) != 0) goto L_869a;
    if (*(int *)(g_ddb4 + 4) > 0x980) goto L_869c;
L_869a:;
    goto L_86a5;
L_869c:;
    *(unsigned char *)(g_ddb4 + 0x11) &= 0xfd;
L_86a5:;
    goto L_86da;
L_86a7:;
    if ((*(unsigned char *)(g_de5c + 1) & 0x10) == 0) goto L_86c7;
    g_8ddc = *(int *)(g_5df8 + (g_8e20 << 3));
    goto L_86da;
L_86c7:;
    g_8ddc = *(int *)(g_5dc0 + (g_8e20 << 3));
L_86da:;
    v_14 = (int)g_df34 + g_8ddc;
    if ((*(unsigned char *)(g_ddb4 + 0x11) & 1) != 0) goto L_8716;
    *(int *)g_ddb4 += *(int *)(g_ddb4 + 8);
    *(int *)(g_ddb4 + 4) += *(int *)(g_ddb4 + 0xc);
    goto L_8780;
L_8716:;
    *(int *)(g_ddb4 + 4) = *(int *)((unsigned char *)g_dee4 + 4) << 4;
    if ((*(unsigned char *)g_de5c & 2) != 0) goto L_877b;
    if (g_7c00 == g_7bfe) goto L_874b;
    if ((*(unsigned char *)&g_7bfe & 1) != 0) goto L_8755;
L_874b:;
    if ((*(unsigned char *)g_de5c & 8) == 0) goto L_877b;
L_8755:;
    *(int *)g_ddb4 += *(int *)g_dee4 << 4;
    *(unsigned char *)(g_ddb4 + 0x11) &= 0xfe;
    g_7c00 = g_7bfe;
L_877b:;
    goto L_8f05;
L_8780:;
    if (*(int *)g_ddb4 > 0x1400) goto L_8797;
    if (*(int *)g_ddb4 >= 0) goto L_8799;
L_8797:;
    goto L_87a7;
L_8799:;
    if (*(int *)(g_ddb4 + 4) <= 0xdc0) goto L_87a9;
L_87a7:;
    goto L_87b4;
L_87a9:;
    if (*(int *)(g_ddb4 + 4) >= 0) goto L_87be;
L_87b4:;
    f_8f7e();
    goto L_864d;
L_87be:;
    *(int *)g_e22c = *(int *)g_ddb4 >> 4;
    g_e230 = *(int *)(g_ddb4 + 4) >> 4;
    f_8004(g_e22c, (unsigned char *)v_14);
    if (*(int *)g_e22c > 0x10) goto L_880f;
    if (*(int *)(g_ddb4 + 8) >= 0) goto L_880f;
    g_8e20 = 0x10;
    goto L_8854;
L_880f:;
    if (g_e234 < 0x130) goto L_8832;
    if (*(int *)(g_ddb4 + 8) <= 0) goto L_8832;
    g_8e20 = 0x130;
    goto L_8854;
L_8832:;
    if (g_e230 > 0x18) goto L_8852;
    if (*(int *)(g_ddb4 + 0xc) >= 0) goto L_8852;
    g_8e1c = 0x18;
    goto L_8878;
L_8852:;
    goto L_88c9;
L_8854:;
    *(int *)(g_ddb4 + 8) = -*(int *)(g_ddb4 + 8);
    g_8e1c = *(int *)(g_ddb4 + 4) >> 4;
    goto L_8899;
L_8878:;
    *(int *)(g_ddb4 + 0xc) = -*(int *)(g_ddb4 + 0xc);
    g_8e20 = *(int *)g_ddb4 >> 4;
L_8899:;
    f_c20d(0x24);
    f_7e62(g_8e20, g_8e1c, 0, 0, (int)g_df34, (int)g_6098, 1);
L_88c9:;
    if (g_e230 > 0xbe) goto L_8f05;
    if (*(int *)(g_ddb4 + 0xc) < 0) goto L_8b85;
    if (g_e250 > g_e238) goto L_8a69;
    if (g_e258 < g_e230) goto L_8a69;
    if (*(int *)g_e24c > g_e234) goto L_8a16;
    if (g_e254 < *(int *)g_e22c) goto L_8a16;
    if ((*(unsigned char *)g_de5c & 8) != 0) goto L_895c;
    if ((*(unsigned char *)g_de5c & 0x40) == 0) goto L_895a;
    *(int *)g_ddb4 -= *(int *)g_dee4 << 4;
    *(unsigned char *)(g_ddb4 + 0x11) |= 1;
L_895a:;
    goto L_8970;
L_895c:;
    if (*(int *)(g_ddb4 + 8) != 0) goto L_8970;
    *(int *)(g_ddb4 + 8) -= 4;
L_8970:;
    g_8e20 = ((*(unsigned char *)(g_ddb4 + 0x10) >> 1) & -2) + 3;
    if ((*(unsigned char *)(g_ddb4 + 0x11) & 2) != 0) goto L_89b9;
    g_e4bc += *(short *)&g_8e20;
    g_e4b4 += *(short *)&g_8e20;
    g_e4b0 += *(short *)&g_8e20;
    goto L_89cd;
L_89b9:;
    if ((*(unsigned char *)(g_de5c + 1) & 0x20) != 0) goto L_89cd;
    *(unsigned char *)(g_ddb4 + 0x11) &= 0xfd;
L_89cd:;
    if ((*(unsigned char *)g_de5c & 0x80) == 0) goto L_89e3;
    f_c20d(0x20);
    goto L_89ed;
L_89e3:;
    f_c20d(0x65);
L_89ed:;
    if ((*(int *)g_e24c + 3) >= g_e234) goto L_8a8d;
    if ((g_e254 - 3) <= *(int *)g_e22c) goto L_8a6e;
    goto L_8ad2;
L_8a16:;
    if ((*(unsigned char *)(g_de5c + 1) & 2) == 0) goto L_8a2e;
    if (*(int *)g_e23c <= g_e234) goto L_8a30;
L_8a2e:;
    goto L_8a69;
L_8a30:;
    if (g_e244 < *(int *)g_e22c) goto L_8a69;
    f_c20d(0x21);
    if ((*(int *)g_e23c + 3) >= g_e234) goto L_8a8d;
    if ((g_e244 - 3) <= *(int *)g_e22c) goto L_8a6e;
    goto L_8ad2;
L_8a69:;
    goto L_8b85;
L_8a6e:;
    if (*(int *)(g_ddb4 + 8) >= 0) goto L_8a8b;
    *(int *)(g_ddb4 + 8) = -*(int *)(g_ddb4 + 8);
L_8a8b:;
    goto L_8aaa;
L_8a8d:;
    if (*(int *)(g_ddb4 + 8) <= 0) goto L_8aaa;
    *(int *)(g_ddb4 + 8) = -*(int *)(g_ddb4 + 8);
L_8aaa:;
    *(int *)(g_ddb4 + 0xc) = -*(int *)(g_ddb4 + 0xc);
    *(int *)(g_ddb4 + 4) += *(int *)(g_ddb4 + 0xc);
    goto L_8b85;
L_8ad2:;
    *(int *)(g_ddb4 + 0xc) = -*(int *)(g_ddb4 + 0xc);
    *(int *)(g_ddb4 + 4) += *(int *)(g_ddb4 + 0xc);
    g_8e20 = *(int *)g_dee4 - *(int *)((unsigned char *)g_dee4 + 8);
    if (g_8e20 <= 0x18) goto L_8b1d;
    g_8e20 = 0x18;
L_8b1d:;
    if (g_8e20 >= -0x18) goto L_8b30;
    g_8e20 = -0x18;
L_8b30:;
    g_8e20 = ((g_8e20 * 2) + (g_8e20 >> 1)) + *(int *)(g_ddb4 + 8);
    if (g_8e20 <= 0x20) goto L_8b64;
    g_8e20 = 0x20;
L_8b64:;
    if (g_8e20 >= -0x20) goto L_8b77;
    g_8e20 = -0x20;
L_8b77:;
    *(int *)(g_ddb4 + 8) = g_8e20;
L_8b85:;
    if ((*(unsigned char *)(g_ddb4 + 0x11) & 2) != 0) goto L_8f05;
    g_dd94 = g_a848;
    g_ddc4 = 0;
L_8ba8:;
    if (g_ddc4 < g_ddcc) goto L_8bc2;
    goto L_8cd2;
L_8bba:;
    ++g_ddc4;
    goto L_8ba8;
L_8bc2:;
    *(int *)g_e25c = *(int *)g_dd94;
    g_e260 = *(int *)(((unsigned char *)g_dd94 + 4));
    f_8066(g_e25c, (unsigned char *)*(int *)((unsigned char *)((unsigned char *)g_dd94 + 0x10)));
    if (f_b5df(g_e22c, g_e25c) == 0) goto L_8cc6;
    *(unsigned char *)(((unsigned char *)g_dd94 + 0x24)) |= 2;
    *(int *)(((unsigned char *)g_dd94 + 0x20)) = 0;
    *(int *)(((unsigned char *)g_dd94 + 8)) += *(int *)(g_ddb4 + 8) >> 4;
    *(int *)(((unsigned char *)g_dd94 + 0xc)) += *(int *)(g_ddb4 + 0xc) >> 4;
    if ((*(unsigned char *)(g_de5c + 1) & 0x10) != 0) goto L_8cc6;
    if ((*(signed char *)&g_8e24 & 0x10) == 0) goto L_8c76;
    *(int *)(g_ddb4 + 0xc) = -*(int *)(g_ddb4 + 0xc);
    goto L_8c88;
L_8c76:;
    *(int *)(g_ddb4 + 8) = -*(int *)(g_ddb4 + 8);
L_8c88:;
    if (*(int *)(g_ddb4 + 8) != 0) goto L_8c9e;
    *(int *)(g_ddb4 + 8) -= 4;
    goto L_8cc6;
L_8c9e:;
    g_ddb8 = 2;
    if ((*(signed char *)&g_8e24 & 1) == 0) goto L_8cb7;
    g_ddb8 = -g_ddb8;
L_8cb7:;
    g_8e1c = 1;
    f_9053();
L_8cc6:;
    (*(unsigned char **)&g_dd94) += 0x28;
    goto L_8bba;
L_8cd2:;
    if (*(int *)(g_ddb4 + 0xc) >= 0) goto L_8d0f;
    v_40.rows[0].active = 1;
    v_40.rows[1].active = 1;
    v_40.rows[2].active = 0;
    v_40.rows[3].active = 0;
    v_40.rows[0].x = *(int *)g_e22c;
    v_40.rows[0].y = g_e230;
    v_40.rows[1].x = g_e234;
    v_40.rows[1].y = g_e230;
    goto L_8d3f;
L_8d0f:;
    v_40.rows[0].active = 0;
    v_40.rows[1].active = 0;
    v_40.rows[2].active = 1;
    v_40.rows[3].active = 1;
    v_40.rows[2].x = g_e234;
    v_40.rows[2].y = g_e238;
    v_40.rows[3].x = *(int *)g_e22c;
    v_40.rows[3].y = g_e238;
L_8d3f:;
    if (*(int *)(g_ddb4 + 8) >= 0) goto L_8d74;
    v_40.rows[0].active += 2;
    v_40.rows[3].active += 2;
    v_40.rows[0].x = *(int *)g_e22c;
    v_40.rows[0].y = g_e230;
    v_40.rows[3].x = *(int *)g_e22c;
    v_40.rows[3].y = g_e238;
    goto L_8da7;
L_8d74:;
    if (*(int *)(g_ddb4 + 8) <= 0) goto L_8da7;
    v_40.rows[1].active += 2;
    v_40.rows[2].active += 2;
    v_40.rows[1].x = g_e234;
    v_40.rows[1].y = g_e230;
    v_40.rows[2].x = g_e234;
    v_40.rows[2].y = g_e238;
L_8da7:;
    v_4 = 0;
    g_dd58 = -1;
    g_dd5c = -1;
    v_c = 0;
L_8dc3:;
    if (v_c < 4) goto L_8dd6;
    goto L_8e45;
L_8dce:;
    v_c++;
    goto L_8dc3;
L_8dd6:;
    if (v_40.rows[v_c].active == 0) goto L_8e37;
    v_40.rows[v_c].result = (unsigned char)f_91a3(v_40.rows[v_c].x, v_40.rows[v_c].y);
    if (v_40.rows[v_c].result == 0) goto L_8e23;
    v_4++;
L_8e23:;
    if (v_40.rows[v_c].result == 3) goto L_8f05;
    goto L_8e43;
L_8e37:;
    v_40.rows[v_c].result = 0;
L_8e43:;
    goto L_8dce;
L_8e45:;
    v_8 = 0;
    v_10 = 0;
    if ((*(unsigned char *)(g_de5c + 1) & 0x10) != 0) goto L_8f05;
    v_c = 0;
L_8e60:;
    if (v_c < 4) goto L_8e73;
    goto L_8ed5;
L_8e6b:;
    v_c++;
    goto L_8e60;
L_8e73:;
    if (v_40.rows[v_c].result == 0) goto L_8ed3;
    switch (v_40.rows[v_c].active) {
        case 1:
L_8ea9:;
        v_10 = 1;
        goto L_8ed3;
        case 2:
L_8eaf:;
        v_8 = 1;
        goto L_8ed3;
        case 3:
L_8eb5:;
        if (v_4 != 1) goto L_8ed3;
        if (v_40.rows[v_c].result != 1) goto L_8ecf;
        v_10 = 1;
        goto L_8ed3;
L_8ecf:;
        v_8 = 1;
    }
L_8ed3:;
    goto L_8e6b;
L_8ed5:;
    if (v_8 == 0) goto L_8eed;
    *(int *)(g_ddb4 + 8) = -*(int *)(g_ddb4 + 8);
L_8eed:;
    if (v_10 == 0) goto L_8f05;
    *(int *)(g_ddb4 + 0xc) = -*(int *)(g_ddb4 + 0xc);
L_8f05:;
    g_8e20 = *(int *)g_ddb4 >> 4;
    if ((*(unsigned char *)(g_ddb4 + 0x11) & 1) == 0) goto L_8f2c;
    g_8e20 += *(int *)g_dee4;
L_8f2c:;
    *(int *)g_e2ec = v_14;
    *(short *)(g_e2ec + 4) = *(short *)&g_8e20;
    *(short *)(g_e2ec + 6) = (unsigned short)(*(int *)(g_ddb4 + 4) >> 4);
    *(short *)(g_e2ec + 8) = 0;
    g_e2ec += 0xa;
    g_ddb4 += 0x12;
    goto L_864d;
}

void f_8f7e(void)
{
    --g_dda8;
    if (g_ddac != g_dda8)
        memcpy(g_ddb4, g_ddb4 + 0x12, (g_dda8 - g_ddac) * 0x12);
    --g_ddac;
}

void f_8fce(int x, int y)
{
    if (g_dda8 < 0x19) {
        g_ddb4 = g_df78;
        g_ddb4 += g_dda8 * 0x12;
        *(int *)(g_ddb4 + 0) = x << 4;
        *(int *)(g_ddb4 + 4) = y << 4;
        *(int *)(g_ddb4 + 8) = 10;
        *(int *)(g_ddb4 + 12) = -20;
        g_ddb4[17] &= (unsigned char)~1;
        g_ddb4[17] &= (unsigned char)~2;
        g_ddb4[16] = 0;
        ++g_dda8;
    }
}

void f_9053(void)
{
    if (*(unsigned char *)&g_8e1c & 1) {
        g_8e20 = *(int *)(g_ddb4 + 8);
        if (g_8e20 > 0) {
            g_8e20 += g_ddb8 * 4;
            if (g_8e20 > 0x20) g_8e20 = 0x20;
            if (g_8e20 < 4) g_8e20 = 4;
        } else if (g_8e20 < 0) {
            g_8e20 -= g_ddb8 * 4;
            if (g_8e20 < -0x20) g_8e20 = -0x20;
            if (g_8e20 > -4) g_8e20 = -4;
        }
        *(int *)(g_ddb4 + 8) = g_8e20;
    }
    if (*(unsigned char *)&g_8e1c & 2) {
        g_8e20 = *(int *)(g_ddb4 + 12);
        if (g_8e20 > 0) {
            g_8e20 += g_ddb8 * 4;
            if (g_8e20 > 0x28) g_8e20 = 0x28;
            if (g_8e20 < 4) g_8e20 = 4;
        } else {
            g_8e20 -= g_ddb8 * 4;
            if (g_8e20 < -0x28) g_8e20 = -0x28;
            if (g_8e20 > -4) g_8e20 = -4;
        }
        *(int *)(g_ddb4 + 12) = g_8e20;
    }
}

int f_91a3(int a0, int a1)
{
    int v_4;
    int v_8;
    if (a1 >= 0x18) {
        if (a1 < 0x98) goto L_91c3;
    }
    goto L_9513;
L_91c3:;
    if (a0 >= 0x10) {
        if (a0 < 0x130) goto L_91d7;
    }
    goto L_9513;
L_91d7:;
    v_4 = (a0 - 0x10) >> 4;
    v_8 = ((a1 - 0x18) >> 3) * 0x12;
    if (v_4 == g_dd58) {
        if (v_8 == g_dd5c) goto L_920a;
    }
    goto L_920f;
L_920a:;
    goto L_9581;
L_920f:;
    g_dd80 = (S2 *)g_a608;
    g_dd80 += v_8;
    g_dd50 = *(unsigned char *)(((unsigned char *)g_dd80) + ((v_4 * 2) + 1));
    if (g_dd50 == 0) goto L_9513;
    if (g_dd50 == 0xf8) {
        *(int *)g_ddb4 += (g_dd68 - g_dd60) << 4;
        *(int *)(g_ddb4 + 4) += (g_dd70 - g_dd64) << 4;
        goto L_9522;
    }
    if (g_dd50 == 0xf9) {
        *(int *)g_ddb4 += (g_dd60 - g_dd68) << 4;
        *(int *)(g_ddb4 + 4) += (g_dd64 - g_dd70) << 4;
        goto L_9522;
    }
    if (g_dd50 >= 1) {
        if (g_dd50 <= 0x90) goto L_92de;
    }
    goto L_9392;
L_92de:;
    if (g_dd50 >= 1) {
        if (g_dd50 <= 0x10) goto L_9304;
    }
    if (g_dd50 >= 0x31) {
        if (g_dd50 <= 0x40) goto L_9304;
    }
    goto L_9306;
L_9304:;
    goto L_931a;
L_9306:;
    if (g_dd50 >= 0x61) {
        if (g_dd50 <= 0x70) goto L_931a;
    }
    goto L_9344;
L_931a:;
    f_3918(v_4, v_8, *(int *)(g_ddb4 + 8) >> 3, *(int *)(g_ddb4 + 0xc) >> 3);
    goto L_9377;
L_9344:;
    g_dd50 -= 0x10;
    *(unsigned char *)(((unsigned char *)g_dd80) + ((v_4 * 2) + 1)) = *(unsigned char *)&g_dd50;
    f_3ac0(v_4, v_8, g_dd50);
L_9377:;
    f_c26a(0xc, 0x19);
    *(int *)g_8e10 = (int)g_5e68;
    goto L_94ec;
L_9392:;
    if (g_dd50 >= 0x91) {
        if (g_dd50 <= 0x100) goto L_93af;
    }
    goto L_9513;
L_93af:;
    *(int *)g_8e10 = (int)g_6098;
    if ((*(unsigned char *)(g_de5c + 1) & 0x10) != 0) {
        f_3918(v_4, v_8, *(int *)(g_ddb4 + 8) >> 3, *(int *)(g_ddb4 + 0xc) >> 3);
        goto L_94ec;
    }
    if (g_dd50 >= 0xf5) {
        if (g_dd50 <= 0xf7) goto L_940b;
    }
    goto L_942b;
L_940b:;
    f_c26a(0x2e, 0x32);
    g_ddb8 = -1;
    f_4394();
    goto L_94ec;
L_942b:;
    if (g_dd50 >= 0xfa) {
        if (g_dd50 <= 0x100) goto L_9448;
    }
    goto L_94e0;
L_9448:;
    f_c26a(1, 9);
    if (--((BF1_2_6 *)(((unsigned char *)g_dd80) + (v_4 * 2)))->f != 0) goto L_94d4;
        *(int *)((unsigned char *)g_dddc + 0x14) += 2 << *(int *)((unsigned char *)g_dee4 + 0x24);
        f_3e0f(g_dd50, v_4 + v_8);
        f_3918(v_4, v_8, *(int *)(g_ddb4 + 8) >> 3, *(int *)(g_ddb4 + 0xc) >> 3);
L_94d4:;
    *(int *)g_8e10 = (int)g_5e68;
    goto L_94ec;
L_94e0:;
    f_c26a(0x2a, 0x2d);
L_94ec:;
    f_7e62(a0, a1, 0, 0, (int)g_df34, *(int *)g_8e10, 1);
    goto L_9581;
L_9513:;
    g_8e20 = 0;
    goto L_95de;
L_9522:;
    if (*(int *)(g_ddb4 + 0xc) > 0) {
        *(int *)(g_ddb4 + 4) += 0x80;
    } else {
        *(int *)(g_ddb4 + 4) -= 0x80;
    }
    if (*(int *)(g_ddb4 + 8) > 0) {
        *(int *)g_ddb4 += 0x100;
        goto L_9575;
    }
    if (*(int *)(g_ddb4 + 8) >= 0) goto L_9575;
    *(int *)g_ddb4 -= 0x100;
L_9575:;
    g_8e20 = 3;
    goto L_95de;
L_9581:;
    g_8e20 = 1;
    a0 &= 0xf;
    if (a0 > 7) {
        a0 = 0xf - a0;
    }
    a1 = (a1 * 2) & 0xf;
    if (a1 > 7) {
        a1 = 0xf - a1;
    }
    if (a1 > a0) {
        g_8e20 = 2;
    }
    g_dd58 = v_4;
    g_dd5c = v_8;
L_95de:;
    return g_8e20;
}

void f_95ee(void)
{
    g_e160 = *(short *)(g_e158 + 2);
    g_e162 = *(short *)(g_e158 + 4);
    g_e15c = *(short *)(g_e158 + 10);
    g_e15e = *(short *)(g_e158 + 12);
}
