/* TU f_a0e0..f_a0e0 [0xa0e0, 0xa284): generated by tools/tu.py */
extern int g_e1c4;
extern int g_e1d0;

struct T07_bss_block {
    int value_e1c4;
    int unused_e1c8;
    int unused_e1cc;
    int value_e1d0;
} g_T07_bss;
#define g_e1c4 (g_T07_bss.value_e1c4)
#define g_e1d0 (g_T07_bss.value_e1d0)

int f_a0e0(int a0, int a1, unsigned char * a2)
{
    unsigned char v_4;
    unsigned char * v_8;
    int v_c;
    unsigned v_10;
    int v_14;
    int v_18;
    int v_1c;
    int v_20;
    int v_24;
    v_8 = (unsigned char *)a0;
    v_c = a0 + 0x80;
    v_10 = a1;
    if (*(int *)v_8 == 0x801050a) goto L_a120;
    v_24 = 0xa01;
    return v_24;
L_a120:;
    v_18 = *(short *)(v_8 + 0xc);
    v_1c = *(short *)(v_8 + 0xe);
    v_20 = v_18 * v_1c;
L_a13e:;
    if ((a1 + v_20) <= v_10) goto L_a19f;
    v_14 = *(unsigned char *)(unsigned char *)(v_c++);
    if ((v_14 & 0xc0) != 0xc0) goto L_a192;
    v_4 = *(unsigned char *)(unsigned char *)(v_c++);
    v_14 &= 0x3f;
L_a173:;
    if (v_14 > 0) goto L_a183;
    goto L_a190;
L_a17b:;
    v_14--;
    goto L_a173;
L_a183:;
    *(unsigned char *)(unsigned char *)(v_10++) = v_4;
    goto L_a17b;
L_a190:;
    goto L_a19d;
L_a192:;
    *(unsigned char *)(unsigned char *)(v_10++) = (signed char)v_14;
L_a19d:;
    goto L_a13e;
L_a19f:;
    v_c++;
    v_10 = a1 + v_20;
    v_14 = 0;
L_a1b5:;
    if (v_14 < 0x300) goto L_a1c8;
    goto L_a1e0;
L_a1c0:;
    v_14++;
    goto L_a1b5;
L_a1c8:;
    *(unsigned char *)(unsigned char *)(v_10++) = (unsigned char)(*(unsigned char *)(unsigned char *)(v_c++) >> 2);
    goto L_a1c0;
L_a1e0:;
    g_e1c4 = v_20 + 0x380;
    g_e1d0 = v_20 + 0x300;
    *(int *)a2 = a1;
    *(int *)(a2 + 8) = v_18;
    *(int *)(a2 + 0xc) = v_1c;
    *(int *)(a2 + 0x14) = 0x100;
    *(int *)(a2 + 0x10) = 4;
    *(int *)(a2 + 0x1c) = *(int *)(a2 + 0x14) * 3;
    *(int *)(a2 + 0x20) = *(int *)(a2 + 8) * *(int *)(a2 + 0xc);
    *(int *)(a2 + 0x18) = *(int *)(a2 + 0x1c) + *(int *)(a2 + 0x20);
    *(int *)(a2 + 4) = (int)(*(unsigned char * *)a2 + *(int *)(a2 + 0x20));
    v_24 = 0;
    return v_24;
}
