/* TU f_c685..f_c826 [0xc685, 0xc886): generated by tools/tu.py */
#include <string.h>
struct Pic { unsigned char *buf; unsigned char *pixels; int w; int h; int bpp; int ncolors; int pal_end; int palsize; int size; };
extern char *g_e270;
extern int g_e26c;
extern int g_7420;
extern int g_7430;
extern int g_7450;
extern int g_7458;
extern int g_7460;
extern int g_7464;
extern int g_745c;
extern int g_744c;
extern short g_7db8;
extern int g_7db4;
extern int f_dd53(int, int);
extern void f_c14b_lmdi(int, int, int, int);
extern void f_c20d(int);
extern void f_c3fb(void);
extern void f_c621(void);
extern void f_1133f(void);
extern void f_11377(int);
extern void *f_ddb9(int);
extern void f_de21(void *);
extern int f_11df8(int, int, int, void *);

int g_e2a4;
int g_e2a8;

int f_c685(int data, unsigned char *buf, struct Pic *pic)
{
    int unused;
    unsigned char *hdr;
    unsigned char *src;
    unsigned char *dst;
    int i;
    hdr = (unsigned char *)data;
    if (strcmp((char *)"mhwanh\0\4", (char *)hdr) != 0)
        return 0x301;
    pic->buf = buf;
    pic->w = ((*(short *)(hdr + 8) >> 8) & 0xff) | ((*(short *)(hdr + 8) << 8) & 0xff00);
    pic->h = ((*(short *)(hdr + 0xa) >> 8) & 0xff) | ((*(short *)(hdr + 0xa) << 8) & 0xff00);
    pic->ncolors = ((*(short *)(hdr + 0xc) >> 8) & 0xff) | ((*(short *)(hdr + 0xc) << 8) & 0xff00);
    pic->bpp = 5;
    pic->palsize = pic->ncolors * 3;
    pic->size = pic->w * pic->h;
    pic->pixels = pic->buf + pic->size;
    pic->pal_end = pic->size + pic->palsize;
    g_e2a8 = pic->size + 0x20 + pic->palsize;
    g_e2a4 = pic->size + pic->palsize;
    memcpy(buf, (void *)(data + 0x20 + pic->palsize), pic->size);
    dst = pic->pixels;
    src = (unsigned char *)(data + 0x20);
    for (i = 0; i < pic->palsize; i++)
        *dst++ = *src++ >> 2;
    return 0;
}

int f_c826(int a, int b, int c)
{
    int result;
    void * p;
    p = f_ddb9(0x6400);
    if (!p) {
        return 0x909;
    } else {
        result = f_11df8(a, b, c, p);
        f_de21(p);
        return result;
    }
}
