/* TU f_c685..f_c826 [0xc685, 0xc886): generated by tools/tu.py */
#include <string.h>
struct BitmapImage { unsigned char *buffer; unsigned char *pixels; int width; int height; int bits_per_pixel; int color_count; int palette_end; int palette_size; int pixel_size; };
struct CompactBitmapHeader {
    char signature[8];
    short width_be;
    short height_be;
    short color_count_be;
    unsigned char reserved[18];
};
#define GAME_BITMAP_SIGNATURE "mhwanh\0\4"
#define GAME_BITMAP_HEADER_BYTES 0x20
#define GIF_DECODE_WORKSPACE_BYTES 0x6400
#define ERROR_BAD_GAME_BITMAP 0x301
#define ERROR_GIF_WORKSPACE_ALLOCATION 0x909
extern char *audio_request_entries;
extern int audio_dma_memory;
extern int audio_dma_buffer_bytes;
extern int audio_buffer_offset;
extern int active_audio_mode;
extern int audio_dma_half_bytes;
extern int audio_dma_state;
extern int audio_dma_gap_bytes;
extern int last_audio_sample_rate;
extern int active_audio_rate;
extern short sound_dma_transfer_count;
extern int sound_dma_buffer_address;
extern int random_in_range(int, int);
extern void queue_audio(int, int, int, int);
extern void submit_audio_request(int);
extern void transfer_audio_stream_block(void);
extern void start_audio_stream_dma(void);
extern void configure_sound_dma_input(void);
extern void set_sound_blaster_sample_rate(int);
extern void *alloc_heap_block(int);
extern void free_heap_block(void *);
extern int decode_gif_image(int, int, int, void *);

int decoded_bitmap_bytes;
int decoded_image_bytes;

/* T08 imports these historical linker names; the C names describe the routines. */
#pragma aux decode_game_bitmap "f_c685";
#pragma aux decode_gif_with_workspace "f_c826";

/* Convert the game's compact bitmap and palette to a working image. */
int decode_game_bitmap(int image_data, unsigned char *output_buffer, struct BitmapImage *image)
{
    int unused;
    struct CompactBitmapHeader *header;
    unsigned char *palette_source;
    unsigned char *pixel_output;
    int index;
    header = (struct CompactBitmapHeader *)image_data;
    if (strcmp((char *)GAME_BITMAP_SIGNATURE, (char *)header) != 0)
        return ERROR_BAD_GAME_BITMAP;
    image->buffer = output_buffer;
    image->width = ((header->width_be >> 8) & 0xff) | ((header->width_be << 8) & 0xff00);
    image->height = ((header->height_be >> 8) & 0xff) | ((header->height_be << 8) & 0xff00);
    image->color_count = ((header->color_count_be >> 8) & 0xff) | ((header->color_count_be << 8) & 0xff00);
    image->bits_per_pixel = 5;
    image->palette_size = image->color_count * 3;
    image->pixel_size = image->width * image->height;
    image->pixels = image->buffer + image->pixel_size;
    image->palette_end = image->pixel_size + image->palette_size;
    decoded_image_bytes = image->pixel_size + GAME_BITMAP_HEADER_BYTES + image->palette_size;
    decoded_bitmap_bytes = image->pixel_size + image->palette_size;
    memcpy(output_buffer, (void *)(image_data + GAME_BITMAP_HEADER_BYTES + image->palette_size), image->pixel_size);
    pixel_output = image->pixels;
    palette_source = (unsigned char *)(image_data + GAME_BITMAP_HEADER_BYTES);
    for (index = 0; index < image->palette_size; index++)
        *pixel_output++ = *palette_source++ >> 2;
    return 0;
}

int decode_gif_with_workspace(int source_size, int source_data, int image_state)
{
    int result;
    void * workspace;
    workspace = alloc_heap_block(GIF_DECODE_WORKSPACE_BYTES);
    if (!workspace) {
        return ERROR_GIF_WORKSPACE_ALLOCATION;
    } else {
        result = decode_gif_image(source_size, source_data, image_state, workspace);
        free_heap_block(workspace);
        return result;
    }
}
