/* These aliases keep descriptive names while preserving verified BSS linker names. */
#define primary_joystick_two_frames_ago primary_joystick_two_frames_ago_0n
#define secondary_joystick secondary_joystick_u
#define secondary_joystick_three_frames_ago secondary_joystick_three_frames_ago_9
#define primary_joystick_three_frames_ago primary_joystick_three_frames_ago_12
#define current_key_code_01 current_key_code_01
#define scan_code current_scan_code
#define JOYSTICK_GAMEPORT 0x201
#define JOYSTICK_PROBE_POLL_LIMIT 1000
#define JOYSTICK_MIN_AXIS_TICKS 0x20

enum JoystickTimingSlot {
    JOY_X_CURRENT,
    JOY_Y_CURRENT,
    JOY_X_LEFT_THRESHOLD,
    JOY_X_RIGHT_THRESHOLD,
    JOY_Y_TOP_THRESHOLD,
    JOY_Y_BOTTOM_THRESHOLD,
    JOY_X_MINIMUM,
    JOY_X_CENTER,
    JOY_X_MAXIMUM,
    JOY_Y_MINIMUM,
    JOY_Y_CENTER,
    JOY_Y_MAXIMUM
};

struct JoystickState {
    unsigned int button_bits;
    short axis_timing[12];
};
struct JoystickState primary_joystick;
struct JoystickState secondary_joystick_two_frames_ago;
struct JoystickState secondary_joystick_three_frames_ago;
struct JoystickState secondary_joystick;
struct JoystickState primary_joystick_three_frames_ago;
struct JoystickState primary_joystick_one_frame_ago;
struct JoystickState secondary_joystick_one_frame_ago;
struct JoystickState primary_joystick_two_frames_ago;
/* TU detect_joystick..initialize_joystick_calibration [0xeeac, 0xf690): generated by tools/tu.py */
extern int outp(int, int);
extern int inp(int);
extern void initialize_joystick_calibration(void);
extern void measure_joystick_axes(void);
extern void update_joystick_directions(void);
void poll_joystick_ports(void);
extern void _disable(void);
extern void _enable(void);
extern unsigned char scan_code;
extern unsigned char current_key_code_01;
extern void poll_keyboard(void);
extern void recalculate_joystick_thresholds(void);
/* _DATA [0x7b28,0x7b34) */
short joystick_available = 0;
int joystick_calibration_active = 0;
int joystick_max_axis_time = 0x3e8;
/* The PC gameport uses changing axis timing; an unchanged all-ones read means no stick. */
int detect_joystick(void) {
    unsigned char first_port_sample;
    unsigned char second_port_sample;
    int poll_attempt;
    outp(JOYSTICK_GAMEPORT, 0xff);
    for (poll_attempt = 0; poll_attempt < JOYSTICK_PROBE_POLL_LIMIT; poll_attempt++) {
        first_port_sample = (unsigned char)inp(JOYSTICK_GAMEPORT);
        if (first_port_sample == 0xff) break;
    }
    for (poll_attempt = 0; poll_attempt < JOYSTICK_PROBE_POLL_LIMIT; poll_attempt++) {
        second_port_sample = (unsigned char)inp(JOYSTICK_GAMEPORT);
        if (second_port_sample != first_port_sample) break;
    }
    if (first_port_sample != second_port_sample || first_port_sample != 0xff || second_port_sample != 0xff) {
        initialize_joystick_calibration();
        if (primary_joystick.axis_timing[JOY_X_CURRENT] < JOYSTICK_MIN_AXIS_TICKS || primary_joystick.axis_timing[JOY_Y_CURRENT] < JOYSTICK_MIN_AXIS_TICKS) {
            joystick_available = 0;
            return joystick_available;
        }
        joystick_available = -1;
        return joystick_available;
    }
    joystick_available = 0;
    return joystick_available;
}

void poll_joystick_ports(void) {
    outp(JOYSTICK_GAMEPORT, 0xff);
    measure_joystick_axes();
    outp(JOYSTICK_GAMEPORT, 0xff);
    update_joystick_directions();
    outp(JOYSTICK_GAMEPORT, 0xff);
}

void measure_joystick_axes(void) {
    unsigned char axis_status;
    unsigned char pending_axis_mask;
    int elapsed_ticks;
    pending_axis_mask = 0x0f;
    elapsed_ticks = 0;
    _disable();
    do {
        axis_status = (unsigned char)(inp(JOYSTICK_GAMEPORT) & 0x0f);
        if (axis_status != pending_axis_mask) {
            axis_status ^= pending_axis_mask;
            if ((axis_status & 1) == 1) {
                pending_axis_mask ^= 1;
                primary_joystick.axis_timing[JOY_X_CURRENT] = elapsed_ticks;
            }
            else if (axis_status & 2) {
                pending_axis_mask ^= 2;
                primary_joystick.axis_timing[JOY_Y_CURRENT] = elapsed_ticks;
            }
            else if (axis_status & 4) {
                pending_axis_mask ^= 4;
                secondary_joystick.axis_timing[JOY_X_CURRENT] = elapsed_ticks;
            }
            else if (axis_status & 8) {
                pending_axis_mask ^= 8;
                secondary_joystick.axis_timing[JOY_Y_CURRENT] = elapsed_ticks;
            }
        }
        ++elapsed_ticks;
        if (elapsed_ticks > joystick_max_axis_time) {
            if (joystick_calibration_active != 0) break;
            if ((axis_status & 1) == 1) primary_joystick.axis_timing[JOY_X_CURRENT] = elapsed_ticks;
            else if (axis_status & 2) primary_joystick.axis_timing[JOY_Y_CURRENT] = elapsed_ticks;
            else if (axis_status & 4) secondary_joystick.axis_timing[JOY_X_CURRENT] = elapsed_ticks;
            else if (axis_status & 8) secondary_joystick.axis_timing[JOY_Y_CURRENT] = elapsed_ticks;
            pending_axis_mask = 0;
        }
    }
    while (pending_axis_mask != 0);
    loop_exit:
    _enable();
}

/* Shift input history, then combine axis thresholds and active-axis_timing_too_short buttons. */
void update_joystick_directions(void) {
    unsigned char gameport_button_bits;
    gameport_button_bits = (unsigned char)inp(JOYSTICK_GAMEPORT);
    primary_joystick_three_frames_ago.button_bits = primary_joystick_two_frames_ago.button_bits;
    secondary_joystick_three_frames_ago.button_bits = secondary_joystick_two_frames_ago.button_bits;
    primary_joystick_two_frames_ago.button_bits = primary_joystick_one_frame_ago.button_bits;
    secondary_joystick_two_frames_ago.button_bits = secondary_joystick_one_frame_ago.button_bits;
    primary_joystick_one_frame_ago.button_bits = primary_joystick.button_bits;
    secondary_joystick_one_frame_ago.button_bits = secondary_joystick.button_bits;
    secondary_joystick.button_bits = 0;
    primary_joystick.button_bits = secondary_joystick.button_bits;
    if (primary_joystick.axis_timing[JOY_X_CURRENT] < primary_joystick.axis_timing[JOY_X_LEFT_THRESHOLD]) *(unsigned char *)&primary_joystick.button_bits |= 1;
    else if (primary_joystick.axis_timing[JOY_X_CURRENT] > primary_joystick.axis_timing[JOY_X_RIGHT_THRESHOLD]) *(unsigned char *)&primary_joystick.button_bits |= 2;
    if (primary_joystick.axis_timing[JOY_Y_CURRENT] < primary_joystick.axis_timing[JOY_Y_TOP_THRESHOLD]) *(unsigned char *)&primary_joystick.button_bits |= 4;
    else if (primary_joystick.axis_timing[JOY_Y_CURRENT] > primary_joystick.axis_timing[JOY_Y_BOTTOM_THRESHOLD]) *(unsigned char *)&primary_joystick.button_bits |= 8;
    if (secondary_joystick.axis_timing[JOY_X_CURRENT] < secondary_joystick.axis_timing[JOY_X_LEFT_THRESHOLD]) *(unsigned char *)&secondary_joystick.button_bits |= 1;
    else if (secondary_joystick.axis_timing[JOY_X_CURRENT] > secondary_joystick.axis_timing[JOY_X_RIGHT_THRESHOLD]) *(unsigned char *)&secondary_joystick.button_bits |= 2;
    if (secondary_joystick.axis_timing[JOY_Y_CURRENT] < secondary_joystick.axis_timing[JOY_Y_TOP_THRESHOLD]) *(unsigned char *)&secondary_joystick.button_bits |= 4;
    else if (secondary_joystick.axis_timing[JOY_Y_CURRENT] > secondary_joystick.axis_timing[JOY_Y_BOTTOM_THRESHOLD]) *(unsigned char *)&secondary_joystick.button_bits |= 8;
    if (!(gameport_button_bits & 0x10)) *(unsigned char *)&primary_joystick.button_bits |= 0x10;
    if (!(gameport_button_bits & 0x20)) *(unsigned char *)&primary_joystick.button_bits |= 0x20;
    if (!(gameport_button_bits & 0x40)) *(unsigned char *)&secondary_joystick.button_bits |= 0x10;
    if (!(gameport_button_bits & 0x80)) *(unsigned char *)&secondary_joystick.button_bits |= 0x20;
}

void capture_joystick_center(void) {
    do {
        outp(JOYSTICK_GAMEPORT, 0xff);
    }
    while ((inp(JOYSTICK_GAMEPORT) & 0xf0) != 0xf0);
    do {
        poll_joystick_ports();
        poll_keyboard();
    }
    while (scan_code == current_key_code_01 && (inp(JOYSTICK_GAMEPORT) & 0xf0) == 0xf0);
    primary_joystick.axis_timing[JOY_X_CENTER] = primary_joystick.axis_timing[JOY_X_CURRENT];
    primary_joystick.axis_timing[JOY_Y_CENTER] = primary_joystick.axis_timing[JOY_Y_CURRENT];
    secondary_joystick.axis_timing[JOY_X_CENTER] = secondary_joystick.axis_timing[JOY_X_CURRENT];
    secondary_joystick.axis_timing[JOY_Y_CENTER] = secondary_joystick.axis_timing[JOY_Y_CURRENT];
    recalculate_joystick_thresholds();
    outp(JOYSTICK_GAMEPORT, 0xff);
}

void capture_joystick_minimums(void) {
    do {
        outp(JOYSTICK_GAMEPORT, 0xff);
    }
    while ((inp(JOYSTICK_GAMEPORT) & 0xf0) != 0xf0);
    do {
        poll_joystick_ports();
        poll_keyboard();
    }
    while (scan_code == current_key_code_01 && (inp(JOYSTICK_GAMEPORT) & 0xf0) == 0xf0);
    primary_joystick.axis_timing[JOY_X_MINIMUM] = primary_joystick.axis_timing[JOY_X_CURRENT];
    primary_joystick.axis_timing[JOY_Y_MINIMUM] = primary_joystick.axis_timing[JOY_Y_CURRENT];
    secondary_joystick.axis_timing[JOY_X_MINIMUM] = secondary_joystick.axis_timing[JOY_X_CURRENT];
    secondary_joystick.axis_timing[JOY_Y_MINIMUM] = secondary_joystick.axis_timing[JOY_Y_CURRENT];
    recalculate_joystick_thresholds();
    outp(JOYSTICK_GAMEPORT, 0xff);
}

void capture_joystick_maximums(void) {
    do {
        outp(JOYSTICK_GAMEPORT, 0xff);
    }
    while ((inp(JOYSTICK_GAMEPORT) & 0xf0) != 0xf0);
    do {
        poll_joystick_ports();
        poll_keyboard();
    }
    while (scan_code == current_key_code_01 && (inp(JOYSTICK_GAMEPORT) & 0xf0) == 0xf0);
    primary_joystick.axis_timing[JOY_X_MAXIMUM] = primary_joystick.axis_timing[JOY_X_CURRENT];
    primary_joystick.axis_timing[JOY_Y_MAXIMUM] = primary_joystick.axis_timing[JOY_Y_CURRENT];
    secondary_joystick.axis_timing[JOY_X_MAXIMUM] = secondary_joystick.axis_timing[JOY_X_CURRENT];
    secondary_joystick.axis_timing[JOY_Y_MAXIMUM] = secondary_joystick.axis_timing[JOY_Y_CURRENT];
    recalculate_joystick_thresholds();
    outp(JOYSTICK_GAMEPORT, 0xff);
}

void recalculate_joystick_thresholds(void) {
    primary_joystick.axis_timing[JOY_X_LEFT_THRESHOLD] = (primary_joystick.axis_timing[JOY_X_MINIMUM] + primary_joystick.axis_timing[JOY_X_CENTER]) >> 1;
    secondary_joystick.axis_timing[JOY_X_LEFT_THRESHOLD] = (secondary_joystick.axis_timing[JOY_X_MINIMUM] + secondary_joystick.axis_timing[JOY_X_CENTER]) >> 1;
    primary_joystick.axis_timing[JOY_X_RIGHT_THRESHOLD] = (primary_joystick.axis_timing[JOY_X_CENTER] + primary_joystick.axis_timing[JOY_X_MAXIMUM]) >> 1;
    secondary_joystick.axis_timing[JOY_X_RIGHT_THRESHOLD] = (secondary_joystick.axis_timing[JOY_X_CENTER] + secondary_joystick.axis_timing[JOY_X_MAXIMUM]) >> 1;
    primary_joystick.axis_timing[JOY_Y_TOP_THRESHOLD] = (primary_joystick.axis_timing[JOY_Y_MINIMUM] + primary_joystick.axis_timing[JOY_Y_CENTER]) >> 1;
    secondary_joystick.axis_timing[JOY_Y_TOP_THRESHOLD] = (secondary_joystick.axis_timing[JOY_Y_MINIMUM] + secondary_joystick.axis_timing[JOY_Y_CENTER]) >> 1;
    primary_joystick.axis_timing[JOY_Y_BOTTOM_THRESHOLD] = (primary_joystick.axis_timing[JOY_Y_CENTER] + primary_joystick.axis_timing[JOY_Y_MAXIMUM]) >> 1;
    secondary_joystick.axis_timing[JOY_Y_BOTTOM_THRESHOLD] = (secondary_joystick.axis_timing[JOY_Y_CENTER] + secondary_joystick.axis_timing[JOY_Y_MAXIMUM]) >> 1;
    joystick_max_axis_time = primary_joystick.axis_timing[JOY_X_RIGHT_THRESHOLD];
    if (primary_joystick.axis_timing[JOY_Y_BOTTOM_THRESHOLD] > joystick_max_axis_time) joystick_max_axis_time = primary_joystick.axis_timing[JOY_Y_BOTTOM_THRESHOLD];
    if (secondary_joystick.axis_timing[JOY_X_RIGHT_THRESHOLD] > joystick_max_axis_time) joystick_max_axis_time = secondary_joystick.axis_timing[JOY_X_RIGHT_THRESHOLD];
    if (secondary_joystick.axis_timing[JOY_Y_BOTTOM_THRESHOLD] > joystick_max_axis_time) joystick_max_axis_time = secondary_joystick.axis_timing[JOY_Y_BOTTOM_THRESHOLD];
}

/* Capture neutral X/Y samples, then seed min/max bounds around the center. */
void initialize_joystick_calibration(void) {
    primary_joystick.axis_timing[JOY_X_CURRENT] = 0;
    primary_joystick.axis_timing[JOY_Y_CURRENT] = 0;
    secondary_joystick.axis_timing[JOY_X_CURRENT] = 0;
    secondary_joystick.axis_timing[JOY_Y_CURRENT] = 0;
    joystick_calibration_active = 1;
    poll_joystick_ports();
    poll_joystick_ports();
    joystick_calibration_active = 0;
    primary_joystick.axis_timing[JOY_X_MINIMUM] = 0;
    primary_joystick.axis_timing[JOY_Y_MINIMUM] = 0;
    secondary_joystick.axis_timing[JOY_X_MINIMUM] = 0;
    secondary_joystick.axis_timing[JOY_Y_MINIMUM] = 0;
    primary_joystick.axis_timing[JOY_X_CENTER] = primary_joystick.axis_timing[JOY_X_CURRENT];
    primary_joystick.axis_timing[JOY_Y_CENTER] = primary_joystick.axis_timing[JOY_Y_CURRENT];
    secondary_joystick.axis_timing[JOY_X_CENTER] = secondary_joystick.axis_timing[JOY_X_CURRENT];
    secondary_joystick.axis_timing[JOY_Y_CENTER] = secondary_joystick.axis_timing[JOY_Y_CURRENT];
    primary_joystick.axis_timing[JOY_X_MAXIMUM] = primary_joystick.axis_timing[JOY_X_CURRENT] * 2;
    primary_joystick.axis_timing[JOY_Y_MAXIMUM] = primary_joystick.axis_timing[JOY_Y_CURRENT] * 2;
    secondary_joystick.axis_timing[JOY_X_MAXIMUM] = secondary_joystick.axis_timing[JOY_X_CURRENT] * 2;
    secondary_joystick.axis_timing[JOY_Y_MAXIMUM] = secondary_joystick.axis_timing[JOY_Y_CURRENT] * 2;
    recalculate_joystick_thresholds();
    outp(JOYSTICK_GAMEPORT, 0xff);
}
