/* These aliases keep descriptive names while preserving verified BSS linker names. */
#define saved_mouse_sensitivity_y saved_mouse_sensitivity_y_6r
#define saved_mouse_sensitivity_x saved_mouse_sensitivity_x_6u
#define mouse_x_sample_5 mouse_x_sample_5_0g
#define mouse_y_sample_5 mouse_y_sample_5_02
#define mouse_y_sample_7 mouse_y_sample_7_04
#define mouse_x_sample_7 mouse_x_sample_7_n
#define mouse_x_sample_6 mouse_x_sample_6_q
#define mouse_y_sample_6 mouse_y_sample_6_05
#define mouse_x_sample_4 mouse_x_sample_4_0f
#define mouse_y_sample_4 mouse_y_sample_4_03
#define mouse_sensitivity_threshold mouse_sensitivity_threshold_5m
#define mouse_sensitivity_x mouse_sensitivity_x_o
#define mouse_sensitivity_y mouse_sensitivity_y_9
#define mouse_y_sample_3 mouse_y_sample_3_a1
#define mouse_x_sample_3 mouse_x_sample_3_0s
#define mouse_x_sample_2 mouse_x_sample_2_0s
#define mouse_y_sample_2 mouse_y_sample_2_1a
#define smoothed_mouse_y smoothed_mouse_y_0f
#define mouse_x_sample_1 mouse_x_sample_1_6
#define mouse_x_sample_0 mouse_x_sample_0_f
#define previous_smoothed_mouse_y previous_smoothed_mouse_y_0t
#define mouse_y_recent_average mouse_y_recent_average_g
#define mouse_x_recent_average mouse_x_recent_average_1c

short mouse_sensitivity_y;
short previous_smoothed_mouse_y;
short previous_smoothed_mouse_x;
short mouse_y_recent_average;
short mouse_x_recent_average;
short mouse_y_sample_0;
/* TU initialize_mouse_driver..move_mouse_to [0xffbe, 0x105a7): generated by tools/tu.py */
#include <i86.h>
#include <stdlib.h>
short mouse_x_sample_8;
short smoothed_mouse_y;
short mouse_y_sample_1;
short mouse_x_sample_1;
short mouse_x_sample_0;
void save_mouse_sensitivity(void);
extern void query_mouse_sensitivity(void);
extern void restore_mouse_sensitivity(void);
extern void restore_mouse_driver_sensitivity(void);
extern void set_mouse_horizontal_bounds(int, int);
extern void set_mouse_vertical_bounds(int, int);
enum MouseDriverFunction {
    MOUSE_RESET = 0,
    MOUSE_GET_POSITION_AND_BUTTONS = 3,
    MOUSE_SET_POSITION = 4,
    MOUSE_SET_HORIZONTAL_RANGE = 7,
    MOUSE_SET_VERTICAL_RANGE = 8,
    MOUSE_GET_SENSITIVITY = 0x1b,
    MOUSE_SET_SENSITIVITY = 0x1a,
    MOUSE_GET_VERSION = 0x24
};

short mouse_available = 0;
unsigned short mouse_btn = 0;
unsigned short mouse_btn_old = 0;
unsigned int mouse_driver_version = 0xffffffff;
short mouse_y_sample_4;
short mouse_x_sample_4;
short mouse_y_sample_6;
short mouse_x_sample_6;
short mouse_x_sample_7;
short mouse_y_sample_7;
short mouse_y_sample_5;
short mouse_x_sample_5;
short saved_mouse_sensitivity_x;
short saved_mouse_sensitivity_y;
short saved_mouse_sensitivity_threshold;
short mouse_sensitivity_threshold;
short mouse_x_sample_3;
short mouse_y_sample_3;
short mouse_sensitivity_x;
short mouse_x_sample_2;
short mouse_y_sample_2;
short mouse_settings_saved = 0;
int initialize_mouse_driver(void) {
    unsigned int *mouse_vector_entry = (unsigned int *)0xcc;
    union REGS regs;

    if (*mouse_vector_entry != 0) {
        regs.w.ax = 0;
        int386(0x33, &regs, &regs);
        if (regs.w.ax == -1) {
            mouse_available = -1;
            regs.w.ax = 0x24;
            int386(0x33, &regs, &regs);
            mouse_driver_version = regs.w.bx;
            save_mouse_sensitivity();
            return mouse_available;
        }
    }
    mouse_available = 0;
    return mouse_available;
}

void save_mouse_sensitivity(void) {
    if (mouse_settings_saved != -1) {
        query_mouse_sensitivity();
        saved_mouse_sensitivity_x=mouse_sensitivity_x;
        saved_mouse_sensitivity_y=mouse_sensitivity_y;
        saved_mouse_sensitivity_threshold=mouse_sensitivity_threshold;
        atexit(restore_mouse_sensitivity);
        mouse_settings_saved=-1;
    }
}

void restore_mouse_sensitivity(void) {
    if (mouse_settings_saved == -1) {
        mouse_sensitivity_x=saved_mouse_sensitivity_x;
        mouse_sensitivity_y=saved_mouse_sensitivity_y;
        mouse_sensitivity_threshold=saved_mouse_sensitivity_threshold;
        restore_mouse_driver_sensitivity();
        mouse_settings_saved=1;
    }
}

void set_mouse_bounds(int x_min, int y_min, int x_max, int y_max) {
    if (mouse_available == -1) {
        set_mouse_horizontal_bounds(x_min,x_max);
        set_mouse_vertical_bounds(y_min,y_max);
    }
}

/* Shift eight half-resolution samples and maintain four- and eight-sample averages. */
void update_mouse(void) {
    if(mouse_available==-1) {
        union REGS regs;
        mouse_btn_old=mouse_btn;
        mouse_x_sample_7=mouse_x_sample_6;
        mouse_x_sample_6=mouse_x_sample_5;
        mouse_x_sample_5=mouse_x_sample_4;
        mouse_x_sample_4=mouse_x_sample_3;
        mouse_y_sample_7=mouse_y_sample_6;
        mouse_y_sample_6=mouse_y_sample_5;
        mouse_y_sample_5=mouse_y_sample_4;
        mouse_y_sample_4=mouse_y_sample_3;
        mouse_x_sample_3=mouse_x_sample_2;
        mouse_x_sample_2=mouse_x_sample_1;
        mouse_x_sample_1=mouse_x_sample_0;
        mouse_y_sample_3=mouse_y_sample_2;
        mouse_y_sample_2=mouse_y_sample_1;
        mouse_y_sample_1=mouse_y_sample_0;
        regs.w.ax=3;
        int386(0x33,&regs,&regs);
        mouse_btn=regs.x.ebx;
        mouse_x_sample_0=regs.w.cx>>1;
        mouse_y_sample_0=regs.w.dx>>1;
        previous_smoothed_mouse_x=mouse_x_recent_average;
        previous_smoothed_mouse_y=mouse_y_recent_average;
        mouse_x_recent_average=(mouse_x_sample_0+mouse_x_sample_1+mouse_x_sample_2+mouse_x_sample_3)>>2;
        mouse_x_sample_8=mouse_x_recent_average;
        mouse_y_recent_average=(mouse_y_sample_0+mouse_y_sample_1+mouse_y_sample_2+mouse_y_sample_3)>>2;
        mouse_x_sample_8=mouse_y_recent_average;
        mouse_x_sample_8=(mouse_x_sample_0+mouse_x_sample_1+mouse_x_sample_2+mouse_x_sample_3+mouse_x_sample_4+mouse_x_sample_5+mouse_x_sample_6+mouse_x_sample_7)>>3;
        smoothed_mouse_y=(mouse_y_sample_0+mouse_y_sample_1+mouse_y_sample_2+mouse_y_sample_3+mouse_y_sample_4+mouse_y_sample_5+mouse_y_sample_6+mouse_y_sample_7)>>3;
    }
}

void query_mouse_sensitivity(void) {
    if (mouse_available == -1) {
        union REGS regs;
        regs.w.ax=0x1b;
        int386(0x33,&regs,&regs);
        mouse_sensitivity_x=regs.x.ebx;
        mouse_sensitivity_y=regs.x.ecx;
        mouse_sensitivity_threshold=regs.x.edx;
    }
}

void restore_mouse_driver_sensitivity(void) {
    if (mouse_available == -1) {
        union REGS regs;
        regs.w.bx=mouse_sensitivity_x;
        regs.w.cx=mouse_sensitivity_y;
        regs.w.dx=mouse_sensitivity_threshold;
        regs.w.ax=0x1a;
        int386(0x33,&regs,&regs);
    }
}

void set_mouse_horizontal_bounds(int minimum_x,int maximum_x) {
    if (mouse_available == -1) {
        union REGS regs;
        int swap_temp;
        if (minimum_x>maximum_x) {
            swap_temp=minimum_x;
            minimum_x=maximum_x;
            maximum_x=swap_temp;
        }
        if (minimum_x<0) minimum_x=0;
        if (maximum_x<0) maximum_x=0;
        regs.w.ax=7;
        regs.w.cx=minimum_x*2;
        regs.w.dx=maximum_x*2;
        int386(0x33,&regs,&regs);
    }
}

void set_mouse_vertical_bounds(int minimum_y,int maximum_y) {
    if (mouse_available == -1) {
        union REGS regs;
        int swap_temp;
        if (minimum_y>maximum_y) {
            swap_temp=minimum_y;
            minimum_y=maximum_y;
            maximum_y=swap_temp;
        }
        if (minimum_y<0) minimum_y=0;
        if (maximum_y<0) maximum_y=0;
        regs.w.ax=8;
        regs.w.cx=minimum_y*2;
        regs.w.dx=maximum_y*2;
        int386(0x33,&regs,&regs);
    }
}

void move_mouse_to(int x,int y) {
    if (mouse_available == -1) {
        union REGS regs;
        regs.w.ax=4;
        regs.w.cx=x*2;
        regs.w.dx=y*2;
        int386(0x33,&regs,&regs);
        mouse_x_sample_2=x;
        mouse_x_sample_1=mouse_x_sample_2;
        mouse_x_sample_0=mouse_x_sample_1;
        mouse_x_recent_average=mouse_x_sample_0;
        mouse_y_sample_2=y;
        mouse_y_sample_1=mouse_y_sample_2;
        mouse_y_sample_0=mouse_y_sample_1;
        mouse_y_recent_average=mouse_y_sample_0;
    }
}
