/* These aliases keep descriptive names while preserving verified BSS linker names. */
#define current_file_length current_file_size_bytes
#define file_bytes_written file_output_bytes_written

unsigned int current_file_name;
unsigned int file_bytes_written;
/* TU ignore_file_data..load_next_file [0x105a7, 0x108a9): generated by tools/tu.py */
#include <stdio.h>
/* These original link names are used by the byte-sensitive T08 picture loader. */
#pragma aux read_file_with_decoder "f_1065b";
#pragma aux file_bytes_read "g_e4c8";
#pragma aux file_buffer_cursor "g_e4d0_wfmxdlyju";
#pragma aux file_buffer_limit "g_7c0c";
unsigned int file_bytes_read;
unsigned int current_file_length;
unsigned int file_buffer_cursor;
int read_file_with_decoder(char *name, void *buf);
enum FileOperationError {
    FILE_ERROR_OPEN = 0x201,
    FILE_ERROR_READ = 0x203,
    FILE_ERROR_WRITE = 0x204,
    FILE_ERROR_SEEK = 0x205,
    FILE_ERROR_TELL = 0x206,
    FILE_ERROR_BUFFER_OVERFLOW = 0x207
};

int ignore_file_data(void);
unsigned int file_error_state = 0;
unsigned int file_buffer_limit = 1000000000;
unsigned int decode_hook = (unsigned int)ignore_file_data;
unsigned int file_load_nesting_state = 0xffffffff;
int ignore_file_data(void) {
    return 0;
}

int get_file_length(char * file_path) {
    FILE * file;
    int error_code;
    current_file_name=(unsigned int)file_path;
    file=fopen(file_path,"r+b");
    if(file==0) error_code=FILE_ERROR_OPEN;
    else {
        if(fseek(file,0,2)!=0) error_code=FILE_ERROR_SEEK;
        else {
            current_file_length=(unsigned int)ftell(file);
            if(current_file_length==0xffffffffU) error_code=FILE_ERROR_TELL;
            else error_code=0;
        }
        fclose(file);
    }
    return error_code;
}

/* The decoder return value is the unconsumed tail; the shared cursor advances past bytes read. */
int read_file_with_decoder(char * file_path,void * destination_buffer) {
    FILE * file;
    int error_code;
    int decode_status;
    unsigned int file_length;
    ++file_load_nesting_state;
    current_file_name=(unsigned int)file_path;
    file=fopen(file_path,"r+b");
    if(file==0) error_code=FILE_ERROR_OPEN;
    else {
        if(fseek(file,0,2)!=0) error_code=FILE_ERROR_SEEK;
        else {
            file_length=(unsigned int)ftell(file);
            if(file_length==0xffffffffU) error_code=FILE_ERROR_TELL;
            else {
                if(fseek(file,0,0)!=0) error_code=FILE_ERROR_SEEK;
                else {
                    if((unsigned int)destination_buffer+file_length>file_buffer_limit && file_load_nesting_state!=0) error_code=FILE_ERROR_BUFFER_OVERFLOW;
                    else {
                        file_bytes_read=(unsigned int)fread(destination_buffer,1,file_length,file);
                        if(file_bytes_read!=file_length) error_code=FILE_ERROR_READ;
                        else {
                            decode_status=((int (*)(void *,unsigned int))decode_hook)(destination_buffer,file_bytes_read);
                            if(decode_status<0) {
                                 file_error_state=0;
                                file_buffer_cursor=file_error_state;
                            }
                            else {
                                file_bytes_read-=decode_status;
                                error_code=0;
                            }
                        }
                    }
                }
            }
        }
        fclose(file);
    }
    file_load_nesting_state=0xffffffffU;
    return error_code;
}

int write_file_buffer(char * file_path,void * source_buffer,unsigned int byte_count) {
    FILE * file;
    int error_code;
    current_file_name=(unsigned int)file_path;
    file=fopen(file_path,"w+b");
    if(file==0) error_code=FILE_ERROR_OPEN;
    else {
        if(fseek(file,0,0)!=0) error_code=FILE_ERROR_SEEK;
        else {
            file_bytes_written=(unsigned int)fwrite(source_buffer,1,byte_count,file);
            if(file_bytes_written!=byte_count) error_code=FILE_ERROR_WRITE;
            else error_code=0;
        }
        fclose(file);
    }
    return error_code;
}

int load_next_file(char * file_path) {
    int read_status;
    --file_load_nesting_state;
    read_status=read_file_with_decoder(file_path,(void *)file_buffer_cursor);
    file_buffer_cursor+=file_bytes_read;
    file_buffer_cursor=(file_buffer_cursor+3)&0xfffffffcU;
    return read_status;
}
