/* These aliases keep descriptive names while preserving verified BSS linker names. */
#define fatal_error_message fatal_message_pointer
#define prior_key_ascii prior_key_ascii
#define ascii_key current_ascii
#define PIC_MASTER_MASK_PORT 0x21
#define PIC_IRQ0_MASK 0x01
#define PIC_MASK_WITH_IRQ0_CLEARED -2
#define JOYSTICK_IO_PORT 0x201

/* TU sys_report..print_encoded_version [0x108a9, 0x11256): generated by tools/tu.py */
#include <stdio.h>
#include <conio.h>
#include <stdlib.h>
#include <i86.h>
extern int probe_cpu_environment(void);
extern int read_dos_version(void);
extern int detect_windows_environment(void);
extern int detect_vga_bios_mode(void);
extern int detect_xms_driver(void);
extern int check_ems_manager_signature(void);
extern int detect_ems_manager(void);
extern int detect_dpmi_host(void);
extern int query_largest_dos_free_block(void);
extern int alloc_heap_block(int);
extern int free_heap_block(int);
extern int detect_sound_blaster(void);
extern int initialize_mouse_driver(void);
extern int detect_joystick(void);
extern void poll_keyboard(void);
extern int verify_timer(void);
extern int f_9f64(void);
extern unsigned int allocate_dpmi_memory(int);
extern unsigned int query_largest_dpmi_free_block(void);
extern void free_dpmi_memory(unsigned int);
extern void print_encoded_version(int);
extern void set_mouse_bounds(int, int, int, int);
extern void move_mouse_to(int, int);
extern int set_display_mode(int);
extern long cpu_type;
extern unsigned long cpu_mode;
extern unsigned long cpu_iopl;
extern long largest_dos_free_block_bytes;
extern unsigned int dpmi_err;
extern unsigned int dos_memory_error;
extern unsigned int dpmi_selector_or_failure_marker;
extern unsigned int heap_block;
extern unsigned int mouse_driver_version;
extern unsigned int file_error;
extern int (*decode_hook)();
/* VGA mode geometry, page bookkeeping, and the register state restored by the video layer. */
struct DisplayModeInfo {
    short render_state;
    int plane_addresses_or_transform_a[4];
    int page_offsets_or_transform_b[4];
    int page_adjustments_or_transform_c[4];
    unsigned char page_mode_classes[4];
    int buffer_size_or_draw_parameter;
    int row_stride;
    int resolution_height;
    int screen_width;
    int screen_height;
    int viewport_left;
    int viewport_top;
    int viewport_right_or_width;
    int viewport_bottom_or_height;
    unsigned char mode_flags;
    unsigned char sequencer_plane_mask;
    unsigned char graphics_read_map;
    unsigned char reserved_vga_byte;
    unsigned char saved_video_mode;
    unsigned char graphics_controller_mode;
    unsigned char render_cache_60;
    unsigned char render_cache_61;
    unsigned char render_cache_62;
    unsigned char tail;
};
extern struct DisplayModeInfo vga_state;
extern unsigned long keyboard_hook_flags;
extern unsigned long irq_flags;
extern short page_idx;
extern unsigned int sound_blaster_mixer_test;
extern short key_irq;
extern unsigned char sound_blaster_irq;
extern unsigned char sound_blaster_dma_channel;
union KeyboardKeyBitmap {
    unsigned short word;
    struct {
        unsigned char low, high;
    }
    bytes;
};
extern union KeyboardKeyBitmap translated_key_bitmap[8];
extern unsigned char prior_key_ascii;
extern unsigned char ascii_key;
extern unsigned long dos_version_packed;
extern unsigned long windows_mode_code;
extern unsigned long vga_bios_version;
extern unsigned long xms_driver_version;
extern unsigned long ems_manager_version;
extern unsigned long ems_manager_handle;
extern unsigned long dpmi_version_bcd;
extern unsigned long sound_blaster_dsp_version;
extern short sound_blaster_base_port;
extern short timer_ok;
extern void restore_system_interrupt_vectors(void);
extern void fatal_exit(unsigned long, unsigned long);
extern void dispatch_keyboard(void);
extern void update_mouse(void);
extern void poll_joystick_ports(void);
extern int set_vga_display_start(int);
extern int initialize_keyboard_manager(int);
extern int start_timer(int);
extern void wait_for_tick(unsigned char);
extern short keyboard_state;
extern void (*key_action_hook)(unsigned long, unsigned long);
extern short *kbd_state_ptr;
extern void (*kbd_irq_hook)(void);
extern void (*kbd_poll_hook)(void);
extern void (*mouse_update_hook)(void);
extern void (*sprite_update_hook)(void);
extern short mouse_available;
extern short vga_bios_mode_supported;
extern short sound_blaster_detected;
extern short joystick_available;
extern void exit(int);
enum SystemReportFlag {
    REPORT_CPU = 0x0001, REPORT_DOS = 0x0002, REPORT_WINDOWS = 0x0004, REPORT_VGA = 0x0008,
    REPORT_XMS = 0x0010, REPORT_EMS = 0x0020, REPORT_VCPI = 0x0040, REPORT_DPMI = 0x0080,
    REPORT_CONVENTIONAL_MEMORY = 0x0100, REPORT_EXTENDED_MEMORY = 0x0200, REPORT_MOUSE = 0x0400,
    REPORT_JOYSTICK = 0x0800, REPORT_VBL = 0x1000, REPORT_SOUND_BLASTER = 0x2000
};

enum RequiredHardwareFlag {
    REQUIRE_VGA = 0x01, REQUIRE_MOUSE = 0x02, REQUIRE_386_CPU = 0x04,
    REQUIRE_SOUND_BLASTER = 0x10, REQUIRE_JOYSTICK = 0x20
};

/* T19 initialized error strings and pointer tables, read from obj3. */
char *system_message_text[91] = {
    "\332\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\277 \n\263   There is some problems in your configuration.   \306\273\n\300\322\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\304\331\272\n \310\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\315\274\n\n",
    "\256<ERROR>\257   You need a VGA card.\n",
    "\256<ERROR>\257   You need a 386 CPU or better.\n",
    "\256<ERROR>\257   You need a Microsoft compatible mouse driver.\n",
    "\256<ERROR>\257   You need a JOYSTICK.\n",
    "\256<ERROR>\257   You need a SoundBlaster compatible sound card.\n",
    "\256<ERROR>\257   You need a XMS driver.\n",
    "\256<ERROR>\257   You need a EMS driver.\n",
    "\256<ERROR>\257   You need a VCPI driver.\n",
    "\256<ERROR>\257   You need a DPMI driver.\n",
    "\256<ERROR>\257   You need at least %u KB free of CONVENTIONAL memory.\n",
    "\256<ERROR>\257   You need at least %u KB free of EXTENDED memory.\n",
    "\256<ERROR>\257   You need at least %u KB free of EXTENDED memory (XMS).\n",
    "\256<ERROR>\257   You need at least %u KB free of EXPANDED memory (EMS).\n",
    "             <Press SPACE BAR to continue>\n",
    "(Real Mode IOPL:%u)\n",
    "(Protected Mode IOPL:%u)\n",
    "(Virtual Mode IOPL:%u)\n",
    "  \376\333\376 80%x CPU detected.      ",
    "  \376\333\376  DOS  System detected.   ",
    "  \376\333\376 WINDOWS System detected. ",
    "  \376\333\376  VGA  Card detected.     (\362 %u Kb)\n",
    "  \376\333\376  XMS  Driver detected.   ",
    "  \376\333\376  EMS  Driver detected.   ",
    "  \376\333\376  VCPI Driver detected.   ",
    "  \376\333\376  DPMI Driver detected.   ",
    "  \376\333\376 JOYSTICK detected.       (IO Port $%X)\n",
    "  \376\333\376 MOUSE Driver detected.   ",
    "  \376\333\376 SOUNDBLASTER detected.   (IO Port $%X, INT %X, DMA %X)\n",
    "  \376\333\376 SB PRO detected.         (IO Port $%X, INT %X, DMA %X)\n",
    "  \376\333\376  DSP  detected.          ",
    "\344 \372\371\372 SOUNDBLASTER cannot find Interrupt (IO Port $%X, INT %X, DMA %X)\n             Change the jumper on your card to enjoy the sound !\n",
    "\344 \371\376\371 SOUNDBLASTER cannot find DMA (IO Port $%X, INT %X, DMA %X)\n             Change the jumper on your card to enjoy the sound !\n",
    "  \376\333\376 B-MEM enough free space. (Use %u Kb of %u Kb)\n",
    "  \376\333\376 X-MEM enough free space. (Use %u Kb of %u+%u Kb)\n",
    "  \376\333\376  VBL  compatibility.     (Synchro $%X)\n",
    "  \376\333\376  VBL  manager installed. ",
    "  \376\333\376 KEYB. manager installed. ",
    "  \376\333\376 DEBUG compatibility. \n",
    "Program interrupted by User.\n",
    "FILE ERROR: Open file: ",
    "FILE ERROR: Close file: ",
    "FILE ERROR: Read file: ",
    "FILE ERROR: Write file: ",
    "FILE ERROR: Move ptr (seek) in file: ",
    "FILE ERROR: Tell position in file: ",
    "FILE ERROR: Buffer overflow in file: ",
    "FILE ERROR: Filelength file: ",
    "FILE ERROR: Create file: ",
    "FILE ERROR: ",
    "FORMAT IDENTIFYING ERROR:\n\tProbably an incorrect extension in file: ",
    "FORMAT DEPACKING OVERFLOW:\n\tThe maximum load address has been exceeded\n\tThe memory integrity is no more guaranteed\n\tIt concerns the file: ",
    "FORMAT ERROR: ",
    "BOB ERROR: Size overflow (exceed screen size).",
    "BOB ERROR: Coordinates overflow (exceeds 32000).",
    "BOB ERROR: Left offset not available.",
    "BOB ERROR: Right offset not available.",
    "BOB ERROR: Header overflow (exceed 4096)",
    "BOB ERROR: BOB Format is TW4 in a BPP screen mode",
    "BOB ERROR: Draw table overflow (Max number of bob exceeded)",
    "BOB ERROR: You try to draw BOB without any Video Mode Set",
    "BOB ERROR: ",
    "FUNCTION ERROR: Init_keyb_manager()\n\tReal mode handler requires unavaible B-mem.",
    "FUNCTION ERROR: Init_vbl_manager()\n\tReal mode handler requires unavaible B-mem.",
    "FUNCTION ERROR: Init_vm()\n\tThe Video Mode required is UNKNOWN.",
    "FUNCTION ERROR: reserve_B_mem()\n\tFunction can not reserve asked size.",
    "FUNCTION ERROR: reserve_X_mem()\n\tFunction can not reserve asked size.",
    "SOUND ERROR: Module: No SoundBlaster present\n",
    "SOUND ERROR: Module: Setup error\n",
    "SOUND ERROR: Module: Multi channel error\n",
    "SOUND ERROR: Module: SoundBlaster init\n",
    "SOUND ERROR: Module: Unable to install manager\n\tMaybe that\t-NO SB present\n\t\t\t-VBL manager installed\n",
    "SOUND ERROR: Digit: Unable to install manager\n\tMaybe that\t-NO SB present\n\t\t\t-MOD manager installed\n",
    "SOUND ERROR: Digit: Cannot reserve B-mem for Buffer\n",
    "SOUND ERROR: Module: Cannot reserve B-mem for Buffer\n",
    "IFF ERROR: The chunk -FORM not found in file: ",
    "IFF ERROR: The chunk -BODY not found in file: ",
    "IFF ERROR: The chunk -BMHD not found in file: ",
    "IFF ERROR: The chunk -CMAP not found in file: ",
    "IFF ERROR: The depacked size is incorrect in file: ",
    "IFF ERROR: ",
    "GIF ERROR: The ID code is not found in file: ",
    "GIF ERROR: This is not GIF87A format in file: ",
    "GIF ERROR: The image width is not 320 in file: ",
    "GIF ERROR: The image height is not 200 in file: ",
    "GIF ERROR: The image colors number is not 256 in file: ",
    "GIF ERROR: The image has an anormal format in file: ",
    "GIF ERROR: The image has a local problem in file: ",
    "GIF ERROR: The image is interlaced in file: ",
    "GIF ERROR: Not enough mem to reserve buffer: GIF ERROR: ",
    "PCX ERROR: The ID code is not found in file: "
};
char **error_message_categories[11] = {
    (char **)"PCX ERROR: ",
    &system_message_text[39],
    &system_message_text[40],
    &system_message_text[50],
    &system_message_text[53],
    &system_message_text[62],
    &system_message_text[67],
    &system_message_text[40],
    &system_message_text[75],
    &system_message_text[81],
    &system_message_text[90]
};
unsigned fatal_error_code;
unsigned fatal_error_message;
#define MSG_MISSING_VGA system_message_text[1]
#define MSG_MISSING_386_CPU system_message_text[2]
#define MSG_MISSING_MOUSE system_message_text[3]
#define MSG_MISSING_JOYSTICK system_message_text[4]
#define MSG_MISSING_SOUND_BLASTER system_message_text[5]
#define MSG_MISSING_XMS system_message_text[6]
#define MSG_MISSING_EMS system_message_text[7]
#define MSG_MISSING_VCPI system_message_text[8]
#define MSG_MISSING_DPMI system_message_text[9]
#define MSG_NEED_CONVENTIONAL_MEMORY system_message_text[10]
#define MSG_NEED_EXTENDED_MEMORY system_message_text[11]
#define MSG_NEED_XMS_MEMORY system_message_text[12]
#define MSG_NEED_EMS_MEMORY system_message_text[13]
#define MSG_PRESS_SPACE_TO_CONTINUE system_message_text[14]
#define MSG_REAL_MODE_IOPL (system_message_text + 15)
#define MSG_PROTECTED_MODE_IOPL system_message_text[16]
#define MSG_VIRTUAL_MODE_IOPL system_message_text[17]
#define MSG_CPU_DETECTED system_message_text[18]
#define MSG_DOS_DETECTED system_message_text[19]
#define MSG_WINDOWS_DETECTED system_message_text[20]
#define MSG_VGA_DETECTED system_message_text[21]
#define MSG_XMS_DETECTED system_message_text[22]
#define MSG_EMS_DETECTED system_message_text[23]
#define MSG_VCPI_DETECTED system_message_text[24]
#define MSG_DPMI_DETECTED system_message_text[25]
#define MSG_JOYSTICK_DETECTED system_message_text[26]
#define MSG_MOUSE_DETECTED system_message_text[27]
#define MSG_SOUND_BLASTER_DETECTED system_message_text[28]
#define MSG_SOUND_BLASTER_PRO_DETECTED system_message_text[29]
#define MSG_DSP_DETECTED system_message_text[30]
#define MSG_SOUND_BLASTER_IRQ_MISSING system_message_text[31]
#define MSG_SOUND_BLASTER_DMA_MISSING system_message_text[32]
#define MSG_CONVENTIONAL_MEMORY_AVAILABLE system_message_text[33]
#define MSG_EXTENDED_MEMORY_AVAILABLE system_message_text[34]
#define MSG_VBL_COMPATIBILITY system_message_text[35]
#define MSG_VBL_MANAGER_INSTALLED system_message_text[36]
#define MSG_KEYBOARD_MANAGER_INSTALLED system_message_text[37]
#define MSG_DEBUG_COMPATIBILITY system_message_text[38]
#define MSG_USER_INTERRUPT system_message_text[39]
#define MSG_FILE_OPEN_ERROR system_message_text[40]
#define MSG_FILE_CLOSE_ERROR system_message_text[41]
#define MSG_FILE_READ_ERROR system_message_text[42]
#define MSG_FILE_WRITE_ERROR system_message_text[43]
#define MSG_FILE_SEEK_ERROR system_message_text[44]
#define MSG_FILE_TELL_ERROR system_message_text[45]
#define MSG_FILE_BUFFER_OVERFLOW system_message_text[46]
#define MSG_FILE_LENGTH_ERROR system_message_text[47]
#define MSG_FILE_CREATE_ERROR system_message_text[48]
#define MSG_FILE_ERROR system_message_text[49]
#define MSG_FORMAT_IDENTIFICATION_ERROR system_message_text[50]
#define MSG_FORMAT_DEPACKING_OVERFLOW system_message_text[51]
#define MSG_FORMAT_ERROR system_message_text[52]
#define MSG_BOB_SIZE_OVERFLOW system_message_text[53]
#define MSG_BOB_COORDINATE_OVERFLOW system_message_text[54]
#define MSG_BOB_LEFT_OFFSET_UNAVAILABLE system_message_text[55]
#define MSG_BOB_RIGHT_OFFSET_UNAVAILABLE system_message_text[56]
#define MSG_BOB_HEADER_OVERFLOW system_message_text[57]
#define MSG_BOB_TW4_MODE_ERROR system_message_text[58]
#define MSG_BOB_DRAW_TABLE_OVERFLOW system_message_text[59]
#define MSG_BOB_MODE_NOT_SET system_message_text[60]
#define MSG_KEYBOARD_MANAGER_INIT_ERROR system_message_text[61]
#define MSG_VBL_MANAGER_INIT_ERROR system_message_text[62]
#define MSG_VIDEO_MODE_INIT_ERROR system_message_text[63]
#define MSG_RESERVE_CONVENTIONAL_MEMORY_ERROR system_message_text[64]
#define MSG_RESERVE_EXTENDED_MEMORY_ERROR system_message_text[65]
#define MSG_SOUND_MODULE_NO_SOUNDBLASTER system_message_text[66]
#define MSG_SOUND_MODULE_SETUP_ERROR system_message_text[67]
#define MSG_SOUND_MODULE_MULTICHANNEL_ERROR system_message_text[68]
#define MSG_SOUND_MODULE_INIT_ERROR system_message_text[69]
#define MSG_SOUND_MODULE_MANAGER_INSTALL_ERROR system_message_text[70]
#define MSG_SOUND_DIGIT_MANAGER_INSTALL_ERROR system_message_text[71]
#define MSG_SOUND_DIGIT_BUFFER_RESERVE_ERROR system_message_text[72]
#define MSG_SOUND_MODULE_BUFFER_RESERVE_ERROR system_message_text[73]
#define MSG_IFF_FORM_CHUNK_MISSING system_message_text[74]
#define MSG_IFF_BODY_CHUNK_MISSING system_message_text[75]
#define MSG_IFF_BMHD_CHUNK_MISSING system_message_text[76]
#define MSG_IFF_CMAP_CHUNK_MISSING system_message_text[77]
#define MSG_IFF_DEPACKED_SIZE_ERROR system_message_text[78]
#define MSG_IFF_ERROR system_message_text[79]
#define MSG_GIF_ID_MISSING system_message_text[80]
#define MSG_GIF_FORMAT_NOT_GIF87A system_message_text[81]
#define MSG_GIF_WIDTH_ERROR system_message_text[82]
#define MSG_GIF_HEIGHT_ERROR system_message_text[83]
#define MSG_GIF_PALETTE_SIZE_ERROR system_message_text[84]
#define MSG_GIF_FORMAT_ERROR system_message_text[85]
#define MSG_GIF_LOCAL_ERROR system_message_text[86]
#define MSG_GIF_INTERLACED_ERROR system_message_text[87]
#define MSG_GIF_BUFFER_RESERVE_ERROR system_message_text[88]
#define MSG_PCX_ID_MISSING system_message_text[89]
#define MSG_PCX_ERROR system_message_text[90]
int sys_report(int conventional_memory_bytes,int extended_memory_bytes,unsigned long report_flags,int reserved_mode) {
    int report_status=0;
    if((report_flags&REPORT_CPU)==1) {
        probe_cpu_environment();
        printf(MSG_CPU_DETECTED,cpu_type);
        printf((char*)MSG_REAL_MODE_IOPL[cpu_mode],cpu_iopl);
    }
    if((report_flags&REPORT_DOS)!=0) if(read_dos_version()==-1) {
        printf(MSG_DOS_DETECTED);
        print_encoded_version(dos_version_packed);
    }
    if((report_flags&REPORT_WINDOWS)!=0) if(detect_windows_environment()==-1) {
        printf(MSG_WINDOWS_DETECTED);
        print_encoded_version(windows_mode_code);
    }
    if((report_flags&REPORT_VGA)!=0) if(detect_vga_bios_mode()==-1) printf(MSG_VGA_DETECTED,vga_bios_version);
    if((report_flags&REPORT_XMS)!=0) if(detect_xms_driver()==-1) {
        printf(MSG_XMS_DETECTED);
        print_encoded_version(xms_driver_version);
    }
    if((report_flags&REPORT_EMS)!=0) if(check_ems_manager_signature()==-1) {
        printf(MSG_EMS_DETECTED);
        print_encoded_version(ems_manager_version);
    }
    if((report_flags&REPORT_VCPI)!=0) if(detect_ems_manager()==-1) {
        printf(MSG_VCPI_DETECTED);
        print_encoded_version(ems_manager_handle);
    }
    if((report_flags&REPORT_DPMI)!=0) if(detect_dpmi_host()==-1) {
        printf(MSG_DPMI_DETECTED);
        print_encoded_version(dpmi_version_bcd);
    }
    if((report_flags&REPORT_CONVENTIONAL_MEMORY)!=0) {
        if(allocate_dpmi_memory(conventional_memory_bytes)==0) {
            report_status=-1;
            printf(MSG_NEED_CONVENTIONAL_MEMORY,conventional_memory_bytes/1024);
        }
        if(dpmi_err==0) free_dpmi_memory(dpmi_selector_or_failure_marker);
        printf(MSG_CONVENTIONAL_MEMORY_AVAILABLE,conventional_memory_bytes/1024,query_largest_dos_free_block()/1024);
    }
    if((report_flags&REPORT_EXTENDED_MEMORY)!=0) {
        if(alloc_heap_block(extended_memory_bytes)==0) {
            report_status=-1;
            printf(MSG_NEED_EXTENDED_MEMORY,extended_memory_bytes/1024);
        }
        if(dos_memory_error==0) free_heap_block(heap_block);
        allocate_dpmi_memory(conventional_memory_bytes);
        printf(MSG_EXTENDED_MEMORY_AVAILABLE,extended_memory_bytes/1024,(int)query_largest_dpmi_free_block()/1024,(largest_dos_free_block_bytes-conventional_memory_bytes)/1024);
        if(dpmi_err==0) free_dpmi_memory(dpmi_selector_or_failure_marker);
    }
    if((report_flags&REPORT_MOUSE)!=0) if(initialize_mouse_driver()==-1) {
        printf(MSG_MOUSE_DETECTED);
        print_encoded_version(mouse_driver_version);
    }
    if((report_flags&REPORT_JOYSTICK)!=0) if(detect_joystick()==-1) printf(MSG_JOYSTICK_DETECTED,JOYSTICK_IO_PORT);
    if((report_flags&REPORT_SOUND_BLASTER)!=0) {
        if(detect_sound_blaster()==-1) {
            if(sound_blaster_mixer_test==0) printf(MSG_SOUND_BLASTER_DETECTED,(int)sound_blaster_base_port,sound_blaster_irq,sound_blaster_dma_channel);
            else printf(MSG_SOUND_BLASTER_PRO_DETECTED,(int)sound_blaster_base_port,sound_blaster_irq,sound_blaster_dma_channel);
            printf(MSG_DSP_DETECTED);
            print_encoded_version(sound_blaster_dsp_version);
        }
        else if(sound_blaster_base_port>=0x200 && sound_blaster_base_port<0x300) {
            if(sound_blaster_irq==0xff) printf(MSG_SOUND_BLASTER_IRQ_MISSING,(int)sound_blaster_base_port,sound_blaster_irq,sound_blaster_dma_channel);
            else if(sound_blaster_dma_channel==0xff) printf(MSG_SOUND_BLASTER_DMA_MISSING,(int)sound_blaster_base_port,sound_blaster_irq,sound_blaster_dma_channel);
            printf(MSG_PRESS_SPACE_TO_CONTINUE);
            if(key_irq==-1) {
                do {
                    poll_keyboard();
                }
                while (prior_key_ascii==ascii_key || ascii_key!=0x20);
            }
            else while(getch()!=0x20) {
            }
        }
    }
    if(report_flags&REPORT_VBL) if(verify_timer()==-1) printf(MSG_VBL_COMPATIBILITY,f_9f64());
    return report_status;
}

void sysinit(int vbl_manager_mode,int keyboard_manager_mode,int debug_compatibility_mode,int mouse_setup_mode) {
    int manager_install_mode;
    int manager_error_code;
    int key_poll_count;
    atexit(restore_system_interrupt_vectors);
    key_action_hook=fatal_exit;
    kbd_state_ptr=&keyboard_state;
    kbd_irq_hook=dispatch_keyboard;
    kbd_poll_hook=poll_keyboard;
    mouse_update_hook=update_mouse;
    sprite_update_hook=poll_joystick_ports;
    set_vga_display_start(page_idx);
    outp(PIC_MASTER_MASK_PORT,inp(PIC_MASTER_MASK_PORT)|PIC_IRQ0_MASK);
    if(debug_compatibility_mode==-1) printf(MSG_DEBUG_COMPATIBILITY);
    if(keyboard_manager_mode==-1) {
        if(debug_compatibility_mode==-1) manager_install_mode=2;
        else manager_install_mode=4;
        manager_error_code=initialize_keyboard_manager(manager_install_mode);
        if(manager_error_code) printf(error_message_categories[(manager_error_code&0xff00)>>8][(manager_error_code&0xff)-1]);
        if(keyboard_hook_flags) {
            printf(MSG_KEYBOARD_MANAGER_INSTALLED);
            if((keyboard_hook_flags&1)==1) printf("(REAL) ");
            if(keyboard_hook_flags&2) printf("(DPMI) ");
            if(keyboard_hook_flags&4) printf("(D4GW) ");
            printf("\n");
        }
    }
    if(vbl_manager_mode==-1 && timer_ok==-1) {
        if(debug_compatibility_mode==-1) manager_install_mode=2;
        else manager_install_mode=4;
        manager_error_code=start_timer(manager_install_mode);
        if(manager_error_code) printf(error_message_categories[(manager_error_code&0xff00)>>8][(manager_error_code&0xff)-1]);
        if(irq_flags) {
            printf(MSG_VBL_MANAGER_INSTALLED);
            if((irq_flags&1)==1) printf("(REAL) ");
            if(irq_flags&2) printf("(DPMI) ");
            if(irq_flags&4) printf("(D4GW) ");
            printf("\n");
        }
    }
    for(key_poll_count=0;key_poll_count<50;key_poll_count++) {
        wait_for_tick((int)1);
        if(translated_key_bitmap[5].bytes.low&0x80) key_poll_count--;
    }
    if(mouse_setup_mode!=-1) {
        set_display_mode(mouse_setup_mode);
        set_mouse_bounds(vga_state.viewport_left,vga_state.viewport_top,vga_state.viewport_right_or_width,vga_state.viewport_bottom_or_height);
        move_mouse_to((vga_state.viewport_left+vga_state.viewport_right_or_width)/2,(vga_state.viewport_top+vga_state.viewport_bottom_or_height)/2);
    }
}

int check_hardware(unsigned long required_hardware) {
    int missing_hardware=0;
    if(required_hardware&REQUIRE_MOUSE) {
        if(mouse_available!=-1) {
            printf(MSG_MISSING_MOUSE);
            missing_hardware=-1;
        }
    }
    if((required_hardware&REQUIRE_VGA)==1) {
        if(vga_bios_mode_supported!=-1) {
            printf(MSG_MISSING_VGA);
            missing_hardware=-1;
        }
    }
    if(required_hardware&REQUIRE_386_CPU) {
        if(cpu_type<0x386) {
            printf(MSG_MISSING_386_CPU);
            missing_hardware=-1;
        }
    }
    if(required_hardware&REQUIRE_SOUND_BLASTER) {
        if(sound_blaster_detected!=-1) {
            printf(MSG_MISSING_SOUND_BLASTER);
            missing_hardware=-1;
        }
    }
    if(required_hardware&REQUIRE_JOYSTICK) {
        if(joystick_available!=-1) {
            printf(MSG_MISSING_JOYSTICK);
            missing_hardware=-1;
        }
    }
    return missing_hardware;
}

void restore_system_interrupt_vectors(void) {
    outp(PIC_MASTER_MASK_PORT, inp(PIC_MASTER_MASK_PORT) & PIC_MASK_WITH_IRQ0_CLEARED);
    if (fatal_error_code != 0) {
        printf((char *)*(int *)((*(unsigned char * *)((unsigned char *)error_message_categories +
               (((int)(fatal_error_code & 0xff00) >> 8) << 2))) + (((fatal_error_code & 0xff) << 2) - 4)));
        if (fatal_error_message != 0) printf("%s\n", fatal_error_message);
        printf("\n\n<Press any key>\n");
        getch();
    }
    _enable();
}

void fatal_exit(unsigned long error_code,unsigned long error_message) {
    fatal_error_code=error_code;
    fatal_error_message=error_message;
    exit(0);
}

void print_encoded_version(int encoded_version) {
    if (encoded_version != -1) printf("(Version %x.%x%x)\n", encoded_version >> 8, (encoded_version >> 4) & 0xf, encoded_version & 0xf);
    else printf("\n");
}
