unsigned char g_8dc8[8];
int g_8dd4;
int g_8dd8;
/* TU f_9f9..f_4066 [0x9f9, 0x4085): generated by tools/tu.py */
#include <process.h>
unsigned char g_8db8[16];
int g_8dd0;

#include <stdlib.h>
#include <string.h>
#pragma pack(1)
#pragma pack()
typedef struct { unsigned char b[5]; } S5;
typedef struct { unsigned char bytes[9]; } Name;
typedef struct { Name name; unsigned char other[16]; } Row;
typedef struct { unsigned char bytes[25]; } Record;
typedef struct { unsigned char prefix : 2; unsigned char value : 6; } IndexBits;
struct Cell { unsigned char lo : 2, hi : 6; unsigned char flag; };
typedef struct { unsigned char prefix : 2; unsigned char code : 6; } CodeBits;
extern unsigned char g_74c4[];
extern unsigned char key_irq[];
extern unsigned char g_756f[];
extern void f_9afc(void);
extern void f_9b44(int);
extern void release_sound_system(void);
extern int configure_sound_dma(int);
extern void set_audio_transfer_mode(int);
extern void save_bios(void);
extern void restore_bios(void);
extern void clear_pal(void);
extern void f_f6d9(void);
extern int f_f6f8(int);
void f_9f9(void);
extern int g_38c6;
extern int g_68f8_jwwqkwr;
extern int g_6910;
extern int g_6914;
extern int g_693c;
extern short image_color_depth;
extern short sound_blaster_detected;
extern int fade_start;
extern int fade_end;
extern short draw_idx;
extern short page2;
extern short g_7b34_cbzosabe;
extern short g_7b3d_yrsiuxxd;
extern unsigned short g_7bfe;
extern unsigned short g_7c00;
extern int g_7c08_orxezsknd;
extern int g_8428;
extern unsigned char g_8870[];
extern unsigned char h_ab40_jbfxrqns[];
extern unsigned char g_bf40_whznxcth[];
extern unsigned char g_d340_schtgisj[];
extern unsigned char *x_dd40_xbukycw;
extern int g_dd44;
extern char *k_DD48_jbwjbqarofg;
extern unsigned char *g_dd4c_ilunphmaok;
extern int g_df48;
extern int g_df4c;
extern int g_df54;
extern int h_df5c;
extern int g_e1d8;
struct DisplayModeInfo { short state; unsigned char plane_addresses[16]; int page_offsets[4]; int page_adjustments[4]; unsigned char page_mode_classes[4]; int buffer_size; int row_stride_bytes; int resolution_height; int width; int height; int left; int top; int right; int bottom; unsigned char mode_flags; unsigned char e37f; unsigned char e380; unsigned char video_mode_low; unsigned char e382; unsigned char e383; unsigned char e384; unsigned char e385; unsigned char e386; unsigned char tail; };
extern struct DisplayModeInfo vga_state;
extern unsigned char g_e48b_3;
extern unsigned char g_e48d_c;
extern unsigned char g_e48e_0g;
extern unsigned char g_e48f;
extern int g_e4c8;
extern int g_e4d0_wfmxdlyju;
extern unsigned g_e4d4;
extern void f_100fa(int, int, int, int);
extern int f_1085a_eklzmb(void *);
extern void shutdown_with_exit_message(unsigned, unsigned);
extern void write_dac_palette(void *, int, int, int);
extern void handle_s_key(void);
extern void f_3beb(int);
extern void f_80d8(void);
extern void f_843a(void);
extern void f_9640(void *, void *);
extern void f_9d40(unsigned char);
extern int f_a574_wrvhrpegbz();
extern void plot_transformed_pixel(void *, int);
extern void draw_text(int, int, int);
extern void configure_text_renderer(int, int, unsigned char, int, int);
extern void set_text_clip_rect(int, int, int, int);
extern void queue_audio(int, int, int, int);
extern void set_img_buffers(int, int, short, int, int);
extern int set_display_mode();
extern void fade_pal(void *, int, int, int);
void f_113c(void);
extern int stop_audio_stream();
void f_ea4(void);
void f_ff0(void);
extern int g_6904;
extern int g_6908;
extern int g_690c;
extern int g_38ca;
extern char *g_3902;
extern int g_dF58;
extern int g_df60;
extern unsigned char *g_df70;
extern int g_df74;
extern unsigned char g_e144;
extern void f_16bb(int);
extern short image_buffer_error_code;
extern void f_1202(void);
extern void f_1227(void);
extern void f_127e(void);
extern void f_13aa(void);
extern void f_1416(void);
extern void redraw_image_region(int, int);
extern void show_page(void);
extern int next_packed_table_value(void *, void *);
extern unsigned char *image_buffer_cursor;
extern short m_E4c4;
extern short g_e4c6;
extern unsigned char g_6988[];
extern unsigned char g_698c[];
extern unsigned char g_6990[];
extern unsigned char g_6994[];
extern int g_8e20;
extern unsigned char g_e13f;
union KeyWord { unsigned short word; struct { unsigned char lo, hi; } bytes; };
extern union KeyWord g_e468[8];
extern short g_e4ba;
extern short g_e4bc;
extern int g_38f6;
extern int g_38fa;
extern unsigned char *g_3906;
extern unsigned char *g_6984;
extern unsigned int g_8e04;
extern unsigned char g_8e10[];
extern unsigned char g_8e46;
extern int i_dF44;
extern int g_df50;
extern unsigned char g_e13b;
int f_17d2(unsigned long a0);
extern short flip_src;
extern short flip_dst;
extern void copy_clipped_screen_rectangle(int, int, int, int, int, int, int, int);
extern unsigned int g_8dfc;
extern unsigned int g_8e00;
extern unsigned int g_8e08;
extern unsigned char g_e13c;
extern unsigned char g_e140;
extern int *r_dDDc_uzmlc;
extern unsigned char g_e143_eayxx;
char *itoa(int, char *, int);
extern int g_df6c;
extern void copy_screen_span_entry(int, int, int, int, int);
void f_1af4(void);
void f_1b7e(void);
void f_1bc2(void);
void f_1d80(void);
void f_1e87(void);
void f_20f4(void);
extern int draw_page();
extern int g_6918;
extern int g_691c;
extern int g_6920;
extern int g_df24_krqpxkj;
extern int g_df34_nnyybtp;
extern int g_df2c_hwkico;
extern int g_df20_rusvejgsscn;
extern int g_dDc8;
extern Row g_37f4[];
extern unsigned char g_37fd[];
extern int g_388e;
extern int g_8ddc;
extern unsigned char g_e141;
struct TextState { unsigned char mode; int v209, v20d, v211, v215, v219, v21d, v221, v225; unsigned char pad[3]; };
extern struct TextState g_text_render_state;
extern unsigned g_3861;
extern unsigned g_dedc;
extern char *strcpy(char *, const char *);
extern int g_3892;
extern int g_3896;
extern int g_df64;
extern int g_dF68;
extern unsigned char g_e13d;
extern void f_10137_squghx(void);
extern int g_387a;
extern char *g_6924;
extern int f_1065b(char *, void *);
extern void f_228e(void);
void f_107b6(int a, int b, int c);
extern unsigned char g_3801[];
extern unsigned char g_3805[];
extern unsigned char g_3809[];
extern int g_389e;
extern int g_38a2;
extern int g_38a6;
extern int g_38aa;
extern int g_38ae;
void f_2484(void);
void f_251c(void);
void f_2565(int a0);
extern int g_6940_hqhettu;
extern int g_6944_bdcftta;
extern int g_6948_kxwrlv;
extern int g_694c_wjufexbevsk;
extern int g_6958_vghgxtjirow;
extern int g_695c_qurvlwasjp;
extern int g_6960_juobaluykyr;
extern int g_6964;
extern int g_6934;
extern int g_6938;
extern int g_389a;
extern short disp_idx;
extern int g_38b2;
extern int g_38b6;
extern int g_38ba;
extern int g_38be;
extern int g_38c2;
void f_26fe(void);
void f_2796(void);
void f_27df(int a);
extern int g_6928;
extern int g_692c;
extern int g_6930;
extern int g_6974;
extern int g_6978;
extern int g_697c;
extern int g_6980;
void set_pal_rgb(unsigned char, unsigned char, unsigned char, unsigned char);
extern int v_DF30;
void f_2e4a(void);
void render_image_with_options(int, int, int, int, int);
extern unsigned char *u_e150;
extern int g_6c08;
void f_2eab(void);
void f_35b5(void);
void f_84a0(int);
extern int b_DF40_omuefnnbqp;
extern int g_Ddd8;
extern int g_6950;
extern int g_6954;
extern int g_df28;
extern int g_6968;
extern int g_6970;
extern int g_696c;
extern short page3;
extern int g_df38;
void set_draw_page(int);
void f_7f8a(void);
extern unsigned char g_e142_baun;
extern int g_ddb0;
extern int g_dd78;
extern unsigned short *g_dd80;
extern unsigned int g_dd50;
extern int g_dd60;
extern int g_dd64;
extern int g_dD68;
extern int b_DD70;
extern int g_e158_tpotbrbk;
extern int g_6c64[];
extern int g_6c7c[];
extern unsigned char g_a608;
extern unsigned char q_A988[];
extern unsigned char g_6b9e[];
extern unsigned char g_2fe4[];
void f_13889(int, int, int);
void draw_bob_sprite_entry(int, int, int);
extern int g_e14c;
void f_339f_adddtkmk(void);
void f_8345_wsdytbf(void);
void f_83b1(void);
extern int g_e154;
extern int g_69c8;
extern int g_e148;
extern int g_ddd4_eoraaik;
void f_82cc(void);
void write_pal(int);
extern int g_6ae8;
extern int g_6b78;
void f_34b7(void);
extern unsigned char *g_dee4;
void f_61a6_vby(void);
void f_10502(int, int);
extern char g_269c[];
void draw_zero_padded_number(int, int, int, int, int);
extern int g_8db0;
void submit_audio_request(int);
extern unsigned char g_8e24;
extern char g_2fec[];
void f_3ba4(int, int);
void f_7e62(int, int, int, int, int, int, int);
void f_42e1(unsigned char, unsigned char, int, int);
void f_3ac0(int a, int b, int c);
extern int g_dd74_ntd;
void f_3cc9(void);
extern unsigned char *g_dd7c;
extern int g_9af8;
extern int g_dd54;
void f_3d23(void);
extern int g_8e1c;
extern int g_68b7[];
extern int g_ddc0;
extern unsigned char *m_de5c;
void f_58b0(void);
void f_4085(void);

/* T02 initialized _DATA, in contribution order; values transcribed from obj3. */
typedef struct { int offset; int count; } GlyphRecord;

GlyphRecord g_390c_lmsbkmaaant[91] = {
    {4212, 1},
    {3704, 1},
    {3196, 1},
    {2772, 1},
    {2350, 1},
    {2004, 1},
    {1658, 1},
    {1338, 1},
    {1060, 1},
    {806, 1},
    {594, 1},
    {400, 1},
    {242, 1},
    {104, 1},
    {2, 1},
    {104, 1},
    {242, 1},
    {400, 1},
    {594, 1},
    {806, 1},
    {1060, 1},
    {1338, 1},
    {1658, 1},
    {2004, 1},
    {2350, 1},
    {2772, 1},
    {3196, 1},
    {3704, 1},
    {4212, 1},
    {4796, 1},
    {5380, 1},
    {6000, 1},
    {6668, 1},
    {7370, 1},
    {8124, 1},
    {8910, 1},
    {9744, 1},
    {10610, 1},
    {11528, 1},
    {12478, 1},
    {13476, 1},
    {14508, 1},
    {15584, 1},
    {16706, 1},
    {17864, 1},
    {16706, 1},
    {15584, 1},
    {14508, 1},
    {13476, 1},
    {12478, 1},
    {11528, 1},
    {10610, 1},
    {9744, 1},
    {8910, 1},
    {8124, 1},
    {7370, 1},
    {6668, 1},
    {6000, 1},
    {5380, 1},
    {4796, 1},
    {4212, 1},
    {19056, 1},
    {19698, 1},
    {20340, 1},
    {21040, 1},
    {21768, 1},
    {22526, 1},
    {23340, 1},
    {24182, 1},
    {25050, 1},
    {25952, 1},
    {26884, 1},
    {27868, 1},
    {28858, 1},
    {29904, 1},
    {30992, 1},
    {29904, 1},
    {28858, 1},
    {27868, 1},
    {26884, 1},
    {25952, 1},
    {25050, 1},
    {24182, 1},
    {23340, 1},
    {22526, 1},
    {21768, 1},
    {21040, 1},
    {20340, 1},
    {19698, 1},
    {19056, 1},
    {0, -90},
};

GlyphRecord g_3be4_zpjqcrvwahs[257] = {
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {35634, 1},
    {2, 1},
    {35688, 0},
    {35856, 0},
    {35990, 0},
    {36134, 0},
    {36280, 0},
    {36426, 0},
    {36574, 0},
    {36718, 0},
    {36860, 0},
    {37010, 0},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {37156, 0},
    {37318, 0},
    {37464, 0},
    {37624, 0},
    {37778, 0},
    {37924, 0},
    {38068, 0},
    {38240, 0},
    {38398, 0},
    {38522, 0},
    {38662, 0},
    {38810, 0},
    {38952, 0},
    {39128, 0},
    {39300, 0},
    {39474, 0},
    {39618, 0},
    {39794, 0},
    {39940, 0},
    {40088, 0},
    {40224, 0},
    {40394, 0},
    {40556, 0},
    {40746, 0},
    {40914, 0},
    {41070, 0},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {32094, 0},
    {32224, 0},
    {32378, 0},
    {32502, 0},
    {32660, 0},
    {32788, 0},
    {32924, 0},
    {33086, 0},
    {33240, 0},
    {33382, 0},
    {33562, 0},
    {33710, 0},
    {33842, 0},
    {33970, 0},
    {34096, 0},
    {34224, 0},
    {34378, 0},
    {34536, 0},
    {34646, 0},
    {34758, 0},
    {34874, 0},
    {35000, 0},
    {35116, 0},
    {35248, 0},
    {35374, 0},
    {35518, 0},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {0, -256},
};

GlyphRecord g_43ec_jxwzisjgagn[257] = {
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {57274, 1},
    {2, 1},
    {57456, 0},
    {57964, 0},
    {58252, 0},
    {58748, 0},
    {59242, 0},
    {59686, 0},
    {60184, 0},
    {60680, 0},
    {61096, 0},
    {61592, 0},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {44590, 0},
    {45084, 0},
    {45576, 0},
    {46034, 0},
    {46540, 0},
    {47034, 0},
    {47474, 0},
    {47978, 0},
    {48474, 0},
    {48960, 0},
    {49450, 0},
    {49936, 0},
    {50336, 0},
    {50844, 0},
    {51362, 0},
    {51870, 0},
    {52322, 0},
    {52832, 0},
    {53338, 0},
    {53836, 0},
    {54290, 0},
    {54798, 0},
    {55304, 0},
    {55810, 0},
    {56314, 0},
    {56778, 0},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {44590, 0},
    {45084, 0},
    {45576, 0},
    {46034, 0},
    {46540, 0},
    {47034, 0},
    {47474, 0},
    {47978, 0},
    {48474, 0},
    {48960, 0},
    {49450, 0},
    {49936, 0},
    {50336, 0},
    {50844, 0},
    {51362, 0},
    {51870, 0},
    {52322, 0},
    {52832, 0},
    {53338, 0},
    {53836, 0},
    {54290, 0},
    {54798, 0},
    {55304, 0},
    {55810, 0},
    {56314, 0},
    {56778, 0},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {0, -256},
};

GlyphRecord g_4bf4_pbqzadnradd[305] = {
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {7028, 1},
    {2, 1},
    {7176, 0},
    {7370, 0},
    {7514, 0},
    {7712, 0},
    {7900, 0},
    {8082, 0},
    {8280, 0},
    {8476, 0},
    {8656, 0},
    {8852, 0},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 0},
    {272, 0},
    {542, 0},
    {814, 0},
    {1084, 0},
    {1356, 0},
    {1628, 0},
    {1902, 0},
    {2168, 0},
    {2442, 0},
    {2716, 0},
    {2980, 0},
    {3246, 0},
    {3512, 0},
    {3778, 0},
    {4050, 0},
    {4312, 0},
    {4584, 0},
    {4852, 0},
    {5126, 0},
    {5404, 0},
    {5674, 0},
    {5944, 0},
    {6210, 0},
    {6480, 0},
    {6754, 0},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 0},
    {272, 0},
    {542, 0},
    {814, 0},
    {1084, 0},
    {1356, 0},
    {1628, 0},
    {1902, 0},
    {2168, 0},
    {2442, 0},
    {2716, 0},
    {2980, 0},
    {3246, 0},
    {3512, 0},
    {3778, 0},
    {4050, 0},
    {4312, 0},
    {4584, 0},
    {4852, 0},
    {5126, 0},
    {5404, 0},
    {5674, 0},
    {5944, 0},
    {6210, 0},
    {6480, 0},
    {6754, 0},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {0, -256},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {57274, 1},
    {2, 1},
};

struct digit_entry { int value; int other; };
struct digit_entry g_557c[10] = {
    {10626, 0},
    {12054, 0},
    {12764, 0},
    {14190, 0},
    {15568, 0},
    {16774, 0},
    {18188, 0},
    {19620, 0},
    {20682, 0},
    {22124, 0},
};

GlyphRecord g_55cc_unbqifhkaac[198] = {
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {44590, 0},
    {45084, 0},
    {45576, 0},
    {46034, 0},
    {46540, 0},
    {47034, 0},
    {47474, 0},
    {47978, 0},
    {48474, 0},
    {48960, 0},
    {49450, 0},
    {49936, 0},
    {50336, 0},
    {50844, 0},
    {51362, 0},
    {51870, 0},
    {52322, 0},
    {52832, 0},
    {53338, 0},
    {53836, 0},
    {54290, 0},
    {54798, 0},
    {55304, 0},
    {55810, 0},
    {56314, 0},
    {56778, 0},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {44590, 0},
    {45084, 0},
    {45576, 0},
    {46034, 0},
    {46540, 0},
    {47034, 0},
    {47474, 0},
    {47978, 0},
    {48474, 0},
    {48960, 0},
    {49450, 0},
    {49936, 0},
    {50336, 0},
    {50844, 0},
    {51362, 0},
    {51870, 0},
    {52322, 0},
    {52832, 0},
    {53338, 0},
    {53836, 0},
    {54290, 0},
    {54798, 0},
    {55304, 0},
    {55810, 0},
    {56314, 0},
    {56778, 0},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {2, 1},
    {0, -256},
};

struct Grad { short x, y; unsigned char r0, g0, b0, r1, g1, b1; };
struct Grad g_5bfc_fosgstopadl[8] = {
    {0, 63, 0, 0, 63, 0, 0, 0},
    {0, 63, 0, 0, 0, 63, 0, 0},
    {0, 63, 63, 0, 0, 0, 0, 0},
    {0, 63, 0, 0, 0, 0, 0, 32},
    {0, 63, 0, 0, 32, 32, 0, 0},
    {0, 63, 32, 0, 0, 0, 0, 63},
    {0, 63, 0, 0, 63, 0, 0, 0},
    {-1, 0, 0, 0, 0, 0, 0, 0},
};

extern char *g_38ce, *g_38d2, *g_38d6, *g_38da, *g_38de, *g_38e2;
extern char *g_38e6, *g_38ea, *g_38ee, *g_38f2, *g_3902;

char **g_5c4c_fbaebsuahb[11] = {
    &g_38ce,
    &g_38d2,
    &g_38d6,
    &g_38da,
    &g_38de,
    &g_38e2,
    &g_38e6,
    &g_38ea,
    &g_38ee,
    &g_38f2,
    &g_3902,
};
char *g_5c78 = "ke_ldcwc.tab";
int g_5c7c = 0;

extern unsigned char g_7b36;
extern int (*g_7b3f_gng)();
extern int (*g_7b43)();
extern int g_dDa8;
extern unsigned char g_e13a;
extern int g_e1b8;
extern short g_e1bc;
extern short g_e1c0;
extern void f_3b2_jzcvbvx(void);
extern void f_441_wfixgn(void);
extern void f_4cf2(void);
extern void f_52f_bssi(void);
extern void f_5771(void);
extern void f_5966(void);
extern void f_608a_ujonj(void);
extern void f_60e5_grt(void);
extern void f_6278(void);
extern void f_7bd5(void);
extern void f_814b(void);
extern void f_8585(void);
extern void f_fc86(void);
void f_10(void);
extern unsigned char g_e13e;
extern unsigned char g_df04[];
extern void f_6ca(int, int, int);
extern int rand_rng(int, int);
extern int f_6b02(void);
extern int g_6230;
extern int g_dd84;
extern unsigned char i_DD98[];
extern int g_dd9c;
extern unsigned char *g_ddb4;
extern int g_dDb8;
extern int g_ddcc;
extern int g_ddd0;
extern unsigned char g_de60[];
extern unsigned char *g_dee0;
extern void f_4886(void);
extern void f_4bae(void);
extern void f_57bf(void);
extern void f_57fa(void);
extern void f_8fce(int, int);
extern void f_7e9(void);
void f_81d_psgpolkaxl(void);
void f_8d3_szjtcdqild(void);
void f_951_vbfkytgovb(void);
extern int g_68fc_ifhyqlddj;
extern int g_6900;
extern short audio_stream_flag;
extern char *g_388a;
extern char *g_38fe;
void f_708(void);

void f_708(void) {
    unsigned int selected_menu_item;
    g_e13f = 0;
    g_df38 = -1;
    g_e13c = 4;
    g_e140 = 0;
    g_e144 = 0;
    g_e13b = 0;
    g_df50 = -1;
    f_7e9();
    do {
        f_e70();
        selected_menu_item = (unsigned int)h_df5c - 1;
        switch (selected_menu_item) {
        case 0:
            f_10();
            if (g_e143_eayxx >= 60 && r_dDDc_uzmlc[1] >= 0)
                f_2689();
            g_dedc = r_dDDc_uzmlc[5];
            f_19b9();
            break;
        case 1:
            g_dedc = 0;
            f_19b9();
            break;
        case 2:
            f_240f();
            break;
        case 3:
            f_aa2();
            break;
        default:
            break;
        }
    } while (g_e13f == 0);
    f_2250();
}

void f_7e9(void)
{
    stop_audio_stream();
    f_81d_psgpolkaxl();
    set_display_mode(5);
    f_8d3_szjtcdqild();
    f_951_vbfkytgovb();
    stop_audio_stream();
}

void f_81d_psgpolkaxl(void)
{
    g_e4d0_wfmxdlyju = g_7c08_orxezsknd;
    k_DD48_jbwjbqarofg = (unsigned char *)g_e4d0_wfmxdlyju;
    g_8428 = f_a574_wrvhrpegbz(g_68fc_ifhyqlddj);
    if (g_8428) {
    shutdown_with_exit_message(g_8428, g_68fc_ifhyqlddj);
    }
L_86d:;
    if ((short)sound_blaster_detected != -1) goto L_8ce;
    g_dd44 = g_e4d0_wfmxdlyju;
    g_8428 = f_1085a_eklzmb(g_6900);
    if (g_8428) {
    shutdown_with_exit_message(g_8428, g_6900);
    }
L_8b3:;
    queue_audio(g_dd44, g_e4c8, 8000, 0);
L_8ce:;
}

void f_8d3_szjtcdqild(void) {
    x_dd40_xbukycw = k_DD48_jbwjbqarofg + vga_state.buffer_size;
    fade_pal(x_dd40_xbukycw, 0, -63, -1);
    disp_idx = flip_src;
    plot_transformed_pixel(k_DD48_jbwjbqarofg, disp_idx);
    draw_page(disp_idx);
    fade_pal(x_dd40_xbukycw, -63, 0, 1);
}

void f_951_vbfkytgovb(void)
{
    g_7b34_cbzosabe = (g_7b34_cbzosabe & 0xfffe) & 0xfffd;
    g_7b3d_yrsiuxxd = 0;
L_976:;
    f_9d40(3);
    handle_s_key();
    if (g_7b3d_yrsiuxxd != 0) goto L_9ae;
    if (g_7bfe == g_7c00) goto L_9ac;
    if (g_7bfe != 0) goto L_9ae;
L_9ac:;
    goto L_9b0;
L_9ae:;
    goto L_9c8;
L_9b0:;
    if (g_e48b_3 == g_e48e_0g) goto L_9c6;
    if (g_e48e_0g == 1) goto L_9c8;
L_9c6:;
    goto L_9ca;
L_9c8:;
    goto L_9e0;
L_9ca:;
    if (sound_blaster_detected == 0) goto L_976;
    if (audio_stream_flag == -1) goto L_976;
L_9e0:;
    fade_pal(x_dd40_xbukycw, 0, 0x3f, 3);
}

void f_9f9(void)
{
    int v_4;
    int v_8;
    int v_c;
    v_4 = *(short *)g_756f;
    v_8 = *(short *)key_irq;
    v_c = *(short *)g_74c4;
    set_audio_transfer_mode(0);
    f_9afc();
    f_f6d9();
    release_sound_system();
    restore_bios();
    spawnlp(0, (char *)("", "printord.bat"), (char *)"", 0);
    clear_pal();
    save_bios();
    if (v_4 != -1) goto L_a73;
    f_9b44(0);
L_a73:;
    if (v_8 != -1) goto L_a83;
    f_f6f8(0);
L_a83:;
    if (v_c != -1) goto L_a93;
    configure_sound_dma(0);
L_a93:;
    set_audio_transfer_mode(-1);
}

void f_aa2(void)
{
    unsigned char v_4;
    int v_8;
L_aae:;
    set_display_mode(2);
    g_e4d0_wfmxdlyju = (unsigned char *)g_7c08_orxezsknd;
    k_DD48_jbwjbqarofg = g_e4d0_wfmxdlyju;
    g_8428 = f_a574_wrvhrpegbz(g_6910);
    if (g_8428 == 0) goto L_afc;
    shutdown_with_exit_message(g_8428, g_e4d4);
L_afc:;
    g_dd4c_ilunphmaok = g_e4d0_wfmxdlyju;
    g_8428 = f_1085a_eklzmb((void *)g_6914);
    if (g_8428 == 0) goto L_b36;
    shutdown_with_exit_message(g_8428, g_e4d4);
L_b36:;
    x_dd40_xbukycw = g_e4d0_wfmxdlyju + 0x900;
    g_8428 = f_1085a_eklzmb((void *)g_68f8_jwwqkwr);
    if (g_8428 == 0) goto L_b75;
    shutdown_with_exit_message(g_8428, g_e4d4);
L_b75:;
    if (sound_blaster_detected != -1) goto L_bd6;
    g_dd44 = (int)g_e4d0_wfmxdlyju;
    g_8428 = f_1085a_eklzmb((void *)g_693c);
    if (g_8428 == 0) goto L_bbb;
    shutdown_with_exit_message(g_8428, g_e4d4);
L_bbb:;
    queue_audio(g_dd44, g_e4c8, 0x1d4c, -1);
L_bd6:;
    v_4 = *(signed char *)&draw_idx;
    v_8 = image_color_depth;
    clear_pal();
    plot_transformed_pixel(k_DD48_jbwjbqarofg, page2);
    configure_text_renderer((int)g_3be4_zpjqcrvwahs, (int)g_dd4c_ilunphmaok, 1, 1, 3);
    set_text_clip_rect((int)(vga_state.left + 6), (int)(vga_state.top + 4), vga_state.right - 6, vga_state.bottom - 2);
    draw_idx = page2;
    image_color_depth = 8;
    draw_text(8, 8, g_38c6);
    draw_idx = (unsigned short)v_4;
    image_color_depth = (unsigned short)v_8;
    f_3beb(g_e1d8);
    fade_start = 1;
    fade_end = 0xbf;
    fade_pal((void *)(g_e1d8 + 3), 0, -0x3f, -3);
    fade_pal(x_dd40_xbukycw + 3, -0x3f, 0, 3);
    f_100fa((int)vga_state.left, (int)vga_state.top, vga_state.right, 0xc4);
    g_df4c = 0xa;
    g_df48 = 0;
    g_df54 = 0x1c0;
    f_9640(g_5bfc_fosgstopadl, g_8870);
    f_843a();
    g_7b34_cbzosabe = (((g_7b34_cbzosabe & 0xfffe) & 0xfffd) & 0xfffb) & 0xff7f;
    h_df5c = 0;
    g_7b3d_yrsiuxxd = 0;
    set_img_buffers((int)g_d340_schtgisj, 0x100, 4, (int)h_ab40_jbfxrqns, (int)g_bf40_whznxcth);
L_d7a:;
    f_9d40(3);
    if (g_e48d_c == 0x50) goto L_d9a;
    if (g_e48f == 0x50) goto L_d9c;
L_d9a:;
    goto L_da6;
L_d9c:;
    f_9f9();
    goto L_aae;
L_da6:;
    f_80d8();
    handle_s_key();
    write_dac_palette((g_df48 * 3) + g_8870, 0xc0, 0x40, 0);
    --g_df4c;
    if (g_df4c != 0) goto L_e0a;
    g_df4c = 0xa;
    if ((g_df54 - 0x40) > ++g_df48) goto L_e0a;
    g_df48 = 0;
L_e0a:;
    if (g_e48d_c == g_e48f) goto L_e20;
    if (g_e48f == 0x20) goto L_e38;
L_e20:;
    if (g_e48b_3 == g_e48e_0g) goto L_e36;
    if (g_e48e_0g == 1) goto L_e38;
L_e36:;
    goto L_e3a;
L_e38:;
    goto L_e57;
L_e3a:;
    if (g_7bfe == g_7c00) goto L_e52;
    if ((*(unsigned char *)&g_7bfe & 1) != 0) goto L_e57;
L_e52:;
    goto L_d7a;
L_e57:;
    fade_start = 0;
    fade_end = 0x100;
}

void f_e70(void)
{
    stop_audio_stream();
    f_ea4();
    set_display_mode(2);
    f_ff0();
    f_113c();
    stop_audio_stream();
}

void f_ea4(void)
{
    g_e4d0_wfmxdlyju = (unsigned char *)g_7c08_orxezsknd;
    k_DD48_jbwjbqarofg = g_e4d0_wfmxdlyju;
    g_8428 = f_a574_wrvhrpegbz(g_6904);
    if (g_8428 == 0) goto L_ef4;
    shutdown_with_exit_message(g_8428, g_6904);
L_ef4:;
    g_dd4c_ilunphmaok = g_e4d0_wfmxdlyju;
    g_8428 = f_1085a_eklzmb((void *)g_6908);
    if (g_8428 == 0) goto L_f2e;
    shutdown_with_exit_message(g_8428, g_6908);
L_f2e:;
    if (sound_blaster_detected != -1) goto L_f8f;
    g_dd44 = (int)g_e4d0_wfmxdlyju;
    g_8428 = f_1085a_eklzmb((void *)g_690c);
    if (g_8428 == 0) goto L_f74;
    shutdown_with_exit_message(g_8428, g_690c);
L_f74:;
    queue_audio(g_dd44, g_e4c8, 0x1f40, -1);
L_f8f:;
    x_dd40_xbukycw = g_e4d0_wfmxdlyju + 0xc00;
    g_8428 = f_1085a_eklzmb((void *)g_68f8_jwwqkwr);
    if (g_8428 == 0) goto L_fce;
    shutdown_with_exit_message(g_8428, g_68f8_jwwqkwr);
L_fce:;
    g_df54 = (g_e4c8 - 0xc00) / 3;
}

void f_ff0(void)
{
    unsigned char v_4;
    int v_8;
    v_4 = *(signed char *)&draw_idx;
    v_8 = image_color_depth;
    clear_pal();
    plot_transformed_pixel(k_DD48_jbwjbqarofg, page2);
    configure_text_renderer((int)g_3be4_zpjqcrvwahs, (int)g_dd4c_ilunphmaok, 1, 1, 3);
    set_text_clip_rect((int)vga_state.left, (int)vga_state.top, vga_state.right, vga_state.bottom);
    draw_idx = page2;
    image_color_depth = 8;
    draw_text(0x10, 0x36, g_38ca);
    draw_idx = (unsigned short)v_4;
    image_color_depth = (unsigned short)v_8;
    f_3beb((int)(k_DD48_jbwjbqarofg + vga_state.buffer_size));
    f_100fa((int)vga_state.left, (int)vga_state.top, vga_state.right, 0xc4);
    g_df60 = 1;
    g_df70 = (unsigned char *)g_390c_lmsbkmaaant;
    g_df4c = 2;
    g_df48 = 0;
    g_df74 = 0;
    g_dF58 = 0;
    if (g_e144 == 0) goto L_1132;
    f_16bb((int)g_3902);
    g_dF58 = 0x15e;
L_1132:;
    f_843a();
}

void f_113c(void)
{
    g_7b34_cbzosabe = (((g_7b34_cbzosabe & 0xfffe) & 0xfffd) & 0xfffb) & 0xff7f;
    h_df5c = 0;
    g_7b3d_yrsiuxxd = 0;
    set_img_buffers((int)g_d340_schtgisj, 0x100, 4, (int)h_ab40_jbfxrqns, (int)g_bf40_whznxcth);
L_1194:;
    if (h_df5c != 0) goto L_11fd;
    f_9d40(3);
    f_80d8();
    handle_s_key();
    f_1202();
    f_1227();
    f_127e();
    f_13aa();
    f_1416();
    redraw_image_region(0, 0);
    if (image_buffer_error_code == 0) goto L_11f6;
    shutdown_with_exit_message(image_buffer_error_code, 0);
L_11f6:;
    show_page();
    goto L_1194;
L_11fd:;
}

void f_1202(void) {
    next_packed_table_value(&g_df60, &g_df70);
}

void f_1227(void) {
    *(int *)image_buffer_cursor = (int)(g_dd4c_ilunphmaok + *(int *)g_df70);
    *(short *)(image_buffer_cursor + 4) = g_e4c6;
    *(short *)(image_buffer_cursor + 6) = m_E4c4;
    *(short *)(image_buffer_cursor + 8) = 0;
    image_buffer_cursor += 10;
}

void f_127e(void)
{
    if (g_e48b_3 == 1) goto L_129c;
    if (g_e48e_0g == 1) goto L_12d9;
L_129c:;
    if (g_7c00 == g_7bfe) goto L_12b5;
    if (g_7bfe != 0) goto L_12b7;
L_12b5:;
    goto L_12c6;
L_12b7:;
    if (g_e4ba == (int)vga_state.left) goto L_12c8;
L_12c6:;
    goto L_12d7;
L_12c8:;
    if (g_e4bc == (int)vga_state.top) goto L_12d9;
L_12d7:;
    goto L_12ea;
L_12d9:;
    g_e13f = 0xff;
    h_df5c = -1;
L_12ea:;
    g_8e20 = 0;
L_12f4:;
    if (g_8e20 < 4) goto L_130a;
    return;
L_1302:;
    ++g_8e20;
    goto L_12f4;
L_130a:;
    if (g_e4ba <= *(int *)(g_6988 + (g_8e20 << 4))) goto L_1338;
    if (g_e4ba < *(int *)(g_698c + (g_8e20 << 4))) goto L_133a;
L_1338:;
    goto L_1351;
L_133a:;
    if (g_e4bc > *(int *)(g_6990 + (g_8e20 << 4))) goto L_1353;
L_1351:;
    goto L_136a;
L_1353:;
    if (g_e4bc < *(int *)(g_6994 + (g_8e20 << 4))) goto L_136c;
L_136a:;
    goto L_13a0;
L_136c:;
    f_1202();
    if ((g_e468[1].bytes.hi & 0x20) != 0) goto L_13a0;
    if (g_7bfe == 0) goto L_1393;
    if (g_7c00 != g_7bfe) goto L_1395;
L_1393:;
    goto L_13a0;
L_1395:;
    h_df5c = g_8e20 + 1;
L_13a0:;
    goto L_1302;
}

void f_13aa(void) {
    write_dac_palette(x_dd40_xbukycw + g_df48 * 3, 0xc0, 0x20, 0);
    --g_df4c;
    if (g_df4c == 0) {
        g_df4c = 2;
        if (g_df54 - 0x20 <= ++g_df48)
            g_df48 = 0;
    }
}

void f_1416(void)
{
    if (g_e48b_3 == 0x39) goto L_1434;
    if (g_e48e_0g == 0x39) goto L_1436;
L_1434:;
    goto L_147d;
L_1436:;
    g_df74 = -1;
    i_dF44 = 0;
    *(S5 *)g_6984 = *(S5 *)"XXXX";
    strcpy((char *)(g_3906 + 0x2b), (char *)g_6984);
    f_16bb((int)g_3906);
L_147d:;
    if (g_df74 == 0) goto L_15cb;
    if (g_e48e_0g == g_e48b_3) goto L_14a0;
    if ((g_e48e_0g & 0x80) == 0) goto L_14a5;
L_14a0:;
    goto L_15c6;
L_14a5:;
    g_8e46 = g_e48e_0g;
    g_e48b_3 = g_8e46;
    if (g_8e46 != 0xe) goto L_150f;
    if (i_dF44 <= 0) goto L_14df;
    --i_dF44;
    *(unsigned char *)(g_6984 + i_dF44) = 0;
L_14df:;
    strcpy((char *)(g_3906 + 0x2b), (char *)g_6984);
    *(unsigned char *)(g_3906 + 0x2f) = 0;
    f_16bb((int)g_3906);
    goto L_152b;
L_150f:;
    if (g_8e46 != 0x1c) goto L_152b;
    i_dF44 = -1;
    *(unsigned char *)(g_3906 + 0x2f) = 0;
L_152b:;
    g_8e46 = g_e48f;
    g_e48d_c = g_8e46;
    if (g_8e46 < 0x41) goto L_1551;
    if (g_8e46 <= 0x46) goto L_1565;
L_1551:;
    if (g_8e46 < 0x30) goto L_1563;
    if (g_8e46 <= 0x39) goto L_1565;
L_1563:;
    goto L_15c6;
L_1565:;
    *(unsigned char *)(g_6984 + i_dF44) = g_8e46;
    *(unsigned char *)(g_6984 + (i_dF44 + 1)) = 0;
    if (i_dF44 >= 3) goto L_1598;
    ++i_dF44;
L_1598:;
    strcpy((char *)(g_3906 + 0x2b), (char *)g_6984);
    *(unsigned char *)(g_3906 + 0x2f) = 0;
    f_16bb((int)g_3906);
L_15c6:;
    goto L_1643;
L_15cb:;
    --g_dF58;
    if (g_dF58 > 0) goto L_1643;
    g_dF58 = 0x15e;
    g_8e20 = 0xa;
    if (g_e144 != 0) goto L_15fd;
    --g_8e20;
L_15fd:;
    ++g_df50;
    if (g_df50 <= g_8e20) goto L_162b;
    g_e13b = 1;
    h_df5c = 1;
    g_df50 = 0;
L_162b:;
    f_16bb(*(int *)*(unsigned char * *)((unsigned char *)g_5c4c_fbaebsuahb + (g_df50 << 2)));
L_1643:;
    if (g_df74 == 0) goto L_1655;
    if (i_dF44 == -1) goto L_1657;
L_1655:;
    return;
L_1657:;
    g_8e04 = strtoul((char *)g_6984, (void *)g_8e10, 0x10);
    if (f_17d2(g_8e04) == 0) goto L_1694;
    f_16bb(g_38fa);
    goto L_16a2;
L_1694:;
    f_16bb(g_38f6);
L_16a2:;
    g_df74 = 0;
    g_dF58 = 0x15e;
}

void f_16bb(int a0)
{
    unsigned char v_4;
    int v_8;
    v_4 = *(signed char *)&draw_idx;
    v_8 = image_color_depth;
    configure_text_renderer((int)g_3be4_zpjqcrvwahs, (int)g_dd4c_ilunphmaok, 1, 1, 3);
    set_text_clip_rect(0x10, 0xda, vga_state.right, vga_state.bottom);
    image_color_depth = 8;
    draw_idx = flip_src;
    copy_clipped_screen_rectangle(page2, 0, 0xd7, 0x13f, 0xef, draw_idx, 0, 0xd7);
    draw_text(0x10, 0xda, a0);
    draw_idx = flip_dst;
    copy_clipped_screen_rectangle(page2, 0, 0xd7, 0x13f, 0xef, draw_idx, 0, 0xd7);
    draw_text(0x10, 0xda, a0);
    image_color_depth = (unsigned short)v_8;
    draw_idx = (unsigned short)v_4;
}

int f_17d2(unsigned long a0)
{
    a0 = (a0 >> 4) | (a0 << 0xc);
    a0 ^= 0x7b69;
    g_8e04 = a0 & 0x3f;
    g_8e00 = (a0 >> 6) & 7;
    g_8dfc = (a0 >> 9) & 1;
    g_8e08 = ~(((a0 >> 0xa) & 0x3f) ^ (~(g_8e00 + 2) << 2)) & 0x3f;
    if (g_8e04 != g_8e08) goto L_189c;
    g_8e08 = ((g_8e00 ^ (((unsigned)g_8e04 >> 1) ^ ((unsigned)g_8e04 >> 3))) ^ (g_8e00 >> 1)) & 1;
    if (g_8dfc != g_8e08) goto L_189a;
    g_e13c = *(signed char *)&g_8e04;
    g_e140 = *(unsigned char *)&g_8e00;
L_189a:;
    goto L_18aa;
L_189c:;
    g_e13c = 4;
    g_e140 = 0;
L_18aa:;
    return g_e140;
}

void f_18bc(void)
{
    g_8e04 = r_dDDc_uzmlc[1] & 0x3f;
    g_8e00 = (g_e143_eayxx / 0xa) & 7;
    g_8dfc = ((g_8e00 ^ (((unsigned)g_8e04 >> 1) ^ ((unsigned)g_8e04 >> 3))) ^ (g_8e00 >> 1)) & 1;
    g_8e08 = ~((~(g_8e00 + 2) << 2) ^ g_8e04) & 0x3f;
    g_8e08 = ((((g_8e08 << 0xa) | (g_8dfc << 9)) | (g_8e00 << 6)) | g_8e04) ^ 0x7b69;
    g_8e08 = (g_8e08 << 4) | (g_8e08 >> 0xc);
    g_e13c = *(signed char *)&g_8e04;
    g_e140 = *(unsigned char *)&g_8e00;
    itoa(g_8e08 & 0xffff, (char *)(g_3902 + 0x32), 0x10);
}

void f_19b9(void)
{
    stop_audio_stream();
    f_1af4();
    set_display_mode(1);
    f_1b7e();
    f_1d80();
    draw_idx = page2;
    f_1bc2();
    copy_screen_span_entry((short)page2, 0, (short)flip_src, 0, vga_state.buffer_size);
    copy_screen_span_entry((short)page2, 0, (short)flip_dst, 0, vga_state.buffer_size);
    draw_idx = flip_dst;
    draw_page((short)draw_idx);
    f_1e87();
    draw_idx = page2;
    f_1bc2();
    copy_screen_span_entry((short)page2, 0, (short)flip_src, 0, vga_state.buffer_size);
    copy_screen_span_entry((short)page2, 0, (short)flip_dst, 0, vga_state.buffer_size);
    draw_idx = flip_src;
    show_page();
    if (image_buffer_error_code) {
    shutdown_with_exit_message((short)image_buffer_error_code, 0);
    }
L_1adb:;
    g_df6c = 1400;
    f_20f4();
    stop_audio_stream();
}

void f_1af4(void)
{
    g_e4d0_wfmxdlyju = g_7c08_orxezsknd;
    k_DD48_jbwjbqarofg = g_e4d0_wfmxdlyju;
    f_a574_wrvhrpegbz(g_6918);
    g_dd4c_ilunphmaok = g_e4d0_wfmxdlyju;
    f_1085a_eklzmb(g_691c);
    if ((short)sound_blaster_detected != -1) goto L_1b79;
    g_dd44 = g_e4d0_wfmxdlyju;
    f_1085a_eklzmb(g_6920);
    queue_audio(g_dd44, g_e4c8, 8000, -1);
L_1b79:;
}

void f_1b7e(void)
{
    plot_transformed_pixel(k_DD48_jbwjbqarofg, page2);
    f_3beb((int)(k_DD48_jbwjbqarofg + vga_state.buffer_size));
    image_color_depth = 8;
}

void f_1bc2(void)
{
    int v_4;
    int v_8;
    int v_c;
    configure_text_renderer((int)g_43ec_jxwzisjgagn, (int)g_dd4c_ilunphmaok, 0, 0x11, 0x17);
    set_text_clip_rect(vga_state.left, vga_state.top, vga_state.right, vga_state.bottom);
    draw_text(0x32, 0x10, g_388e);
    v_8 = 0x32;
    g_e141 = 1;
L_1c29:;
    if (g_e141 <= 5) goto L_1c3c;
    goto L_1c91;
L_1c34:;
    ++g_e141;
    goto L_1c29;
L_1c3c:;
    v_c = (int)g_6984;
    itoa(g_e141, (char *)v_c, 0xa);
    strcat((char *)v_c, (char *)".");
    v_4 = 0xe;
    draw_text(v_4, v_8, v_c);
    v_8 += g_text_render_state.v20d;
    goto L_1c34;
L_1c91:;
    v_8 = 0x32;
    g_e141 = 0;
L_1c9f:;
    if (g_e141 < 5) goto L_1cb2;
    goto L_1ceb;
L_1caa:;
    ++g_e141;
    goto L_1c9f;
L_1cb2:;
    v_4 = 0x36;
    v_c = (int)((unsigned char *)g_37f4 + (g_e141 * 0x19));
    draw_text(v_4, v_8, v_c);
    v_8 += g_text_render_state.v20d;
    goto L_1caa;
L_1ceb:;
    v_8 = 0x32;
    g_e141 = 0;
L_1cf9:;
    if (g_e141 < 5) goto L_1d0c;
    return;
L_1d04:;
    ++g_e141;
    goto L_1cf9;
L_1d0c:;
    g_8ddc = *(int *)(g_37fd + (g_e141 * 0x19));
    v_c = (int)g_6984;
    ltoa(g_8ddc, (char *)v_c, 0xa);
    v_4 = ((6 - strlen((char *)v_c)) * 0x11) + 0xd5;
    draw_text(v_4, v_8, v_c);
    v_8 += g_text_render_state.v20d;
    goto L_1d04;
}

void f_1d80(void)
{
    if (g_dedc < g_3861) goto L_1e78;
    g_8e46 = 5;
L_1da4:;
    --g_8e46;
    if (g_dedc < *(unsigned int *)((unsigned char *)g_37fd + ((g_8e46 - 1) * 0x19))) goto L_1dcc;
    if (g_8e46 > 0) goto L_1da4;
L_1dcc:;
    g_e141 = 4;
L_1dd3:;
    --g_e141;
    if (g_8e46 > g_e141) goto L_1e34;
    strcpy((char *)g_37f4 + ((g_e141 + 1) * 0x19),
           (char *)g_37f4 + (g_e141 * 0x19));
    *(unsigned int *)((unsigned char *)g_37fd + ((g_e141 + 1) * 0x19)) =
        *(unsigned int *)((unsigned char *)g_37fd + (g_e141 * 0x19));
L_1e34:;
    if (g_e141 > 0) goto L_1dd3;
    g_37f4[g_8e46].name = *(Name *)"        ";
    *(unsigned int *)((unsigned char *)g_37fd + (g_8e46 * 0x19)) = g_dedc;
    g_dedc = g_8e46;
    return;
L_1e78:;
    g_dedc = 0xffffffff;
}

void f_1e87(void)
{
    if (g_dedc == 0xffffffff) goto L_20ce;
    g_e141 = 0;
    *(unsigned char *)g_6984 = 0;
    g_e13d = 0x80;
    g_dF68 = 0x24;
    g_df64 = -1;
L_1eca:;
    --g_dF68;
    if (g_dF68 != 0) goto L_1ee9;
    g_dF68 = 0x23;
    g_df64 = -g_df64;
L_1ee9:;
    if (g_e48e_0g == g_e48b_3) goto L_1f3b;
    g_8e46 = g_e48e_0g;
    g_e48b_3 = g_8e46;
    if (g_8e46 != 0xe) goto L_1f3b;
    if (g_e141 == 0) goto L_1f34;
    --g_e141;
    *(unsigned char *)(g_6984 + g_e141) = 0;
L_1f34:;
    g_e13d = 0x80;
L_1f3b:;
    if (g_e48f == g_e48d_c) goto L_1fd0;
    g_8e46 = g_e48f;
    g_e48d_c = g_8e46;
    if (g_8e46 < 0x41) goto L_1f72;
    if (g_8e46 <= 0x5a) goto L_1f86;
L_1f72:;
    if (g_8e46 < 0x30) goto L_1f84;
    if (g_8e46 <= 0x39) goto L_1f86;
L_1f84:;
    goto L_1f88;
L_1f86:;
    goto L_1f91;
L_1f88:;
    if (g_8e46 != 0x20) goto L_1fd0;
L_1f91:;
    *(unsigned char *)(g_6984 + g_e141) = g_8e46;
    *(unsigned char *)(g_6984 + g_e141 + 1) = 0;
    if (g_e141 >= 7) goto L_1fc9;
    ++g_e141;
L_1fc9:;
    g_e13d = 0x80;
L_1fd0:;
    if (g_e13d == 0) goto L_202b;
    g_e13d = 0;
    copy_clipped_screen_rectangle(page2, 0xe, 0x32, vga_state.right, 0xa5, draw_idx, 0xe, 0x32);
    draw_text(0x36, (g_text_render_state.v20d * g_dedc) + 0x32, (int)g_6984);
L_202b:;
    if (g_dF68 != 0x23) goto L_2083;
    copy_clipped_screen_rectangle(page2, 0x24, 0xae, vga_state.right, 0xc5, draw_idx, 0x24, 0xae);
    if (g_df64 >= 0) goto L_2083;
    draw_text(0x24, 0xae, g_3892);
L_2083:;
    f_9d40(1);
    if (g_e48e_0g == 0x1c) goto L_20a7;
    if (g_e48e_0g != 1) goto L_1eca;
L_20a7:;
    strcpy((char *)((unsigned char *)g_37f4 + (g_dedc * 0x19)), (char *)g_6984);
    g_dedc = 0xffffffff;
L_20ce:;
    draw_idx = page2;
    draw_text(0x32, 0xae, g_3896);
}

void f_20f4(void)
{
    g_7b3d_yrsiuxxd = 0;
    *(unsigned char *)&g_7b34_cbzosabe &= 0xfc;
    *(unsigned char *)&g_7b34_cbzosabe |= 4;
    show_page();
    f_10137_squghx();
L_2121:;
    f_9d40(3);
    handle_s_key();
    if (g_7b3d_yrsiuxxd != 0) goto L_2158;
    if (g_7bfe == g_7c00) goto L_2156;
    if ((*(unsigned char *)&g_7bfe & 7) != 0) goto L_2158;
L_2156:;
    goto L_215a;
L_2158:;
    goto L_2172;
L_215a:;
    if (g_e48b_3 == g_e48e_0g) goto L_2170;
    if (g_e48e_0g == 1) goto L_2172;
L_2170:;
    goto L_2174;
L_2172:;
    return;
L_2174:;
    --g_df6c;
    if (g_df6c != 0) goto L_2121;
}

void f_2188(void)
{
    Row saved[5];
    for (g_8e20 = 0; g_8e20 < 5; ++g_8e20)
        saved[g_8e20] = g_37f4[g_8e20];
    f_228e();
    g_8428 = f_1065b(g_6924, g_e4d0_wfmxdlyju);
    if (g_8428 == 0) {
        f_228e();
        if (g_387a == g_8ddc)
            return;
    }
    for (g_8e20 = 0; g_8e20 < 5; ++g_8e20)
        g_37f4[g_8e20] = saved[g_8e20];
}

void f_2250(void)
{
    f_228e();
    f_228e();
    g_387a = g_8ddc;
    f_107b6((int)g_6924, (int)g_e4d0_wfmxdlyju, 150);
}

void f_228e(void)
{
    g_e4d0_wfmxdlyju = (int)g_37f4;
    g_8ddc = 0;
    g_8dd4 = 0;
L_22b8:;
    if (g_8dd4 < 5) goto L_22ce;
    goto L_234f;
L_22c6:;
    ++g_8dd4;
    goto L_22b8;
L_22ce:;
    g_8ddc ^= ~(*(int *)(g_37fd + (g_8dd4 * 0x19)) << g_8dd4);
    g_8dd8 = 0;
L_22f5:;
    if (g_8dd8 < 8) goto L_2308;
    goto L_234a;
L_2300:;
    ++g_8dd8;
    goto L_22f5;
L_2308:;
    g_8dd0 = *((unsigned char *)g_37f4 + (g_8dd4 * 0x19) + g_8dd8);
    g_8ddc ^= g_8dd0 << ((g_8dd8 % 8) << 2);
    goto L_2300;
L_234a:;
    goto L_22c6;
L_234f:;
    g_8e20 = 0;
L_2359:;
    if (g_8e20 < 5) goto L_236f;
    return;
L_2367:;
    ++g_8e20;
    goto L_2359;
L_236f:;
    if ((((*(int *)(g_37fd + (g_8e20 * 0x19)) * (*(int *)(g_3805 + (g_8e20 * 0x19)) * *(int *)(g_3801 + (g_8e20 * 0x19)))) * 0x1b2c3e4f) ^ -0x758ea2dc) == *(int *)(g_3809 + (g_8e20 * 0x19))) goto L_23be;
    ++g_8ddc;
L_23be:;
    *(int *)(g_3809 + (g_8e20 * 0x19)) = ((*(int *)(g_37fd + (g_8e20 * 0x19)) * (*(int *)(g_3805 + (g_8e20 * 0x19)) * *(int *)(g_3801 + (g_8e20 * 0x19)))) * 0x1b2c3e4f) ^ -0x758ea2dc;
    goto L_2367;
}

void f_240f(void)
{
    stop_audio_stream();
    f_2484();
    set_display_mode(1);
    f_251c();
    f_2565(g_389e);
    f_2565(g_38a2);
    f_2565(g_38a6);
    f_2565(g_38aa);
    f_2565(g_38ae);
    stop_audio_stream();
}

void f_2484(void)
{
    g_e4d0_wfmxdlyju = g_7c08_orxezsknd;
    k_DD48_jbwjbqarofg = g_e4d0_wfmxdlyju;
    f_a574_wrvhrpegbz(g_6934);
    f_1085a_eklzmb(g_68f8_jwwqkwr);
    g_dd4c_ilunphmaok = g_e4d0_wfmxdlyju;
    f_1085a_eklzmb(g_6938);
    if ((short)sound_blaster_detected != -1) goto L_2517;
    g_dd44 = g_e4d0_wfmxdlyju;
    f_1085a_eklzmb(g_693c);
    queue_audio(g_dd44, g_e4c8, 7500, -1);
L_2517:;
}

void f_251c(void)
{
    plot_transformed_pixel(k_DD48_jbwjbqarofg, (short)page2);
    f_3beb((int)((k_DD48_jbwjbqarofg + vga_state.buffer_size) + 1536));
    image_color_depth = 8;
}

void f_2565(int a0)
{
    copy_screen_span_entry(page2, 0, flip_src, 0, vga_state.buffer_size);
    copy_screen_span_entry(page2, 0, flip_dst, 0, vga_state.buffer_size);
    draw_idx = disp_idx;
    configure_text_renderer((int)g_43ec_jxwzisjgagn, (int)g_dd4c_ilunphmaok, 0, 0x11, 0x17);
    set_text_clip_rect(vga_state.left, vga_state.top, vga_state.right, vga_state.bottom);
    draw_text(0x40, 0xa, g_389a);
    configure_text_renderer((int)g_4bf4_pbqzadnradd, (int)g_dd4c_ilunphmaok, 0, 0xa, 0xd);
    set_text_clip_rect(vga_state.left, vga_state.top, vga_state.right, vga_state.bottom);
    draw_text(7, 0x1e, a0);
    if (image_buffer_error_code == 0) goto L_2675;
    shutdown_with_exit_message(image_buffer_error_code, 0);
L_2675:;
    g_df6c = 0x834;
    f_20f4();
}

void f_2689(void)
{
    stop_audio_stream();
    set_display_mode(-1);
    f_26fe();
    f_2796();
    f_27df(g_38b2);
    f_27df(g_38b6);
    f_27df(g_38ba);
    f_27df(g_38be);
    f_27df(g_38c2);
    stop_audio_stream();
}

void f_26fe(void)
{
    g_e4d0_wfmxdlyju = g_7c08_orxezsknd;
    k_DD48_jbwjbqarofg = g_e4d0_wfmxdlyju;
    f_a574_wrvhrpegbz(g_6928);
    f_1085a_eklzmb(g_68f8_jwwqkwr);
    if ((short)sound_blaster_detected == -1) {
    g_dd44 = g_e4d0_wfmxdlyju;
    f_1085a_eklzmb(g_6930);
    queue_audio(g_dd44, g_e4c8, 12000, -1);
    }
L_2779:;
    g_dd4c_ilunphmaok = g_e4d0_wfmxdlyju;
    f_1085a_eklzmb(g_692c);
}

void f_2796(void)
{
    plot_transformed_pixel(k_DD48_jbwjbqarofg, page2);
    f_3beb((int)(k_DD48_jbwjbqarofg + vga_state.buffer_size + 0x900));
    image_color_depth = 8;
}

void f_27df(int a)
{
    copy_screen_span_entry(page2, 0, flip_src, 0, vga_state.buffer_size);
    copy_screen_span_entry(page2, 0, flip_dst, 0, vga_state.buffer_size);
    draw_idx = disp_idx;
    configure_text_renderer((int)g_43ec_jxwzisjgagn, (int)g_dd4c_ilunphmaok, 0, 17, 23);
    set_text_clip_rect(vga_state.left, vga_state.top, vga_state.right, vga_state.bottom);
    draw_text(0x40, 10, g_389a);
    configure_text_renderer((int)g_4bf4_pbqzadnradd, (int)g_dd4c_ilunphmaok, 0, 10, 13);
    set_text_clip_rect(vga_state.left, vga_state.top, vga_state.right, vga_state.bottom);
    draw_text(7, 30, a);
    if (image_buffer_error_code != 0)
        shutdown_with_exit_message(image_buffer_error_code, 0);
    g_df6c = 0x5208;
    f_20f4();
}

void f_2903(void)
{
    int i;
    int unused1;
    int unused2;
    char *old1;
    char *old2;

    stop_audio_stream();
    set_display_mode(1);
    g_e4d0_wfmxdlyju = g_7c08_orxezsknd;
    fade_pal(x_dd40_xbukycw, 0, 0x3f, 8);
    k_DD48_jbwjbqarofg = (char *)g_e4d0_wfmxdlyju;
    x_dd40_xbukycw = k_DD48_jbwjbqarofg + vga_state.buffer_size;
    f_a574_wrvhrpegbz(g_6978);
    old1 = g_e4d0_wfmxdlyju;
    f_a574_wrvhrpegbz(g_697c);
    old2 = g_e4d0_wfmxdlyju;
    f_a574_wrvhrpegbz(g_6980);
    g_dd44 = g_e4d0_wfmxdlyju;
    f_1085a_eklzmb(g_6974);
    queue_audio(g_dd44, g_e4c8, 0x2ae4, -1);
    plot_transformed_pixel(k_DD48_jbwjbqarofg, page2);
    copy_screen_span_entry(page2, 0, flip_src, 0, vga_state.buffer_size);
    copy_screen_span_entry(page2, 0, flip_dst, 0, vga_state.buffer_size);

    for (i = 0; i < 0x40; i++)
        set_pal_rgb(1, (unsigned char)i, (unsigned char)i, (unsigned char)i);
    for (i = 0; i < 0x15e; i++)
        f_9d40(1);
    for (i = 0; i < 0x80; i++)
        write_dac_palette(x_dd40_xbukycw, 0x80, 0x80, 0x3f - i / 2);
    fade_pal(x_dd40_xbukycw, 0, -0x3f, -1);

    k_DD48_jbwjbqarofg = old1;
    x_dd40_xbukycw = k_DD48_jbwjbqarofg + vga_state.buffer_size;
    plot_transformed_pixel(k_DD48_jbwjbqarofg, page2);
    copy_screen_span_entry(page2, 0, flip_src, 0, vga_state.buffer_size);
    copy_screen_span_entry(page2, 0, flip_dst, 0, vga_state.buffer_size);
    fade_pal(x_dd40_xbukycw, -0x3f, 0, 1);
    for (i = 0; i < 0x8c; i++)
        f_9d40(1);
    fade_pal(x_dd40_xbukycw, 0, -0x3f, -3);

    k_DD48_jbwjbqarofg = old2;
    x_dd40_xbukycw = k_DD48_jbwjbqarofg + vga_state.buffer_size;
    plot_transformed_pixel(k_DD48_jbwjbqarofg, page2);
    copy_screen_span_entry(page2, 0, flip_src, 0, vga_state.buffer_size);
    copy_screen_span_entry(page2, 0, flip_dst, 0, vga_state.buffer_size);
    fade_pal(x_dd40_xbukycw, -0x3f, 0, 1);
    for (i = 0; i < 0x8c; i++)
        f_9d40(1);
    fade_pal(x_dd40_xbukycw, 0, -0x3f, -3);
}

void f_2c72_zyd(void)
{
    stop_audio_stream();
    f_2e4a();
    queue_audio(g_dd44, g_e4c8, 0x1f40, -1);
    render_image_with_options(disp_idx, 8, v_DF30 + 0x7102, 0xa0, 100);
}

void f_2ccc(void)
{
    copy_screen_span_entry(disp_idx, 0, page2, 0, vga_state.buffer_size);
    copy_screen_span_entry(page2, 0, flip_src, 0, vga_state.buffer_size);
    copy_screen_span_entry(page2, 0, flip_dst, 0, vga_state.buffer_size);
    stop_audio_stream();
    g_e4d0_wfmxdlyju = g_7c08_orxezsknd;
    f_2eab();
    queue_audio(g_dd44, g_e4c8, 0x1f40, -1);
    u_e150 = (unsigned char *)&g_6c08;
    f_35b5();
    g_7b34_cbzosabe = ((*(short *)&g_7b34_cbzosabe) & 0xfffe) & 0xfffd;
    f_84a0(0x8ca);
    stop_audio_stream();
}

void f_2da3_ehlot(void)
{
    b_DF40_omuefnnbqp = g_e4d0_wfmxdlyju;
    g_Ddd8 = g_e4d0_wfmxdlyju;
    f_1085a_eklzmb(g_6950);
    v_DF30 = g_e4d0_wfmxdlyju;
    f_1085a_eklzmb(g_6954);
    g_df28 = g_e4d0_wfmxdlyju;
    f_1085a_eklzmb(g_5c78);
    if (g_e4c8 != 0x8958)
        g_7c08_orxezsknd = 0;
    g_dd44 = g_e4d0_wfmxdlyju;
    if (sound_blaster_detected == -1)
        f_1085a_eklzmb(g_6968);
    g_e4d0_wfmxdlyju = b_DF40_omuefnnbqp;
}

void f_2e4a(void)
{
    b_DF40_omuefnnbqp = g_e4d0_wfmxdlyju;
    v_DF30 = g_e4d0_wfmxdlyju;
    f_1085a_eklzmb(g_6954);
    g_dd44 = g_e4d0_wfmxdlyju;
    if (sound_blaster_detected == -1)
        f_1085a_eklzmb(g_6970);
    g_e4d0_wfmxdlyju = b_DF40_omuefnnbqp;
}

void f_2eab(void)
{
    b_DF40_omuefnnbqp = g_e4d0_wfmxdlyju;
    v_DF30 = g_e4d0_wfmxdlyju;
    f_1085a_eklzmb(g_6954);
    g_dd44 = g_e4d0_wfmxdlyju;
    if (sound_blaster_detected == -1)
        f_1085a_eklzmb(g_696c);
    g_e4d0_wfmxdlyju = b_DF40_omuefnnbqp;
}

void f_2f0c_cdhyn(void);

void f_2f9e_zo(void);

int f_3203_tjmv(void);

void f_339f_adddtkmk(void);

void f_3406_qruj(void);

void f_34b7(void);

void f_353f(void);

void f_35b5(void);

void f_35e4_rqk(void);

void f_3702(void);

void f_3918(int a, int b, int c, int d);

void f_3ac0(int a, int b, int c);

void f_3ba4(int a, int b);

void f_3beb(int a);

void f_3caa(void);

void f_3cc9(void);

void f_3d23(void);

void f_3e0f(int a, int b);

void f_3e75(void);

void f_4066(void);
