unsigned char screen_palette_buffer[1344];
int sprite_frame_pointer;
/* TU run_gameplay_session..wait_menu_select [0x10, 0x9f9): generated by tools/tu.py */
extern short image_buffer_error_code;
extern short hook_flags_word;
extern unsigned char keyboard_cheat_flags;
int next_extra_life_score;

extern int (*key_repeat)();
extern int (*keyboard_release_handler)();
extern unsigned short mouse_btn;
extern unsigned short mouse_btn_old;
extern int file_error_state;
extern int temp;
extern int frames;
extern unsigned char frnt_pg_upd_buf[];
extern unsigned char back_pg_upd_buf[];
extern unsigned char sprite_commands[];
extern int sfx_data_ptr;
extern int timed_change_count;
extern int remaining_brick_count;
extern int current_ball_count;
extern int spell_count;
extern unsigned char *racket_state;
extern unsigned char *player_key_flags;
extern unsigned char life_lost_flag;
extern unsigned char arcade;
extern unsigned char bonus_index;
extern unsigned char level_number;
extern int g_e1b8;
extern short g_e1bc;
extern short g_e1c0;
extern unsigned char *image_buffer_cursor;
extern unsigned char current_scan_code;
extern unsigned char keyboard_scan_byte;
extern int g_e4c8;
extern int g_e4d0_wfmxdlyju;
extern void update_mouse(void);
extern void fatal_exit(unsigned, unsigned);
extern void handle_s_key(void);
extern int show_order_info(void);
extern void return_to_main_menu(void);
extern void load_assets(void);
extern void reset_lvl(void);
extern void load_and_draw_level(void);
extern int wait_level(void);
extern void entry_prompt(void);
extern int redraw_level_state(void);
extern void draw_status(void);
extern void update_game_status_panel(void);
extern void init_game(void);
extern void process_timed_level_changes(void);
extern void update_falling_spells(void);
extern void next_lvl(void);
extern void update_racket_state(void);
extern void init_round(void);
extern void start_racket_release_animation(void);
extern void update_enemy_projectiles(void);
extern void load_palette(void);
extern void load_enemy(void);
extern void prep_brick(void);
extern void shot_cd(void);
extern void upd_ani(void);
extern void rkt_mv(void);
extern void handle_keyboard_controls(void);
extern void upd_bl(void);
extern void f_9d40(unsigned char);
extern void queue_audio(int, int, int, int);
extern void stop_audio_stream(void);
extern void set_img_buffers(int, int, short, int, int);
extern void redraw_image_region(int, int);
extern int set_display_mode(int);
extern void set_pal_rgb(unsigned char, unsigned char, unsigned char, unsigned char);
extern void show_page(void);
extern void reset_keyboard_action_handlers(void);
/* Initialised data owned by this object: _DATA [0x269c,0x390a) and its CONST literal pool [0x4,0x100d)
   (hall-of-fame table, texts). HYPOTHESIS: may have been a separate data-only object. */
char monster_font_glyph_metrics[2048] = {
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 0, 0, 0, 0, 0xa6, 0, 0, 0,
    0, 0, 0, 0, 0x4a, 1, 0, 0, 0, 0, 0, 0,
    0xee, 1, 0, 0, 0, 0, 0, 0, 0x92, 2, 0, 0,
    0, 0, 0, 0, 0x36, 3, 0, 0, 0, 0, 0, 0,
    0xda, 3, 0, 0, 0, 0, 0, 0, 0x7e, 4, 0, 0,
    0, 0, 0, 0, 0x22, 5, 0, 0, 0, 0, 0, 0,
    0xc6, 5, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1
};
int background_tile_offsets[82] = {
    0x4404, 0, 0x46c0, 0, 0x497c, 0, 0x4d88, 0, 0x509c, 0, 0x54a8, 0,
    0x595c, 0, 0x59a2, 0, 0x5d36, 0, 0x5ea2, 0, 0x605e, 0, 0x6182, 0,
    0x61f8, 0, 0x625c, 0, 0x6348, 0, 0x6400, 0, 0x66bc, 0, 0x6ac8, 0,
    0x70d2, 0, 0x742c, 0, 0x7988, 0, 0x7b5e, 0, 0x7dc6, 0, 0x81d2, 0,
    0x82be, 0, 0x83fa, 0, 0x8536, 0, 0x865c, 0, 0x87c8, 0, 0x88be, 0,
    0x89ba, 0, 0x8a92, 0, 0x8c12, 0, 0x96a0, 0, 0x978c, 0, 0x9878, 0,
    0x9a34, 0, 0x9bf0, 0, 0x9cdc, 0, 0x9e5c, 0, 0x9fdc
};
unsigned char brick_sprite_offsets_first[8] = {0, 0, 0, 0, 0xd7, 0xff, 0xff, 0xff};
char brick_sprite_offsets_remaining[2056] = {
    2, 0, 0, 0, 0, 0, 0, 0, 0xea, 0, 0, 0,
    0, 0, 0, 0, 0xd2, 1, 0, 0, 0, 0, 0, 0,
    0xba, 2, 0, 0, 0, 0, 0, 0, 0xa2, 3, 0, 0,
    0, 0, 0, 0, 0x8a, 4, 0, 0, 0, 0, 0, 0,
    0x72, 5, 0, 0, 0, 0, 0, 0, 0x5a, 6, 0, 0,
    0, 0, 0, 0, 0x42, 7, 0, 0, 0, 0, 0, 0,
    0x2a, 8, 0, 0, 0, 0, 0, 0, 0x12, 9, 0, 0,
    0, 0, 0, 0, 0xfa, 9, 0, 0, 0, 0, 0, 0,
    0xe2, 0xa, 0, 0, 0, 0, 0, 0, 0xca, 0xb, 0, 0,
    0, 0, 0, 0, 0xb2, 0xc, 0, 0, 0, 0, 0, 0,
    0x9a, 0xd, 0, 0, 0, 0, 0, 0, 0x82, 0xe, 0, 0,
    0, 0, 0, 0, 0x6c, 0xf, 0, 0, 0, 0, 0, 0,
    0x56, 0x10, 0, 0, 0, 0, 0, 0, 0x40, 0x11, 0, 0,
    0, 0, 0, 0, 0x2a, 0x12, 0, 0, 0, 0, 0, 0,
    0x14, 0x13, 0, 0, 0, 0, 0, 0, 0xfe, 0x13, 0, 0,
    0, 0, 0, 0, 0xe8, 0x14, 0, 0, 0, 0, 0, 0,
    0xd2, 0x15, 0, 0, 0, 0, 0, 0, 0xbc, 0x16, 0, 0,
    0, 0, 0, 0, 0xa6, 0x17, 0, 0, 0, 0, 0, 0,
    0x90, 0x18, 0, 0, 0, 0, 0, 0, 0x7a, 0x19, 0, 0,
    0, 0, 0, 0, 0x64, 0x1a, 0, 0, 0, 0, 0, 0,
    0x4e, 0x1b, 0, 0, 0, 0, 0, 0, 0x38, 0x1c, 0, 0,
    0, 0, 0, 0, 0x22, 0x1d, 0, 0, 0, 0, 0, 0,
    0xe, 0x1e, 0, 0, 0, 0, 0, 0, 0xfa, 0x1e, 0, 0,
    0, 0, 0, 0, 0xe6, 0x1f, 0, 0, 0, 0, 0, 0,
    0xd2, 0x20, 0, 0, 0, 0, 0, 0, 0xbe, 0x21, 0, 0,
    0, 0, 0, 0, 0xaa, 0x22, 0, 0, 0, 0, 0, 0,
    0x96, 0x23, 0, 0, 0, 0, 0, 0, 0x82, 0x24, 0, 0,
    0, 0, 0, 0, 0x6e, 0x25, 0, 0, 0, 0, 0, 0,
    0x5a, 0x26, 0, 0, 0, 0, 0, 0, 0x46, 0x27, 0, 0,
    0, 0, 0, 0, 0x32, 0x28, 0, 0, 0, 0, 0, 0,
    0x1e, 0x29, 0, 0, 0, 0, 0, 0, 0xa, 0x2a, 0, 0,
    0, 0, 0, 0, 0xf6, 0x2a, 0, 0, 0, 0, 0, 0,
    0xe2, 0x2b, 0, 0, 0, 0, 0, 0, 0xca, 0x2c, 0, 0,
    0, 0, 0, 0, 0xb2, 0x2d, 0, 0, 0, 0, 0, 0,
    0x9a, 0x2e, 0, 0, 0, 0, 0, 0, 0x82, 0x2f, 0, 0,
    0, 0, 0, 0, 0x6a, 0x30, 0, 0, 0, 0, 0, 0,
    0x52, 0x31, 0, 0, 0, 0, 0, 0, 0x3a, 0x32, 0, 0,
    0, 0, 0, 0, 0x22, 0x33, 0, 0, 0, 0, 0, 0,
    0xa, 0x34, 0, 0, 0, 0, 0, 0, 0xf2, 0x34, 0, 0,
    0, 0, 0, 0, 0xda, 0x35, 0, 0, 0, 0, 0, 0,
    0xc2, 0x36, 0, 0, 0, 0, 0, 0, 0xac, 0x37, 0, 0,
    0, 0, 0, 0, 0x96, 0x38, 0, 0, 0, 0, 0, 0,
    0x80, 0x39, 0, 0, 0, 0, 0, 0, 0x6a, 0x3a, 0, 0,
    0, 0, 0, 0, 0x54, 0x3b, 0, 0, 0, 0, 0, 0,
    0x3e, 0x3c, 0, 0, 0, 0, 0, 0, 0x28, 0x3d, 0, 0,
    0, 0, 0, 0, 0x12, 0x3e, 0, 0, 0, 0, 0, 0,
    0xfc, 0x3e, 0, 0, 0, 0, 0, 0, 0xe6, 0x3f, 0, 0,
    0, 0, 0, 0, 0xd0, 0x40, 0, 0, 0, 0, 0, 0,
    0xba, 0x41, 0, 0, 0, 0, 0, 0, 0xa4, 0x42, 0, 0,
    0, 0, 0, 0, 0x8e, 0x43, 0, 0, 0, 0, 0, 0,
    0x78, 0x44, 0, 0, 0, 0, 0, 0, 0x62, 0x45, 0, 0,
    0, 0, 0, 0, 0x4c, 0x46, 0, 0, 0, 0, 0, 0,
    0x36, 0x47, 0, 0, 0, 0, 0, 0, 0x20, 0x48, 0, 0,
    0, 0, 0, 0, 0xa, 0x49, 0, 0, 0, 0, 0, 0,
    0xf6, 0x49, 0, 0, 0, 0, 0, 0, 0xe2, 0x4a, 0, 0,
    0, 0, 0, 0, 0xce, 0x4b, 0, 0, 0, 0, 0, 0,
    0xba, 0x4c, 0, 0, 0, 0, 0, 0, 0xa6, 0x4d, 0, 0,
    0, 0, 0, 0, 0x92, 0x4e, 0, 0, 0, 0, 0, 0,
    0x7e, 0x4f, 0, 0, 0, 0, 0, 0, 0x6a, 0x50, 0, 0,
    0, 0, 0, 0, 0x56, 0x51, 0, 0, 0, 0, 0, 0,
    0x42, 0x52, 0, 0, 0, 0, 0, 0, 0x2e, 0x53, 0, 0,
    0, 0, 0, 0, 0x1a, 0x54, 0, 0, 0, 0, 0, 0,
    4, 0x55, 0, 0, 0, 0, 0, 0, 0xee, 0x55, 0, 0,
    0, 0, 0, 0, 0xd8, 0x56, 0, 0, 0, 0, 0, 0,
    0xc2, 0x57, 0, 0, 0, 0, 0, 0, 0xaa, 0x58, 0, 0,
    0, 0, 0, 0, 0x92, 0x59, 0, 0, 0, 0, 0, 0,
    0x7a, 0x5a, 0, 0, 0, 0, 0, 0, 0x62, 0x5b, 0, 0,
    0, 0, 0, 0, 0x4a, 0x5c, 0, 0, 0, 0, 0, 0,
    0x32, 0x5d, 0, 0, 0, 0, 0, 0, 0x1a, 0x5e, 0, 0,
    0, 0, 0, 0, 2, 0x5f, 0, 0, 0, 0, 0, 0,
    0xea, 0x5f, 0, 0, 0, 0, 0, 0, 0xd2, 0x60, 0, 0,
    0, 0, 0, 0, 0xba, 0x61, 0, 0, 0, 0, 0, 0,
    0xa2, 0x62, 0, 0, 0, 0, 0, 0, 0x8a, 0x63, 0, 0,
    0, 0, 0, 0, 0x72, 0x64, 0, 0, 0, 0, 0, 0,
    0x5a, 0x65, 0, 0, 0, 0, 0, 0, 0x42, 0x66, 0, 0,
    0, 0, 0, 0, 0x2c, 0x67, 0, 0, 0, 0, 0, 0,
    0x16, 0x68, 0, 0, 0, 0, 0, 0, 0, 0x69, 0, 0,
    0, 0, 0, 0, 0xea, 0x69, 0, 0, 0, 0, 0, 0,
    0xd4, 0x6a, 0, 0, 0, 0, 0, 0, 0xbe, 0x6b, 0, 0,
    0, 0, 0, 0, 0xa8, 0x6c, 0, 0, 0, 0, 0, 0,
    0x92, 0x6d, 0, 0, 0, 0, 0, 0, 0x7c, 0x6e, 0, 0,
    0, 0, 0, 0, 0x66, 0x6f, 0, 0, 0, 0, 0, 0,
    0x50, 0x70, 0, 0, 0, 0, 0, 0, 0x3a, 0x71, 0, 0,
    0, 0, 0, 0, 0x24, 0x72, 0, 0, 0, 0, 0, 0,
    0xe, 0x73, 0, 0, 0, 0, 0, 0, 0xf8, 0x73, 0, 0,
    0, 0, 0, 0, 0xe2, 0x74, 0, 0, 0, 0, 0, 0,
    0xce, 0x75, 0, 0, 0, 0, 0, 0, 0xba, 0x76, 0, 0,
    0, 0, 0, 0, 0xa6, 0x77, 0, 0, 0, 0, 0, 0,
    0x92, 0x78, 0, 0, 0, 0, 0, 0, 0x7e, 0x79, 0, 0,
    0, 0, 0, 0, 0x6a, 0x7a, 0, 0, 0, 0, 0, 0,
    0x56, 0x7b, 0, 0, 0, 0, 0, 0, 0x42, 0x7c, 0, 0,
    0, 0, 0, 0, 0x2e, 0x7d, 0, 0, 0, 0, 0, 0,
    0x1a, 0x7e, 0, 0, 0, 0, 0, 0, 6, 0x7f, 0, 0,
    0, 0, 0, 0, 0xf2, 0x7f, 0, 0, 0, 0, 0, 0,
    0xdc, 0x80, 0, 0, 0, 0, 0, 0, 0xc8, 0x81, 0, 0,
    0, 0, 0, 0, 0xb4, 0x82, 0, 0, 0, 0, 0, 0,
    0xa0, 0x83, 0, 0, 0, 0, 0, 0, 0x86, 0x84, 0, 0,
    0, 0, 0, 0, 0x6c, 0x85, 0, 0, 0, 0, 0, 0,
    0x52, 0x86, 0, 0, 0, 0, 0, 0, 0x38, 0x87, 0, 0,
    0, 0, 0, 0, 0x1e, 0x88, 0, 0, 0, 0, 0, 0,
    4, 0x89, 0, 0, 0, 0, 0, 0, 0xea, 0x89, 0, 0,
    0, 0, 0, 0, 0xd0, 0x8a, 0, 0, 0, 0, 0, 0,
    0xb6, 0x8b, 0, 0, 0, 0, 0, 0, 0x9c, 0x8c, 0, 0,
    0, 0, 0, 0, 0x82, 0x8d, 0, 0, 0, 0, 0, 0,
    0x68, 0x8e, 0, 0, 0, 0, 0, 0, 0x4e, 0x8f, 0, 0,
    0, 0, 0, 0, 0x34, 0x90, 0, 0, 0, 0, 0, 0,
    0x1a, 0x91, 0, 0, 0, 0, 0, 0, 0, 0x92, 0, 0,
    0, 0, 0, 0, 0xe6, 0x92, 0, 0, 0, 0, 0, 0,
    0xcc, 0x93, 0, 0, 0, 0, 0, 0, 0xb2, 0x94, 0, 0,
    0, 0, 0, 0, 0x98, 0x95, 0, 0, 0, 0, 0, 0,
    0x7e, 0x96, 0, 0, 0, 0, 0, 0, 0x64, 0x97, 0, 0,
    0, 0, 0, 0, 0x4a, 0x98, 0, 0, 0, 0, 0, 0,
    0x30, 0x99, 0, 0, 0, 0, 0, 0, 0x16, 0x9a, 0, 0,
    0, 0, 0, 0, 0xfc, 0x9a, 0, 0, 0, 0, 0, 0,
    0xe2, 0x9b, 0, 0, 0, 0, 0, 0, 0xc8, 0x9c, 0, 0,
    0, 0, 0, 0, 0xae, 0x9d, 0, 0, 0, 0, 0, 0,
    0x94, 0x9e, 0, 0, 0, 0, 0, 0, 0x7a, 0x9f, 0, 0,
    0, 0, 0, 0, 0x60, 0xa0, 0, 0, 0, 0, 0, 0,
    0x46, 0xa1, 0, 0, 0, 0, 0, 0, 0x2c, 0xa2, 0, 0,
    0, 0, 0, 0, 0x12, 0xa3, 0, 0, 0, 0, 0, 0,
    0xf8, 0xa3, 0, 0, 0, 0, 0, 0, 0xde, 0xa4, 0, 0,
    0, 0, 0, 0, 0xc4, 0xa5, 0, 0, 0, 0, 0, 0,
    0xaa, 0xa6, 0, 0, 0, 0, 0, 0, 0x90, 0xa7, 0, 0,
    0, 0, 0, 0, 0x76, 0xa8, 0, 0, 0, 0, 0, 0,
    0x5c, 0xa9, 0, 0, 0, 0, 0, 0, 0x42, 0xaa, 0, 0,
    0, 0, 0, 0, 0x28, 0xab, 0, 0, 0, 0, 0, 0,
    0xe, 0xac, 0, 0, 0, 0, 0, 0, 0xf4, 0xac, 0, 0,
    0, 0, 0, 0, 0xda, 0xad, 0, 0, 0, 0, 0, 0,
    0xc0, 0xae, 0, 0, 0, 0, 0, 0, 0xa6, 0xaf, 0, 0,
    0, 0, 0, 0, 0x8c, 0xb0, 0, 0, 0, 0, 0, 0,
    0x72, 0xb1, 0, 0, 0, 0, 0, 0, 0x58, 0xb2, 0, 0,
    0, 0, 0, 0, 0x3e, 0xb3, 0, 0, 0, 0, 0, 0,
    0x24, 0xb4, 0, 0, 0, 0, 0, 0, 0xa, 0xb5, 0, 0,
    0, 0, 0, 0, 0xf0, 0xb5, 0, 0, 0, 0, 0, 0,
    0xd6, 0xb6, 0, 0, 0, 0, 0, 0, 0xbc, 0xb7, 0, 0,
    0, 0, 0, 0, 0xa2, 0xb8, 0, 0, 0, 0, 0, 0,
    0x88, 0xb9, 0, 0, 0, 0, 0, 0, 0x6e, 0xba, 0, 0,
    0, 0, 0, 0, 0x54, 0xbb, 0, 0, 0, 0, 0, 0,
    0x3a, 0xbc, 0, 0, 0, 0, 0, 0, 0x20, 0xbd, 0, 0,
    0, 0, 0, 0, 6, 0xbe, 0, 0, 0, 0, 0, 0,
    0xec, 0xbe, 0, 0, 0, 0, 0, 0, 0xd2, 0xbf, 0, 0,
    0, 0, 0, 0, 0xb8, 0xc0, 0, 0, 0, 0, 0, 0,
    0x9e, 0xc1, 0, 0, 0, 0, 0, 0, 0x84, 0xc2, 0, 0,
    0, 0, 0, 0, 0x6a, 0xc3, 0, 0, 0, 0, 0, 0,
    0x50, 0xc4, 0, 0, 0, 0, 0, 0, 0x36, 0xc5, 0, 0,
    0, 0, 0, 0, 0x1c, 0xc6, 0, 0, 0, 0, 0, 0,
    2, 0xc7, 0, 0, 0, 0, 0, 0, 0xe8, 0xc7, 0, 0,
    0, 0, 0, 0, 0xce, 0xc8, 0, 0, 0, 0, 0, 0,
    0xb4, 0xc9, 0, 0, 0, 0, 0, 0, 0x9a, 0xca, 0, 0,
    0, 0, 0, 0, 0x80, 0xcb, 0, 0, 0, 0, 0, 0,
    0x66, 0xcc, 0, 0, 0, 0, 0, 0, 0x4c, 0xcd, 0, 0,
    0, 0, 0, 0, 0x32, 0xce, 0, 0, 0, 0, 0, 0,
    0x18, 0xcf, 0, 0, 0, 0, 0, 0, 0xfe, 0xcf, 0, 0,
    0, 0, 0, 0, 0xe4, 0xd0, 0, 0, 0, 0, 0, 0,
    0xca, 0xd1, 0, 0, 0, 0, 0, 0, 0xb0, 0xd2, 0, 0,
    0, 0, 0, 0, 0x96, 0xd3, 0, 0, 0, 0, 0, 0,
    0x7c, 0xd4, 0, 0, 0, 0, 0, 0, 0x62, 0xd5, 0, 0,
    0, 0, 0, 0, 0x48, 0xd6, 0, 0, 0, 0, 0, 0,
    0x2e, 0xd7, 0, 0, 0, 0, 0, 0, 0x14, 0xd8, 0, 0,
    0, 0, 0, 0, 0xfa, 0xd8, 0, 0, 0, 0, 0, 0,
    0xe0, 0xd9, 0, 0, 0, 0, 0, 0, 0xc6, 0xda, 0, 0,
    0, 0, 0, 0, 0xac, 0xdb, 0, 0, 0, 0, 0, 0,
    0x92, 0xdc, 0, 0, 0, 0, 0, 0, 0x78, 0xdd, 0, 0,
    0, 0, 0, 0, 0x5e, 0xde, 0, 0, 0, 0, 0, 0,
    0x44, 0xdf, 0, 0, 0, 0, 0, 0, 0x2a, 0xe0, 0, 0,
    0, 0, 0, 0, 0x10, 0xe1, 0, 0, 0, 0, 0, 0,
    0xf6, 0xe1, 0, 0, 0, 0, 0, 0, 0xdc, 0xe2, 0, 0,
    0, 0, 0, 0, 0xc2, 0xe3, 0, 0, 0, 0, 0, 0,
    0xa8, 0xe4, 0, 0, 0, 0, 0, 0, 0x8e, 0xe5, 0, 0,
    0, 0, 0, 0, 0x74, 0xe6, 0, 0, 0, 0, 0, 0,
    0x5a, 0xe7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0xff, 0xff, 0xff
};
unsigned char high_score_records[9] = {0x46, 0x69, 0x6e, 0x64, 0x20, 0x74, 0x68, 0x65};
unsigned char high_score_values[4] = {0x88, 0x13};
unsigned char high_score_factor_a[4] = {0};
unsigned char high_score_factor_b[4] = {0};
unsigned char high_score_checksums[88] = {
    0, 0, 0, 0, 0x20, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x20,
    0, 0xa0, 0xf, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0x20, 0x6f, 0x66, 0x20, 0x74, 0x68, 0x65,
    0x20, 0, 0xb8, 0xb, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0x65, 0x74, 0x65, 0x72, 0x6e, 0x61,
    0x6c, 0, 0, 0xd0, 7, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0x20, 0x20, 0x6c, 0x69, 0x66,
    0x65, 0x20, 0x20
};
unsigned int minimum_high_score = 0x3e8;
unsigned char g_3865[21] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0x43, 0x75, 0x72, 0x69, 0x6f, 0x75, 0x73
};
int saved_high_score_state = 0;
unsigned char g_387e[12] = {0};
char *best_of_the_bests_text = "\016\013\022\000BestOfTheBests";
char *hall_of_fame_text = "Hall Of Fame";
char *enter_name_text = "Enter your name";
char *enjoy_yourself_text = "Enjoy yourself";
char *game_title_text = "KRYPTON EGG\n";
char *opening_credits_page = "     THE ULTIMATE BREAK OUT    \n    Thank you for purchasing\n\n This game has been created in \n the hope of making a fun game.\n\n We have worked in the spirit\n   to give you the best and \n  We hope you will enjoy it\n\n     Our only ambition is...\n       ...to amaze you\n                   Page 1 of 5\n";
char *how_to_play_page = "         HOW TO PLAY\n\n  Press the\nLeft button..to release the ball\nRight button.to shoot\nKEY ESCAPE...to kill the racket\nKEY   P......to pause the game\n\n If you move the racket while \nreceive the ball you create a \nslide effect \n\n                   Page 2 of 5\n";
char *enemies_and_shields_page = "\n         THE ENEMIES\n  The enemies arrive on screen\ntrough the upper door. You can\ntouch most of them. The only one\nthat can kill you if you have no\nshield is the picus vulgarus.\n\n         THE SHIELDS\nTo have shields catch the spells\nA star on your racket indicates\nthat you possess some shields.\n                   Page 3 of 5\n";
char *mouse_and_high_score_page = "\nIf you want to adjust the mouse\nspeed keep pushing the CONTROL \nkey and CLICK many times the...\n..LEFT mouse button to slow down\n..RIGHT mouse button to speed up\n\n    IN THE HIGHSCORE SCREEN\n\n    If you are in the top 5\nYou can enter your name with\n      the keyboard\n                   Page 4 of 5\n";
char *programming_credits_page = "           Programming\n\n Alexandre Kral  1988  AMIGA ST\n    Xavier Kral  1993     PC\n\n Graphic Artist       Black Ray\n                  Kral Brothers\n               Philippe Geurten\n\n Sound Sculptor    Ryo Innagaki\n               Philippe Deneyer\n\n                   Page 5 of 5\n";
char *ending_page_one = "\n          YOU MADE IT\n\n\n   SO FAR...\n    SO HARD...\n     SO INCREDIBLE...   IT WAS.\n\n\n WHAT KIND OF HUMAN ARE YOU ...\n       ARE YOU ONLY HUMAN ...\n\n                   Page 1 of 5\n";
char *ending_page_two = "\n          YOU DID IT\n\n\n      I CONGRATULATE YOU\n\n       WORDS ESCAPES ME...\n    BUT THE FACTS ARE TRUE\n\n     YOU NOW BELONG TO THE \n     FINEST TEAM EVER SEEN  \n\n                   Page 2 of 5\n";
char *ending_page_three = "\n   NOW THAT YOU HAVE PASSED\n      THE HARDEST LEVELS\n\n         THE SECRET OF \n   ETERNAL LIFE IS NOW YOURS\n\n YOU MUST TYPE DURING THE GAME\n\n     I WANT TO BE IMMORTAL\n\nWITHOUT SPACES BUT WITH RETURN\n                   Page 3 of 5\n";
char *ending_page_four = "\n     I HOPE YOU ENJOYED\n        WHILE PLAYING\n\n  You must absolutely send us\n  your highscore file named\n  ke.score.lst to enter the\n      great tournament\n\n   You can win our new game\n          IKO SAN\n\n                   Page 4 of 5\n";
char *ending_page_five = "\n     EVERYTHING HAS AN END\n      EVEN THE END ITSELF\n\n     ITS NOW TIME FOR ME TO\n         SAY GOODBYE AND\n   ONCE MORE CONGRATULATIONS\n\n    Dont forget to write us\n\nTHANK YOU FOR PLAYING  XAVIER\n\n                   Page 5 of 5\n";
char *ordering_information_text = "          Ordering informations\n\n To order by VISA EuroCard ... Call us at\n331 40.08.07.07 and have your card handy. You can also print the file ORDER.FRM and fax it to 331  43.87.35.99 or mail it to\n           C2V Productions\n        82 Boulevard Haussman\n             75008 Paris\n               France\n\nDOS Full version 60 levels for 30 US\n\nWindows NATIVE version release in October\nDemo Version     10 levels for 15 US\nFull Version     60 levels for 35 US\n\nPress the P key to print your order now.";
char *version_text = "MS DOS Commercial Version 1.1 60 levels\n";
char *game_credit = "    Original Game and Ideas by\n          Alexandre Kral.";
char *pc_credits = "   PC Programming by Xavier Kral.\nPC Graphics improvements by Black Ray.";
char *pub_credit = "           Edited by C2V\n           Copyright 1994";
char *mouse_speed_help = "      To adjust the mouse speed. \nPress the CTRL key n without letting go";
char *mouse_button_help = "   Click on LEFT button to slow down\n   Click on RIGHT button to speed up";
char *return_to_dos_help = "      To go back to the DOS.\n       Press the ESCape key.";
char *restart_code_help = "   Every 10 levels you will receive\na code to restart from where you died";
char *enter_code_help = "        To enter your code.\n   Press the SPACE BAR key and ...";
char *validate_code_help = " Type the letters and numbers of your\n code and press RETURN to validate it.";
char *author_message_text = " I really hope that you will enjoy it.\n                        Xavier.";
char *invalid_code_text = "      I am sorry but ... \n    your code is NOT correct.";
char *valid_code_text = "  G R E A T ... your code is correct\nClick on PLAY panel to continue the game";
char *immortality_cheat_phrase = "NeverEndingProgram";
char *last_code_prompt = "    Your last code is the following\n                         ";
char *enter_code_prompt = "     Please Enter your code.\n              XXXX    ";

void run_gameplay_session(void);
extern unsigned char lives;
extern unsigned char difficulty_tier_index;
extern unsigned char start_decade;
extern unsigned char score_storage[];
extern void set_game_progress(int, int, int);
extern int rand_rng(int, int);
extern unsigned char codeok;
extern void encode_restart_code(void);
extern int run_level(void);
typedef struct { int value, pad; } Pair8;
extern Pair8 racket_sprite_frames[];
extern int sprite_instance_count;
extern unsigned char player_key_flag_storage[];
extern int enemy_cursor;
extern unsigned char enemy_spawn_wait_time[];
extern unsigned char *current_ball_pointer;
extern int motion_dir;
extern int player_shot_total;
extern int moving_target_count;
extern int enemy_timer;
extern int palette_base;
extern unsigned char racket_state_storage[];
extern unsigned char *game_art_base;
extern unsigned char *racket_object;
extern void write_dac_palette(void *, int, int, int);
extern void advance_racket_anim(void);
extern void start_spell_animation_e(void);
extern void start_racket_movement_animation(void);
extern void update_racket_dimensions(void);
extern void update_racket_movement_bounds(void);
extern void spawn_game_ball(int, int);
extern int tileid;
extern int prompt;
extern int menu_result;
extern int points;
extern unsigned char done;
extern void show_game_over_screen(void);
extern void write_high_score_table(void);
extern void show_instructions(void);
extern void show_ending_pages(void);
extern void initialize_main_menu(void);
extern void show_high_score_screen(void);
extern void update_menu_screen(void);
void load_menu_graphics(void);
void prep_menu_background(void);
void wait_menu_select(void);
extern int title_image_file;
extern int title_data_filename;
extern short sound_blaster_detected;
extern int file_operation_result;
extern unsigned char *sprite_memory_base;
extern int load_next_file();
extern int f_a574_wrvhrpegbz();
extern unsigned char *vga_buffer_base;
struct DisplayModeInfo { short state; unsigned char plane_addresses[16]; int page_offsets[4]; int page_adjustments[4]; unsigned char page_mode_classes[4]; int buffer_size; int row_stride_bytes; int resolution_height; int width; int height; int left; int top; int right; int bottom; unsigned char mode_flags; unsigned char e37f; unsigned char e380; unsigned char video_mode_low; unsigned char e382; unsigned char e383; unsigned char e384; unsigned char e385; unsigned char e386; unsigned char tail; };
extern struct DisplayModeInfo vga_state;
extern short disp_idx;
extern short flip_src;
extern void fade_pal(void *, int, int, int);
extern void plot_transformed_pixel(void *, int);
extern void draw_page(int);
extern short audio_stream_flag;
extern short space_pressed;

/* Original text pointer initializers from obj3 fixups, in _DATA definition order. */

void run_gameplay_session(void)
{
    init_game();
    while (1) {
        stop_audio_stream();
        set_display_mode(1);
        next_lvl();
        if (*(int *)(racket_state + 4) < 0) goto L_374;
        if (level_number >= 0x3c) goto L_385;
        g_e4d0_wfmxdlyju = file_error_state;
        load_palette();
        load_assets();
        reset_lvl();
        load_and_draw_level();
        queue_audio(sfx_data_ptr, g_e4c8, 0x157c, 0);
        if (wait_level()) {
            if (!bonus_index) {
                entry_prompt();
            }
        }
        stop_audio_stream();
        load_enemy();
        prep_brick();
        timed_change_count = 0;
        if (image_buffer_error_code) {
            fatal_exit(image_buffer_error_code, 0);
        }
L_d6:;
        stop_audio_stream();
        init_round();
        draw_status();
        key_repeat = show_order_info;
        keyboard_release_handler = redraw_level_state;
        *(unsigned char *)&hook_flags_word |= 0x80;
        *(unsigned char *)&hook_flags_word &= 0xfb;
        *(unsigned char *)&hook_flags_word |= 3;
        set_img_buffers((int)sprite_commands, 0x100, 4, (int)frnt_pg_upd_buf, (int)back_pg_upd_buf);
        f_9d40(0);
        f_9d40(0);
        for (temp = 0; temp < 4; ++temp) {
            update_mouse();
        }
L_16d:;
        f_9d40(3);
        if (keyboard_cheat_flags & 0x80) {
            set_pal_rgb(0, 0, 0x3f, 0);
        }
        g_e1bc = 0;
        g_e1b8 = (int)image_buffer_cursor;
        do {
            image_buffer_cursor = (unsigned char *)g_e1b8;
            handle_s_key();
            ++frames;
            rkt_mv();
            update_racket_state();
            if (keyboard_cheat_flags & 0x80) {
                set_pal_rgb(0, 0, 0x2a, 0);
            }
            if (arcade) {
                *(unsigned char *)player_key_flags |= 8;
            }
            upd_bl();
            if (keyboard_cheat_flags & 0x80) {
                set_pal_rgb(0, 0, 0x15, 0);
            }
            shot_cd();
            if (arcade) {
                *(unsigned char *)player_key_flags &= 0xf7;
            }
            update_falling_spells();
            upd_ani();
            update_enemy_projectiles();
            process_timed_level_changes();
            ++g_e1bc;
        } while (g_e1bc < g_e1c0);
        redraw_image_region(0, 0);
        if (image_buffer_error_code) {
            fatal_exit(image_buffer_error_code, 0);
        }
        update_game_status_panel();
        if ((current_scan_code != 1 && keyboard_scan_byte == 1) || (current_ball_count <= 0 && spell_count <= 0 && !bonus_index)) {
            start_racket_release_animation();
        }
        if (remaining_brick_count > 0 || spell_count > 0) break;
        if (arcade) goto L_385;
        for (temp = 0; temp < 5; ++temp) {
            f_9d40(0);
        }
    }
    handle_keyboard_controls();
    show_page();
    if (arcade && (mouse_btn_old != mouse_btn || keyboard_scan_byte == 0x39)) goto L_385;
    if (!life_lost_flag) goto L_16d;
    if (!arcade) {
        if ((*(int *)(racket_state + 4) -= 0x71) >= 0) goto L_d6;
L_374:;
        *(unsigned char *)&hook_flags_word &= 0xfc;
        reset_keyboard_action_handlers();
        return_to_main_menu();
    }
L_385:;
    if (arcade) {
        arcade = 0;
        *(int *)(racket_state + 0x14) = 0;
    }
    *(unsigned char *)&hook_flags_word &= 0xfc;
    reset_keyboard_action_handlers();
}

void init_game(void) {
    level_number = (unsigned char)(start_decade * 10 - 1);
    temp = lives;
    if (arcade) {
        level_number = (unsigned char)(rand_rng(0, 0x3b) - 1);
        temp = 0;
    }
    racket_state = score_storage;
    set_game_progress(1, temp, 0);
    if (start_decade) {
        difficulty_tier_index = 1;
    } else {
        difficulty_tier_index = 0;
    }
    bonus_index = 0;
}

void next_lvl(void)
{
    if (bonus_index) {
        bonus_index = 0;
        return;
    }
    if (difficulty_tier_index) {
        if (start_decade == 6) goto L_4bb;
        ++level_number;
        difficulty_tier_index = 0;
        return;
    }
    ++level_number;
    if (!arcade) {
        if (level_number >= 0xa && !(level_number % 0xa)) {
L_4bb:;
            difficulty_tier_index = (unsigned char)(level_number / 0xa);
            if (run_level()) {
                encode_restart_code();
                codeok = 0xff;
            } else {
                *(int *)(racket_state + 4) = -1;
            }
            return;
        }
        if (!(level_number % 5)) {
            bonus_index = (unsigned char)(((level_number / 5) + 1) >> 1);
        }
    }
}

void init_round(void)
{
    life_lost_flag = 0;
    player_key_flags = player_key_flag_storage;
    *(int *)player_key_flags = 0;
    racket_object = racket_state_storage;
    *(int *)racket_object = 0x90;
    *(int *)(racket_object + 4) = 0xbc;
    *(int *)(racket_object + 0x1c) = 3;
    *(int *)(racket_object + 0x78) = (int)(game_art_base + racket_sprite_frames[3].value);
    *(int *)(racket_object + 0x24) = 0;
    *(int *)(racket_object + 0x28) = 0;
    *(int *)(racket_object + 0x2c) = 0;
    *(int *)(racket_object + 0x30) = 0;
    write_dac_palette((void *)palette_base, 0, 0x100, 0);
    *(int *)(racket_object + 0x34) = 0;
    *(int *)(racket_object + 0x38) = 0;
    *(int *)(racket_object + 0x3c) = 0;
    update_racket_dimensions();
    update_racket_movement_bounds();
    start_racket_movement_animation();
    current_ball_count = 0;
    if (!bonus_index) {
        spawn_game_ball(0x90, 0xbc);
        *(unsigned char *)(current_ball_pointer + 0x11) |= 1;
        *(int *)current_ball_pointer -= 0x900;
    }
    spell_count = 0;
    sprite_instance_count = 0;
    player_shot_total = 0;
    moving_target_count = 0;
    enemy_cursor = 0;
    enemy_timer = *(int *)enemy_spawn_wait_time;
    if (bonus_index) {
        start_spell_animation_e();
        *(int *)(racket_object + 0x64) = 2;
        *(int *)(racket_object + 0x68) = 0xa;
        motion_dir = 1;
        advance_racket_anim();
        *(unsigned char *)(player_key_flags + 1) |= 4;
    }
}

void set_game_progress(int a0, int a1, int a2) {
    ((int *)racket_state)[0] = a0;
    ((int *)racket_state)[1] = a1 * 113;
    ((int *)racket_state)[5] = a2;
    next_extra_life_score = 0x7cf;
}

void run_main_menu(void);

void initialize_main_menu(void);

void load_menu_graphics(void);

void prep_menu_background(void);

void wait_menu_select(void);
