unsigned char g_8870[1344];
int g_8db4;
/* TU f_10..f_951_vbfkytgovb [0x10, 0x9f9): generated by tools/tu.py */
extern short g_746c_mmw;
extern short g_7b34_cbzosabe;
extern unsigned char g_7b36;
int g_8db0;

extern int (*g_7b3f_gng)();
extern int (*g_7b43)();
extern unsigned short g_7bfe;
extern unsigned short g_7c00;
extern int g_7c08_orxezsknd;
extern int g_8e20;
extern int g_8e24;
extern unsigned char h_ab40_jbfxrqns[];
extern unsigned char g_bf40_whznxcth[];
extern unsigned char g_d340_schtgisj[];
extern int g_dd44;
extern int g_dd74_ntd;
extern int g_dd78;
extern int g_dDa8;
extern int g_ddc0;
extern unsigned char *r_dDDc_uzmlc;
extern unsigned char *m_de5c;
extern unsigned char g_e13a;
extern unsigned char g_e13b;
extern unsigned char g_e142_baun;
extern unsigned char g_e143_eayxx;
extern int g_e1b8;
extern short g_e1bc;
extern short g_e1c0;
extern unsigned char *g_e2ec;
extern unsigned char g_e48b_3;
extern unsigned char g_e48e_0g;
extern int g_e4c8;
extern int g_e4d0_wfmxdlyju;
extern void f_10137_squghx(void);
extern void shutdown_with_exit_message(unsigned, unsigned);
extern void f_13b72(void);
extern int f_2c72_zyd(void);
extern void f_2ccc(void);
extern void f_2da3_ehlot(void);
extern void f_2f0c_cdhyn(void);
extern void f_2f9e_zo(void);
extern int f_3203_tjmv(void);
extern void f_3406_qruj(void);
extern int f_353f(void);
extern void f_35e4_rqk(void);
extern void f_3702(void);
extern void f_3b2_jzcvbvx(void);
extern void f_3caa(void);
extern void f_4066(void);
extern void f_441_wfixgn(void);
extern void f_4cf2(void);
extern void f_52f_bssi(void);
extern void f_5771(void);
extern void f_5966(void);
extern void f_608a_ujonj(void);
extern void f_60e5_grt(void);
extern void f_61a6_vby(void);
extern void f_6278(void);
extern void f_7bd5(void);
extern void f_80d8(void);
extern void f_814b(void);
extern void f_8585(void);
extern void f_9d40(unsigned char);
extern void f_c14b_lmdi(int, int, int, int);
extern void f_c3ab_euckgzihaj(void);
extern void f_c8c0_pm(int, int, short, int, int);
extern void f_c9ce(int, int);
extern int f_e095_ughrsvpfh(int);
extern void f_ecdf(unsigned char, unsigned char, unsigned char, unsigned char);
extern void f_ed38(void);
extern void f_fc86(void);
/* Initialised data owned by this object: _DATA [0x269c,0x390a) and its CONST literal pool [0x4,0x100d)
   (hall-of-fame table, texts). HYPOTHESIS: may have been a separate data-only object. */
char g_269c[2048] = {
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 0, 0, 0, 0, 0xa6, 0, 0, 0,
    0, 0, 0, 0, 0x4a, 1, 0, 0, 0, 0, 0, 0,
    0xee, 1, 0, 0, 0, 0, 0, 0, 0x92, 2, 0, 0,
    0, 0, 0, 0, 0x36, 3, 0, 0, 0, 0, 0, 0,
    0xda, 3, 0, 0, 0, 0, 0, 0, 0x7e, 4, 0, 0,
    0, 0, 0, 0, 0x22, 5, 0, 0, 0, 0, 0, 0,
    0xc6, 5, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    2, 0, 0, 0, 1
};
int g_2e9c[82] = {
    0x4404, 0, 0x46c0, 0, 0x497c, 0, 0x4d88, 0, 0x509c, 0, 0x54a8, 0,
    0x595c, 0, 0x59a2, 0, 0x5d36, 0, 0x5ea2, 0, 0x605e, 0, 0x6182, 0,
    0x61f8, 0, 0x625c, 0, 0x6348, 0, 0x6400, 0, 0x66bc, 0, 0x6ac8, 0,
    0x70d2, 0, 0x742c, 0, 0x7988, 0, 0x7b5e, 0, 0x7dc6, 0, 0x81d2, 0,
    0x82be, 0, 0x83fa, 0, 0x8536, 0, 0x865c, 0, 0x87c8, 0, 0x88be, 0,
    0x89ba, 0, 0x8a92, 0, 0x8c12, 0, 0x96a0, 0, 0x978c, 0, 0x9878, 0,
    0x9a34, 0, 0x9bf0, 0, 0x9cdc, 0, 0x9e5c, 0, 0x9fdc
};
unsigned char g_2fe4[8] = {0, 0, 0, 0, 0xd7, 0xff, 0xff, 0xff};
char g_2fec[2056] = {
    2, 0, 0, 0, 0, 0, 0, 0, 0xea, 0, 0, 0,
    0, 0, 0, 0, 0xd2, 1, 0, 0, 0, 0, 0, 0,
    0xba, 2, 0, 0, 0, 0, 0, 0, 0xa2, 3, 0, 0,
    0, 0, 0, 0, 0x8a, 4, 0, 0, 0, 0, 0, 0,
    0x72, 5, 0, 0, 0, 0, 0, 0, 0x5a, 6, 0, 0,
    0, 0, 0, 0, 0x42, 7, 0, 0, 0, 0, 0, 0,
    0x2a, 8, 0, 0, 0, 0, 0, 0, 0x12, 9, 0, 0,
    0, 0, 0, 0, 0xfa, 9, 0, 0, 0, 0, 0, 0,
    0xe2, 0xa, 0, 0, 0, 0, 0, 0, 0xca, 0xb, 0, 0,
    0, 0, 0, 0, 0xb2, 0xc, 0, 0, 0, 0, 0, 0,
    0x9a, 0xd, 0, 0, 0, 0, 0, 0, 0x82, 0xe, 0, 0,
    0, 0, 0, 0, 0x6c, 0xf, 0, 0, 0, 0, 0, 0,
    0x56, 0x10, 0, 0, 0, 0, 0, 0, 0x40, 0x11, 0, 0,
    0, 0, 0, 0, 0x2a, 0x12, 0, 0, 0, 0, 0, 0,
    0x14, 0x13, 0, 0, 0, 0, 0, 0, 0xfe, 0x13, 0, 0,
    0, 0, 0, 0, 0xe8, 0x14, 0, 0, 0, 0, 0, 0,
    0xd2, 0x15, 0, 0, 0, 0, 0, 0, 0xbc, 0x16, 0, 0,
    0, 0, 0, 0, 0xa6, 0x17, 0, 0, 0, 0, 0, 0,
    0x90, 0x18, 0, 0, 0, 0, 0, 0, 0x7a, 0x19, 0, 0,
    0, 0, 0, 0, 0x64, 0x1a, 0, 0, 0, 0, 0, 0,
    0x4e, 0x1b, 0, 0, 0, 0, 0, 0, 0x38, 0x1c, 0, 0,
    0, 0, 0, 0, 0x22, 0x1d, 0, 0, 0, 0, 0, 0,
    0xe, 0x1e, 0, 0, 0, 0, 0, 0, 0xfa, 0x1e, 0, 0,
    0, 0, 0, 0, 0xe6, 0x1f, 0, 0, 0, 0, 0, 0,
    0xd2, 0x20, 0, 0, 0, 0, 0, 0, 0xbe, 0x21, 0, 0,
    0, 0, 0, 0, 0xaa, 0x22, 0, 0, 0, 0, 0, 0,
    0x96, 0x23, 0, 0, 0, 0, 0, 0, 0x82, 0x24, 0, 0,
    0, 0, 0, 0, 0x6e, 0x25, 0, 0, 0, 0, 0, 0,
    0x5a, 0x26, 0, 0, 0, 0, 0, 0, 0x46, 0x27, 0, 0,
    0, 0, 0, 0, 0x32, 0x28, 0, 0, 0, 0, 0, 0,
    0x1e, 0x29, 0, 0, 0, 0, 0, 0, 0xa, 0x2a, 0, 0,
    0, 0, 0, 0, 0xf6, 0x2a, 0, 0, 0, 0, 0, 0,
    0xe2, 0x2b, 0, 0, 0, 0, 0, 0, 0xca, 0x2c, 0, 0,
    0, 0, 0, 0, 0xb2, 0x2d, 0, 0, 0, 0, 0, 0,
    0x9a, 0x2e, 0, 0, 0, 0, 0, 0, 0x82, 0x2f, 0, 0,
    0, 0, 0, 0, 0x6a, 0x30, 0, 0, 0, 0, 0, 0,
    0x52, 0x31, 0, 0, 0, 0, 0, 0, 0x3a, 0x32, 0, 0,
    0, 0, 0, 0, 0x22, 0x33, 0, 0, 0, 0, 0, 0,
    0xa, 0x34, 0, 0, 0, 0, 0, 0, 0xf2, 0x34, 0, 0,
    0, 0, 0, 0, 0xda, 0x35, 0, 0, 0, 0, 0, 0,
    0xc2, 0x36, 0, 0, 0, 0, 0, 0, 0xac, 0x37, 0, 0,
    0, 0, 0, 0, 0x96, 0x38, 0, 0, 0, 0, 0, 0,
    0x80, 0x39, 0, 0, 0, 0, 0, 0, 0x6a, 0x3a, 0, 0,
    0, 0, 0, 0, 0x54, 0x3b, 0, 0, 0, 0, 0, 0,
    0x3e, 0x3c, 0, 0, 0, 0, 0, 0, 0x28, 0x3d, 0, 0,
    0, 0, 0, 0, 0x12, 0x3e, 0, 0, 0, 0, 0, 0,
    0xfc, 0x3e, 0, 0, 0, 0, 0, 0, 0xe6, 0x3f, 0, 0,
    0, 0, 0, 0, 0xd0, 0x40, 0, 0, 0, 0, 0, 0,
    0xba, 0x41, 0, 0, 0, 0, 0, 0, 0xa4, 0x42, 0, 0,
    0, 0, 0, 0, 0x8e, 0x43, 0, 0, 0, 0, 0, 0,
    0x78, 0x44, 0, 0, 0, 0, 0, 0, 0x62, 0x45, 0, 0,
    0, 0, 0, 0, 0x4c, 0x46, 0, 0, 0, 0, 0, 0,
    0x36, 0x47, 0, 0, 0, 0, 0, 0, 0x20, 0x48, 0, 0,
    0, 0, 0, 0, 0xa, 0x49, 0, 0, 0, 0, 0, 0,
    0xf6, 0x49, 0, 0, 0, 0, 0, 0, 0xe2, 0x4a, 0, 0,
    0, 0, 0, 0, 0xce, 0x4b, 0, 0, 0, 0, 0, 0,
    0xba, 0x4c, 0, 0, 0, 0, 0, 0, 0xa6, 0x4d, 0, 0,
    0, 0, 0, 0, 0x92, 0x4e, 0, 0, 0, 0, 0, 0,
    0x7e, 0x4f, 0, 0, 0, 0, 0, 0, 0x6a, 0x50, 0, 0,
    0, 0, 0, 0, 0x56, 0x51, 0, 0, 0, 0, 0, 0,
    0x42, 0x52, 0, 0, 0, 0, 0, 0, 0x2e, 0x53, 0, 0,
    0, 0, 0, 0, 0x1a, 0x54, 0, 0, 0, 0, 0, 0,
    4, 0x55, 0, 0, 0, 0, 0, 0, 0xee, 0x55, 0, 0,
    0, 0, 0, 0, 0xd8, 0x56, 0, 0, 0, 0, 0, 0,
    0xc2, 0x57, 0, 0, 0, 0, 0, 0, 0xaa, 0x58, 0, 0,
    0, 0, 0, 0, 0x92, 0x59, 0, 0, 0, 0, 0, 0,
    0x7a, 0x5a, 0, 0, 0, 0, 0, 0, 0x62, 0x5b, 0, 0,
    0, 0, 0, 0, 0x4a, 0x5c, 0, 0, 0, 0, 0, 0,
    0x32, 0x5d, 0, 0, 0, 0, 0, 0, 0x1a, 0x5e, 0, 0,
    0, 0, 0, 0, 2, 0x5f, 0, 0, 0, 0, 0, 0,
    0xea, 0x5f, 0, 0, 0, 0, 0, 0, 0xd2, 0x60, 0, 0,
    0, 0, 0, 0, 0xba, 0x61, 0, 0, 0, 0, 0, 0,
    0xa2, 0x62, 0, 0, 0, 0, 0, 0, 0x8a, 0x63, 0, 0,
    0, 0, 0, 0, 0x72, 0x64, 0, 0, 0, 0, 0, 0,
    0x5a, 0x65, 0, 0, 0, 0, 0, 0, 0x42, 0x66, 0, 0,
    0, 0, 0, 0, 0x2c, 0x67, 0, 0, 0, 0, 0, 0,
    0x16, 0x68, 0, 0, 0, 0, 0, 0, 0, 0x69, 0, 0,
    0, 0, 0, 0, 0xea, 0x69, 0, 0, 0, 0, 0, 0,
    0xd4, 0x6a, 0, 0, 0, 0, 0, 0, 0xbe, 0x6b, 0, 0,
    0, 0, 0, 0, 0xa8, 0x6c, 0, 0, 0, 0, 0, 0,
    0x92, 0x6d, 0, 0, 0, 0, 0, 0, 0x7c, 0x6e, 0, 0,
    0, 0, 0, 0, 0x66, 0x6f, 0, 0, 0, 0, 0, 0,
    0x50, 0x70, 0, 0, 0, 0, 0, 0, 0x3a, 0x71, 0, 0,
    0, 0, 0, 0, 0x24, 0x72, 0, 0, 0, 0, 0, 0,
    0xe, 0x73, 0, 0, 0, 0, 0, 0, 0xf8, 0x73, 0, 0,
    0, 0, 0, 0, 0xe2, 0x74, 0, 0, 0, 0, 0, 0,
    0xce, 0x75, 0, 0, 0, 0, 0, 0, 0xba, 0x76, 0, 0,
    0, 0, 0, 0, 0xa6, 0x77, 0, 0, 0, 0, 0, 0,
    0x92, 0x78, 0, 0, 0, 0, 0, 0, 0x7e, 0x79, 0, 0,
    0, 0, 0, 0, 0x6a, 0x7a, 0, 0, 0, 0, 0, 0,
    0x56, 0x7b, 0, 0, 0, 0, 0, 0, 0x42, 0x7c, 0, 0,
    0, 0, 0, 0, 0x2e, 0x7d, 0, 0, 0, 0, 0, 0,
    0x1a, 0x7e, 0, 0, 0, 0, 0, 0, 6, 0x7f, 0, 0,
    0, 0, 0, 0, 0xf2, 0x7f, 0, 0, 0, 0, 0, 0,
    0xdc, 0x80, 0, 0, 0, 0, 0, 0, 0xc8, 0x81, 0, 0,
    0, 0, 0, 0, 0xb4, 0x82, 0, 0, 0, 0, 0, 0,
    0xa0, 0x83, 0, 0, 0, 0, 0, 0, 0x86, 0x84, 0, 0,
    0, 0, 0, 0, 0x6c, 0x85, 0, 0, 0, 0, 0, 0,
    0x52, 0x86, 0, 0, 0, 0, 0, 0, 0x38, 0x87, 0, 0,
    0, 0, 0, 0, 0x1e, 0x88, 0, 0, 0, 0, 0, 0,
    4, 0x89, 0, 0, 0, 0, 0, 0, 0xea, 0x89, 0, 0,
    0, 0, 0, 0, 0xd0, 0x8a, 0, 0, 0, 0, 0, 0,
    0xb6, 0x8b, 0, 0, 0, 0, 0, 0, 0x9c, 0x8c, 0, 0,
    0, 0, 0, 0, 0x82, 0x8d, 0, 0, 0, 0, 0, 0,
    0x68, 0x8e, 0, 0, 0, 0, 0, 0, 0x4e, 0x8f, 0, 0,
    0, 0, 0, 0, 0x34, 0x90, 0, 0, 0, 0, 0, 0,
    0x1a, 0x91, 0, 0, 0, 0, 0, 0, 0, 0x92, 0, 0,
    0, 0, 0, 0, 0xe6, 0x92, 0, 0, 0, 0, 0, 0,
    0xcc, 0x93, 0, 0, 0, 0, 0, 0, 0xb2, 0x94, 0, 0,
    0, 0, 0, 0, 0x98, 0x95, 0, 0, 0, 0, 0, 0,
    0x7e, 0x96, 0, 0, 0, 0, 0, 0, 0x64, 0x97, 0, 0,
    0, 0, 0, 0, 0x4a, 0x98, 0, 0, 0, 0, 0, 0,
    0x30, 0x99, 0, 0, 0, 0, 0, 0, 0x16, 0x9a, 0, 0,
    0, 0, 0, 0, 0xfc, 0x9a, 0, 0, 0, 0, 0, 0,
    0xe2, 0x9b, 0, 0, 0, 0, 0, 0, 0xc8, 0x9c, 0, 0,
    0, 0, 0, 0, 0xae, 0x9d, 0, 0, 0, 0, 0, 0,
    0x94, 0x9e, 0, 0, 0, 0, 0, 0, 0x7a, 0x9f, 0, 0,
    0, 0, 0, 0, 0x60, 0xa0, 0, 0, 0, 0, 0, 0,
    0x46, 0xa1, 0, 0, 0, 0, 0, 0, 0x2c, 0xa2, 0, 0,
    0, 0, 0, 0, 0x12, 0xa3, 0, 0, 0, 0, 0, 0,
    0xf8, 0xa3, 0, 0, 0, 0, 0, 0, 0xde, 0xa4, 0, 0,
    0, 0, 0, 0, 0xc4, 0xa5, 0, 0, 0, 0, 0, 0,
    0xaa, 0xa6, 0, 0, 0, 0, 0, 0, 0x90, 0xa7, 0, 0,
    0, 0, 0, 0, 0x76, 0xa8, 0, 0, 0, 0, 0, 0,
    0x5c, 0xa9, 0, 0, 0, 0, 0, 0, 0x42, 0xaa, 0, 0,
    0, 0, 0, 0, 0x28, 0xab, 0, 0, 0, 0, 0, 0,
    0xe, 0xac, 0, 0, 0, 0, 0, 0, 0xf4, 0xac, 0, 0,
    0, 0, 0, 0, 0xda, 0xad, 0, 0, 0, 0, 0, 0,
    0xc0, 0xae, 0, 0, 0, 0, 0, 0, 0xa6, 0xaf, 0, 0,
    0, 0, 0, 0, 0x8c, 0xb0, 0, 0, 0, 0, 0, 0,
    0x72, 0xb1, 0, 0, 0, 0, 0, 0, 0x58, 0xb2, 0, 0,
    0, 0, 0, 0, 0x3e, 0xb3, 0, 0, 0, 0, 0, 0,
    0x24, 0xb4, 0, 0, 0, 0, 0, 0, 0xa, 0xb5, 0, 0,
    0, 0, 0, 0, 0xf0, 0xb5, 0, 0, 0, 0, 0, 0,
    0xd6, 0xb6, 0, 0, 0, 0, 0, 0, 0xbc, 0xb7, 0, 0,
    0, 0, 0, 0, 0xa2, 0xb8, 0, 0, 0, 0, 0, 0,
    0x88, 0xb9, 0, 0, 0, 0, 0, 0, 0x6e, 0xba, 0, 0,
    0, 0, 0, 0, 0x54, 0xbb, 0, 0, 0, 0, 0, 0,
    0x3a, 0xbc, 0, 0, 0, 0, 0, 0, 0x20, 0xbd, 0, 0,
    0, 0, 0, 0, 6, 0xbe, 0, 0, 0, 0, 0, 0,
    0xec, 0xbe, 0, 0, 0, 0, 0, 0, 0xd2, 0xbf, 0, 0,
    0, 0, 0, 0, 0xb8, 0xc0, 0, 0, 0, 0, 0, 0,
    0x9e, 0xc1, 0, 0, 0, 0, 0, 0, 0x84, 0xc2, 0, 0,
    0, 0, 0, 0, 0x6a, 0xc3, 0, 0, 0, 0, 0, 0,
    0x50, 0xc4, 0, 0, 0, 0, 0, 0, 0x36, 0xc5, 0, 0,
    0, 0, 0, 0, 0x1c, 0xc6, 0, 0, 0, 0, 0, 0,
    2, 0xc7, 0, 0, 0, 0, 0, 0, 0xe8, 0xc7, 0, 0,
    0, 0, 0, 0, 0xce, 0xc8, 0, 0, 0, 0, 0, 0,
    0xb4, 0xc9, 0, 0, 0, 0, 0, 0, 0x9a, 0xca, 0, 0,
    0, 0, 0, 0, 0x80, 0xcb, 0, 0, 0, 0, 0, 0,
    0x66, 0xcc, 0, 0, 0, 0, 0, 0, 0x4c, 0xcd, 0, 0,
    0, 0, 0, 0, 0x32, 0xce, 0, 0, 0, 0, 0, 0,
    0x18, 0xcf, 0, 0, 0, 0, 0, 0, 0xfe, 0xcf, 0, 0,
    0, 0, 0, 0, 0xe4, 0xd0, 0, 0, 0, 0, 0, 0,
    0xca, 0xd1, 0, 0, 0, 0, 0, 0, 0xb0, 0xd2, 0, 0,
    0, 0, 0, 0, 0x96, 0xd3, 0, 0, 0, 0, 0, 0,
    0x7c, 0xd4, 0, 0, 0, 0, 0, 0, 0x62, 0xd5, 0, 0,
    0, 0, 0, 0, 0x48, 0xd6, 0, 0, 0, 0, 0, 0,
    0x2e, 0xd7, 0, 0, 0, 0, 0, 0, 0x14, 0xd8, 0, 0,
    0, 0, 0, 0, 0xfa, 0xd8, 0, 0, 0, 0, 0, 0,
    0xe0, 0xd9, 0, 0, 0, 0, 0, 0, 0xc6, 0xda, 0, 0,
    0, 0, 0, 0, 0xac, 0xdb, 0, 0, 0, 0, 0, 0,
    0x92, 0xdc, 0, 0, 0, 0, 0, 0, 0x78, 0xdd, 0, 0,
    0, 0, 0, 0, 0x5e, 0xde, 0, 0, 0, 0, 0, 0,
    0x44, 0xdf, 0, 0, 0, 0, 0, 0, 0x2a, 0xe0, 0, 0,
    0, 0, 0, 0, 0x10, 0xe1, 0, 0, 0, 0, 0, 0,
    0xf6, 0xe1, 0, 0, 0, 0, 0, 0, 0xdc, 0xe2, 0, 0,
    0, 0, 0, 0, 0xc2, 0xe3, 0, 0, 0, 0, 0, 0,
    0xa8, 0xe4, 0, 0, 0, 0, 0, 0, 0x8e, 0xe5, 0, 0,
    0, 0, 0, 0, 0x74, 0xe6, 0, 0, 0, 0, 0, 0,
    0x5a, 0xe7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0xff, 0xff, 0xff
};
unsigned char g_37f4[9] = {0x46, 0x69, 0x6e, 0x64, 0x20, 0x74, 0x68, 0x65};
unsigned char g_37fd[4] = {0x88, 0x13};
unsigned char g_3801[4] = {0};
unsigned char g_3805[4] = {0};
unsigned char g_3809[88] = {
    0, 0, 0, 0, 0x20, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x20,
    0, 0xa0, 0xf, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0x20, 0x6f, 0x66, 0x20, 0x74, 0x68, 0x65,
    0x20, 0, 0xb8, 0xb, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0x65, 0x74, 0x65, 0x72, 0x6e, 0x61,
    0x6c, 0, 0, 0xd0, 7, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0x20, 0x20, 0x6c, 0x69, 0x66,
    0x65, 0x20, 0x20
};
unsigned int g_3861 = 0x3e8;
unsigned char g_3865[21] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0x43, 0x75, 0x72, 0x69, 0x6f, 0x75, 0x73
};
int g_387a = 0;
unsigned char g_387e[12] = {0};
char *g_388a = "\016\013\022\000BestOfTheBests";
char *g_388e = "Hall Of Fame";
char *g_3892 = "Enter your name";
char *g_3896 = "Enjoy yourself";
char *g_389a = "KRYPTON EGG\n";
char *g_389e = "     THE ULTIMATE BREAK OUT    \n    Thank you for purchasing\n\n This game has been created in \n the hope of making a fun game.\n\n We have worked in the spirit\n   to give you the best and \n  We hope you will enjoy it\n\n     Our only ambition is...\n       ...to amaze you\n                   Page 1 of 5\n";
char *g_38a2 = "         HOW TO PLAY\n\n  Press the\nLeft button..to release the ball\nRight button.to shoot\nKEY ESCAPE...to kill the racket\nKEY   P......to pause the game\n\n If you move the racket while \nreceive the ball you create a \nslide effect \n\n                   Page 2 of 5\n";
char *g_38a6 = "\n         THE ENEMIES\n  The enemies arrive on screen\ntrough the upper door. You can\ntouch most of them. The only one\nthat can kill you if you have no\nshield is the picus vulgarus.\n\n         THE SHIELDS\nTo have shields catch the spells\nA star on your racket indicates\nthat you possess some shields.\n                   Page 3 of 5\n";
char *g_38aa = "\nIf you want to adjust the mouse\nspeed keep pushing the CONTROL \nkey and CLICK many times the...\n..LEFT mouse button to slow down\n..RIGHT mouse button to speed up\n\n    IN THE HIGHSCORE SCREEN\n\n    If you are in the top 5\nYou can enter your name with\n      the keyboard\n                   Page 4 of 5\n";
char *g_38ae = "           Programming\n\n Alexandre Kral  1988  AMIGA ST\n    Xavier Kral  1993     PC\n\n Graphic Artist       Black Ray\n                  Kral Brothers\n               Philippe Geurten\n\n Sound Sculptor    Ryo Innagaki\n               Philippe Deneyer\n\n                   Page 5 of 5\n";
char *g_38b2 = "\n          YOU MADE IT\n\n\n   SO FAR...\n    SO HARD...\n     SO INCREDIBLE...   IT WAS.\n\n\n WHAT KIND OF HUMAN ARE YOU ...\n       ARE YOU ONLY HUMAN ...\n\n                   Page 1 of 5\n";
char *g_38b6 = "\n          YOU DID IT\n\n\n      I CONGRATULATE YOU\n\n       WORDS ESCAPES ME...\n    BUT THE FACTS ARE TRUE\n\n     YOU NOW BELONG TO THE \n     FINEST TEAM EVER SEEN  \n\n                   Page 2 of 5\n";
char *g_38ba = "\n   NOW THAT YOU HAVE PASSED\n      THE HARDEST LEVELS\n\n         THE SECRET OF \n   ETERNAL LIFE IS NOW YOURS\n\n YOU MUST TYPE DURING THE GAME\n\n     I WANT TO BE IMMORTAL\n\nWITHOUT SPACES BUT WITH RETURN\n                   Page 3 of 5\n";
char *g_38be = "\n     I HOPE YOU ENJOYED\n        WHILE PLAYING\n\n  You must absolutely send us\n  your highscore file named\n  ke.score.lst to enter the\n      great tournament\n\n   You can win our new game\n          IKO SAN\n\n                   Page 4 of 5\n";
char *g_38c2 = "\n     EVERYTHING HAS AN END\n      EVEN THE END ITSELF\n\n     ITS NOW TIME FOR ME TO\n         SAY GOODBYE AND\n   ONCE MORE CONGRATULATIONS\n\n    Dont forget to write us\n\nTHANK YOU FOR PLAYING  XAVIER\n\n                   Page 5 of 5\n";
char *g_38c6 = "          Ordering informations\n\n To order by VISA EuroCard ... Call us at\n331 40.08.07.07 and have your card handy. You can also print the file ORDER.FRM and fax it to 331  43.87.35.99 or mail it to\n           C2V Productions\n        82 Boulevard Haussman\n             75008 Paris\n               France\n\nDOS Full version 60 levels for 30 US\n\nWindows NATIVE version release in October\nDemo Version     10 levels for 15 US\nFull Version     60 levels for 35 US\n\nPress the P key to print your order now.";
char *g_38ca = "MS DOS Commercial Version 1.1 60 levels\n";
char *g_38ce = "    Original Game and Ideas by\n          Alexandre Kral.";
char *g_38d2 = "   PC Programming by Xavier Kral.\nPC Graphics improvements by Black Ray.";
char *g_38d6 = "           Edited by C2V\n           Copyright 1994";
char *g_38da = "      To adjust the mouse speed. \nPress the CTRL key n without letting go";
char *g_38de = "   Click on LEFT button to slow down\n   Click on RIGHT button to speed up";
char *g_38e2 = "      To go back to the DOS.\n       Press the ESCape key.";
char *g_38e6 = "   Every 10 levels you will receive\na code to restart from where you died";
char *g_38ea = "        To enter your code.\n   Press the SPACE BAR key and ...";
char *g_38ee = " Type the letters and numbers of your\n code and press RETURN to validate it.";
char *g_38f2 = " I really hope that you will enjoy it.\n                        Xavier.";
char *g_38f6 = "      I am sorry but ... \n    your code is NOT correct.";
char *g_38fa = "  G R E A T ... your code is correct\nClick on PLAY panel to continue the game";
char *g_38fe = "NeverEndingProgram";
char *g_3902 = "    Your last code is the following\n                         ";
char *g_3906 = "     Please Enter your code.\n              XXXX    ";

void f_10(void);
extern unsigned char g_e13c;
extern unsigned char g_e13e;
extern unsigned char g_e140;
extern unsigned char g_df04[];
extern void f_6ca(int, int, int);
extern int f_dd53(int, int);
extern unsigned char g_e144;
extern void f_18bc(void);
extern int f_6b02(void);
typedef struct { int value, pad; } Pair8;
extern Pair8 g_6218[];
extern int g_dd84;
extern unsigned char i_DD98[];
extern int g_dd9c;
extern unsigned char g_ddb0[];
extern unsigned char *g_ddb4;
extern int g_dDb8;
extern int g_dDc8;
extern int g_ddcc;
extern int g_ddd0;
extern int g_ddd4_eoraaik;
extern unsigned char g_de60[];
extern unsigned char *g_dee0;
extern unsigned char *g_dee4;
extern void f_13a48(void *, int, int, int);
extern void f_4886(void);
extern void f_4bae(void);
extern void f_57bf(void);
extern void f_57fa(void);
extern void f_58b0(void);
extern void f_8fce(int, int);
extern int g_df38;
extern int g_df50;
extern int h_df5c;
extern int g_dedc;
extern unsigned char g_e13f;
extern void f_19b9(void);
extern void f_2250(void);
extern void f_240f(void);
extern void f_2689(void);
extern void f_7e9(void);
extern void f_aa2(void);
extern void f_e70(void);
void f_81d_psgpolkaxl(void);
void f_8d3_szjtcdqild(void);
void f_951_vbfkytgovb(void);
extern int g_68fc_ifhyqlddj;
extern int g_6900;
extern short g_747c;
extern int g_8428;
extern unsigned char *k_DD48_jbwjbqarofg;
extern int f_1085a_eklzmb();
extern int f_a574_wrvhrpegbz();
extern unsigned char *x_dd40_xbukycw;
extern int g_e35a;
extern short g_7b14;
extern short g_7b20;
extern void f_ea9f(void *, int, int, int);
extern void f_a810(void *, int);
extern void f_ee33(int);
extern short g_742c;
extern short g_7b3d_yrsiuxxd;

/* Original text pointer initializers from obj3 fixups, in _DATA definition order. */

void f_10(void)
{
    f_3b2_jzcvbvx();
L_21:;
    f_c3ab_euckgzihaj();
    f_e095_ughrsvpfh(1);
    f_441_wfixgn();
    if (*(int *)(r_dDDc_uzmlc + 4) < 0) goto L_374;
    if (g_e143_eayxx >= 0x3c) goto L_385;
    g_e4d0_wfmxdlyju = g_7c08_orxezsknd;
    f_608a_ujonj();
    f_2da3_ehlot();
    f_2f0c_cdhyn();
    f_2f9e_zo();
    f_c14b_lmdi(g_dd44, g_e4c8, 0x157c, 0);
    if (f_3203_tjmv() == 0) goto L_a1;
    if (g_e142_baun != 0) goto L_a1;
    f_3406_qruj();
L_a1:;
    f_c3ab_euckgzihaj();
    f_60e5_grt();
    f_61a6_vby();
    g_dd74_ntd = 0;
    if (g_746c_mmw == 0) goto L_d6;
    shutdown_with_exit_message(g_746c_mmw, 0);
L_d6:;
    f_c3ab_euckgzihaj();
    f_52f_bssi();
    f_35e4_rqk();
    g_7b3f_gng = f_2c72_zyd;
    g_7b43 = f_353f;
    *(unsigned char *)&g_7b34_cbzosabe |= 0x80;
    *(unsigned char *)&g_7b34_cbzosabe &= 0xfb;
    *(unsigned char *)&g_7b34_cbzosabe |= 3;
    f_c8c0_pm((int)g_d340_schtgisj, 0x100, 4, (int)h_ab40_jbfxrqns, (int)g_bf40_whznxcth);
    f_9d40(0);
    f_9d40(0);
    g_8e20 = 0;
L_153:;
    if (g_8e20 < 4) goto L_166;
    goto L_16d;
L_15e:;
    ++g_8e20;
    goto L_153;
L_166:;
    f_10137_squghx();
    goto L_15e;
L_16d:;
    f_9d40(3);
    if ((g_7b36 & 0x80) == 0) goto L_19b;
    f_ecdf(0, 0, 0x3f, 0);
L_19b:;
    g_e1bc = 0;
    g_e1b8 = (int)g_e2ec;
L_1ae:;
    g_e2ec = (unsigned char *)g_e1b8;
    f_13b72();
    ++g_8e24;
    f_80d8();
    f_4cf2();
    if ((g_7b36 & 0x80) == 0) goto L_1ed;
    f_ecdf(0, 0, 0x2a, 0);
L_1ed:;
    if (g_e13b == 0) goto L_1fe;
    *(unsigned char *)m_de5c |= 8;
L_1fe:;
    f_8585();
    if ((g_7b36 & 0x80) == 0) goto L_223;
    f_ecdf(0, 0, 0x15, 0);
L_223:;
    f_6278();
    if (g_e13b == 0) goto L_239;
    *(unsigned char *)m_de5c &= 0xf7;
L_239:;
    f_4066();
    f_7bd5();
    f_5966();
    f_3caa();
    ++g_e1bc;
    if (g_e1bc < g_e1c0) goto L_1ae;
    f_c9ce(0, 0);
    if (g_746c_mmw == 0) goto L_28f;
    shutdown_with_exit_message(g_746c_mmw, 0);
L_28f:;
    f_3702();
    if (g_e48b_3 == 1) goto L_2a6;
    if (g_e48e_0g == 1) goto L_2c5;
L_2a6:;
    if (g_dDa8 > 0) goto L_2b8;
    if (g_ddc0 <= 0) goto L_2ba;
L_2b8:;
    goto L_2c3;
L_2ba:;
    if (g_e142_baun == 0) goto L_2c5;
L_2c3:;
    goto L_2ca;
L_2c5:;
    f_5771();
L_2ca:;
    if (g_dd78 > 0) goto L_2dc;
    if (g_ddc0 <= 0) goto L_2de;
L_2dc:;
    goto L_31a;
L_2de:;
    if (g_e13b != 0) goto L_385;
    g_8e20 = 0;
L_2f5:;
    if (g_8e20 < 5) goto L_308;
    goto L_315;
L_300:;
    ++g_8e20;
    goto L_2f5;
L_308:;
    f_9d40(0);
    goto L_300;
L_315:;
    goto L_21;
L_31a:;
    f_814b();
    f_ed38();
    if (g_e13b == 0) goto L_347;
    if (g_7c00 != g_7bfe) goto L_345;
    if (g_e48e_0g != 0x39) goto L_347;
L_345:;
    goto L_349;
L_347:;
    goto L_34b;
L_349:;
    goto L_385;
L_34b:;
    if (g_e13a == 0) goto L_16d;
    if (g_e13b != 0) goto L_385;
    if ((*(int *)(r_dDDc_uzmlc + 4) -= 0x71) >= 0) goto L_d6;
L_374:;
    *(unsigned char *)&g_7b34_cbzosabe &= 0xfc;
    f_fc86();
    f_2ccc();
L_385:;
    if (g_e13b == 0) goto L_3a1;
    g_e13b = 0;
    *(int *)(r_dDDc_uzmlc + 0x14) = 0;
L_3a1:;
    *(unsigned char *)&g_7b34_cbzosabe &= 0xfc;
    f_fc86();
}

void f_3b2_jzcvbvx(void) {
    g_e143_eayxx = (unsigned char)(g_e140 * 10 - 1);
    g_8e20 = g_e13c;
    if (g_e13b) {
        g_e143_eayxx = (unsigned char)(f_dd53(0, 0x3b) - 1);
        g_8e20 = 0;
    }
    r_dDDc_uzmlc = g_df04;
    f_6ca(1, g_8e20, 0);
    if (g_e140) {
        g_e13e = 1;
    } else {
        g_e13e = 0;
    }
    g_e142_baun = 0;
}

void f_441_wfixgn(void)
{
    if (g_e142_baun == 0) goto L_462;
    g_e142_baun = 0;
    return;
L_462:;
    if (g_e13e == 0) goto L_486;
    if (g_e140 == 6) goto L_4bb;
    ++g_e143_eayxx;
    g_e13e = 0;
    return;
L_486:;
    ++g_e143_eayxx;
    if (g_e13b != 0) goto L_52a;
    if (g_e143_eayxx < 0xa) goto L_4b9;
    if ((g_e143_eayxx % 0xa) == 0) goto L_4bb;
L_4b9:;
    goto L_4f8;
L_4bb:;
    g_e13e = (unsigned char)(g_e143_eayxx / 0xa);
    if (f_6b02() == 0) goto L_4ea;
    f_18bc();
    g_e144 = 0xff;
    goto L_4f6;
L_4ea:;
    *(int *)(r_dDDc_uzmlc + 4) = -1;
L_4f6:;
    return;
L_4f8:;
    if ((g_e143_eayxx % 5) != 0) goto L_52a;
    g_e142_baun = (unsigned char)(((g_e143_eayxx / 5) + 1) >> 1);
L_52a:;
}

void f_52f_bssi(void)
{
    g_e13a = 0;
    m_de5c = i_DD98;
    *(int *)m_de5c = 0;
    g_dee4 = g_de60;
    *(int *)g_dee4 = 0x90;
    *(int *)(g_dee4 + 4) = 0xbc;
    *(int *)(g_dee4 + 0x1c) = 3;
    *(int *)(g_dee4 + 0x78) = (int)(g_dee0 + g_6218[3].value);
    *(int *)(g_dee4 + 0x24) = 0;
    *(int *)(g_dee4 + 0x28) = 0;
    *(int *)(g_dee4 + 0x2c) = 0;
    *(int *)(g_dee4 + 0x30) = 0;
    f_13a48((void *)g_ddd4_eoraaik, 0, 0x100, 0);
    *(int *)(g_dee4 + 0x34) = 0;
    *(int *)(g_dee4 + 0x38) = 0;
    *(int *)(g_dee4 + 0x3c) = 0;
    f_57fa();
    f_58b0();
    f_57bf();
    g_dDa8 = 0;
    if (g_e142_baun != 0) goto L_64b;
    f_8fce(0x90, 0xbc);
    *(unsigned char *)(g_ddb4 + 0x11) |= 1;
    *(int *)g_ddb4 -= 0x900;
L_64b:;
    g_ddc0 = 0;
    g_dd84 = 0;
    g_dDc8 = 0;
    g_ddcc = 0;
    g_dd9c = 0;
    g_ddd0 = *(int *)g_ddb0;
    if (g_e142_baun == 0) goto L_6c5;
    f_4bae();
    *(int *)(g_dee4 + 0x64) = 2;
    *(int *)(g_dee4 + 0x68) = 0xa;
    g_dDb8 = 1;
    f_4886();
    *(unsigned char *)(m_de5c + 1) |= 4;
L_6c5:;
}

void f_6ca(int a0, int a1, int a2) {
    ((int *)r_dDDc_uzmlc)[0] = a0;
    ((int *)r_dDDc_uzmlc)[1] = a1 * 113;
    ((int *)r_dDDc_uzmlc)[5] = a2;
    g_8db0 = 0x7cf;
}

void f_708(void);

void f_7e9(void);

void f_81d_psgpolkaxl(void);

void f_8d3_szjtcdqild(void);

void f_951_vbfkytgovb(void);
