/* TU process_timed_level_changes..queue_timed_level_change [0x3caa, 0x3e75): generated by tools/tu.py */
#include <process.h>
#include <stdlib.h>
#include <string.h>
#pragma pack(1)
#pragma pack()
struct SpriteFrame;
struct HighScoreName { unsigned char bytes[9]; };
struct HighScoreRecord {
    struct HighScoreName name;
    unsigned score;
    unsigned factor_a;
    unsigned factor_b;
    unsigned checksum;
};
struct BrickCell { unsigned char drop_kind : 2; unsigned char drop_value : 6; unsigned char tile_code; };
struct GlyphRecord { int offset; int count; };
struct DigitSpriteRecord {
    int sprite_offset;
    int opaque_04;
};
struct PaletteGradient {
    short first_index;
    short last_index;
    unsigned char start_red;
    unsigned char start_green;
    unsigned char start_blue;
    unsigned char end_red;
    unsigned char end_green;
    unsigned char end_blue;
};
struct TransitionTrack {
    int first_value;
    int second_value;
    int current_value;
    int step_delta;
    int duration_ticks;
    int auxiliary;
};
struct Racket {
    int x;
    int y;
    int previous_x;
    int min_x;
    int max_x;
    int min_y;
    int max_y;
    int sprite_frame_index;
    int sprite_height;
    int reward_level;
    int capture_timer;
    int state_2c;
    int state_30;
    int effect_state;
    int horizontal_recenter_timer;
    int vertical_recenter_timer;
    int effect_timer_40;
    int effect_frame_44;
    int animation_timer_48;
    int animation_step_4c;
    int animation_timer_50;
    int animation_step_54;
    int shield_frame_timer;
    int shield_frame_index;
    int spell_anim_timer;
    int spell_anim_index;
    int spell_parameter_68;
    int spell_parameter_6c;
    int spell_parameter_70;
    int previous_x_snapshot;
    unsigned char *sprite_pointer;
};
struct GameBall { int x, y, velocity_x, velocity_y; unsigned char behavior, flags; };
struct EnemyProjectile {
    int x;
    int y;
    int velocity_x;
    int velocity_y;
    int sprite_info;
    int flight_phase;
    int state_18;
    struct SpriteFrame *animation_sequence;
    int hit_points;
    unsigned char flags;
    unsigned char tail[3];
};
struct FallingSpell {
    int x;
    int y;
    int frame_countdown;
    struct SpriteFrame *frame_sequence;
    unsigned char variant;
    unsigned char spell_id;
};
struct SpriteFrame {
    unsigned image_offset;
    int duration_or_delta;
};
struct SpriteDrawCommand {
    int sprite_or_frame;
    short x;
    short y;
    short flags;
};
struct PlayerInputFlags { unsigned char control_flags, spell_flags, reserved_2, reserved_3; };
struct AudioRequest {
    int source_address;
    int byte_count;
    int sample_rate;
    int playback_mode;
};
struct TimedLevelChange { int cell_index, ticks_remaining; unsigned char replacement_tile; };
struct EnemyStageTuning { int enemy_health_max, enemy_pattern, enemy_attack_interval, attack_delay; };
struct DisplayModeInfo {
    short render_state;
    int plane_addresses_or_transform_a[4];
    int page_offsets_or_transform_b[4];
    int page_adjustments_or_transform_c[4];
    unsigned char page_mode_classes[4];
    int buffer_size_or_draw_parameter;
    int row_stride;
    int resolution_height;
    int screen_width;
    int screen_height;
    int viewport_left;
    int viewport_top;
    int viewport_right_or_width;
    int viewport_bottom_or_height;
    unsigned char mode_flags;
    unsigned char sequencer_plane_mask;
    unsigned char graphics_read_map;
    unsigned char reserved_vga_byte;
    unsigned char saved_video_mode;
    unsigned char graphics_controller_mode;
    unsigned char render_cache_60;
    unsigned char render_cache_61;
    unsigned char render_cache_62;
    unsigned char tail;
};
extern int temp;
extern struct BrickCell *cell_cursor;
extern struct BrickCell brick_code_map[];
extern unsigned char brick_code_mapping[];
void draw_level_tile_on_pages(int a, int b, int c);
extern int timed_change_count;
void tick_level_change_queue(void);
extern struct TimedLevelChange *timed_change_cursor;
extern struct TimedLevelChange timed_change_records[];
extern int timed_event_cursor;
void apply_timed_level_change(void);
extern int work_value;
extern struct EnemyStageTuning gameplay_tuning_by_stage[];
void process_timed_level_changes(void);
void queue_timed_level_change(int replacement_tile, int cell_index);

#define TIMED_CHANGE_CAPACITY 0x120
#define TIMED_CHANGE_STRIDE 9
#define LEVEL_COLUMN_COUNT 0x12

void process_timed_level_changes(void)
{
    if (timed_change_count != 0)
        tick_level_change_queue();
}

void tick_level_change_queue(void)
{
    timed_change_cursor = timed_change_records;
    for (timed_event_cursor = 0; timed_event_cursor < timed_change_count; ++timed_event_cursor) {
        if (--timed_change_cursor->ticks_remaining == 0) {
            apply_timed_level_change();
            continue;
        } else {
            timed_change_cursor += 1;
        }
    }
}

void apply_timed_level_change(void)
{
    temp = timed_change_cursor->cell_index % LEVEL_COLUMN_COUNT;
    work_value = timed_change_cursor->cell_index - temp;
    cell_cursor = brick_code_map;
    cell_cursor += temp + work_value;
    cell_cursor->tile_code = timed_change_cursor->replacement_tile;
    cell_cursor->drop_value = brick_code_mapping[timed_change_cursor->replacement_tile];
    draw_level_tile_on_pages(temp, work_value, timed_change_cursor->replacement_tile);
    --timed_change_count;
    if (timed_event_cursor != timed_change_count)
        memcpy(timed_change_cursor, timed_change_cursor + 1, (timed_change_count - timed_event_cursor) * TIMED_CHANGE_STRIDE);
    --timed_event_cursor;
}

void queue_timed_level_change(int replacement_tile, int cell_index)
{
    if (timed_change_count < TIMED_CHANGE_CAPACITY) {
        timed_change_cursor = timed_change_records;
        timed_change_cursor += timed_change_count;
        timed_change_cursor->ticks_remaining = ((int *)((unsigned char *)gameplay_tuning_by_stage + 0x33))[replacement_tile];
        timed_change_cursor->cell_index = cell_index;
        timed_change_cursor->replacement_tile = (unsigned char)replacement_tile;
        ++timed_change_count;
    }
}
