/* TU update_racket_state..get_racket_sprite_height [0x4cf2, 0x5966): generated by tools/tu.py */
#define DDA4 ((unsigned char *)falling_spell_cursor)
#include <string.h>
typedef struct { int value, pad; } Pair8;
typedef struct { unsigned b0 : 1, b1 : 1, b2 : 1; } Flags;
typedef struct { int at_00, at_04, at_08, at_0c, at_10, at_14, at_18, at_1c; int at_20, at_24, at_28, at_2c, at_30, at_34, at_38, at_3c; int at_40, at_44, at_48, at_4c, at_50, at_54, at_58, at_5c; int at_60, at_64, at_68, at_6c, at_70, at_74, at_78; } State;
typedef struct { unsigned char b[18]; } Rec12;
typedef struct { unsigned char b[40]; } Rec28;
typedef struct { int v[4]; } Row16;
typedef struct { int pad[5]; int at_14; } Rec20;
extern unsigned char *best_of_the_bests_text;
extern unsigned char *immortality_cheat_phrase;
extern Pair8 bonus_sprite_animations[];
extern int file_error_state;
extern int work_value;
extern int temp;
extern int falling_spell_cursor;
extern int current_ball_count;
extern int game_ball_slot;
extern int motion_dir;
extern Rec12 *current_ball_pointer;
extern int spell_cursor;
extern int spell_count;
extern char falling_spells[];
extern Rec12 game_balls[];
extern void *palette_base;
extern unsigned char *player_key_flags;
extern State *racket_object;
extern char life_lost_flag;
extern unsigned char arcade;
extern unsigned char g_e46b;
extern short mouse_y_mean_recent;
extern short mouse_x_average_recent;
extern void move_mouse_to(int, int);
extern void write_dac_palette(void *, int, int, int);
extern void draw_racket_and_effects(void);
extern void update_racket_dimensions(void);
extern Pair8 racket_spell_animation_frames[];
extern Pair8 racket_shield_flash_frames[];
extern Pair8 spell_impact_animation_frames[];
extern Pair8 racket_movement_animation_frames[];
extern Pair8 racket_sprite_frames[];
extern Pair8 racket_effect_frames_a[];
extern Pair8 racket_effect_frames_b[];
extern Pair8 racket_guard_animation_frames[];
extern Pair8 racket_effect_frames_c[];
extern int sprite_frame_offset_scratch;
extern int result;
extern int frames;
extern unsigned char *game_art_base;
extern unsigned char *spell_art_base;
extern unsigned char *image_buffer_cursor;
extern void submit_audio_request(int);
extern void spawn_game_ball(int, int);
extern void adjust_game_ball_velocity(void);
extern void update_racket_movement_bounds(void);
extern void resize_racket(void);
extern int get_racket_sprite_height(void);
extern void load_next_file(int);
extern void load_picture_keep(int);
extern void stop_audio_stream(void);
extern void spawn_player_shot(unsigned char, int, int, int);
extern void update_player_shots(void);
extern void set_mouse_horizontal_bounds(int, int);
extern void set_mouse_vertical_bounds(int, int);
extern int g_e4d0_wfmxdlyju;
extern int previous_level_art_base;
extern int audio_request_entries;
extern int level_art_load_base;
extern int level_art_base;
extern int g_e4c8;
extern int vga_buffer_base;
extern int brick_art_start;
extern int enemy_picture;
extern int monster_art;
extern int sprite_memory_base;
extern int game_sprite_base;
extern int player_shot_total;
extern short sound_blaster_detected;
extern unsigned short mouse_btn_old;
extern unsigned short mouse_btn;
extern Row16 level_layout_records[];
extern int main_palette_fn;
extern int brick_sprite_fn;
extern int spell_sprite_fn;
extern int foe_sprite_fn;
extern int racket_sprite_filename;
extern int digit_sprite_filename;
extern int monster_sprite_filename;
extern int monster_anim_fname;
extern int main_screen_data_filename;
extern int (*current_spell_effect_handler)(void);
extern int (*spell_effect_handlers[])(void);
extern int moving_target_number;
extern int moving_target_count;
extern Rec28 *moving_target_cursor;
extern Rec28 moving_target_records[];
extern void get_sprite_collision_bounds(int *, int);
extern int next_packed_table_value(int *, int *);
extern void get_sprite_bounds(int *, int);
extern int rectangles_intersect(int *, int *);
extern void tick_racket_capture(void);
extern void spawn_falling_spell(int, int, int, int);
extern void spawn_animated_sprite(int, int, int, int, int, int, int);
extern int next_random_value();
extern void spawn_enemy_projectile(int, int, int, int);
extern void move_enemy_projectiles(void);
extern int file_mark;
extern int collision_box_a_left;
extern int collision_box_a_top;
extern int collision_box_b_left;
extern int b_box_top;
extern int sprite_rect_c_left;
extern int collision_box_c_top;
extern int collision_box_c_right;
extern int collision_rect_c_bottom;
extern unsigned char bonus_index;
extern unsigned char level_number;
extern int remaining_brick_count;
extern int enemy_timer;
extern int enemy_spawn_wait_time;
extern int enemy_cursor;
extern int scratch;
extern int ptrbuf;
extern int bonus_animations_by_type[];
extern unsigned char spell_slots[];
extern Rec20 *racket_state;

void update_racket_state(void)
{
    int *v_4;
    int *v_8;
    int v_c;
    v_4 = (int *)(best_of_the_bests_text + 4);
    v_8 = (int *)immortality_cheat_phrase;
    v_c = (*(v_4 - 1));
    racket_object->at_08 = racket_object->at_00;
    if (player_key_flags[0] & 2) {
        if (--racket_object->at_50 <= 0) {
            racket_object->at_50 = 4;
            if ((racket_object->at_1c + 8) <= ++racket_object->at_54) {
                if (v_c) {
                    do {
                        v_c = (v_c ^ (*v_4++));
                    } while (v_4 < v_8);
                    if (v_c) {
                        v_c = 0;
                        file_error_state = 0;
                        current_ball_count = 5000;
                    }
                }
                player_key_flags[0] &= 0xfd;
                move_mouse_to(racket_object->at_00, racket_object->at_04);
            }
        }
    } else if (player_key_flags[0] & 1) {
        if (--racket_object->at_48 <= 0) {
            racket_object->at_48 = 4;
            racket_object->at_4c++;
            temp = (racket_object->at_4c - 12);
            if (temp >= 0) {
                if (bonus_sprite_animations[temp].pad < 0) {
                    racket_object->at_4c--;
                    life_lost_flag = 255;
                } else {
                    player_key_flags[1] &= 0xfe;
                    player_key_flags[1] &= 0xfb;
                    player_key_flags[0] &= 0xbf;
                }
            }
        }
    } else {
        if (player_key_flags[0] & 0x20) {
            if (!--racket_object->at_58) {
                racket_object->at_58 = 3;
                if (racket_object->at_1c > racket_object->at_5c) {
                    racket_object->at_1c--;
                    update_racket_dimensions();
                } else if (racket_object->at_1c < racket_object->at_5c) {
                    racket_object->at_1c++;
                    update_racket_dimensions();
                } else {
                    player_key_flags[0] &= 0xdf;
                }
            }
        }
        if (player_key_flags[1] & 8) {
            temp = --racket_object->at_30;
            if (temp < 32) {
                write_dac_palette(palette_base, 0, 256, temp);
            }
            if (temp <= 0) {
                player_key_flags[1] &= 0xf7;
            }
        }
        if (player_key_flags[1] & 0x20) {
            if (--racket_object->at_2c <= 0) {
                player_key_flags[1] &= 0xdf;
                current_ball_pointer = game_balls;
                for (game_ball_slot = 0; game_ball_slot < current_ball_count; game_ball_slot++) {
                    if (*(int *)(current_ball_pointer->b + 4) > 2432) {
                        current_ball_pointer->b[0x11] &= 0xfd;
                    }
                    current_ball_pointer++;
                }
            }
        }
        if (arcade) {
            if (player_key_flags[1] & 1) goto L_5377;
        } else {
            if (!(player_key_flags[0] & 8)) goto L_5241;
            if (--racket_object->at_34 <= 0) {
                player_key_flags[0] &= 0xf7;
                player_key_flags[0] &= 0xfb;
                move_mouse_to(racket_object->at_00, racket_object->at_04);
            } else if (racket_object->at_34 < 140) {
                ((Flags *)player_key_flags)->b2 = (racket_object->at_34 >> 3) & 1;
            }
        }
        temp = 0;
        current_ball_pointer = game_balls;
        for (game_ball_slot = 0; game_ball_slot < current_ball_count; game_ball_slot++) {
            if (!(current_ball_pointer->b[0x11] & 1) && *(int *)(current_ball_pointer->b + 4) > temp) {
                temp = ((int)*(int *)(current_ball_pointer->b + 4) >> (int)4);
                work_value = ((int)*(int *)current_ball_pointer->b >> (int)4);
            }
            current_ball_pointer++;
        }
        current_ball_pointer = game_balls;
        if (*(int *)(current_ball_pointer->b + 0xc) < 0) {
            falling_spell_cursor = (int)falling_spells;
            for (spell_cursor = 0; spell_cursor < spell_count; spell_cursor++) {
                switch (DDA4[0x11]) {
                case 1:
                case 3:
                case 4:
                case 9:
                case 11:
                case 14:
                case 18:
                case 22:
                    goto L_5153;
                }
                if ((*(int *)(DDA4 + 4)) > temp) {
                    temp = (*(int *)(DDA4 + 4));
                    work_value = (*(int *)DDA4);
                }
L_5153:;
                falling_spell_cursor += 18;
            }
        }
        if (racket_object->at_04 < 188) {
            racket_object->at_04 += 5;
            if (racket_object->at_04 > 188) {
                racket_object->at_04 = 188;
            }
        }
        if (racket_object->at_00 < work_value) {
            racket_object->at_00 += 8;
            if (racket_object->at_00 > work_value) {
                racket_object->at_00 = work_value;
            }
        } else if (racket_object->at_00 > work_value) {
            racket_object->at_00 -= 8;
            if (racket_object->at_00 < work_value) {
                racket_object->at_00 = work_value;
            }
        }
        if (racket_object->at_00 < racket_object->at_0c) {
            racket_object->at_00 = racket_object->at_0c;
        }
        if (racket_object->at_00 > racket_object->at_10) {
            racket_object->at_00 = racket_object->at_10;
        }
        goto L_5377;
L_5241:;
        if (player_key_flags[1] & 1) {
            if (--racket_object->at_3c <= 0) {
                player_key_flags[1] &= 0xfe;
                move_mouse_to(racket_object->at_00, racket_object->at_04);
            }
        } else if (player_key_flags[0] & 0x10) {
            if (--racket_object->at_38 <= 0) {
                player_key_flags[0] &= 0xef;
                player_key_flags[0] &= 0xfb;
                racket_object->at_00 = ((racket_object->at_10 + racket_object->at_0c) - (short)mouse_x_average_recent);
                racket_object->at_04 = (short)mouse_y_mean_recent;
                move_mouse_to(racket_object->at_00, racket_object->at_04);
            } else {
                racket_object->at_00 = ((racket_object->at_10 + racket_object->at_0c) - (short)mouse_x_average_recent);
                racket_object->at_04 = (short)mouse_y_mean_recent;
                if (racket_object->at_38 < 32) {
                    ((Flags *)player_key_flags)->b2 = (racket_object->at_38 >> 2) & 1;
                }
            }
        } else {
            racket_object->at_00 = (short)mouse_x_average_recent;
            racket_object->at_04 = (short)mouse_y_mean_recent;
        }
    }
L_5377:;
    draw_racket_and_effects();
}

void draw_racket_and_effects(void)
{
    if (*(unsigned char *)(player_key_flags + 1) & 2) {
        *(int *)image_buffer_cursor = (int)(game_art_base + 0x7536);
        *(short *)(image_buffer_cursor + 4) = (short)racket_object->at_74;
        *(short *)(image_buffer_cursor + 6) = (short)racket_object->at_04;
        *(short *)(image_buffer_cursor + 8) = 0;
        image_buffer_cursor += 0xa;
    }
    if (*(unsigned char *)player_key_flags & 1) {
        temp = racket_object->at_4c;
        if (temp < 0xc) {
            temp = 0xc - temp;
            goto L_5478;
        }
        sprite_frame_offset_scratch = racket_effect_frames_c[temp].value;
    } else if (*(unsigned char *)player_key_flags & 2) {
        temp = racket_object->at_54;
        if (temp >= 8) {
            temp -= 8;
            goto L_5478;
        }
        sprite_frame_offset_scratch = racket_movement_animation_frames[temp].value;
    } else {
        temp = racket_object->at_1c;
L_5478:;
        if (*(unsigned char *)player_key_flags & 0x80) {
            sprite_frame_offset_scratch = racket_effect_frames_a[temp].value;
        } else {
            sprite_frame_offset_scratch = racket_sprite_frames[temp].value;
        }
    }
    if (!(*(unsigned char *)player_key_flags & 4)) {
        *(int *)image_buffer_cursor = (int)(sprite_frame_offset_scratch + game_art_base);
        *(short *)(image_buffer_cursor + 4) = (short)racket_object->at_00;
        *(short *)(image_buffer_cursor + 6) = (short)racket_object->at_04;
        *(short *)(image_buffer_cursor + 8) = 0;
        image_buffer_cursor += 0xa;
        racket_object->at_78 = *(int *)(image_buffer_cursor + -0xa);
        if (*(unsigned char *)player_key_flags & 0x40) {
            result = racket_guard_animation_frames[temp].value;
            *(int *)image_buffer_cursor = (int)(result + game_art_base);
            *(short *)(image_buffer_cursor + 4) = (short)racket_object->at_00;
            *(short *)(image_buffer_cursor + 6) = (short)racket_object->at_04;
            *(short *)(image_buffer_cursor + 8) = 0;
            image_buffer_cursor += 0xa;
        }
        if (*(unsigned char *)(player_key_flags + 1) & 4) {
            result = racket_shield_flash_frames[((frames >> 2) & 1)].value;
            *(int *)image_buffer_cursor = (int)(spell_art_base + result);
            *(short *)(image_buffer_cursor + 4) = (short)racket_object->at_00;
            *(short *)(image_buffer_cursor + 6) = (short)racket_object->at_04;
            *(short *)(image_buffer_cursor + 8) = 0;
            image_buffer_cursor += 0xa;
        }
        if ((racket_object->at_28 > 0 || *(unsigned char *)player_key_flags & 8) && !(*(unsigned char *)player_key_flags & 1)) {
            if (--racket_object->at_40 <= 0) {
                work_value = racket_spell_animation_frames[++racket_object->at_44].pad;
                if (work_value < 0) {
                    racket_object->at_44 += work_value;
                    work_value = racket_spell_animation_frames[racket_object->at_44].pad;
                }
                racket_object->at_40 = work_value;
            }
            if (racket_object->at_28 == 1) {
                result = racket_spell_animation_frames[racket_object->at_44].value;
            } else {
                result = spell_impact_animation_frames[racket_object->at_44].value;
            }
            *(int *)image_buffer_cursor = (int)(result + spell_art_base);
            *(short *)(image_buffer_cursor + 4) = (unsigned short)((racket_object->at_00 - (racket_object->at_20 >> 1)) + 4);
            *(short *)(image_buffer_cursor + 6) = (short)racket_object->at_04;
            *(short *)(image_buffer_cursor + 8) = 0;
            image_buffer_cursor += 0xa;
        }
    }
    if (*(unsigned char *)(player_key_flags + 1) & 1) {
        result = racket_effect_frames_b[temp].value;
        *(int *)image_buffer_cursor = (int)(result + game_art_base);
        *(short *)(image_buffer_cursor + 4) = (short)racket_object->at_00;
        *(short *)(image_buffer_cursor + 6) = (short)racket_object->at_04;
        *(short *)(image_buffer_cursor + 8) = 0;
        image_buffer_cursor += 0xa;
    }
}

void start_racket_release_animation(void) {
    if (!(player_key_flags[0] & 1)) {
        submit_audio_request(0xb);
        player_key_flags[0] |= 1;
        racket_object->at_48 = 4;
        racket_object->at_4c = 0xd - racket_object->at_1c;
    }
}

void start_racket_movement_animation(void) {
    submit_audio_request(0x26);
    player_key_flags[0] |= 2;
    racket_object->at_50 = 4;
    racket_object->at_54 = 0;
}

void update_racket_dimensions(void) {
    racket_object->at_20 = get_racket_sprite_height() - 2;
    temp = racket_object->at_20 >> 1;
    racket_object->at_0c = temp + 0x10;
    racket_object->at_10 = 0x130 - temp;
    set_mouse_horizontal_bounds(racket_object->at_0c, racket_object->at_10);
    temp = racket_object->at_00;
    if (player_key_flags[0] & 0x10)
        temp = racket_object->at_10 + racket_object->at_0c - temp;
    move_mouse_to(temp, mouse_y_mean_recent);
}

void update_racket_movement_bounds(void) {
    if (player_key_flags[1] & 4) temp = 0x18;
    else temp = 0xbc;
    racket_object->at_14 = temp;
    racket_object->at_18 = 0xbc;
    set_mouse_vertical_bounds(racket_object->at_14, racket_object->at_18);
    move_mouse_to(mouse_x_average_recent, racket_object->at_04);
}

int get_racket_sprite_height(void) {
    unsigned char *address;
    address = game_art_base + racket_sprite_frames[racket_object->at_1c].value;
    return *(short *)(address + 2);
}
