int g_8e24;
unsigned char g_8e28[30];
unsigned char g_8e46;
unsigned char g_8e47;
/* TU f_4066..f_4ce1 [0x4066, 0x4cf2): generated by tools/tu.py */
#include <process.h>
unsigned char g_8e10[12];
int g_8e1c;
int g_8e20;

#include <stdlib.h>
unsigned int g_8e08;
int g_8e0c;

#include <string.h>
#pragma pack(1)
#pragma pack()
typedef struct { unsigned char b[5]; } S5;
typedef struct { unsigned char bytes[9]; } Name;
typedef struct { Name name; unsigned char other[16]; } Row;
typedef struct { unsigned char bytes[25]; } Record;
typedef struct { unsigned char prefix : 2; unsigned char value : 6; } IndexBits;
struct Cell { unsigned char lo : 2, hi : 6; unsigned char flag; };
typedef struct { unsigned char prefix : 2; unsigned char code : 6; } CodeBits;
typedef struct { int offset; int count; } GlyphRecord;
struct digit_entry { int value; int other; };
struct Grad { short x, y; unsigned char r0, g0, b0, r1, g1, b1; };
typedef struct { int at_00, at_04, at_08, at_0c, at_10, at_14, at_18, at_1c; int at_20, at_24, at_28, at_2c, at_30, at_34, at_38, at_3c; int at_40, at_44, at_48, at_4c, at_50, at_54, at_58, at_5c; int at_60, at_64, at_68, at_6c, at_70, at_74, at_78; } State;
typedef struct { unsigned char b[18]; } Rec12;
typedef struct { unsigned char b[40]; } Rec28;
typedef struct { int value, pad; } Pair8;
typedef struct { int v[4]; } Row16;
extern unsigned char g_74c4[];
extern unsigned char key_irq[];
extern unsigned char g_756f[];
extern void f_9afc(void);
extern void f_9b44(int);
extern void release_sound_system(void);
extern int configure_sound_dma(int);
extern void set_audio_transfer_mode(int);
extern void save_bios(void);
extern void restore_bios(void);
extern void clear_pal(void);
extern void f_f6d9(void);
extern int f_f6f8(int);
void f_9f9(void);
extern int g_38c6;
extern int g_68f8_jwwqkwr;
extern int g_6910;
extern int g_6914;
extern int g_693c;
extern short image_color_depth;
extern short sound_blaster_detected;
extern int fade_start;
extern int fade_end;
extern short draw_idx;
extern short page2;
extern short g_7b34_cbzosabe;
extern short g_7b3d_yrsiuxxd;
extern unsigned short g_7bfe;
extern unsigned short g_7c00;
extern int g_7c08_orxezsknd;
extern int g_8428;
extern unsigned char g_8870[];
extern unsigned char h_ab40_jbfxrqns[];
extern unsigned char g_bf40_whznxcth[];
extern unsigned char g_d340_schtgisj[];
extern int x_dd40_xbukycw;
extern int g_dd44;
extern int k_DD48_jbwjbqarofg;
extern int g_dd4c_ilunphmaok;
extern int g_df48;
extern int g_df4c;
extern int g_df54;
extern int h_df5c;
extern int g_e1d8;
struct DisplayModeInfo { short state; unsigned char plane_addresses[16]; int page_offsets[4]; int page_adjustments[4]; unsigned char page_mode_classes[4]; int buffer_size; int row_stride_bytes; int resolution_height; int width; int height; int left; int top; int right; int bottom; unsigned char mode_flags; unsigned char e37f; unsigned char e380; unsigned char video_mode_low; unsigned char e382; unsigned char e383; unsigned char e384; unsigned char e385; unsigned char e386; unsigned char tail; };
extern struct DisplayModeInfo vga_state;
extern unsigned char g_e48b_3;
extern unsigned char g_e48d_c;
extern unsigned char g_e48e_0g;
extern unsigned char g_e48f;
extern int g_e4c8;
extern int g_e4d0_wfmxdlyju;
extern unsigned g_e4d4;
extern void f_100fa(int, int, int, int);
extern void f_1085a_eklzmb(int);
extern void shutdown_with_exit_message(unsigned, unsigned);
extern void write_dac_palette(void *, int, int, int);
extern void handle_s_key(void);
extern void f_3beb(int);
extern void f_80d8(void);
extern void f_843a(void);
extern void f_9640(void *, void *);
extern void f_9d40(unsigned char);
extern void f_a574_wrvhrpegbz(int);
extern void plot_transformed_pixel(void *, int);
extern void draw_text(int, int, int);
extern void configure_text_renderer(int, int, unsigned char, int, int);
extern void set_text_clip_rect(int, int, int, int);
extern void queue_audio(int, int, int, int);
extern void set_img_buffers(int, int, short, int, int);
extern int set_display_mode();
extern void fade_pal(void *, int, int, int);
void f_113c(void);
extern void stop_audio_stream(void);
void f_ea4(void);
void f_ff0(void);
extern int g_6904;
extern int g_6908;
extern int g_690c;
extern int g_38ca;
extern char *g_3902;
extern int g_dF58;
extern int g_df60;
extern unsigned char *g_df70;
extern int g_df74;
extern unsigned char g_e144;
extern void f_16bb(int);
extern short image_buffer_error_code;
extern void f_1202(void);
extern void f_1227(void);
extern void f_127e(void);
extern void f_13aa(void);
extern void f_1416(void);
extern void redraw_image_region(int, int);
extern void show_page(void);
extern int next_packed_table_value(void *, void *);
extern unsigned char *image_buffer_cursor;
extern short m_E4c4;
extern short g_e4c6;
extern unsigned char g_6988[];
extern unsigned char g_698c[];
extern unsigned char g_6990[];
extern unsigned char g_6994[];
extern unsigned char g_e13f;
extern unsigned char g_e46b;
extern short g_e4ba;
extern short g_e4bc;
extern int g_38f6;
extern int g_38fa;
extern unsigned char *g_3906;
extern unsigned char *g_6984;
extern unsigned int g_8e04;
extern int i_dF44;
extern int g_df50;
extern unsigned char g_e13b;
int f_17d2(unsigned long a0);
extern short flip_src;
extern short flip_dst;
extern void copy_clipped_screen_rectangle(int, int, int, int, int, int, int, int);
extern unsigned int g_8dfc;
extern unsigned int g_8e00;
extern unsigned char g_e13c;
extern unsigned char g_e140;
extern int *r_dDDc_uzmlc;
extern unsigned char g_e143_eayxx;
char *itoa(int, char *, int);
extern int g_df6c;
extern void copy_screen_span_entry(int, int, int, int, int);
void f_1af4(void);
void f_1b7e(void);
void f_1bc2(void);
void f_1d80(void);
void f_1e87(void);
void f_20f4(void);
extern int draw_page();
extern int g_6918;
extern int g_691c;
extern int g_6920;
extern int g_df24_krqpxkj;
extern int g_df34_nnyybtp;
extern int g_df2c_hwkico;
extern int g_df20_rusvejgsscn;
extern int g_dDc8;
extern Row g_37f4[];
extern unsigned char g_37fd[];
extern int g_388e;
extern int g_8ddc;
extern unsigned char g_e141;
extern int g_e20d;
extern unsigned g_3861;
extern unsigned g_dedc;
extern char *strcpy(char *, const char *);
extern int g_3892;
extern int g_3896;
extern int g_df64;
extern int g_dF68;
extern unsigned char g_e13d;
extern void f_10137_squghx(void);
extern int g_387a;
extern char *g_6924;
extern int f_1065b(char *, void *);
extern void f_228e(void);
void f_107b6(int a, int b, int c);
extern unsigned char g_3801[];
extern unsigned char g_3805[];
extern unsigned char g_3809[];
extern int g_8dd0;
extern int g_8dd4;
extern int g_8dd8;
extern int g_389e;
extern int g_38a2;
extern int g_38a6;
extern int g_38aa;
extern int g_38ae;
void f_2484(void);
void f_251c(void);
void f_2565(int a0);
extern int g_6940_hqhettu;
extern int g_6944_bdcftta;
extern int g_6948_kxwrlv;
extern int g_694c_wjufexbevsk;
extern int g_6958_vghgxtjirow;
extern int g_695c_qurvlwasjp;
extern int g_6960_juobaluykyr;
extern int g_6964;
extern int g_6934;
extern int g_6938;
extern int g_389a;
extern short disp_idx;
extern int g_38b2;
extern int g_38b6;
extern int g_38ba;
extern int g_38be;
extern int g_38c2;
void f_26fe(void);
void f_2796(void);
void f_27df(int a);
extern int g_6928;
extern int g_692c;
extern int g_6930;
extern int g_6974;
extern int g_6978;
extern int g_697c;
extern int g_6980;
void set_pal_rgb(unsigned char, unsigned char, unsigned char, unsigned char);
extern int v_DF30;
void f_2e4a(void);
void render_image_with_options(int, int, int, int, int);
extern unsigned char *u_e150;
extern int g_6c08;
void f_2eab(void);
void f_35b5(void);
void f_84a0(int);
extern int b_DF40_omuefnnbqp;
extern int g_Ddd8;
extern int g_6950;
extern int g_6954;
extern int g_df28;
extern int g_6968;
extern int g_6970;
extern int g_696c;
extern short page3;
extern int g_df38;
void set_draw_page(int);
void f_7f8a(void);
extern unsigned char g_e142_baun;
extern int g_ddb0;
extern int g_dd78;
extern unsigned short *g_dd80;
extern unsigned int g_dd50;
extern int g_dd60;
extern int g_dd64;
extern int g_dD68;
extern int b_DD70;
extern int g_e158_tpotbrbk;
extern int g_6c64[];
extern int g_6c7c[];
extern unsigned char g_a608;
extern unsigned char q_A988[];
extern unsigned char g_6b9e[];
extern unsigned char g_2fe4[];
void f_13889(int, int, int);
void draw_bob_sprite_entry(int, int, int);
extern int g_e14c;
void f_339f_adddtkmk(void);
void f_8345_wsdytbf(void);
void f_83b1(void);
extern int g_e154;
extern int g_69c8;
extern int g_e148;
extern void *g_ddd4_eoraaik;
void f_82cc(void);
void write_pal(int);
extern int g_6ae8;
extern int g_6b78;
void f_34b7(void);
extern State *g_dee4;
void f_61a6_vby(void);
void f_10502(int, int);
extern char g_269c[];
void draw_zero_padded_number(int, int, int, int, int);
extern int g_8db0;
void submit_audio_request(int);
extern char g_2fec[];
void f_3ba4(int, int);
void f_7e62(int, int, int, int, int, int, int);
void f_42e1(unsigned char, unsigned char, int, int);
void f_3ac0(int a, int b, int c);
extern int g_dd74_ntd;
void f_3cc9(void);
extern unsigned char *g_dd7c;
extern int g_9af8;
extern int g_dd54;
void f_3d23(void);
extern int g_68b7[];
extern int g_ddc0;
extern unsigned char *m_de5c;
void f_58b0(void);
void f_4085(void);
extern unsigned char g_390a[2];
extern GlyphRecord g_390c[91];
extern GlyphRecord g_3be4[257];
extern GlyphRecord g_43ec[257];
extern GlyphRecord g_4bf4[305];
extern GlyphRecord g_55cc[198];
extern char *g_38ce;
extern char *g_38d2;
extern char *g_38d6;
extern char *g_38da;
extern char *g_38de;
extern char *g_38e2;
extern char *g_38e6;
extern char *g_38ea;
extern char *g_38ee;
extern char *g_38f2;
extern char **g_5c4c[11];
extern char *g_5c78;
void f_aa2(void);
void f_e70(void);
void f_18bc(void);
void f_19b9(void);
void f_2188(void);
void f_2250(void);
void f_240f(void);
void f_2689(void);
void f_2903(void);
void f_2c72_zyd(void);
void f_2ccc(void);
void f_2da3_ehlot(void);
void f_2f0c_cdhyn(void);
void f_2f9e_zo(void);
int f_3203_tjmv(void);
void f_3406_qruj(void);
void f_353f(void);
void f_35e4_rqk(void);
void f_3702(void);
void f_3918(int a, int b, int c, int d);
void f_3caa(void);
void f_3e0f(int a, int b);
void f_3e75(void);
extern unsigned char *g_dda4;
extern int g_ddbc;
extern int g_dDb8;
extern int g_e24c;
extern int r_e250;
extern int g_e22c;
extern int g_e230;
extern int g_8db4;
extern void (*g_8db8)(void);
extern unsigned char p_A990[];
void f_8004(int *, int);
int rectangles_intersect(void *, void *);
void f_4291(void);
extern short windows_environment_detected;
void f_4394(void);
void f_5771(void);
void f_4602_state_handler(void);
extern void f_8fce(int, int);
extern void f_9053(void);
extern int c_DDAC;
extern int g_dDa8;
extern Rec12 *g_ddb4;
extern Rec12 g_df78[];
extern int g_ddc4;
extern int g_ddcc;
extern Rec28 *g_dd94;
extern Rec28 g_a848[];
extern int f_592c(void);
extern void f_6a1d(unsigned char, int, int, int);
extern void f_6327(void);
extern void f_1040c(int, int);
extern void f_10487(int, int);
extern int g_dee0;
extern int g_67b0;
extern int audio_request_table_8;
extern int g_df3c;
extern int g_8e48;
extern Row16 g_6cbb[];
extern int g_8dc8;
extern Pair8 g_6218[];
void f_4413(void);
void f_4480_state_handler(void);
void f_44a9_state_handler(void);
void f_4551_state_handler(void);
void f_456d_state_handler(void);
void f_45a6_state_handler(void);
void f_45d0_state_handler(void);
void f_469b_state_handler(void);
void f_46e7_state_handler(void);
void f_4745_state_handler(void);
void f_4761_state_handler(void);
void f_4802_state_handler(void);
void f_4847_state_handler(void);
void f_4886(void);
void f_48d2_state_handler(void);
void f_4931_state_handler(void);
void f_4955_state_handler(void);
void f_49c7_state_handler(void);
void f_49fb_state_handler(void);
void f_4a5a_state_handler(void);
void f_4aca_state_handler(void);
void f_4af0_state_handler(void);
void f_4b4f_state_handler(void);
void f_4bae(void);
void f_4c0d_state_handler(void);
void f_4c6c_state_handler(void);
void f_4cd0(void);
void f_4ce1(void);
extern int g_5c7c;

/* _DATA [0x5c80,0x61d0): animation sequences ({frame, time} pairs ending {0, -loop}),
   the per-state sequence table and the state handler table. */
Pair8 g_5c80[2] = {{9634, 127}, {0, -1}};
Pair8 g_5c90[2] = {{9990, 127}, {0, -1}};
Pair8 g_5ca0[2] = {{10496, 127}, {0, -1}};
Pair8 g_5cb0[2] = {{10830, 127}, {0, -1}};
Pair8 g_5cc0[2] = {{11956, 127}, {0, -1}};
Pair8 g_5cd0[2] = {{12260, 127}, {0, -1}};
Pair8 g_5ce0[2] = {{12558, 127}, {0, -1}};
Pair8 g_5cf0[2] = {{12670, 127}, {0, -1}};
Pair8 g_5d00[2] = {{12870, 127}, {0, -1}};
Pair8 g_5d10[2] = {{13018, 127}, {0, -1}};
Pair8 g_5d20[2] = {{13308, 127}, {0, -1}};
Pair8 g_5d30[2] = {{13502, 127}, {0, -1}};
Pair8 g_5d40[2] = {{13882, 127}, {0, -1}};
Pair8 g_5d50[2] = {{14104, 127}, {0, -1}};
Pair8 g_5d60[2] = {{15452, 127}, {0, -1}};
Pair8 g_5d70[2] = {{16358, 127}, {0, -1}};
Pair8 g_5d80[2] = {{20076, 127}, {0, -1}};
Pair8 g_5d90[2] = {{20562, 127}, {0, -1}};
Pair8 g_5da0[2] = {{21010, 127}, {0, -1}};
Pair8 g_5db0[2] = {{21374, 127}, {0, -1}};
Pair8 g_5dc0[7] = {
    {2, 0}, {150, 0}, {326, 0}, {560, 0}, {858, 0}, {1268, 0},
    {0, -6}
};
Pair8 g_5df8[7] = {
    {1802, 0}, {1950, 0}, {2126, 0}, {2360, 0}, {2658, 0}, {3068, 0},
    {0, -6}
};
Pair8 g_5e30[7] = {
    {3602, 0}, {3750, 0}, {3926, 0}, {4160, 0}, {4458, 0}, {4868, 0},
    {0, -6}
};
Pair8 g_5e68[11] = {
    {5402, 3}, {5522, 3}, {5692, 3}, {5898, 3}, {6158, 3}, {6484, 3},
    {6158, 3}, {5898, 3}, {5692, 3}, {5522, 3}, {0, -10}
};
Pair8 g_5ec0[6] = {{6876, 10}, {7116, 10}, {7352, 10}, {7632, 10}, {7922, 10}, {0, -5}};
Pair8 g_5ef0[3] = {{8236, 4}, {8334, 4}, {0, -2}};
Pair8 g_5f08[4] = {{14334, 8}, {14716, 8}, {15072, 8}, {0, -3}};
Pair8 g_5f28[3] = {{15766, 4}, {16000, 4}, {0, -2}};
Pair8 g_5f40[9] = {
    {16802, 6}, {17132, 6}, {17466, 6}, {17790, 6}, {18108, 6}, {17790, 6},
    {17466, 6}, {17132, 6}, {0, -8}
};
Pair8 g_5f88[9] = {
    {18418, 5}, {18718, 5}, {19034, 5}, {19368, 5}, {19716, 5}, {19368, 5},
    {19034, 5}, {18718, 5}, {0, -8}
};
Pair8 g_5fd0[9] = {
    {21600, 5}, {21882, 5}, {22180, 5}, {22496, 5}, {22826, 5}, {22496, 5},
    {22180, 5}, {21882, 5}, {0, -8}
};
Pair8 g_6018[3] = {{11124, 10}, {11540, 10}, {0, -2}};
Pair8 g_6030[9] = {
    {23168, 6}, {23426, 6}, {23686, 6}, {23936, 6}, {24170, 6}, {23936, 6},
    {23686, 6}, {23426, 6}, {0, -8}
};
Pair8 g_6078[4] = {{24402, 3}, {24936, 3}, {25490, 3}, {0, -3}};
Pair8 g_6098[11] = {
    {26048, 3}, {26152, 3}, {26302, 3}, {26468, 3}, {26684, 3}, {26958, 3},
    {26684, 3}, {26468, 3}, {26302, 3}, {26152, 3}, {0, -10}
};
int *g_60f0[28] = {
    (int *)&g_5f88, (int *)&g_5d80, (int *)&g_5d60, (int *)&g_5f08, (int *)&g_6030, (int *)&g_5db0, (int *)&g_5cb0, (int *)&g_5d40, (int *)&g_5f40, (int *)&g_5c80, (int *)&g_5da0, (int *)&g_5d90,
    (int *)&g_5d70, (int *)&g_5f28, (int *)&g_5cd0, (int *)&g_5c90, (int *)&g_5d20, (int *)&g_6018, (int *)&g_5cc0, (int *)&g_5d50, (int *)&g_5d30, (int *)&g_5ca0, (int *)&g_5fd0, (int *)&g_5ce0,
    (int *)&g_5d00, (int *)&g_5cf0, (int *)&g_5d10, (int *)&g_6078
};
void (*g_6160[28])(void) = {
    (void (*)(void))f_4394, (void (*)(void))f_4413, (void (*)(void))f_4480_state_handler, (void (*)(void))f_44a9_state_handler, (void (*)(void))f_4551_state_handler, (void (*)(void))f_456d_state_handler, (void (*)(void))f_45a6_state_handler, (void (*)(void))f_45d0_state_handler, (void (*)(void))f_4602_state_handler, (void (*)(void))f_469b_state_handler, (void (*)(void))f_46e7_state_handler, (void (*)(void))f_4745_state_handler,
    (void (*)(void))f_4761_state_handler, (void (*)(void))f_4802_state_handler, (void (*)(void))f_4847_state_handler, (void (*)(void))f_4886, (void (*)(void))f_48d2_state_handler, (void (*)(void))f_4931_state_handler, (void (*)(void))f_4955_state_handler, (void (*)(void))f_49c7_state_handler, (void (*)(void))f_49fb_state_handler, (void (*)(void))f_4a5a_state_handler, (void (*)(void))f_4aca_state_handler, (void (*)(void))f_4af0_state_handler,
    (void (*)(void))f_4b4f_state_handler, (void (*)(void))f_4bae, (void (*)(void))f_4c0d_state_handler, (void (*)(void))f_4c6c_state_handler
};

void f_4066(void)
{
    if (g_ddc0 != 0)
        f_4085();
}

void f_4085(void)
{
    int unused;

    g_e24c = g_dee4->at_00;
    r_e250 = g_dee4->at_04;
    f_8004(&g_e24c, g_dee4->at_78);
    g_dda4 = p_A990;
    for (g_ddbc = 0; g_ddbc < g_ddc0; ++g_ddbc) {
        *(int *)g_dda4 = *(int *)g_dda4;
        ++*(int *)(g_dda4 + 4);
        if (g_e142_baun != 0)
            ++*(int *)(g_dda4 + 4);
        g_8db4 = next_packed_table_value(g_dda4 + 8, g_dda4 + 0xc) + g_df34_nnyybtp;
        if (*(int *)g_dda4 > 0x140 || *(int *)g_dda4 < 0 ||
            *(int *)(g_dda4 + 4) > 0xd8 || *(int *)(g_dda4 + 4) < 0) {
            f_4291();
            continue;
        }
        if (*(int *)(g_dda4 + 4) < 0xc3) {
            g_e22c = *(int *)g_dda4;
            g_e230 = *(int *)(g_dda4 + 4);
            f_8004(&g_e22c, g_8db4);
            if (rectangles_intersect(&g_e24c, &g_e22c) != 0) {
                g_dDb8 = ((unsigned char *)g_dda4)[0x10] + 1;
                g_8e20 = ((unsigned char *)g_dda4)[0x11];
                if (g_8e20 >= 0x1c)
                    g_8e20 -= 0x1c;
                g_8db8 = g_6160[g_8e20];
                g_8db8();
                r_dDDc_uzmlc[5] += 2 << g_dee4->at_24;
                f_4291();
                continue;
            }
        }
        *(int *)image_buffer_cursor = g_8db4;
        *(short *)(image_buffer_cursor + 4) = *(short *)g_dda4;
        *(short *)(image_buffer_cursor + 6) = *(short *)(g_dda4 + 4);
        *(short *)(image_buffer_cursor + 8) = 0;
        image_buffer_cursor += 0xa;
        g_dda4 += 0x12;
    }
}

void f_4291(void)
{
    --g_ddc0;
    if (g_ddbc != g_ddc0)
        memcpy((void *)g_dda4, (void *)(g_dda4 + 0x12), (g_ddc0 - g_ddbc) * 0x12);
    --g_ddbc;
}

void f_42e1(unsigned char a, unsigned char b, int c, int d)
{
    if (g_ddc0 < 0x18 && a < 0x1c) {
        g_dda4 = p_A990;
        g_dda4 += g_ddc0 * 0x12;
        if (windows_environment_detected == -1)
            g_ddc0 = 0x1388;
        *(int *)g_dda4 = c;
        *(int *)(g_dda4 + 4) = d;
        *(int *)(g_dda4 + 0xc) = (int)g_60f0[a];
        *(int *)(g_dda4 + 8) = 0;
        *(unsigned char *)(g_dda4 + 0x10) = b;
        *(unsigned char *)(g_dda4 + 0x11) = a;
        submit_audio_request(0x1e);
        ++g_ddc0;
    }
}

void f_4394(void)
{
    if (g_dDb8 > 0)
        submit_audio_request(0x29);
    *m_de5c |= 0x20;
    g_dee4->at_58 = 3;
    g_8e20 = g_dee4->at_1c + g_dDb8;
    if (g_8e20 > 12) g_8e20 = 12;
    if (g_8e20 < 0) g_8e20 = 0;
    g_dee4->at_5c = g_8e20;
}

void f_4413(void)
{
    int b;
    int a;
    if (g_dee4->at_28 > 0) a = 1; else a = 0;
    if ((*m_de5c & 8) == 0) b = 1; else b = 0;
    if (b | a) {
        submit_audio_request(0x27);
        if (--g_dee4->at_28 < 0)
            f_5771();
    }
}

void f_4480_state_handler(void)
{
    submit_audio_request(0x4c);
    g_dee4->at_24 += g_dDb8;
}

void f_44a9_state_handler(void)
{
    submit_audio_request(0x5b);
    if ((*m_de5c & 8) == 0) {
        if ((*m_de5c & 0x10) == 0) {
            *m_de5c |= 0x10;
            g_dee4->at_00 = g_dee4->at_10 + g_dee4->at_0c - g_e4c6;
            g_dee4->at_04 = m_E4c4;
            f_10502(g_dee4->at_00, g_dee4->at_04);
            g_dee4->at_38 = g_dDb8 << 6;
        } else {
            g_dee4->at_38 += g_dDb8 << 6;
        }
    }
}

void f_4551_state_handler(void)
{
    g_dDb8 = -g_dDb8;
    f_4602_state_handler();
}

void f_456d_state_handler(void)
{
    submit_audio_request(0x1f);
    f_7e62(0, 0, 0, 0, g_df34_nnyybtp, (int)g_5ec0, 13);
}

void f_45a6_state_handler(void)
{
    submit_audio_request(0x3c);
    r_dDDc_uzmlc[1] += g_dDb8 * 0x71;
}

void f_45d0_state_handler(void) {
    submit_audio_request(0x3c);
    f_8fce(g_dee4->at_00, g_dee4->at_04);
}

void f_4602_state_handler(void) {
    submit_audio_request(0x5c);
    g_ddb4 = g_df78;
    for (c_DDAC = 0; c_DDAC < g_dDa8; ++c_DDAC) {
        g_8e20 = g_ddb4->b[0x10] + g_dDb8;
        if (g_8e20 > 5) g_8e20 = 5;
        if (g_8e20 < 0) g_8e20 = 0;
        g_ddb4->b[0x10] = (unsigned char)g_8e20;
        ++g_ddb4;
    }
}

void f_469b_state_handler(void) {
    submit_audio_request(0x56);
    m_de5c[1] |= 8;
    write_dac_palette(g_ddd4_eoraaik, 0, 0x100, 0x20);
    g_dee4->at_30 += g_dDb8 << 7;
}

void f_46e7_state_handler(void) {
    submit_audio_request(0x4c);
    g_8e1c = 3;
    g_ddb4 = g_df78;
    for (c_DDAC = 0; c_DDAC < g_dDa8; ++c_DDAC) {
        f_9053();
        g_ddb4++;
    }
}

void f_4745_state_handler(void) {
    g_dDb8 = -g_dDb8;
    f_46e7_state_handler();
}

void f_4761_state_handler(void) {
    submit_audio_request(0x33);
    m_de5c[1] &= 0xfe;
    m_de5c[0] |= 8;
    g_dee4->at_34 = g_dDb8 << 10;
    m_de5c[1] &= 0xfe;
    if (m_de5c[0] & 0x10) {
        m_de5c[0] &= 0xef;
        g_dee4->at_00 = g_dee4->at_10 + g_dee4->at_0c - (short)g_e4c6;
        g_dee4->at_04 = (short)m_E4c4;
        f_10502(g_dee4->at_00, g_dee4->at_04);
    }
}

void f_4802_state_handler(void) {
    submit_audio_request(0x68);
    if (!(m_de5c[1] & 4)) {
        g_dee4->at_04 = g_dee4->at_18;
        m_de5c[1] |= 4;
        f_58b0();
    }
}

void f_4847_state_handler(void) {
    submit_audio_request(0x5b);
    if (!(m_de5c[0] & 8)) {
        m_de5c[1] |= 1;
        g_dee4->at_3c += g_dDb8 << 5;
    }
}

void f_4886(void) {
    submit_audio_request(0x3c);
    if (!g_dee4->at_28) {
        g_dee4->at_44 = 0;
        g_dee4->at_40 = 3;
    }
    g_dee4->at_28 += g_dDb8;
}

void f_48d2_state_handler(void) {
    submit_audio_request(0x3c);
    m_de5c[0] |= 0x80;
    g_dee4->at_60 = 0xf;
    g_dee4->at_64 = 0xf;
    g_dee4->at_68 = 1;
    g_dee4->at_6c = 2;
    g_dee4->at_70 = -2;
}

void f_4931_state_handler(void) {
    submit_audio_request(0x3c);
    m_de5c[1] |= 0x10;
}

void f_4955_state_handler(void) {
    submit_audio_request(0x67);
    m_de5c[1] |= 0x20;
    g_dee4->at_2c += g_dDb8 << 9;
    g_ddb4 = g_df78;
    for (c_DDAC = 0; c_DDAC < g_dDa8; ++c_DDAC) {
        g_ddb4->b[0x11] |= 2;
        ++g_ddb4;
    }
}

void f_49c7_state_handler(void) {
    submit_audio_request(0x1f);
    m_de5c[1] |= 2;
    g_dee4->at_74 = g_dee4->at_00;
}

void f_49fb_state_handler(void) {
    submit_audio_request(0x3c);
    m_de5c[0] |= 0x80;
    g_dee4->at_60 = 0xf;
    g_dee4->at_64 = 0xf;
    g_dee4->at_68 = 5;
    g_dee4->at_6c = 2;
    g_dee4->at_70 = -2;
}

void f_4a5a_state_handler(void) {
    g_8e20 = (g_8e24 >> 2) & 0x1f;
    if (g_8e20 < 0x1c) {
    } else {
        g_8e20 -= 0x1c;
    }
    if (g_8e20 == 1) g_8e20 = 0xf;
    if (g_8e20 == 0x15) g_8e20 = 0x13;
    g_8db8 = g_6160[g_8e20];
    g_8db8();
}

void f_4aca_state_handler(void) {
    submit_audio_request(0x28);
    g_dDb8 = -g_dDb8;
    f_4394();
}

void f_4af0_state_handler(void) {
    submit_audio_request(0x3c);
    m_de5c[0] |= 0x80;
    g_dee4->at_60 = 4;
    g_dee4->at_64 = 4;
    g_dee4->at_68 = 1;
    g_dee4->at_6c = 0;
    g_dee4->at_70 = -5;
}

void f_4b4f_state_handler(void) {
    submit_audio_request(0x3c);
    m_de5c[0] |= 0x80;
    g_dee4->at_60 = 6;
    g_dee4->at_64 = 6;
    g_dee4->at_68 = 1;
    g_dee4->at_6c = 1;
    g_dee4->at_70 = -4;
}

void f_4bae(void) {
    submit_audio_request(0x3c);
    m_de5c[0] |= 0x80;
    g_dee4->at_60 = 4;
    g_dee4->at_64 = 4;
    g_dee4->at_68 = 5;
    g_dee4->at_6c = 0;
    g_dee4->at_70 = -5;
}

void f_4c0d_state_handler(void) {
    submit_audio_request(0x3c);
    m_de5c[0] |= 0x80;
    g_dee4->at_60 = 6;
    g_dee4->at_64 = 6;
    g_dee4->at_68 = 3;
    g_dee4->at_6c = 1;
    g_dee4->at_70 = -4;
}

void f_4c6c_state_handler(void) {
    submit_audio_request(0x57);
    g_dd94 = g_a848;
    for (g_ddc4 = 0; g_ddc4 < g_ddcc; ++g_ddc4) {
        g_dd94->b[0x24] |= 2;
        *(int *)&g_dd94->b[0x20] = 0;
        ++g_dd94;
    }
}

void f_4cd0(void) { }

void f_4ce1(void) {
}
