unsigned char g_8e4c[864];
int g_94b0;
int g_94b4;
/* TU f_6b02..f_798c [0x6b02, 0x7bd5): generated by tools/tu.py */
typedef unsigned int size_t;
typedef struct { int a, b, c; short d; int e; } S18;
int g_94a0;
int g_94a4;
int g_94a8;
int g_94ac;

extern unsigned char g_67b4[];
extern short audio_stream_flag;
extern short image_buffer_error_code;
extern short disp_idx;
extern short page2;
extern short flip_src;
extern short flip_dst;
extern short hook_flags_word;
extern int file_error_state;
extern unsigned char h_ab40_jbfxrqns[];
extern unsigned char g_bf40_whznxcth[];
extern unsigned char g_d340_schtgisj[];
extern int x_dd40_xbukycw;
extern int k_DD48_jbwjbqarofg;
extern unsigned char *g_dd4c_ilunphmaok;
struct DisplayModeInfo { short state; unsigned char plane_addresses[16]; int page_offsets[4]; int page_adjustments[4]; unsigned char page_mode_classes[4]; int buffer_size; int row_stride_bytes; int resolution_height; int width; int height; int left; int top; int right; int bottom; unsigned char mode_flags; unsigned char e37f; unsigned char e380; unsigned char video_mode_low; unsigned char e382; unsigned char e383; unsigned char e384; unsigned char e385; unsigned char e386; unsigned char tail; };
extern struct DisplayModeInfo vga_state;
void save_bios(void);
extern unsigned char current_scan_code;
extern unsigned char current_key_code_01;
extern short mouse_y_recent_average_g;
extern short mouse_x_recent_average_1c;
int g_9490;
int g_9494;
int g_9498;
int g_949c;

extern int g_e4d0_wfmxdlyju;
extern void fatal_exit(unsigned, unsigned);
extern void copy_screen_span_entry(int, int, int, int, int);
extern void handle_s_key(void);
extern void f_6156(void);
extern void f_61a6_vby(void);
extern void f_6e13(void);
extern int f_6e2e(void);
extern int f_6ee8(void);
extern void f_6f66(void);
extern void f_7032(void);
extern void f_704d(void);
extern void f_7068(void);
extern void f_7112_ngllzczwwhoqgnyg(void);
extern void f_7184(void);
extern void f_73c0(void);
extern void f_7532(void);
extern void f_798c(void);
extern void f_7bd5(void);
extern void f_7e62(int, int, int, int, int, int, int);
extern void f_9d40(unsigned char);
int g_9470;
int g_9474;
unsigned char *g_9478;
int g_947c;
int g_9480;
int g_9484;
int g_9488;
int g_948c;

extern void plot_transformed_pixel(void *, int);
extern void submit_audio_request(int);
extern void set_img_buffers(int, int, short, int, int);
extern void redraw_image_region(int, int);
extern int rand_rng(int, int);
extern void fade_pal(void *, int, int, int);
extern void show_page(void);
extern int fade_delay;
extern int g_8e1c;
extern int g_8e20;
extern void write_pal(void *);
extern unsigned char g_e13e;
extern unsigned char g_e13b;
extern unsigned char g_e46b;
extern void *r_dDDc_uzmlc;
void restore_bios(void);
void save_vga_state(void);
int g_9468;
int g_946c;

extern unsigned char gameplay_tuning_by_stage[];
extern short g_7b24;
extern short g_7b26;
extern short draw_idx;
extern short page3;
extern unsigned short mouse_btn;
extern unsigned short mouse_btn_old;
extern short mouse_sensitivity_x_o;
extern short mouse_sensitivity_y_9;
extern void query_mouse_sensitivity(void);
extern void restore_mouse_driver_sensitivity(void);
void f_80d8(void);
void f_843a(void);
extern unsigned char read_vga_pixel_entry(int, int);
extern int g_dd84;
extern int g_dd88;
extern int g_dDa8;
extern int c_DDAC;
extern char *g_dd6c;
extern char *g_ddb4;
extern char g_df78[];
extern void f_7551(void);
extern void f_7bf4(void);
unsigned char g_91ac[700];

extern void f_85a4(void);
extern void set_mouse_bounds(int, int, int, int);
extern void move_mouse_to(int, int);
extern void update_mouse(void);
void *memmove(void *, const void *, size_t);
void f_788d(void);
void f_7e12(void);
void f_8585(void);
void f_8f7e(void);
void f_8fce(int x, int y);
extern short mouse_x_sample_0_f;
extern short mouse_y_sample_0;
extern int fill_clipped_vga_rectangle(int, int, int, int, int, int);
extern void write_dac_palette(void *, int, int, int);
extern int g_68f4;
extern unsigned char *image_buffer_cursor;
extern unsigned char g_6864[];
extern void f_78dd(int, int, int, int, int, int, int);
extern int next_packed_table_value(void *, void *);
extern int frames_intersect_inset(S18, int, int, S18, int, int, int, int, int, int);
void *memcpy(void *, const void *, size_t);
extern unsigned char g_687c[];

/* file names of the game data */
/* _DATA [0x68f8,0x6984) */
char *g_68f8_jwwqkwr = "ke_all.pal";
char *g_68fc_ifhyqlddj = "ke_tit.gif";
char *g_6900 = "ke_tit.dig";
char *g_6904 = "ke_menu.gif";
char *g_6908 = "ke_menu.bob";
char *g_690c = "ke_menu.dig";
char *g_6910 = "ke_order.gif";
char *g_6914 = "ke_menu.bob";
char *g_6918 = "ke_score.gif";
char *g_691c = "ke_font.bob";
char *g_6920 = "ke_score.dig";
char *g_6924 = "ke_score.lst";
char *g_6928 = "ke_score.gif";
char *g_692c = "ke_font.bob";
char *g_6930 = "ke_end.dig";
char *g_6934 = "ke_score.gif";
char *g_6938 = "ke_font.bob";
char *g_693c = "ke_infos.dig";
char *g_6940_hqhettu = "ke_brick.bob";
char *g_6944_bdcftta = "ke_spell.bob";
char *g_6948_kxwrlv = "ke_nmy.bob";
char *g_694c_wjufexbevsk = "ke_rack.bob";
char *g_6950 = "ke_fill.bob";
char *g_6954 = "ke_font.bob";
char *g_6958_vghgxtjirow = "ke_digit.bob";
char *g_695c_qurvlwasjp = "ke_monst.bob";
char *g_6960_juobaluykyr = "ke_monst.gif";
char *g_6964 = "ke_main.dig";
char *g_6968 = "ke_lvl.dig";
char *g_696c = "ke_go.dig";
char *g_6970 = "ke_pause.dig";
char *g_6974 = "ke_pub.dig";
char *g_6978 = "ke_pub1.gif";
char *g_697c = "ke_pub2.gif";
char *g_6980 = "ke_pub3.gif";

int f_6b02(void)
{
    g_9468 = 0x118;
    g_9484 = 0;
    g_947c = vga_state.bottom;
    vga_state.bottom = 0xa6;
    fade_pal((void *)x_dd40_xbukycw, 0, 0x3f, 8);
    g_e4d0_wfmxdlyju = file_error_state;
    f_6156();
    f_61a6_vby();
    *(unsigned char *)&hook_flags_word &= 0xf8;
    set_img_buffers((int)g_d340_schtgisj, 0x100, 4, (int)h_ab40_jbfxrqns, (int)g_bf40_whznxcth);
    f_7112_ngllzczwwhoqgnyg();
    f_7032();
    f_704d();
    f_7068();
    f_9d40(0);
    f_9d40(0);
    plot_transformed_pixel((void *)k_DD48_jbwjbqarofg, page2);
    copy_screen_span_entry(page2, 0, flip_src, 0, vga_state.buffer_size);
    copy_screen_span_entry(page2, 0, flip_dst, 0, vga_state.buffer_size);
    disp_idx = page2;
    f_6f66();
    f_798c();
    f_73c0();
    fade_pal((void *)x_dd40_xbukycw, 0x3f, 0, 1);
L_6c3d:;
    f_9d40(3);
    f_7184();
    handle_s_key();
    f_798c();
    f_7532();
    f_73c0();
    f_7bd5();
    redraw_image_region(0, 0);
    if (image_buffer_error_code == 0) goto L_6c91;
    fatal_exit(image_buffer_error_code, 0);
L_6c91:;
    show_page();
    if (g_94a8 <= 0) goto L_6cac;
    if (g_9490 > 0) goto L_6db7;
L_6cac:;
    --g_9468;
    --g_9470;
    if (g_9470 > 0) goto L_6db7;
    if (g_94a8 > 0) goto L_6d4d;
    if (audio_stream_flag != 0) goto L_6ce6;
    submit_audio_request(0x6b);
L_6ce6:;
    g_9470 = 0;
L_6cf0:;
    if (g_9470 < 2) goto L_6d03;
    goto L_6d41;
L_6cfb:;
    ++g_9470;
    goto L_6cf0;
L_6d03:;
    f_7e62(rand_rng(-0x1e, 0x1e) + 0x106, rand_rng(-0x1e, 0x1e) + 0x56, 0, 0, (int)g_dd4c_ilunphmaok, (int)g_67b4, 1);
    goto L_6cfb;
L_6d41:;
    g_9470 = 8;
    goto L_6db7;
L_6d4d:;
    if (audio_stream_flag != 0) goto L_6d61;
    submit_audio_request(0x6a);
L_6d61:;
    f_7e62(rand_rng(-0x10, 0x10) + (mouse_x_recent_average_1c + 4), (mouse_y_recent_average_g + 8) + rand_rng(-0x10, 0x10), 0, 0, (int)g_dd4c_ilunphmaok, (int)g_67b4, 1);
    g_9470 = 0x19;
L_6db7:;
    if (g_94a8 > 0) goto L_6dc9;
    if (g_9468 <= 0) goto L_6dcb;
L_6dc9:;
    goto L_6dda;
L_6dcb:;
    f_6e13();
    return f_6ee8();
L_6dda:;
    if (g_9468 <= 0) goto L_6dfe;
    if (current_scan_code == current_key_code_01) goto L_6df9;
    if (current_key_code_01 == 1) goto L_6dfe;
L_6df9:;
    goto L_6c3d;
L_6dfe:;
    f_6e13();
    return f_6e2e();
}

void f_6e13(void) { vga_state.bottom = g_947c; }

int f_6e2e(void)
{
    submit_audio_request(0xb);
    fade_delay = 2;
    g_8e1c = 0;
L_6e58:;
    if (g_8e1c < 0x3f) goto L_6e6e;
    goto L_6ecf;
L_6e66:;
    ++g_8e1c;
    goto L_6e58;
L_6e6e:;
    g_8e20 = 0;
L_6e78:;
    if (g_8e20 < 0x300) goto L_6e8f;
    goto L_6eb1;
L_6e86:;
    g_8e20 += 3;
    goto L_6e78;
L_6e8f:;
    if (++*(unsigned char *)(unsigned char *)(x_dd40_xbukycw + g_8e20) <= 0x3f) goto L_6eaf;
    *(unsigned char *)(unsigned char *)(x_dd40_xbukycw + g_8e20) = 0x3f;
L_6eaf:;
    goto L_6e86;
L_6eb1:;
    write_pal((void *)x_dd40_xbukycw);
    f_9d40(3);
    goto L_6e66;
L_6ecf:;
    fade_delay = 1;
    return 0;
}

int f_6ee8(void)
{
    submit_audio_request(0x26);
    if (g_e13b == 0)
        *(int *)((unsigned char *)r_dDDc_uzmlc + 20) += (5000 / g_94a0) * g_9490 + 5000;
    fade_delay = 3;
    fade_pal(x_dd40_xbukycw, 0, -63, -1);
    fade_delay = 1;
    return 1;
}

void f_6f66(void)
{
    int v_4;
    int v_8;
    int v_c;
    v_8 = 0;
L_6f79:;
    if (v_8 < 0xa6) goto L_6f8f;
    return;
L_6f87:;
    v_8++;
    goto L_6f79;
L_6f8f:;
    v_4 = 0xa0;
L_6f96:;
    if (v_4 < 0x140) goto L_6faa;
    goto L_7028;
L_6fa4:;
    v_4 += 2;
    goto L_6f96;
L_6faa:;
    v_c = (unsigned char)read_vga_pixel_entry(v_4, v_8);
    if (v_c < 0x18) goto L_6fcc;
    if (v_c <= 0x27) goto L_6fce;
L_6fcc:;
    goto L_6fdf;
L_6fce:;
    *(int *)(g_91ac + (v_8 << 2)) = v_4;
    goto L_7028;
L_6fdf:;
    if (v_c < 0x50) goto L_6feb;
    if (v_c <= 0x58) goto L_6fed;
L_6feb:;
    goto L_6ffe;
L_6fed:;
    *(int *)(g_91ac + (v_8 << 2)) = v_4;
    goto L_7028;
L_6ffe:;
    if (v_c < 0x90) goto L_7010;
    if (v_c <= 0xa7) goto L_7012;
L_7010:;
    goto L_7023;
L_7012:;
    *(int *)(g_91ac + (v_8 << 2)) = v_4;
    goto L_7028;
L_7023:;
    goto L_6fa4;
L_7028:;
    goto L_6f87;
}

void f_7032(void) { g_9488 = 0; }

void f_704d(void) { g_dd84 = 0; }

void f_7068(void)
{
    g_94a4 = *(int *)(gameplay_tuning_by_stage + (g_e13e << 4));
    g_94a8 = g_94a4;
    g_9494 = g_94a8;
    g_94ac = *(int *)(gameplay_tuning_by_stage + 4 + ((g_e13e << 2) << 2));
    g_946c = *(int *)(gameplay_tuning_by_stage + 8 + ((g_e13e << 2) << 2));
    g_948c = g_946c;
    g_949c = *(int *)(gameplay_tuning_by_stage + 12 + ((g_e13e << 2) << 2));
    g_94b4 = 0;
    g_9498 = 7;
    g_9474 = 0xf;
}

void f_7112_ngllzczwwhoqgnyg(void)
{
    set_mouse_bounds(4, 16, 4, 0x95);
    move_mouse_to(4, 0x52);
    for (g_8e20 = 0; g_8e20 < 4; ++g_8e20)
        update_mouse();
    g_94a0 = 100;
    g_9490 = g_94a0;
    g_94b0 = g_9490;
}

void f_7184(void)
{
    if (g_9490 > 0) goto L_71cb;
    g_9490 = 0;
    set_mouse_bounds(mouse_x_sample_0_f, mouse_y_sample_0, mouse_x_sample_0_f, mouse_y_sample_0);
L_71cb:;
    if (g_9490 == g_94b0) goto L_72c0;
    g_94b0 = g_9490;
    vga_state.bottom = g_947c;
    fill_clipped_vga_rectangle(draw_idx, ((g_9490 * 0x6f) / g_94a0) + 0x1c, 0xb3, 0x8b, 0xb9, 0);
    fill_clipped_vga_rectangle(disp_idx, ((g_9490 * 0x6f) / g_94a0) + 0x1c, 0xb3, 0x8b, 0xb9, 0);
    vga_state.bottom = 0xa6;
    g_8e20 = 0;
L_7272:;
    if (g_8e20 < 0x300) goto L_7289;
    goto L_72ac;
L_7280:;
    g_8e20 += 3;
    goto L_7272;
L_7289:;
    if ((*(unsigned char *)(unsigned char *)(x_dd40_xbukycw + g_8e20) += 3) <= 0x3f) goto L_72aa;
    *(unsigned char *)(unsigned char *)(x_dd40_xbukycw + g_8e20) = 0x3f;
L_72aa:;
    goto L_7280;
L_72ac:;
    g_9484 = 1;
    submit_audio_request(0x69);
L_72c0:;
    if (g_94a8 == g_9494) goto L_738f;
    if (g_94a8 >= 0) goto L_72ee;
    g_94a8 = 0;
    g_94b4 = 0x1388;
L_72ee:;
    g_9494 = g_94a8;
    vga_state.bottom = g_947c;
    fill_clipped_vga_rectangle(draw_idx, ((g_94a8 * 0x6f) / g_94a4) + 0xb4, 0xb3, 0x123, 0xb9, 0);
    fill_clipped_vga_rectangle(disp_idx, ((g_94a8 * 0x6f) / g_94a4) + 0xb4, 0xb3, 0x123, 0xb9, 0);
    vga_state.bottom = 0xa6;
    g_9484 += 8;
    submit_audio_request(0x25);
L_738f:;
    if (g_9484 <= 0) goto L_73bb;
    write_dac_palette((void *)x_dd40_xbukycw, 0, 0x100, -g_9484);
    --g_9484;
L_73bb:;
}

void f_73c0(void)
{
    if (g_9490 <= 0) goto bottom;
    if (g_68f4 != 0) goto reset_gate;
    if (mouse_btn == 3) goto reset_gate;
    goto first_compare;
reset_gate:
    goto reset_flag;
first_compare:
    if (mouse_btn == mouse_btn_old) goto second_gate;
    if ((mouse_btn & 1) == 1) goto first_side;
second_gate:
    goto second_side;
first_side:
    submit_audio_request(0x66);
    f_78dd(0, 4, mouse_x_recent_average_1c, mouse_y_recent_average_g, 0x40, 0, (int)g_6864);
    mouse_x_sample_0_f -= 7;
    g_68f4 = 1;
    goto second_exit;
second_side:
    if (mouse_btn == mouse_btn_old) goto second_skip;
    if (mouse_btn & 2) goto second_actions;
second_skip:
    goto second_exit;
second_actions:
    submit_audio_request(0x66);
    f_78dd(0, 1, mouse_x_recent_average_1c, mouse_y_recent_average_g, 0x60, 0x18, (int)g_6864);
    f_78dd(0, 1, mouse_x_recent_average_1c, mouse_y_recent_average_g, 0x60, -0x18, (int)g_6864);
    mouse_x_sample_0_f -= 7;
    g_68f4 = 1;
second_exit:
    goto bottom;
reset_flag:
    g_68f4 = 0;
bottom:
    *(int *)image_buffer_cursor = (int)(g_dd4c_ilunphmaok + 0x35d6);
    *(short *)(image_buffer_cursor + 4) = mouse_x_recent_average_1c;
    *(short *)(image_buffer_cursor + 6) = mouse_y_recent_average_g;
    *(short *)(image_buffer_cursor + 8) = 0;
    image_buffer_cursor += 10;
}

void f_7532(void) { if (g_9488) f_7551(); }

void f_7551(void)
{
    S18 *v_4;
    S18 *v_8;
    g_9478 = g_8e4c;
    g_9480 = 0;
L_7571:;
    if (g_9480 < g_9488) goto L_758b;
    return;
L_7583:;
    ++g_9480;
    goto L_7571;
L_758b:;
    *(int *)(g_9478 + 4) += *(int *)(g_9478 + 0xc);
    *(int *)(g_9478 + 8) += *(int *)(g_9478 + 0x10);
    next_packed_table_value(g_9478 + 0x18, g_9478 + 0x1c);
    v_8 = (S18 *)(*(int *)*(unsigned char * *)(g_9478 + 0x1c) + *(unsigned char * *)(g_9478 + 0x14));
    if ((*(int *)(g_9478 + 4) >> 4) > 0x150) goto L_7600;
    if ((*(int *)(g_9478 + 4) >> 4) >= -0x10) goto L_7602;
L_7600:;
    goto L_7614;
L_7602:;
    if ((*(int *)(g_9478 + 8) >> 4) <= 0xd8) goto L_7616;
L_7614:;
    goto L_7626;
L_7616:;
    if ((*(int *)(g_9478 + 8) >> 4) >= -0x10) goto L_7630;
L_7626:;
    f_788d();
    goto L_7583;
L_7630:;
    if (*(int *)g_9478 != 0) goto L_7771;
    v_4 = (S18 *)(g_dd4c_ilunphmaok + 0x395c);
    if (frames_intersect_inset(*v_4, 0xf6, 0x46,
               *v_8,
               *(int *)(g_9478 + 4) >> 4, *(int *)(g_9478 + 8) >> 4,
               0xa, 0, 0xa, 0) != -1) goto L_7701;
    g_94a8 -= *(int *)(g_9478 + 0x20);
    f_7e62(*(int *)(g_9478 + 4) >> 4, *(int *)(g_9478 + 8) >> 4, *(int *)(g_9478 + 0xc) >> 6, *(int *)(g_9478 + 0x10) >> 6, (int)g_dd4c_ilunphmaok, (int)g_67b4, 1);
    f_788d();
    goto L_7583;
L_7701:;
    if (((*(int *)(g_9478 + 4) >> 4) + 5) <= *(int *)(g_91ac + ((*(int *)(g_9478 + 8) >> 4) << 2))) goto L_776c;
    submit_audio_request(0x57);
    f_7e62(*(int *)(g_9478 + 4) >> 4, *(int *)(g_9478 + 8) >> 4, 0, 0, (int)g_dd4c_ilunphmaok, (int)g_67b4, 1);
    f_788d();
    goto L_7583;
L_776c:;
    goto L_7835;
L_7771:;
    v_4 = (S18 *)(g_dd4c_ilunphmaok + 0x35d6);
    if (frames_intersect_inset(*v_4,
               mouse_x_recent_average_1c, mouse_y_recent_average_g,
               *v_8,
               (*(int *)(g_9478 + 4) >> 4) + 8, *(int *)(g_9478 + 8) >> 4,
               4, 4, 4, 4) != -1) goto L_7835;
    if (g_9490 <= 0) goto L_77f9;
    g_9490 -= *(int *)(g_9478 + 0x20);
L_77f9:;
    f_7e62(*(int *)(g_9478 + 4) >> 4, *(int *)(g_9478 + 8) >> 4, 0, 0, (int)g_dd4c_ilunphmaok, (int)g_67b4, 1);
    f_788d();
    goto L_7583;
L_7835:;
    *(int *)image_buffer_cursor = v_8;
    *(short *)(image_buffer_cursor + 4) = (unsigned short)(*(int *)(g_9478 + 4) >> 4);
    *(short *)(image_buffer_cursor + 6) = (unsigned short)(*(int *)(g_9478 + 8) >> 4);
    *(short *)(image_buffer_cursor + 8) = 0;
    image_buffer_cursor += 0xa;
    g_9478 += 0x24;
    goto L_7583;
}

void f_788d(void)
{
    --g_9488;
    if (g_9480 != g_9488)
        memcpy(g_9478, g_9478 + 0x24, (g_9488 - g_9480) * 0x24);
    --g_9480;
}

void f_78dd(int a, int b, int x, int y, int c, int d, int e)
{
    if (g_9488 < 0x18) {
        g_9478 = g_8e4c;
        g_9478 += g_9488 * 0x24;
        *(int *)(g_9478 + 0) = a;
        *(int *)(g_9478 + 0x20) = b;
        *(int *)(g_9478 + 4) = x << 4;
        *(int *)(g_9478 + 8) = y << 4;
        *(int *)(g_9478 + 12) = c;
        *(int *)(g_9478 + 16) = d;
        *(int *)(g_9478 + 24) = 0;
        *(int *)(g_9478 + 28) = e - 8;
        *(int *)(g_9478 + 20) = (int)g_dd4c_ilunphmaok;
        ++g_9488;
    }
}

void f_798c(void)
{
    int v_4;
    int v_8;
    int v_c;
    int v_10;
    int v_14;
    v_4 = 0xf6;
    v_8 = 0x56;
    v_14 = 0;
    if (g_94a8 <= 0) goto L_7b95;
    --g_94b4;
    if (g_94b4 > 0) goto L_7af8;
    *(int *)image_buffer_cursor = (int)(g_dd4c_ilunphmaok + 0x43b6);
    *(short *)(image_buffer_cursor + 4) = 0xf6;
    *(short *)(image_buffer_cursor + 6) = 0x46;
    *(short *)(image_buffer_cursor + 8) = 0;
    image_buffer_cursor += 0xa;
    v_14 = 1;
    --g_9498;
    if (g_9498 > 0) goto L_7af8;
    g_9498 = 7;
    v_c = ((mouse_x_recent_average_1c - v_4) << 4) / 0x28;
    v_10 = ((rand_rng(-0x1e, 0x1e) + (mouse_y_recent_average_g - v_8)) << 4) / 0x28;
    f_78dd(1, g_94ac, v_4, v_8, v_c, v_10, (int)g_687c);
    if (g_9490 <= 0) goto L_7aaf;
    submit_audio_request(0x58);
L_7aaf:;
    --g_948c;
    if (g_948c > 0) goto L_7af8;
    g_949c -= 2;
    g_94b4 = g_949c;
    g_948c = g_946c;
    --g_9474;
    if (g_9474 > 0) goto L_7af8;
    ++g_946c;
    g_9474 = 0xf;
L_7af8:;
    if (v_14 != 0) goto L_7b93;
    if (g_94b4 < 0xf) goto L_7b1b;
    if ((g_949c - 0x14) >= g_94b4) goto L_7b58;
L_7b1b:;
    *(int *)image_buffer_cursor = (int)(g_dd4c_ilunphmaok + 0x3e70);
    *(short *)(image_buffer_cursor + 4) = 0xf6;
    *(short *)(image_buffer_cursor + 6) = 0x46;
    *(short *)(image_buffer_cursor + 8) = 0;
    image_buffer_cursor += 0xa;
    goto L_7b93;
L_7b58:;
    *(int *)image_buffer_cursor = (int)(g_dd4c_ilunphmaok + 0x395c);
    *(short *)(image_buffer_cursor + 4) = 0xf6;
    *(short *)(image_buffer_cursor + 6) = 0x46;
    *(short *)(image_buffer_cursor + 8) = 0;
    image_buffer_cursor += 0xa;
L_7b93:;
    return;
L_7b95:;
    *(int *)image_buffer_cursor = (int)(g_dd4c_ilunphmaok + 0x43b6);
    *(short *)(image_buffer_cursor + 4) = 0xf6;
    *(short *)(image_buffer_cursor + 6) = 0x46;
    *(short *)(image_buffer_cursor + 8) = 0;
    image_buffer_cursor += 0xa;
}
