/* Firing and brick-map bits used by this unit. */
#define PLAYER_KEY_FIRE_HELD_FLAG 0x80
#define PLAYER_KEY_FIRE_FLAG 8
#define MOUSE_SECOND_BUTTON_MASK 2
#define PLAYER_SHOT_KIND_MASK 3
#define PLAYER_SHOT_KIND_PIERCING 1
#define PLAYER_SHOT_KIND_EXPLOSIVE 2
#define BRICK_TILE_PORTAL_ENTRY 0xf8
#define BRICK_TILE_PORTAL_EXIT 0xf9
#define PLAYER_SHOT_OUTSIDE_RIGHT_EDGE 0x140
#define PLAYER_SHOT_OUTSIDE_BOTTOM_EDGE 0xdc
#define BRICK_FIELD_TOP 0x18
#define BRICK_FIELD_BOTTOM 0x98
#define BRICK_TILE_WIDTH 0x10
#define BRICK_ROW_SHIFT 3
#define BRICK_COLUMN_SHIFT 4
#define BRICK_COLUMNS_PER_ROW 0x12
#define BRICK_LAST_COLUMN 0x11
#define BRICK_FIELD_RIGHT_EDGE 0x130
#define PLAYFIELD_TOP_EDGE 0x14
#define ENEMY_PROJECTILE_HIT_BY_SHOT_FLAG 2

struct Racket {
    int x, y, previous_x, min_x, max_x, min_y, max_y, sprite_frame_index;
    int sprite_height, reward_level, capture_timer, state_2c, state_30;
    int effect_state, horizontal_recenter_timer, vertical_recenter_timer;
    int effect_timer_40, effect_frame_44, animation_timer_48, animation_step_4c;
    int animation_timer_50, animation_step_54, shield_frame_timer, shield_frame_index;
    int spell_anim_timer, spell_anim_index, spell_parameter_68, spell_parameter_6c;
    int spell_parameter_70, previous_x_snapshot, sprite_pointer;
};

struct GameBall {
    int x, y, velocity_x, velocity_y;
    unsigned char behavior;
    unsigned char flags;
};

struct EnemyProjectile {
    int x, y, velocity_x, velocity_y, sprite_info, flight_phase, state_18;
    int animation_sequence, hit_points;
    unsigned char flags;
    unsigned char tail[3];
};

struct PlayerShot {
    int x, y, vertical_speed, sprite_offset;
    unsigned flags;
};

struct SpriteFrame {
    int image_offset;
    int duration_or_delta;
};

struct AudioRequestEntry {
    int source, byte_count, sample_rate, playback_mode;
};

struct GameProgressState {
    int progress_marker, life_balance, opaque_08, opaque_0c, opaque_10, score, tail;
};

struct BrickCell {
    unsigned char drop_kind : 2;
    unsigned char drop_value : 6;
    unsigned char tile_code;
};

struct SpriteDrawCommand {
    int sprite_or_frame;
    short x, y, flags;
};

struct PlayerShotKindBits { unsigned f : 2; };

int level_art_base;
/* TU load_palette..spawn_player_shot [0x608a, 0x6b02): generated by tools/tu.py */
#include <string.h>
extern void submit_audio_request(int);
extern void spawn_game_ball(int, int);
extern void write_dac_palette(void *, int, int, int);
extern void adjust_game_ball_velocity(void);
extern void move_mouse_to(int, int);
extern void update_racket_movement_bounds(void);
extern void resize_racket(void);
extern int get_racket_sprite_height(void);
extern void load_next_file(int);
extern void load_picture_keep(int); /* External helper called with monster_anim_fname. */
extern void stop_audio_stream(void);
extern void spawn_player_shot(unsigned char, int, int, int);
extern void update_player_shots(void);
extern void set_mouse_horizontal_bounds(int, int);
extern void set_mouse_vertical_bounds(int, int);
extern struct Racket *racket_object;
extern int game_art_base;
extern struct SpriteDrawCommand *image_buffer_cursor;
extern unsigned char *player_key_flags;
extern int game_ball_slot;
extern int current_ball_count;
extern int motion_dir;
extern int file_buf_ptr; /* Shared cursor/base for the asset blocks loaded here. */
extern int previous_level_art_base;
extern int audio_request_entries;
extern int level_art_load_base;
extern int n_read; /* Shared image/audio buffer capacity. */
extern int vga_buffer_base;
extern int brick_art_start;
extern unsigned char *spell_art_base;
extern unsigned char *enemy_picture;
extern int monster_art;
extern int sprite_memory_base;
extern int game_sprite_base;
extern int player_shot_total;
extern short sound_blaster_detected;
extern unsigned short mouse_btn_old;
extern unsigned short mouse_btn;
extern struct AudioRequestEntry level_audio_requests[];
extern int main_palette_fn;
extern int brick_sprite_fn;
extern int spell_sprite_fn;
extern int foe_sprite_fn;
extern int racket_sprite_filename;
extern int digit_sprite_filename;
extern int monster_sprite_filename;
extern int monster_anim_fname;
extern int main_screen_data_filename;
extern struct GameBall *current_ball_pointer;
extern struct GameBall game_balls[];
extern int work_value;
extern int temp;
extern int frames;
extern int sprite_frame_offset_scratch;
extern int result;
extern int (*current_spell_effect_handler)(void);
extern int (*spell_effect_handlers[])(void);
extern void *palette_base;
extern int moving_target_number;
extern int moving_target_count;
extern struct EnemyProjectile *moving_target_cursor;
extern struct EnemyProjectile moving_target_records[];
extern struct SpriteFrame racket_sprite_frames[];
extern short mouse_x_average_recent;
extern short mouse_y_mean_recent;
extern void spawn_falling_spell(int, int, int, int);
extern void spawn_animated_sprite(int, int, int, int, int, int, int);
extern int next_random_value();
extern void spawn_enemy_projectile(int, int, int, int);
extern void move_enemy_projectiles(void);
extern int file_mark;
extern unsigned char bonus_index;
extern unsigned char level_number;
extern int remaining_brick_count;
extern int enemy_timer;
extern int enemy_spawn_wait_time;
extern int enemy_cursor;
extern int scratch;
extern int ptrbuf;
extern int bonus_animations_by_type[];
extern unsigned char spell_slots[];
extern struct GameProgressState *score_state;
extern unsigned char collision_animation_frames[];
extern unsigned char racket_spell_animation_frames[];
extern unsigned char spell_impact_animation_frames[];
extern int sprite_frame_pointer;
extern struct PlayerShot player_shot_records[];
extern unsigned char brick_code_map[];
extern unsigned current_brick_code;
extern int portal_start_x;
extern int portal_y_source;
extern int portal_exit_xpos;
extern int portal_destination_y;
extern struct BrickCell *cell_cursor;
extern struct PlayerShot *player_shot_cursor;
extern int player_shot_index;
extern int collision_box_b_left;
extern int b_box_top;
extern int collision_box_a_left;
extern int collision_box_a_top;
extern int sprite_rect_a_right;
extern int sprite_bounds_a_bottom;
extern void process_brick_hit(int, int, int, int);
extern void draw_level_tile_on_pages(int, int, int);
extern void queue_timed_level_change(int, int);
extern void remove_player_shot(void);
extern void get_sprite_bounds(void *, void *);
extern void get_sprite_collision_bounds(void *, void *);
extern int rectangles_intersect(void *, void *);
extern void play_audio_request_at(int, int);
void *memcpy(void *, const void *, size_t);

/* Loads the palette followed immediately by the brick sprite block. */
void load_palette(void) {
    palette_base = (void *)file_buf_ptr;
    vga_buffer_base = file_buf_ptr;
    load_next_file(main_palette_fn);
    file_buf_ptr -= n_read - 0x300;
    brick_art_start = file_buf_ptr;
    load_next_file(brick_sprite_fn);
}

/* Loads the spell, enemy, racket, and digit sprite assets for a level. */
void load_enemy(void) {
    spell_art_base = (unsigned char *)file_buf_ptr;
    load_next_file(spell_sprite_fn);
    enemy_picture = (unsigned char *)file_buf_ptr;
    load_next_file(foe_sprite_fn);
    game_art_base = file_buf_ptr;
    load_next_file(racket_sprite_filename);
    monster_art = file_buf_ptr;
    load_next_file(digit_sprite_filename);
}

void load_monster_art(void) {
    sprite_memory_base = file_buf_ptr;
    vga_buffer_base = sprite_memory_base + 0xfa00;
    load_picture_keep(monster_anim_fname);
    game_sprite_base = file_buf_ptr;
    load_next_file(monster_sprite_filename);
}

void prep_level(void) {
    file_mark = file_buf_ptr;
    audio_request_entries = (int)level_audio_requests;
    stop_audio_stream();
    for (temp = 0; temp < 0x6e; ++temp)
        level_audio_requests[temp].source -= previous_level_art_base;
    level_art_load_base = file_buf_ptr;
    level_art_base = level_art_load_base;
    if (sound_blaster_detected == -1) load_next_file(main_screen_data_filename);
    for (temp = 0; temp < 0x6e; ++temp)
        level_audio_requests[temp].source += level_art_base;
    previous_level_art_base = level_art_base;
    file_buf_ptr = file_mark;
}

/* Handle shot cooldown, firing input, and updates to active shots. */
void shot_cd(void) {
    /* Racket bytes 0x60..0x70 carry shot controls here and spell parameters in other states. */
    if (racket_object->spell_anim_timer == 0 && (player_key_flags[0] & PLAYER_KEY_FIRE_HELD_FLAG)) {
        if (player_shot_total < racket_object->spell_parameter_68) {
            if ((mouse_btn_old != mouse_btn && (mouse_btn & MOUSE_SECOND_BUTTON_MASK)) || (player_key_flags[0] & PLAYER_KEY_FIRE_FLAG)) {
                spawn_player_shot((unsigned char)racket_object->spell_parameter_6c, racket_object->spell_parameter_70,
                       racket_object->x, racket_object->y);
                racket_object->spell_anim_timer = racket_object->spell_anim_index;
            }
        }
    } else {
        --racket_object->spell_anim_timer;
    }
    if (player_shot_total != 0) update_player_shots();
}

/* Move the player's shots, damage bonus_stage_brick_counts, and queue their draw records. */
void update_player_shots(void)
{
    int row_y;
    int first_column;
    int last_column;
    int row_offset;
    int tile_hit;
    player_shot_cursor = player_shot_records;
    for (player_shot_index = 0; player_shot_index < player_shot_total; ++player_shot_index) {
        player_shot_cursor->y += player_shot_cursor->vertical_speed;
        sprite_frame_pointer = player_shot_cursor->sprite_offset;
        collision_box_a_left = player_shot_cursor->x;
        collision_box_a_top = player_shot_cursor->y;
        get_sprite_bounds(&collision_box_a_left, (void *)sprite_frame_pointer);
            if (sprite_rect_a_right > PLAYER_SHOT_OUTSIDE_RIGHT_EDGE || collision_box_a_left < 0 || sprite_bounds_a_bottom > PLAYER_SHOT_OUTSIDE_BOTTOM_EDGE || collision_box_a_top < PLAYFIELD_TOP_EDGE) {
            if ((player_shot_cursor->flags & PLAYER_SHOT_KIND_MASK) == PLAYER_SHOT_KIND_EXPLOSIVE) {
                spawn_animated_sprite((collision_box_a_left + sprite_rect_a_right) >> 1, (collision_box_a_top + sprite_bounds_a_bottom) >> 1, 0, 0, (int)enemy_picture, (int)collision_animation_frames, 1);
                submit_audio_request(0x57);
            } else {
                spawn_animated_sprite((collision_box_a_left + sprite_rect_a_right) >> 1, 0x18, 0, 0, (int)spell_art_base, (int)spell_impact_animation_frames, 1);
            }
            remove_player_shot();
            continue;
        }
        moving_target_cursor = moving_target_records;
        for (moving_target_number = 0; moving_target_number < moving_target_count; ++moving_target_number) {
            collision_box_b_left = moving_target_cursor->x;
            b_box_top = moving_target_cursor->y;
            get_sprite_collision_bounds(&collision_box_b_left, (void *)moving_target_cursor->sprite_info);
            if (rectangles_intersect(&collision_box_a_left, &collision_box_b_left)) {
                moving_target_cursor->flags |= ENEMY_PROJECTILE_HIT_BY_SHOT_FLAG;
                if ((player_shot_cursor->flags & PLAYER_SHOT_KIND_MASK) == PLAYER_SHOT_KIND_EXPLOSIVE) {
                    moving_target_cursor->hit_points = 0;
                } else if ((player_shot_cursor->flags & PLAYER_SHOT_KIND_MASK) == PLAYER_SHOT_KIND_PIERCING) {
                    moving_target_cursor->hit_points -= 4;
                } else {
                    --moving_target_cursor->hit_points;
                }
                if (moving_target_cursor->hit_points <= 0) {
                    moving_target_cursor->velocity_y += player_shot_cursor->vertical_speed >> 1;
                }
                if ((player_shot_cursor->flags & PLAYER_SHOT_KIND_MASK) != PLAYER_SHOT_KIND_EXPLOSIVE) {
                    spawn_animated_sprite((collision_box_a_left + sprite_rect_a_right) >> 1, (collision_box_a_top + sprite_bounds_a_bottom) >> 1, 0, 0, (int)spell_art_base, (int)racket_spell_animation_frames, 1);
                    remove_player_shot();
                    goto next_player_shot; /* A hit removes this shot and skips its remaining update. */
                }
            }
            moving_target_cursor++;
        }
        tile_hit = 0;
        row_y = (collision_box_a_top + sprite_bounds_a_bottom) >> 1;
        if (row_y >= BRICK_FIELD_TOP && row_y <= BRICK_FIELD_BOTTOM) {
            if (sprite_rect_a_right < BRICK_TILE_WIDTH || collision_box_a_left > BRICK_FIELD_RIGHT_EDGE) goto queue_player_shot_draw; /* Queue the shot draw without checking bonus_stage_brick_counts. */
            cell_cursor = (struct BrickCell *)brick_code_map;
            first_column = (collision_box_a_left - BRICK_TILE_WIDTH) >> BRICK_COLUMN_SHIFT;
            last_column = (sprite_rect_a_right - BRICK_TILE_WIDTH) >> BRICK_COLUMN_SHIFT;
            row_offset = ((row_y - BRICK_FIELD_TOP) >> BRICK_ROW_SHIFT) * BRICK_COLUMNS_PER_ROW;
            if (first_column < 0) {
                first_column = 0;
            }
            if (last_column > BRICK_LAST_COLUMN) {
                last_column = BRICK_LAST_COLUMN;
            }
            if (row_offset > 0x10e) {
                row_offset = 0x10e;
            }
            cell_cursor += row_offset;
            for (row_y = first_column; row_y <= last_column; row_y++) {
                current_brick_code = cell_cursor[row_y].tile_code;
                if (current_brick_code == BRICK_TILE_PORTAL_ENTRY) {
                    player_shot_cursor->x += portal_exit_xpos - portal_start_x;
                    player_shot_cursor->y += (portal_destination_y - portal_y_source) - 8;
                    row_y = last_column;
                } else if (current_brick_code == BRICK_TILE_PORTAL_EXIT) {
                    player_shot_cursor->x += portal_start_x - portal_exit_xpos;
                    player_shot_cursor->y += (portal_y_source - portal_destination_y) - 8;
                    row_y = last_column;
                } else if (current_brick_code && (player_shot_cursor->flags & PLAYER_SHOT_KIND_MASK) == PLAYER_SHOT_KIND_EXPLOSIVE) {
                    process_brick_hit(row_y, row_offset, 0, player_shot_cursor->vertical_speed);
                } else {
                    if (current_brick_code >= 1 && current_brick_code <= 0x90) {
                        if ((current_brick_code >= 1 && current_brick_code <= 0x10) || (current_brick_code >= 0x31 && current_brick_code <= 0x40) || (current_brick_code >= 0x61 && current_brick_code <= 0x70)) {
                            process_brick_hit(row_y, row_offset, 0, player_shot_cursor->vertical_speed);
                        } else {
                            current_brick_code -= 0x10;
                            cell_cursor[row_y].tile_code = current_brick_code;
                            draw_level_tile_on_pages(row_y, row_offset, current_brick_code);
                        }
                        play_audio_request_at(0xc, 0x19);
                        ptrbuf = (int)racket_spell_animation_frames;
                    } else {
                        if (current_brick_code < 0x91 || current_brick_code > 0x100) goto next_brick_column; /* Skip unsupported tile codes. */
                        if (current_brick_code >= 0xf5 && current_brick_code <= 0xf7) {
                            play_audio_request_at(0x2e, 0x32);
                            motion_dir = -1;
                            resize_racket();
                            ptrbuf = (int)spell_impact_animation_frames;
                        } else if (current_brick_code >= 0xfa && current_brick_code <= 0x100) {
                            play_audio_request_at(1, 9);
                            if (!--cell_cursor[row_y].drop_value) {
                                score_state->score += 2 << racket_object->reward_level;
                                queue_timed_level_change(current_brick_code, row_y + row_offset);
                                process_brick_hit(row_y, row_offset, 0, player_shot_cursor->vertical_speed);
                            }
                            ptrbuf = (int)racket_spell_animation_frames;
                        } else {
                            play_audio_request_at(0x2a, 0x2d);
                            ptrbuf = (int)spell_impact_animation_frames;
                        }
                    }
                    spawn_animated_sprite((row_y << 4) + 0x18, ((row_offset / 0x12) << 3) + 0x1c, 0, 0, (int)spell_art_base, ptrbuf, 1);
                    tile_hit = -1;
                    continue;
                }
next_brick_column:;
            }
            if (!tile_hit) goto queue_player_shot_draw; /* Fall through to the shared draw-record path. */
            remove_player_shot();
        } else {
queue_player_shot_draw:;
            image_buffer_cursor->sprite_or_frame = player_shot_cursor->sprite_offset;
            image_buffer_cursor->x = player_shot_cursor->x;
            image_buffer_cursor->y = player_shot_cursor->y;
            image_buffer_cursor->flags = 0;
            ++image_buffer_cursor;
            ++player_shot_cursor;
        }
next_player_shot:;
    }
}

void remove_player_shot(void)
{
    --player_shot_total;
    if (player_shot_index != player_shot_total)
        memcpy(player_shot_cursor, player_shot_cursor + 1, (player_shot_total - player_shot_index) * sizeof(*player_shot_cursor));
    --player_shot_index;
}

void spawn_player_shot(unsigned char shot_kind, int vertical_speed, int start_x, int start_y)
{
    if (player_shot_total < 0xc) {
        player_shot_cursor = player_shot_records;
        player_shot_cursor += player_shot_total;
        player_shot_cursor->x = start_x;
        player_shot_cursor->y = start_y;
        player_shot_cursor->vertical_speed = vertical_speed;
        switch (shot_kind) {
        case 0:
            temp = 0x21e6;
            submit_audio_request(0x5a);
            break;
        case 1:
            temp = 0x2280;
            submit_audio_request(0x58);
            break;
        case 2:
            temp = 0x2342;
            submit_audio_request(0x66);
        }
        player_shot_cursor->sprite_offset = (int)(spell_art_base + temp);
        ((struct PlayerShotKindBits *)&player_shot_cursor->flags)->f = shot_kind;
        ++player_shot_total;
    }
}
