unsigned char g_8e4c[864];
int g_94b0;
int g_94b4;
/* TU f_6b02..f_798c [0x6b02, 0x7bd5): generated by tools/tu.py */
typedef unsigned int size_t;
typedef struct { int a, b, c; short d; int e; } S18;
int g_94a0;
int g_94a4;
int g_94a8;
int g_94ac;

extern unsigned char g_67b4[];
extern short g_742c;
extern short g_746c_mmw;
extern short g_7b14;
extern short g_7b18;
extern short g_7b20;
extern short g_7b22;
extern short g_7b34_cbzosabe;
extern int g_7c08_orxezsknd;
extern unsigned char h_ab40_jbfxrqns[];
extern unsigned char g_bf40_whznxcth[];
extern unsigned char g_d340_schtgisj[];
extern int x_dd40_xbukycw;
extern int k_DD48_jbwjbqarofg;
extern unsigned char *g_dd4c_ilunphmaok;
struct VideoState { short state; unsigned char e326[16]; int e336[4]; int e346[4]; unsigned char e356[4]; int e35a; int e35e; int e362; int e366; int e36a; int e36e; int e372; int e376; int e37a; unsigned char e37e; unsigned char e37f; unsigned char e380; unsigned char e381; unsigned char e382; unsigned char e383; unsigned char e384; unsigned char e385; unsigned char e386; unsigned char tail; };
extern struct VideoState g_e324;
void f_dfc3(void);
extern unsigned char g_e48b_3;
extern unsigned char g_e48e_0g;
extern short m_E4c4;
extern short g_e4c6;
int g_9490;
int g_9494;
int g_9498;
int g_949c;

extern int g_e4d0_wfmxdlyju;
extern void shutdown_with_exit_message(unsigned, unsigned);
extern void copy_screen_span_entry(int, int, int, int, int);
extern void handle_s_key(void);
extern void f_6156(void);
extern void f_61a6_vby(void);
extern void f_6e13(void);
extern int f_6e2e(void);
extern int f_6ee8(void);
extern void f_6f66(void);
extern void f_7032(void);
extern void f_704d(void);
extern void f_7068(void);
extern void f_7112_ngllzczwwhoqgnyg(void);
extern void f_7184(void);
extern void f_73c0(void);
extern void f_7532(void);
extern void f_798c(void);
extern void f_7bd5(void);
extern void f_7e62(int, int, int, int, int, int, int);
extern void f_9d40(unsigned char);
int g_9470;
int g_9474;
unsigned char *g_9478;
int g_947c;
int g_9480;
int g_9484;
int g_9488;
int g_948c;

extern void f_a810(void *, int);
extern void f_c20d(int);
extern void f_c8c0_pm(int, int, short, int, int);
extern void f_c9ce(int, int);
extern int f_dd53(int, int);
extern void f_ea9f(void *, int, int, int);
extern void f_ed38(void);
extern int g_7b0c;
extern int g_8e1c;
extern int g_8e20;
extern void f_ec76(void *);
extern unsigned char g_e13e;
extern unsigned char g_e13b;
extern unsigned char g_e46b;
extern void *r_dDDc_uzmlc;
void f_e028(void);
void f_e3e5(void);
int g_9468;
int g_946c;

extern unsigned char g_6884[];
extern short g_7b24;
extern short g_7b26;
extern short g_7b16;
extern short g_7b1a;
extern unsigned short g_7bfe;
extern unsigned short g_7c00;
extern short g_e4a8;
extern short n_e4c2;
extern void f_10369(void);
extern void f_103b9(void);
void f_80d8(void);
void f_843a(void);
extern unsigned char read_vga_pixel_entry(int, int);
extern int g_dd84;
extern int g_dd88;
extern int g_dDa8;
extern int c_DDAC;
extern char *g_dd6c;
extern char *g_ddb4;
extern char g_df78[];
extern void f_7551(void);
extern void f_7bf4(void);
unsigned char g_91ac[700];

extern void f_85a4(void);
extern void f_100fa(int, int, int, int);
extern void f_10502(int, int);
extern void f_10137_squghx(void);
void *memmove(void *, const void *, size_t);
void f_788d(void);
void f_7e12(void);
void f_8585(void);
void f_8f7e(void);
void f_8fce(int x, int y);
extern short g_e4ba;
extern short g_e4bc;
extern int fill_clipped_vga_rectangle(int, int, int, int, int, int);
extern void write_dac_palette(void *, int, int, int);
extern int g_68f4;
extern unsigned char *g_e2ec;
extern unsigned char g_6864[];
extern void f_78dd(int, int, int, int, int, int, int);
extern int f_b17e(void *, void *);
extern int f_b76c(S18, int, int, S18, int, int, int, int, int, int);
void *memcpy(void *, const void *, size_t);
extern unsigned char g_687c[];

/* file names of the game data */
/* _DATA [0x68f8,0x6984) */
char *g_68f8_jwwqkwr = "ke_all.pal";
char *g_68fc_ifhyqlddj = "ke_tit.gif";
char *g_6900 = "ke_tit.dig";
char *g_6904 = "ke_menu.gif";
char *g_6908 = "ke_menu.bob";
char *g_690c = "ke_menu.dig";
char *g_6910 = "ke_order.gif";
char *g_6914 = "ke_menu.bob";
char *g_6918 = "ke_score.gif";
char *g_691c = "ke_font.bob";
char *g_6920 = "ke_score.dig";
char *g_6924 = "ke_score.lst";
char *g_6928 = "ke_score.gif";
char *g_692c = "ke_font.bob";
char *g_6930 = "ke_end.dig";
char *g_6934 = "ke_score.gif";
char *g_6938 = "ke_font.bob";
char *g_693c = "ke_infos.dig";
char *g_6940_hqhettu = "ke_brick.bob";
char *g_6944_bdcftta = "ke_spell.bob";
char *g_6948_kxwrlv = "ke_nmy.bob";
char *g_694c_wjufexbevsk = "ke_rack.bob";
char *g_6950 = "ke_fill.bob";
char *g_6954 = "ke_font.bob";
char *g_6958_vghgxtjirow = "ke_digit.bob";
char *g_695c_qurvlwasjp = "ke_monst.bob";
char *g_6960_juobaluykyr = "ke_monst.gif";
char *g_6964 = "ke_main.dig";
char *g_6968 = "ke_lvl.dig";
char *g_696c = "ke_go.dig";
char *g_6970 = "ke_pause.dig";
char *g_6974 = "ke_pub.dig";
char *g_6978 = "ke_pub1.gif";
char *g_697c = "ke_pub2.gif";
char *g_6980 = "ke_pub3.gif";

int f_6b02(void)
{
    g_9468 = 0x118;
    g_9484 = 0;
    g_947c = g_e324.e37a;
    g_e324.e37a = 0xa6;
    f_ea9f((void *)x_dd40_xbukycw, 0, 0x3f, 8);
    g_e4d0_wfmxdlyju = g_7c08_orxezsknd;
    f_6156();
    f_61a6_vby();
    *(unsigned char *)&g_7b34_cbzosabe &= 0xf8;
    f_c8c0_pm((int)g_d340_schtgisj, 0x100, 4, (int)h_ab40_jbfxrqns, (int)g_bf40_whznxcth);
    f_7112_ngllzczwwhoqgnyg();
    f_7032();
    f_704d();
    f_7068();
    f_9d40(0);
    f_9d40(0);
    f_a810((void *)k_DD48_jbwjbqarofg, g_7b18);
    copy_screen_span_entry(g_7b18, 0, g_7b20, 0, g_e324.e35a);
    copy_screen_span_entry(g_7b18, 0, g_7b22, 0, g_e324.e35a);
    g_7b14 = g_7b18;
    f_6f66();
    f_798c();
    f_73c0();
    f_ea9f((void *)x_dd40_xbukycw, 0x3f, 0, 1);
L_6c3d:;
    f_9d40(3);
    f_7184();
    handle_s_key();
    f_798c();
    f_7532();
    f_73c0();
    f_7bd5();
    f_c9ce(0, 0);
    if (g_746c_mmw == 0) goto L_6c91;
    shutdown_with_exit_message(g_746c_mmw, 0);
L_6c91:;
    f_ed38();
    if (g_94a8 <= 0) goto L_6cac;
    if (g_9490 > 0) goto L_6db7;
L_6cac:;
    --g_9468;
    --g_9470;
    if (g_9470 > 0) goto L_6db7;
    if (g_94a8 > 0) goto L_6d4d;
    if (g_742c != 0) goto L_6ce6;
    f_c20d(0x6b);
L_6ce6:;
    g_9470 = 0;
L_6cf0:;
    if (g_9470 < 2) goto L_6d03;
    goto L_6d41;
L_6cfb:;
    ++g_9470;
    goto L_6cf0;
L_6d03:;
    f_7e62(f_dd53(-0x1e, 0x1e) + 0x106, f_dd53(-0x1e, 0x1e) + 0x56, 0, 0, (int)g_dd4c_ilunphmaok, (int)g_67b4, 1);
    goto L_6cfb;
L_6d41:;
    g_9470 = 8;
    goto L_6db7;
L_6d4d:;
    if (g_742c != 0) goto L_6d61;
    f_c20d(0x6a);
L_6d61:;
    f_7e62(f_dd53(-0x10, 0x10) + (g_e4c6 + 4), (m_E4c4 + 8) + f_dd53(-0x10, 0x10), 0, 0, (int)g_dd4c_ilunphmaok, (int)g_67b4, 1);
    g_9470 = 0x19;
L_6db7:;
    if (g_94a8 > 0) goto L_6dc9;
    if (g_9468 <= 0) goto L_6dcb;
L_6dc9:;
    goto L_6dda;
L_6dcb:;
    f_6e13();
    return f_6ee8();
L_6dda:;
    if (g_9468 <= 0) goto L_6dfe;
    if (g_e48b_3 == g_e48e_0g) goto L_6df9;
    if (g_e48e_0g == 1) goto L_6dfe;
L_6df9:;
    goto L_6c3d;
L_6dfe:;
    f_6e13();
    return f_6e2e();
}

void f_6e13(void) { g_e324.e37a = g_947c; }

int f_6e2e(void)
{
    f_c20d(0xb);
    g_7b0c = 2;
    g_8e1c = 0;
L_6e58:;
    if (g_8e1c < 0x3f) goto L_6e6e;
    goto L_6ecf;
L_6e66:;
    ++g_8e1c;
    goto L_6e58;
L_6e6e:;
    g_8e20 = 0;
L_6e78:;
    if (g_8e20 < 0x300) goto L_6e8f;
    goto L_6eb1;
L_6e86:;
    g_8e20 += 3;
    goto L_6e78;
L_6e8f:;
    if (++*(unsigned char *)(unsigned char *)(x_dd40_xbukycw + g_8e20) <= 0x3f) goto L_6eaf;
    *(unsigned char *)(unsigned char *)(x_dd40_xbukycw + g_8e20) = 0x3f;
L_6eaf:;
    goto L_6e86;
L_6eb1:;
    f_ec76((void *)x_dd40_xbukycw);
    f_9d40(3);
    goto L_6e66;
L_6ecf:;
    g_7b0c = 1;
    return 0;
}

int f_6ee8(void)
{
    f_c20d(0x26);
    if (g_e13b == 0)
        *(int *)((unsigned char *)r_dDDc_uzmlc + 20) += (5000 / g_94a0) * g_9490 + 5000;
    g_7b0c = 3;
    f_ea9f(x_dd40_xbukycw, 0, -63, -1);
    g_7b0c = 1;
    return 1;
}

void f_6f66(void)
{
    int v_4;
    int v_8;
    int v_c;
    v_8 = 0;
L_6f79:;
    if (v_8 < 0xa6) goto L_6f8f;
    return;
L_6f87:;
    v_8++;
    goto L_6f79;
L_6f8f:;
    v_4 = 0xa0;
L_6f96:;
    if (v_4 < 0x140) goto L_6faa;
    goto L_7028;
L_6fa4:;
    v_4 += 2;
    goto L_6f96;
L_6faa:;
    v_c = (unsigned char)read_vga_pixel_entry(v_4, v_8);
    if (v_c < 0x18) goto L_6fcc;
    if (v_c <= 0x27) goto L_6fce;
L_6fcc:;
    goto L_6fdf;
L_6fce:;
    *(int *)(g_91ac + (v_8 << 2)) = v_4;
    goto L_7028;
L_6fdf:;
    if (v_c < 0x50) goto L_6feb;
    if (v_c <= 0x58) goto L_6fed;
L_6feb:;
    goto L_6ffe;
L_6fed:;
    *(int *)(g_91ac + (v_8 << 2)) = v_4;
    goto L_7028;
L_6ffe:;
    if (v_c < 0x90) goto L_7010;
    if (v_c <= 0xa7) goto L_7012;
L_7010:;
    goto L_7023;
L_7012:;
    *(int *)(g_91ac + (v_8 << 2)) = v_4;
    goto L_7028;
L_7023:;
    goto L_6fa4;
L_7028:;
    goto L_6f87;
}

void f_7032(void) { g_9488 = 0; }

void f_704d(void) { g_dd84 = 0; }

void f_7068(void)
{
    g_94a4 = *(int *)(g_6884 + (g_e13e << 4));
    g_94a8 = g_94a4;
    g_9494 = g_94a8;
    g_94ac = *(int *)(g_6884 + 4 + ((g_e13e << 2) << 2));
    g_946c = *(int *)(g_6884 + 8 + ((g_e13e << 2) << 2));
    g_948c = g_946c;
    g_949c = *(int *)(g_6884 + 12 + ((g_e13e << 2) << 2));
    g_94b4 = 0;
    g_9498 = 7;
    g_9474 = 0xf;
}

void f_7112_ngllzczwwhoqgnyg(void)
{
    f_100fa(4, 16, 4, 0x95);
    f_10502(4, 0x52);
    for (g_8e20 = 0; g_8e20 < 4; ++g_8e20)
        f_10137_squghx();
    g_94a0 = 100;
    g_9490 = g_94a0;
    g_94b0 = g_9490;
}

void f_7184(void)
{
    if (g_9490 > 0) goto L_71cb;
    g_9490 = 0;
    f_100fa(g_e4ba, g_e4bc, g_e4ba, g_e4bc);
L_71cb:;
    if (g_9490 == g_94b0) goto L_72c0;
    g_94b0 = g_9490;
    g_e324.e37a = g_947c;
    fill_clipped_vga_rectangle(g_7b16, ((g_9490 * 0x6f) / g_94a0) + 0x1c, 0xb3, 0x8b, 0xb9, 0);
    fill_clipped_vga_rectangle(g_7b14, ((g_9490 * 0x6f) / g_94a0) + 0x1c, 0xb3, 0x8b, 0xb9, 0);
    g_e324.e37a = 0xa6;
    g_8e20 = 0;
L_7272:;
    if (g_8e20 < 0x300) goto L_7289;
    goto L_72ac;
L_7280:;
    g_8e20 += 3;
    goto L_7272;
L_7289:;
    if ((*(unsigned char *)(unsigned char *)(x_dd40_xbukycw + g_8e20) += 3) <= 0x3f) goto L_72aa;
    *(unsigned char *)(unsigned char *)(x_dd40_xbukycw + g_8e20) = 0x3f;
L_72aa:;
    goto L_7280;
L_72ac:;
    g_9484 = 1;
    f_c20d(0x69);
L_72c0:;
    if (g_94a8 == g_9494) goto L_738f;
    if (g_94a8 >= 0) goto L_72ee;
    g_94a8 = 0;
    g_94b4 = 0x1388;
L_72ee:;
    g_9494 = g_94a8;
    g_e324.e37a = g_947c;
    fill_clipped_vga_rectangle(g_7b16, ((g_94a8 * 0x6f) / g_94a4) + 0xb4, 0xb3, 0x123, 0xb9, 0);
    fill_clipped_vga_rectangle(g_7b14, ((g_94a8 * 0x6f) / g_94a4) + 0xb4, 0xb3, 0x123, 0xb9, 0);
    g_e324.e37a = 0xa6;
    g_9484 += 8;
    f_c20d(0x25);
L_738f:;
    if (g_9484 <= 0) goto L_73bb;
    write_dac_palette((void *)x_dd40_xbukycw, 0, 0x100, -g_9484);
    --g_9484;
L_73bb:;
}

void f_73c0(void)
{
    if (g_9490 <= 0) goto bottom;
    if (g_68f4 != 0) goto reset_gate;
    if (g_7bfe == 3) goto reset_gate;
    goto first_compare;
reset_gate:
    goto reset_flag;
first_compare:
    if (g_7bfe == g_7c00) goto second_gate;
    if ((g_7bfe & 1) == 1) goto first_side;
second_gate:
    goto second_side;
first_side:
    f_c20d(0x66);
    f_78dd(0, 4, g_e4c6, m_E4c4, 0x40, 0, (int)g_6864);
    g_e4ba -= 7;
    g_68f4 = 1;
    goto second_exit;
second_side:
    if (g_7bfe == g_7c00) goto second_skip;
    if (g_7bfe & 2) goto second_actions;
second_skip:
    goto second_exit;
second_actions:
    f_c20d(0x66);
    f_78dd(0, 1, g_e4c6, m_E4c4, 0x60, 0x18, (int)g_6864);
    f_78dd(0, 1, g_e4c6, m_E4c4, 0x60, -0x18, (int)g_6864);
    g_e4ba -= 7;
    g_68f4 = 1;
second_exit:
    goto bottom;
reset_flag:
    g_68f4 = 0;
bottom:
    *(int *)g_e2ec = (int)(g_dd4c_ilunphmaok + 0x35d6);
    *(short *)(g_e2ec + 4) = g_e4c6;
    *(short *)(g_e2ec + 6) = m_E4c4;
    *(short *)(g_e2ec + 8) = 0;
    g_e2ec += 10;
}

void f_7532(void) { if (g_9488) f_7551(); }

void f_7551(void)
{
    S18 *v_4;
    S18 *v_8;
    g_9478 = g_8e4c;
    g_9480 = 0;
L_7571:;
    if (g_9480 < g_9488) goto L_758b;
    return;
L_7583:;
    ++g_9480;
    goto L_7571;
L_758b:;
    *(int *)(g_9478 + 4) += *(int *)(g_9478 + 0xc);
    *(int *)(g_9478 + 8) += *(int *)(g_9478 + 0x10);
    f_b17e(g_9478 + 0x18, g_9478 + 0x1c);
    v_8 = (S18 *)(*(int *)*(unsigned char * *)(g_9478 + 0x1c) + *(unsigned char * *)(g_9478 + 0x14));
    if ((*(int *)(g_9478 + 4) >> 4) > 0x150) goto L_7600;
    if ((*(int *)(g_9478 + 4) >> 4) >= -0x10) goto L_7602;
L_7600:;
    goto L_7614;
L_7602:;
    if ((*(int *)(g_9478 + 8) >> 4) <= 0xd8) goto L_7616;
L_7614:;
    goto L_7626;
L_7616:;
    if ((*(int *)(g_9478 + 8) >> 4) >= -0x10) goto L_7630;
L_7626:;
    f_788d();
    goto L_7583;
L_7630:;
    if (*(int *)g_9478 != 0) goto L_7771;
    v_4 = (S18 *)(g_dd4c_ilunphmaok + 0x395c);
    if (f_b76c(*v_4, 0xf6, 0x46,
               *v_8,
               *(int *)(g_9478 + 4) >> 4, *(int *)(g_9478 + 8) >> 4,
               0xa, 0, 0xa, 0) != -1) goto L_7701;
    g_94a8 -= *(int *)(g_9478 + 0x20);
    f_7e62(*(int *)(g_9478 + 4) >> 4, *(int *)(g_9478 + 8) >> 4, *(int *)(g_9478 + 0xc) >> 6, *(int *)(g_9478 + 0x10) >> 6, (int)g_dd4c_ilunphmaok, (int)g_67b4, 1);
    f_788d();
    goto L_7583;
L_7701:;
    if (((*(int *)(g_9478 + 4) >> 4) + 5) <= *(int *)(g_91ac + ((*(int *)(g_9478 + 8) >> 4) << 2))) goto L_776c;
    f_c20d(0x57);
    f_7e62(*(int *)(g_9478 + 4) >> 4, *(int *)(g_9478 + 8) >> 4, 0, 0, (int)g_dd4c_ilunphmaok, (int)g_67b4, 1);
    f_788d();
    goto L_7583;
L_776c:;
    goto L_7835;
L_7771:;
    v_4 = (S18 *)(g_dd4c_ilunphmaok + 0x35d6);
    if (f_b76c(*v_4,
               g_e4c6, m_E4c4,
               *v_8,
               (*(int *)(g_9478 + 4) >> 4) + 8, *(int *)(g_9478 + 8) >> 4,
               4, 4, 4, 4) != -1) goto L_7835;
    if (g_9490 <= 0) goto L_77f9;
    g_9490 -= *(int *)(g_9478 + 0x20);
L_77f9:;
    f_7e62(*(int *)(g_9478 + 4) >> 4, *(int *)(g_9478 + 8) >> 4, 0, 0, (int)g_dd4c_ilunphmaok, (int)g_67b4, 1);
    f_788d();
    goto L_7583;
L_7835:;
    *(int *)g_e2ec = v_8;
    *(short *)(g_e2ec + 4) = (unsigned short)(*(int *)(g_9478 + 4) >> 4);
    *(short *)(g_e2ec + 6) = (unsigned short)(*(int *)(g_9478 + 8) >> 4);
    *(short *)(g_e2ec + 8) = 0;
    g_e2ec += 0xa;
    g_9478 += 0x24;
    goto L_7583;
}

void f_788d(void)
{
    --g_9488;
    if (g_9480 != g_9488)
        memcpy(g_9478, g_9478 + 0x24, (g_9488 - g_9480) * 0x24);
    --g_9480;
}

void f_78dd(int a, int b, int x, int y, int c, int d, int e)
{
    if (g_9488 < 0x18) {
        g_9478 = g_8e4c;
        g_9478 += g_9488 * 0x24;
        *(int *)(g_9478 + 0) = a;
        *(int *)(g_9478 + 0x20) = b;
        *(int *)(g_9478 + 4) = x << 4;
        *(int *)(g_9478 + 8) = y << 4;
        *(int *)(g_9478 + 12) = c;
        *(int *)(g_9478 + 16) = d;
        *(int *)(g_9478 + 24) = 0;
        *(int *)(g_9478 + 28) = e - 8;
        *(int *)(g_9478 + 20) = (int)g_dd4c_ilunphmaok;
        ++g_9488;
    }
}

void f_798c(void)
{
    int v_4;
    int v_8;
    int v_c;
    int v_10;
    int v_14;
    v_4 = 0xf6;
    v_8 = 0x56;
    v_14 = 0;
    if (g_94a8 <= 0) goto L_7b95;
    --g_94b4;
    if (g_94b4 > 0) goto L_7af8;
    *(int *)g_e2ec = (int)(g_dd4c_ilunphmaok + 0x43b6);
    *(short *)(g_e2ec + 4) = 0xf6;
    *(short *)(g_e2ec + 6) = 0x46;
    *(short *)(g_e2ec + 8) = 0;
    g_e2ec += 0xa;
    v_14 = 1;
    --g_9498;
    if (g_9498 > 0) goto L_7af8;
    g_9498 = 7;
    v_c = ((g_e4c6 - v_4) << 4) / 0x28;
    v_10 = ((f_dd53(-0x1e, 0x1e) + (m_E4c4 - v_8)) << 4) / 0x28;
    f_78dd(1, g_94ac, v_4, v_8, v_c, v_10, (int)g_687c);
    if (g_9490 <= 0) goto L_7aaf;
    f_c20d(0x58);
L_7aaf:;
    --g_948c;
    if (g_948c > 0) goto L_7af8;
    g_949c -= 2;
    g_94b4 = g_949c;
    g_948c = g_946c;
    --g_9474;
    if (g_9474 > 0) goto L_7af8;
    ++g_946c;
    g_9474 = 0xf;
L_7af8:;
    if (v_14 != 0) goto L_7b93;
    if (g_94b4 < 0xf) goto L_7b1b;
    if ((g_949c - 0x14) >= g_94b4) goto L_7b58;
L_7b1b:;
    *(int *)g_e2ec = (int)(g_dd4c_ilunphmaok + 0x3e70);
    *(short *)(g_e2ec + 4) = 0xf6;
    *(short *)(g_e2ec + 6) = 0x46;
    *(short *)(g_e2ec + 8) = 0;
    g_e2ec += 0xa;
    goto L_7b93;
L_7b58:;
    *(int *)g_e2ec = (int)(g_dd4c_ilunphmaok + 0x395c);
    *(short *)(g_e2ec + 4) = 0xf6;
    *(short *)(g_e2ec + 6) = 0x46;
    *(short *)(g_e2ec + 8) = 0;
    g_e2ec += 0xa;
L_7b93:;
    return;
L_7b95:;
    *(int *)g_e2ec = (int)(g_dd4c_ilunphmaok + 0x43b6);
    *(short *)(g_e2ec + 4) = 0xf6;
    *(short *)(g_e2ec + 6) = 0x46;
    *(short *)(g_e2ec + 8) = 0;
    g_e2ec += 0xa;
}
