struct AuxiliaryProjectile { int target_type, x, y, velocity_x, velocity_y; unsigned char *sprite_data; void *frame_info; unsigned char *frame_offset; int damage; };
struct AuxiliaryProjectile auxiliary_projectiles[24];
int last_displayed_time;
int enemy_attack_timer;
/* TU run_level..update_enemy_attack_cycle [0x6b02, 0x7bd5): generated by tools/tu.py */
typedef unsigned int size_t;
typedef struct { int a, b, c; short d; int e; } S18;
int total_level_time;
int enemy_max_health;
int enemy_health_current;
int enemy_pattern;

extern unsigned char bolt_impact_animation_frames[];
extern short audio_stream_flag;
extern short image_buffer_error_code;
extern short page_idx;
extern short page2;
extern short src_page;
extern short dst_page;
extern short hook_flags_word;
extern int file_error_state;
extern unsigned char frnt_pg_upd_buf[];
extern unsigned char back_pg_upd_buf[];
extern unsigned char sprite_commands[];
extern int vga_buffer_base;
extern int sprite_memory_base;
extern unsigned char *game_sprite_base;
struct DisplayModeInfo { short state; unsigned char plane_addresses[16]; int page_offsets[4]; int page_adjustments[4]; unsigned char page_mode_classes[4]; int buffer_size; int row_stride_bytes; int resolution_height; int width; int height; int left; int top; int right; int bottom; unsigned char mode_flags; unsigned char e37f; unsigned char e380; unsigned char video_mode_low; unsigned char e382; unsigned char e383; unsigned char e384; unsigned char e385; unsigned char e386; unsigned char tail; };
extern struct DisplayModeInfo vga_state;
void save_bios(void);
extern unsigned char current_scan_code;
extern unsigned char keyboard_scan_byte;
extern short mouse_y_mean_recent;
extern short mouse_x_average_recent;
int remaining_level_time;
int last_displayed_enemy_health;
int attack_frame_count;
int attack_delay;

extern int g_e4d0_wfmxdlyju;
extern void fatal_exit(unsigned, unsigned);
extern void copy_screen_span_entry(int, int, int, int, int);
extern void handle_s_key(void);
extern void load_monster_art(void);
extern void prep_brick(void);
extern void restore_gameplay_display_mode(void);
extern int fade_level_to_white(void);
extern int award_level_completion_bonus(void);
extern void scan(void);
extern void clr_bc(void);
extern void clr_sp(void);
extern void set_lc(void);
extern void initialize_level_hud(void);
extern void update_level_hud(void);
extern void upd_sh(void);
extern void update_auxiliary_projectiles(void);
extern void update_enemy_attack_cycle(void);
extern void upd_ani(void);
extern void spawn_animated_sprite(int, int, int, int, int, int, int);
extern void f_9d40(unsigned char);
int enemy_shot_countdown;
int enemy_fire_acceleration;
struct AuxiliaryProjectile *bolt_cursor;
int old_display_mode;
int projectile_index;
int hud_flash_ticks;
int enemy_projectile_count;
int attack_cooldown;

extern void plot_transformed_pixel(void *, int);
extern void submit_audio_request(int);
extern void set_image_pages(int, int, short, int, int);
extern void redraw_image_region(int, int);
extern int random_in_range(int, int);
extern void fade_dac(void *, int, int, int);
extern void show_page(void);
extern int palette_fade_delay_ticks;
extern int work_value;
extern int temp;
extern void write_vga_palette(void *);
extern unsigned char difficulty_tier_index;
extern unsigned char arcade;
extern unsigned char g_e46b;
extern void *racket_state;
void restore_bios(void);
void save_vga_state(void);
int level_intro_ticks;
int enemy_attack_interval;

extern unsigned char gameplay_tuning_by_stage[];
extern short stored_page_2_index;
extern short page_3;
extern short drawpage;
extern short page3;
extern unsigned short mouse_btn;
extern unsigned short mouse_btn_old;
extern short x_cursor_sensitivity;
extern short mouse_sensitivity_y_axis;
extern void query_mouse_sensitivity(void);
extern void restore_mouse_driver_sensitivity(void);
void rkt_mv(void);
void set_pg(void);
extern unsigned char read_vga_pixel_entry(int, int);
extern int sprite_instance_count;
extern int sprite_removal_index;
extern int current_ball_count;
extern int game_ball_slot;
extern char *sprite_current;
extern char *current_ball_pointer;
extern char game_balls[];
extern void move_auxiliary_projectiles(void);
extern void draw_animated_sprites(void);
unsigned char open_brick_x_by_row[700];

extern void update_game_balls(void);
extern void set_mouse_bounds(int, int, int, int);
extern void move_mouse_to(int, int);
extern void update_mouse(void);
void *memmove(void *, const void *, size_t);
void remove_auxiliary_projectile(void);
void remove_animated_sprite(void);
void upd_bl(void);
void remove_game_ball(void);
void spawn_game_ball(int x, int y);
extern short history_mouse_x_0;
extern short mouse_y_sample_0;
extern int fill_clipped_vga_rectangle(int, int, int, int, int, int);
extern void write_dac_palette(void *, int, int, int);
extern int player_shot_button_latch;
extern unsigned char *image_buffer_cursor;
extern unsigned char player_projectile_animation_frames[];
extern void spawn_auxiliary_projectile(int, int, int, int, int, int, int);
extern int next_packed_table_value(void *, void *);
extern int frames_intersect_inset(S18, int, int, S18, int, int, int, int, int, int);
void *memcpy(void *, const void *, size_t);
extern unsigned char enemy_projectile_animation_frames[];

/* file names of the game data */
/* _DATA [0x68f8,0x6984) */
char *main_palette_fn = "ke_all.pal";
char *title_image_file = "ke_tit.gif";
char *title_data_filename = "ke_tit.dig";
char *menu_image_filename = "ke_menu.gif";
char *menu_sprite_filename = "ke_menu.bob";
char *menu_data_filename = "ke_menu.dig";
char *order_image_filename = "ke_order.gif";
char *order_sprite_filename = "ke_menu.bob";
char *score_image_filename = "ke_score.gif";
char *font_sprite_filename = "ke_font.bob";
char *score_data_filename = "ke_score.dig";
char *high_score_filename = "ke_score.lst";
char *score_background_filename = "ke_score.gif";
char *score_font_filename = "ke_font.bob";
char *end_screen_data_filename = "ke_end.dig";
char *scoref = "ke_score.gif";
char *end_fn = "ke_font.bob";
char *information_data_filename = "ke_infos.dig";
char *brick_sprite_fn = "ke_brick.bob";
char *spell_sprite_fn = "ke_spell.bob";
char *foe_sprite_fn = "ke_nmy.bob";
char *racket_sprite_filename = "ke_rack.bob";
char *fill_sprite_filename = "ke_fill.bob";
char *game_font_filename = "ke_font.bob";
char *digit_sprite_filename = "ke_digit.bob";
char *monster_sprite_filename = "ke_monst.bob";
char *monster_anim_fname = "ke_monst.gif";
char *main_screen_data_filename = "ke_main.dig";
char *level_screen_data_filename = "ke_lvl.dig";
char *game_over_data_filename = "ke_go.dig";
char *pause_screen_data_filename = "ke_pause.dig";
char *publisher_data_filename = "ke_pub.dig";
char *publisher_image_one_filename = "ke_pub1.gif";
char *publisher_image_two_filename = "ke_pub2.gif";
char *publisher_image_three_filename = "ke_pub3.gif";

int run_level(void)
{
    level_intro_ticks = 0x118;
    hud_flash_ticks = 0;
    old_display_mode = vga_state.bottom;
    vga_state.bottom = 0xa6;
    fade_dac((void *)vga_buffer_base, 0, 0x3f, 8);
    g_e4d0_wfmxdlyju = file_error_state;
    load_monster_art();
    prep_brick();
    *(unsigned char *)&hook_flags_word &= 0xf8;
    set_image_pages((int)sprite_commands, 0x100, 4, (int)frnt_pg_upd_buf, (int)back_pg_upd_buf);
    initialize_level_hud();
    clr_bc();
    clr_sp();
    set_lc();
    f_9d40(0);
    f_9d40(0);
    plot_transformed_pixel((void *)sprite_memory_base, page2);
    copy_screen_span_entry(page2, 0, src_page, 0, vga_state.buffer_size);
    copy_screen_span_entry(page2, 0, dst_page, 0, vga_state.buffer_size);
    page_idx = page2;
    scan();
    update_enemy_attack_cycle();
    upd_sh();
    fade_dac((void *)vga_buffer_base, 0x3f, 0, 1);
    do {
        f_9d40(3);
        update_level_hud();
        handle_s_key();
        update_enemy_attack_cycle();
        update_auxiliary_projectiles();
        upd_sh();
        upd_ani();
        redraw_image_region(0, 0);
        if (image_buffer_error_code) {
            fatal_exit(image_buffer_error_code, 0);
        }
        show_page();
        if (enemy_health_current <= 0 || remaining_level_time <= 0) {
            --level_intro_ticks;
            --enemy_shot_countdown;
            if (enemy_shot_countdown <= 0) {
                if (enemy_health_current <= 0) {
                    if (!audio_stream_flag) {
                        submit_audio_request(0x6b);
                    }
                    for (enemy_shot_countdown = 0; enemy_shot_countdown < 2; ++enemy_shot_countdown) {
                        spawn_animated_sprite(random_in_range(-0x1e, 0x1e) + 0x106, random_in_range(-0x1e, 0x1e) + 0x56, 0, 0, (int)game_sprite_base, (int)bolt_impact_animation_frames, 1);
                    }
                    enemy_shot_countdown = 8;
                } else {
                    if (!audio_stream_flag) {
                        submit_audio_request(0x6a);
                    }
                    spawn_animated_sprite(random_in_range(-0x10, 0x10) + (mouse_x_average_recent + 4), (mouse_y_mean_recent + 8) + random_in_range(-0x10, 0x10), 0, 0, (int)game_sprite_base, (int)bolt_impact_animation_frames, 1);
                    enemy_shot_countdown = 0x19;
                }
            }
        }
        if (enemy_health_current <= 0 && level_intro_ticks <= 0) {
            restore_gameplay_display_mode();
            return award_level_completion_bonus();
        }
    } while (level_intro_ticks > 0 && (current_scan_code == keyboard_scan_byte || keyboard_scan_byte != 1));
    restore_gameplay_display_mode();
    return fade_level_to_white();
}

void restore_gameplay_display_mode(void) { vga_state.bottom = old_display_mode; }

int fade_level_to_white(void)
{
    submit_audio_request(0xb);
    palette_fade_delay_ticks = 2;
    for (work_value = 0; work_value < 0x3f; ++work_value) {
        for (temp = 0; temp < 0x300; temp += 3) {
            if (++*(unsigned char *)(unsigned char *)(vga_buffer_base + temp) > 0x3f)
                *(unsigned char *)(unsigned char *)(vga_buffer_base + temp) = 0x3f;
        }
        write_vga_palette((void *)vga_buffer_base);
        f_9d40(3);
    }
    palette_fade_delay_ticks = 1;
    return 0;
}

int award_level_completion_bonus(void)
{
    submit_audio_request(0x26);
    if (arcade == 0)
        *(int *)((unsigned char *)racket_state + 20) += (5000 / total_level_time) * remaining_level_time + 5000;
    palette_fade_delay_ticks = 3;
    fade_dac(vga_buffer_base, 0, -63, -1);
    palette_fade_delay_ticks = 1;
    return 1;
}

void scan(void)
{
    int screen_x;
    int screen_y;
    int tile_code;
    for (screen_y = 0; screen_y < 0xa6; screen_y++) {
        for (screen_x = 0xa0; screen_x < 0x140; screen_x += 2) {
            tile_code = (unsigned char)read_vga_pixel_entry(screen_x, screen_y);
            if (tile_code >= 0x18 && tile_code <= 0x27) {
                *(int *)(open_brick_x_by_row + (screen_y << 2)) = screen_x;
                break;
            }
            if (tile_code >= 0x50 && tile_code <= 0x58) {
                *(int *)(open_brick_x_by_row + (screen_y << 2)) = screen_x;
                break;
            }
            if (tile_code >= 0x90 && tile_code <= 0xa7) {
                *(int *)(open_brick_x_by_row + (screen_y << 2)) = screen_x;
                break;
            }
        }
    }
}

void clr_bc(void) { enemy_projectile_count = 0; }

void clr_sp(void) { sprite_instance_count = 0; }

void set_lc(void)
{
    enemy_max_health = *(int *)(gameplay_tuning_by_stage + (difficulty_tier_index << 4));
    enemy_health_current = enemy_max_health;
    last_displayed_enemy_health = enemy_health_current;
    enemy_pattern = *(int *)(gameplay_tuning_by_stage + 4 + ((difficulty_tier_index << 2) << 2));
    enemy_attack_interval = *(int *)(gameplay_tuning_by_stage + 8 + ((difficulty_tier_index << 2) << 2));
    attack_cooldown = enemy_attack_interval;
    attack_delay = *(int *)(gameplay_tuning_by_stage + 12 + ((difficulty_tier_index << 2) << 2));
    enemy_attack_timer = 0;
    attack_frame_count = 7;
    enemy_fire_acceleration = 0xf;
}

void initialize_level_hud(void)
{
    set_mouse_bounds(4, 16, 4, 0x95);
    move_mouse_to(4, 0x52);
    for (temp = 0; temp < 4; ++temp)
        update_mouse();
    total_level_time = 100;
    remaining_level_time = total_level_time;
    last_displayed_time = remaining_level_time;
}

void update_level_hud(void)
{
    if (remaining_level_time <= 0) {
        remaining_level_time = 0;
        set_mouse_bounds(history_mouse_x_0, mouse_y_sample_0, history_mouse_x_0, mouse_y_sample_0);
    }
    if (remaining_level_time != last_displayed_time) {
        last_displayed_time = remaining_level_time;
        vga_state.bottom = old_display_mode;
        fill_clipped_vga_rectangle(drawpage, ((remaining_level_time * 0x6f) / total_level_time) + 0x1c, 0xb3, 0x8b, 0xb9, 0);
        fill_clipped_vga_rectangle(page_idx, ((remaining_level_time * 0x6f) / total_level_time) + 0x1c, 0xb3, 0x8b, 0xb9, 0);
        vga_state.bottom = 0xa6;
        for (temp = 0; temp < 0x300; temp += 3) {
            if ((*(unsigned char *)(unsigned char *)(vga_buffer_base + temp) += 3) > 0x3f) {
                *(unsigned char *)(unsigned char *)(vga_buffer_base + temp) = 0x3f;
            }
        }
        hud_flash_ticks = 1;
        submit_audio_request(0x69);
    }
    if (enemy_health_current != last_displayed_enemy_health) {
        if (enemy_health_current < 0) {
            enemy_health_current = 0;
            enemy_attack_timer = 0x1388;
        }
        last_displayed_enemy_health = enemy_health_current;
        vga_state.bottom = old_display_mode;
        fill_clipped_vga_rectangle(drawpage, ((enemy_health_current * 0x6f) / enemy_max_health) + 0xb4, 0xb3, 0x123, 0xb9, 0);
        fill_clipped_vga_rectangle(page_idx, ((enemy_health_current * 0x6f) / enemy_max_health) + 0xb4, 0xb3, 0x123, 0xb9, 0);
        vga_state.bottom = 0xa6;
        hud_flash_ticks += 8;
        submit_audio_request(0x25);
    }
    if (hud_flash_ticks > 0) {
        write_dac_palette((void *)vga_buffer_base, 0, 0x100, -hud_flash_ticks);
        --hud_flash_ticks;
    }
}

void upd_sh(void)
{
    if (remaining_level_time > 0) {
        if (!player_shot_button_latch && mouse_btn != 3) {
            if (mouse_btn != mouse_btn_old && (mouse_btn & 1) == 1) {
                submit_audio_request(0x66);
                spawn_auxiliary_projectile(0, 4, mouse_x_average_recent, mouse_y_mean_recent, 0x40, 0, (int)player_projectile_animation_frames);
                history_mouse_x_0 -= 7;
                player_shot_button_latch = 1;
            } else if (mouse_btn != mouse_btn_old && mouse_btn & 2) {
                submit_audio_request(0x66);
                spawn_auxiliary_projectile(0, 1, mouse_x_average_recent, mouse_y_mean_recent, 0x60, 0x18, (int)player_projectile_animation_frames);
                spawn_auxiliary_projectile(0, 1, mouse_x_average_recent, mouse_y_mean_recent, 0x60, -0x18, (int)player_projectile_animation_frames);
                history_mouse_x_0 -= 7;
                player_shot_button_latch = 1;
            }
        } else {
            player_shot_button_latch = 0;
        }
    }
    *(int *)image_buffer_cursor = (int)(game_sprite_base + 0x35d6);
    *(short *)(image_buffer_cursor + 4) = mouse_x_average_recent;
    *(short *)(image_buffer_cursor + 6) = mouse_y_mean_recent;
    *(short *)(image_buffer_cursor + 8) = 0;
    image_buffer_cursor += 10;
}

void update_auxiliary_projectiles(void) { if (enemy_projectile_count) move_auxiliary_projectiles(); }

/* Move enemy bolts, test them against the racket and brick field, and draw survivors. */
void move_auxiliary_projectiles(void)
{
    S18 *target_bounds;
    S18 *shot_frame_info;
    bolt_cursor = auxiliary_projectiles;
    for (projectile_index = 0; projectile_index < enemy_projectile_count; ++projectile_index) {
        bolt_cursor->x += bolt_cursor->velocity_x;
        bolt_cursor->y += bolt_cursor->velocity_y;
        next_packed_table_value(&bolt_cursor->frame_info, &bolt_cursor->frame_offset);
        shot_frame_info = (S18 *)(*(int *)bolt_cursor->frame_offset + bolt_cursor->sprite_data);
        if ((bolt_cursor->x >> 4) > 0x150 || (bolt_cursor->x >> 4) < -0x10 || (bolt_cursor->y >> 4) > 0xd8 || (bolt_cursor->y >> 4) < -0x10) {
            remove_auxiliary_projectile();
            continue;
        }
        if (!bolt_cursor->target_type) {
            target_bounds = (S18 *)(game_sprite_base + 0x395c);
            if (frames_intersect_inset(*target_bounds, 0xf6, 0x46, *shot_frame_info, bolt_cursor->x >> 4, bolt_cursor->y >> 4, 0xa, 0, 0xa, 0) == -1) {
                enemy_health_current -= bolt_cursor->damage;
                spawn_animated_sprite(bolt_cursor->x >> 4, bolt_cursor->y >> 4, bolt_cursor->velocity_x >> 6, bolt_cursor->velocity_y >> 6, (int)game_sprite_base, (int)bolt_impact_animation_frames, 1);
                remove_auxiliary_projectile();
                continue;
            }
            if (((bolt_cursor->x >> 4) + 5) > *(int *)(open_brick_x_by_row + ((bolt_cursor->y >> 4) << 2))) {
                submit_audio_request(0x57);
                spawn_animated_sprite(bolt_cursor->x >> 4, bolt_cursor->y >> 4, 0, 0, (int)game_sprite_base, (int)bolt_impact_animation_frames, 1);
                remove_auxiliary_projectile();
                continue;
            }
        } else {
            target_bounds = (S18 *)(game_sprite_base + 0x35d6);
            if (frames_intersect_inset(*target_bounds, mouse_x_average_recent, mouse_y_mean_recent, *shot_frame_info, (bolt_cursor->x >> 4) + 8, bolt_cursor->y >> 4, 4, 4, 4, 4) == -1) {
                if (remaining_level_time > 0) {
                    remaining_level_time -= bolt_cursor->damage;
                }
                spawn_animated_sprite(bolt_cursor->x >> 4, bolt_cursor->y >> 4, 0, 0, (int)game_sprite_base, (int)bolt_impact_animation_frames, 1);
                remove_auxiliary_projectile();
                continue;
            }
        }
        *(int *)image_buffer_cursor = shot_frame_info;
        *(short *)(image_buffer_cursor + 4) = (unsigned short)(bolt_cursor->x >> 4);
        *(short *)(image_buffer_cursor + 6) = (unsigned short)(bolt_cursor->y >> 4);
        *(short *)(image_buffer_cursor + 8) = 0;
        image_buffer_cursor += 0xa;
        ++bolt_cursor;
    }
}

void remove_auxiliary_projectile(void)
{
    --enemy_projectile_count;
    if (projectile_index != enemy_projectile_count)
        memcpy(bolt_cursor, bolt_cursor + 1, (enemy_projectile_count - projectile_index) * sizeof(*bolt_cursor));
    --projectile_index;
}

void spawn_auxiliary_projectile(int kind, int damage, int x, int y, int velocity_x, int velocity_y, int sprite_offset)
{
    if (enemy_projectile_count < 0x18) {
        bolt_cursor = auxiliary_projectiles;
        bolt_cursor += enemy_projectile_count;
        *(int *)(bolt_cursor + 0) = kind;
        bolt_cursor->damage = damage;
        bolt_cursor->x = x << 4;
        bolt_cursor->y = y << 4;
        bolt_cursor->velocity_x = velocity_x;
        bolt_cursor->velocity_y = velocity_y;
        bolt_cursor->frame_info = 0;
        bolt_cursor->frame_offset = (unsigned char *)(sprite_offset - 8);
        bolt_cursor->sprite_data = game_sprite_base;
        ++enemy_projectile_count;
    }
}

void update_enemy_attack_cycle(void)
{
    int monster_x;
    int monster_y;
    int projectile_dx;
    int projectile_dy;
    int emitted_effect;
    monster_x = 0xf6;
    monster_y = 0x56;
    emitted_effect = 0;
    if (enemy_health_current > 0) {
        --enemy_attack_timer;
        if (enemy_attack_timer <= 0) {
            *(int *)image_buffer_cursor = (int)(game_sprite_base + 0x43b6);
            *(short *)(image_buffer_cursor + 4) = 0xf6;
            *(short *)(image_buffer_cursor + 6) = 0x46;
            *(short *)(image_buffer_cursor + 8) = 0;
            image_buffer_cursor += 0xa;
            emitted_effect = 1;
            --attack_frame_count;
            if (attack_frame_count <= 0) {
                attack_frame_count = 7;
                projectile_dx = ((mouse_x_average_recent - monster_x) << 4) / 0x28;
                projectile_dy = ((random_in_range(-0x1e, 0x1e) + (mouse_y_mean_recent - monster_y)) << 4) / 0x28;
                spawn_auxiliary_projectile(1, enemy_pattern, monster_x, monster_y, projectile_dx, projectile_dy, (int)enemy_projectile_animation_frames);
                if (remaining_level_time > 0) {
                    submit_audio_request(0x58);
                }
                --attack_cooldown;
                if (attack_cooldown <= 0) {
                    attack_delay -= 2;
                    enemy_attack_timer = attack_delay;
                    attack_cooldown = enemy_attack_interval;
                    --enemy_fire_acceleration;
                    if (enemy_fire_acceleration <= 0) {
                        ++enemy_attack_interval;
                        enemy_fire_acceleration = 0xf;
                    }
                }
            }
        }
        if (!emitted_effect) {
            if (enemy_attack_timer < 0xf || (attack_delay - 0x14) < enemy_attack_timer) {
                *(int *)image_buffer_cursor = (int)(game_sprite_base + 0x3e70);
                *(short *)(image_buffer_cursor + 4) = 0xf6;
                *(short *)(image_buffer_cursor + 6) = 0x46;
                *(short *)(image_buffer_cursor + 8) = 0;
                image_buffer_cursor += 0xa;
            } else {
                *(int *)image_buffer_cursor = (int)(game_sprite_base + 0x395c);
                *(short *)(image_buffer_cursor + 4) = 0xf6;
                *(short *)(image_buffer_cursor + 6) = 0x46;
                *(short *)(image_buffer_cursor + 8) = 0;
                image_buffer_cursor += 0xa;
            }
        }
        return;
    }
    *(int *)image_buffer_cursor = (int)(game_sprite_base + 0x43b6);
    *(short *)(image_buffer_cursor + 4) = 0xf6;
    *(short *)(image_buffer_cursor + 6) = 0x46;
    *(short *)(image_buffer_cursor + 8) = 0;
    image_buffer_cursor += 0xa;
}
