unsigned char q_A988[8];
unsigned char p_A990[432];
unsigned char h_ab40_jbfxrqns[5120];
unsigned char g_bf40_whznxcth[5120];
unsigned char g_d340_schtgisj[2560];
int g_dd78;
int g_dd7c;
int g_dd80;
int sprite_instance_count;
/* TU upd_ani..spawn_animated_sprite [0x7bd5, 0x7f8a): generated by tools/tu.py */
typedef unsigned int size_t;
struct SpriteFrame { unsigned image_offset; int frame_duration; };
struct AnimatedSprite { int x, y, velocity_x, velocity_y; int sprite_bank; int frame_delay; struct SpriteFrame *current_frame; unsigned reserved_flag : 1, animation_delay : 4, follows_player : 1, signals_bonus : 1, check_screen_bounds : 1, remove_after_animation : 1; };
extern int projectile_index;
extern int enemy_projectile_count;
extern int remaining_level_time;
extern int total_level_time;
extern int last_displayed_time;
extern int g_8e20;
extern int g_dd88;
extern int current_ball_count;
extern int game_ball_slot;
extern char *bolt_cursor;
extern char *current_ball_pointer;
extern char game_balls[];
extern void move_auxiliary_projectiles(void);
extern void draw_animated_sprites(void);
extern void update_game_balls(void);
extern void set_mouse_bounds(int, int, int, int);
extern void move_mouse_to(int, int);
struct PlayerShot { int x, y, vertical_speed, sprite_offset; unsigned flags; };
struct PlayerShot player_shot_records[12];
unsigned char brick_code_map[576];
struct MovingTargetRecord { int x, y, velocity_x, velocity_y, sprite_info, field_14, field_18, field_1c, hit_points; unsigned char flags; unsigned char pad[3]; };
struct MovingTargetRecord moving_target_records[8];
int brick_x_index;
int brick_y_index;
int g_dd60;
int g_dd64;
int g_dD68;
struct AnimatedSprite *sprite_current;
int b_DD70;
int g_dd74_ntd;

extern void update_mouse(void);
void *memmove(void *, const void *, size_t);
void clr_sp(void);
void f_7112(void);
void update_auxiliary_projectiles(void);
void remove_auxiliary_projectile(void);
void upd_ani(void);
void remove_animated_sprite(void);
void upd_bl(void);
void remove_game_ball(void);
void spawn_game_ball(int x, int y);
extern int g_8db4;
extern unsigned char *player_key_flags;
extern unsigned char *racket_object;
extern int g_e24c;
struct AnimatedSprite sprite_animations[50];
unsigned char g_9af8[2592];
int vga_buffer_base;
int sprite_memory_base;
int g_dd44;
int game_sprite_data_base_j;
int g_dd50;
int g_dd54;

extern int r_e250;
extern unsigned char *image_buffer_cursor;
extern void get_sprite_bounds(int *, int);
void *memcpy(void *, const void *, size_t);

/* _DATA [0x6984,0x739c) */
char *g_6984 = "123456789012345678901234679012";
int g_6988 = 0x5b;
int g_698c = 0xde;
int g_6990 = 0x46;
int g_6994[13] = {
    0x5d, 0x5b, 0xde, 0x6f, 0x86, 0x5b, 0xde, 0x97, 0xae, 0x5b, 0xde, 0xbf,
    0xd6
};
int g_69c8[72] = {
    0x1400, 0, 0, 0, 0x2e, 2, -256, 0, 0, 0, 0x2e, 2,
    0x740, 0x740, 0, 0, 0x2e, 0x71a, -256, 0, 0, 0, 0x2e, 0x71a,
    0, 0xb40, 0, 0, 0x2e, 0xb52, -256, 0, 0, 0, 0x2e, 0xb52,
    0x1400, 0, 0, 0, 0x2e, 0x13ee, 0x180, 0x180, 0, 0, 0x2e, 0x13ee,
    -256, 0x1300, 0, 0, 0x2e, 0x26ba, 0x180, 0x180, 0, 0, 0x2e, 0x26ba,
    0, 0, 0, 0, 0x2e, 0x3988, 0xc80, 0x100, 0, 0, 0x2e, 0x3988
};
int g_6ae8[36] = {
    -1792, 0xa00, 0, 0, 0x32, 0x5bf8, 0x640, 0x640, 0, 0, 0x32, 0,
    -640, 0x780, 0, 0, 0x32, 0, 0xf00, 0x640, 0, 0, 0x32, 0,
    0x1400, 0xa00, 0, 0, 0x32, 0, 0xf00, 0x640, 0, 0, 0x32
};
short g_6b78[19] = {
    0xa00, 0, 0x1b00, 0, 0, 0, 0, 0, 0x32, 0, 0x5bf8, 0,
    0x640, 0, 0x640
};
short g_6b9e[53] = {
    0, 0x32, 0, 0, 0, 0x780, 0, 0x1400, 0, 0, 0, 0,
    0, 0x32, 0, 0, 0, 0x640, 0, -640, -1, 0, 0, 0,
    0, 0x32, 0, 0, 0, 0xa00, 0, -640, -1, 0, 0, 0,
    0, 0x32, 0, 0, 0, 0x640, 0, -640, -1, 0, 0, 0,
    0, 0x32
};
int g_6c08[23] = {
    0xa00, 0xa00, 0, 0, 0x96, 0x87be, 0xfa0, 0x640, 0, 0, 0x96, 0,
    0xa00, 0xa00, 0, 0, 0x96, 0x9b1c, -800, 0x640, 0, 0, 0x96
};
int g_6c64[6] = {0, 0x78, 0x6e, 0x64, 0x5a, 0x50};
unsigned char g_6c7c[63] = {
    0x46, 0, 0, 0, 0xf, 0, 0, 0, 0x14, 0, 0, 0,
    0x19, 0, 0, 0, 0x1e, 0, 0, 0, 0x23, 0, 0, 0,
    0x2d, 0, 0, 0, 2, 2, 3, 3, 4, 4, 5, 0x5e,
    1, 0, 0, 0x5e, 1, 0, 0, 0xa4, 1, 0, 0, 0xea,
    1, 0, 0, 0x30, 2, 0, 0, 0x76, 2, 0, 0, 0xbc,
    2
};
unsigned char g_6cbb[1761] = {
    0, 0, 0, 0, 0x14, 5, 0, 0, 0x88, 0x13, 0, 0,
    0, 0, 0, 0, 0x14, 5, 0, 0, 0x14, 5, 0, 0,
    0x88, 0x13, 0, 0, 0, 0, 0, 0, 0x28, 0xa, 0, 0,
    0x19, 5, 0, 0, 0x88, 0x13, 0, 0, 0, 0, 0, 0,
    0x41, 0xf, 0, 0, 0xf, 5, 0, 0, 0x88, 0x13, 0, 0,
    0, 0, 0, 0, 0x50, 0x14, 0, 0, 0x14, 5, 0, 0,
    0x88, 0x13, 0, 0, 0, 0, 0, 0, 0x64, 0x19, 0, 0,
    0xe2, 4, 0, 0, 0x88, 0x13, 0, 0, 0, 0, 0, 0,
    0x46, 0x1e, 0, 0, 0xe2, 4, 0, 0, 0x88, 0x13, 0, 0,
    0, 0, 0, 0, 0x28, 0x23, 0, 0, 0xb0, 4, 0, 0,
    0x88, 0x13, 0, 0, 0, 0, 0, 0, 0xd8, 0x27, 0, 0,
    0x4c, 4, 0, 0, 0x88, 0x13, 0, 0, 0, 0, 0, 0,
    0x24, 0x2c, 0, 0, 0x10, 0x27, 0, 0, 0x88, 0x13, 0, 0,
    0, 0, 0, 0, 0x34, 0x53, 0, 0, 0x88, 0x2a, 0, 0,
    0x88, 0x13, 0, 0, 0, 0, 0, 0, 0xbc, 0x7d, 0, 0,
    0x78, 5, 0, 0, 0x88, 0x13, 0, 0, 0, 0, 0, 0,
    0x34, 0x83, 0, 0, 0x78, 5, 0, 0, 0x88, 0x13, 0, 0,
    0, 0, 0, 0, 0xac, 0x88, 0, 0, 0x78, 5, 0, 0,
    0x88, 0x13, 0, 0, 0, 0, 0, 0, 0x24, 0x8e, 0, 0,
    0xe8, 3, 0, 0, 0x88, 0x13, 0, 0, 0, 0, 0, 0,
    0xc, 0x92, 0, 0, 0xe2, 4, 0, 0, 0x88, 0x13, 0, 0,
    0, 0, 0, 0, 0xee, 0x96, 0, 0, 0x46, 5, 0, 0,
    0x88, 0x13, 0, 0, 0, 0, 0, 0, 0x34, 0x9c, 0, 0,
    0x40, 6, 0, 0, 0x88, 0x13, 0, 0, 0, 0, 0, 0,
    0x74, 0xa2, 0, 0, 0xdc, 5, 0, 0, 0x88, 0x13, 0, 0,
    0, 0, 0, 0, 0x50, 0xa8, 0, 0, 0xdc, 5, 0, 0,
    0x88, 0x13, 0, 0, 0, 0, 0, 0, 0x2c, 0xae, 0, 0,
    0x14, 5, 0, 0, 0x88, 0x13, 0, 0, 0, 0, 0, 0,
    0x40, 0xb3, 0, 0, 0xe8, 3, 0, 0, 0x88, 0x13, 0, 0,
    0, 0, 0, 0, 0x28, 0xb7, 0, 0, 0x78, 5, 0, 0,
    0x88, 0x13, 0, 0, 0, 0, 0, 0, 0xa0, 0xbc, 0, 0,
    0x78, 5, 0, 0, 0x88, 0x13, 0, 0, 0, 0, 0, 0,
    0x18, 0xc2, 0, 0, 0x78, 5, 0, 0, 0x88, 0x13, 0, 0,
    0, 0, 0, 0, 0x90, 0xc7, 0, 0, 0xe8, 3, 0, 0,
    0x88, 0x13, 0, 0, 0, 0, 0, 0, 0x78, 0xcb, 0, 0,
    0xe8, 3, 0, 0, 0x88, 0x13, 0, 0, 0, 0, 0, 0,
    0xfc, 0xce, 0, 0, 0xf2, 3, 0, 0, 0x88, 0x13, 0, 0,
    0, 0, 0, 0, 0xee, 0xd2, 0, 0, 0xa, 5, 0, 0,
    0x88, 0x13, 0, 0, 0, 0, 0, 0, 0xf8, 0xd7, 0, 0,
    0xa0, 0xf, 0, 0, 0x88, 0x13, 0, 0, 0, 0, 0, 0,
    0x98, 0xe7, 0, 0, 0x1c, 0xc, 0, 0, 0x88, 0x13, 0, 0,
    0, 0, 0, 0, 0xb4, 0xf3, 0, 0, 0xe4, 0xc, 0, 0,
    0x88, 0x13, 0, 0, 0, 0, 0, 0, 0x98, 0, 1, 0,
    0xc4, 9, 0, 0, 0x88, 0x13, 0, 0, 0, 0, 0, 0,
    0x5c, 0xa, 1, 0, 0x98, 8, 0, 0, 0x88, 0x13, 0, 0,
    0, 0, 0, 0, 0xf4, 0x12, 1, 0, 0x4c, 4, 0, 0,
    0x88, 0x13, 0, 0, 0, 0, 0, 0, 0x40, 0x17, 1, 0,
    0x7e, 4, 0, 0, 0x88, 0x13, 0, 0, 0, 0, 0, 0,
    0xbe, 0x1b, 1, 0, 0x4c, 0x1d, 0, 0, 0x88, 0x13, 0, 0,
    0, 0, 0, 0, 0xa, 0x39, 1, 0, 0x4c, 0x1d, 0, 0,
    0x88, 0x13, 0, 0, 0, 0, 0, 0, 0x56, 0x56, 1, 0,
    0x48, 0xd, 0, 0, 0x88, 0x13, 0, 0, 0, 0, 0, 0,
    0x9e, 0x63, 1, 0, 0xb8, 0xb, 0, 0, 0x88, 0x13, 0, 0,
    0, 0, 0, 0, 0x56, 0x6f, 1, 0, 0xf8, 0x11, 0, 0,
    0x88, 0x13, 0, 0, 0, 0, 0, 0, 0x4e, 0x81, 1, 0,
    0xdc, 5, 0, 0, 0x88, 0x13, 0, 0, 0, 0, 0, 0,
    0x2a, 0x87, 1, 0, 0xdc, 5, 0, 0, 0x88, 0x13, 0, 0,
    0, 0, 0, 0, 6, 0x8d, 1, 0, 0xd0, 7, 0, 0,
    0x88, 0x13, 0, 0, 0, 0, 0, 0, 0xd6, 0x94, 1, 0,
    0xd0, 7, 0, 0, 0x88, 0x13, 0, 0, 0, 0, 0, 0,
    0xa6, 0x9c, 1, 0, 0xd0, 7, 0, 0, 0x88, 0x13, 0, 0,
    0, 0, 0, 0, 0x76, 0xa4, 1, 0, 0xd0, 7, 0, 0,
    0x88, 0x13, 0, 0, 0, 0, 0, 0, 0x46, 0xac, 1, 0,
    0xdc, 5, 0, 0, 0x88, 0x13, 0, 0, 0, 0, 0, 0,
    0x22, 0xb2, 1, 0, 0xdc, 5, 0, 0, 0x88, 0x13, 0, 0,
    0, 0, 0, 0, 0xfe, 0xb7, 1, 0, 0x14, 5, 0, 0,
    0x88, 0x13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0x24, 0x2c, 0, 0, 0x98, 0x3a, 0, 0, 0, 0, 0, 0,
    0x14, 5, 0, 0, 0x14, 5, 0, 0, 0x98, 0x3a, 0, 0,
    0, 0, 0, 0, 0x28, 0xa, 0, 0, 0x14, 5, 0, 0,
    0x98, 0x3a, 0, 0, 0, 0, 0, 0, 0x3c, 0xf, 0, 0,
    0x14, 5, 0, 0, 0x98, 0x3a, 0, 0, 0, 0, 0, 0,
    0x50, 0x14, 0, 0, 0x14, 5, 0, 0, 0x98, 0x3a, 0, 0,
    0, 0, 0, 0, 0x64, 0x19, 0, 0, 0xe2, 4, 0, 0,
    0x98, 0x3a, 0, 0, 0, 0, 0, 0, 0x46, 0x1e, 0, 0,
    0xe2, 4, 0, 0, 0x98, 0x3a, 0, 0, 0, 0, 0, 0,
    0x28, 0x23, 0, 0, 0xb0, 4, 0, 0, 0x98, 0x3a, 0, 0,
    0, 0, 0, 0, 0xd8, 0x27, 0, 0, 0x4c, 4, 0, 0,
    0x98, 0x3a, 0, 0, 0, 0, 0, 0, 0x24, 0x2c, 0, 0,
    0x10, 0x27, 0, 0, 0x98, 0x3a, 0, 0, 0, 0, 0, 0,
    0x34, 0x53, 0, 0, 0x88, 0x2a, 0, 0, 0x98, 0x3a, 0, 0,
    0, 0, 0, 0, 0xbc, 0x7d, 0, 0, 0x78, 5, 0, 0,
    0x98, 0x3a, 0, 0, 0, 0, 0, 0, 0x34, 0x83, 0, 0,
    0x78, 5, 0, 0, 0x98, 0x3a, 0, 0, 0, 0, 0, 0,
    0xac, 0x88, 0, 0, 0x78, 5, 0, 0, 0x98, 0x3a, 0, 0,
    0, 0, 0, 0, 0x24, 0x8e, 0, 0, 0xe8, 3, 0, 0,
    0x98, 0x3a, 0, 0, 0, 0, 0, 0, 0xc, 0x92, 0, 0,
    0xe2, 4, 0, 0, 0x98, 0x3a, 0, 0, 0, 0, 0, 0,
    0xee, 0x96, 0, 0, 0x46, 5, 0, 0, 0x98, 0x3a, 0, 0,
    0, 0, 0, 0, 0x34, 0x9c, 0, 0, 0x40, 6, 0, 0,
    0x98, 0x3a, 0, 0, 0, 0, 0, 0, 0x74, 0xa2, 0, 0,
    0xdc, 5, 0, 0, 0x98, 0x3a, 0, 0, 0, 0, 0, 0,
    0x50, 0xa8, 0, 0, 0xdc, 5, 0, 0, 0x98, 0x3a, 0, 0,
    0, 0, 0, 0, 0x2c, 0xae, 0, 0, 0x14, 5, 0, 0,
    0x98, 0x3a, 0, 0, 0, 0, 0, 0, 0x40, 0xb3, 0, 0,
    0xe8, 3, 0, 0, 0x98, 0x3a, 0, 0, 0, 0, 0, 0,
    0x28, 0xb7, 0, 0, 0x78, 5, 0, 0, 0x98, 0x3a, 0, 0,
    0, 0, 0, 0, 0xa0, 0xbc, 0, 0, 0x78, 5, 0, 0,
    0x98, 0x3a, 0, 0, 0, 0, 0, 0, 0x18, 0xc2, 0, 0,
    0x78, 5, 0, 0, 0x98, 0x3a, 0, 0, 0, 0, 0, 0,
    0x90, 0xc7, 0, 0, 0xcc, 0x10, 0, 0, 0x10, 0x27, 0, 0,
    0, 0, 0, 0, 0xf8, 0xd7, 0, 0, 0xa0, 0xf, 0, 0,
    0x58, 0x1b, 0, 0, 0, 0, 0, 0, 0x98, 0xe7, 0, 0,
    0x1c, 0xc, 0, 0, 0x40, 0x1f, 0, 0, 0, 0, 0, 0,
    0xf8, 0xd7, 0, 0, 0xa0, 0xf, 0, 0, 0x28, 0x23, 0, 0,
    0, 0, 0, 0, 0xf8, 0xd7, 0, 0, 0xa0, 0xf, 0, 0,
    0x10, 0x27, 0, 0, 0, 0, 0, 0, 0x98, 0xe7, 0, 0,
    0x1c, 0xc, 0, 0, 0x40, 0x1f, 0, 0, 0, 0, 0, 0,
    0xb4, 0xf3, 0, 0, 0xe4, 0xc, 0, 0, 0x98, 0x3a, 0, 0,
    0, 0, 0, 0, 0x98, 0, 1, 0, 0xc4, 9, 0, 0,
    0x98, 0x3a, 0, 0, 0, 0, 0, 0, 0x5c, 0xa, 1, 0,
    0x98, 8, 0, 0, 0x98, 0x3a, 0, 0, 0, 0, 0, 0,
    0xf4, 0x12, 1, 0, 0x4c, 4, 0, 0, 0x98, 0x3a, 0, 0,
    0, 0, 0, 0, 0x40, 0x17, 1, 0, 0x7e, 4, 0, 0,
    0x98, 0x3a, 0, 0, 0, 0, 0, 0, 0xbe, 0x1b, 1, 0,
    0x4c, 0x1d, 0, 0, 0x98, 0x3a, 0, 0, 0, 0, 0, 0,
    0xa, 0x39, 1, 0, 0x4c, 0x1d, 0, 0, 0x98, 0x3a, 0, 0,
    0, 0, 0, 0, 0x56, 0x56, 1, 0, 0x48, 0xd, 0, 0,
    0x98, 0x3a, 0, 0, 0, 0, 0, 0, 0x9e, 0x63, 1, 0,
    0xb8, 0xb, 0, 0, 0x98, 0x3a, 0, 0, 0, 0, 0, 0,
    0x56, 0x6f, 1, 0, 0xf8, 0x11, 0, 0, 0x98, 0x3a, 0, 0,
    0, 0, 0, 0, 0x4e, 0x81, 1, 0, 0x88, 0x13, 0, 0,
    0xe0, 0x2e, 0, 0, 0, 0, 0, 0, 0x2a, 0x87, 1, 0,
    0xdc, 5, 0, 0, 0x98, 0x3a, 0, 0, 0, 0, 0, 0,
    6, 0x8d, 1, 0, 0xd0, 7, 0, 0, 0x98, 0x3a, 0, 0,
    0, 0, 0, 0, 0xd6, 0x94, 1, 0, 0xd0, 7, 0, 0,
    0x98, 0x3a, 0, 0, 0, 0, 0, 0, 0xa6, 0x9c, 1, 0,
    0xd0, 7, 0, 0, 0x98, 0x3a, 0, 0, 0, 0, 0, 0,
    0x76, 0xa4, 1, 0, 0xd0, 7, 0, 0, 0x98, 0x3a, 0, 0,
    0, 0, 0, 0, 0x46, 0xac, 1, 0, 0xdc, 5, 0, 0,
    0x98, 0x3a, 0, 0, 0, 0, 0, 0, 0x22, 0xb2, 1, 0,
    0xdc, 5, 0, 0, 0xb8, 0xb, 0, 0, 0, 0, 0, 0,
    0xfe, 0xb7, 1, 0, 0x14, 5, 0, 0, 0x98, 0x3a, 0, 0,
    0, 0, 0, 0, 0x12, 0xbd, 1, 0, 0x60, 9, 0, 0,
    0x88, 0x13, 0, 0, 0, 0, 0, 0, 0x72, 0xc6, 1, 0,
    0xea, 0xb, 0, 0, 0x88, 0x13, 0, 0, 0, 0, 0, 0,
    0x12, 0xbd, 1, 0, 0x60, 9, 0, 0, 0x20, 0x4e, 0, 0,
    0, 0, 0, 0, 0x72, 0xc6, 1, 0, 0xea, 0xb, 0, 0,
    0x98, 0x3a, 0, 0, 0, 0, 0, 0, 0x34, 0x53, 0, 0,
    0x88, 0x2a, 0, 0, 0x98, 0x3a, 0, 0, 0, 0, 0, 0,
    0xbe, 0x1b, 1, 0, 0x88, 0x13, 0, 0, 0x98, 0x3a, 0, 0,
    0, 0, 0, 0, 0xbe, 0x1b, 1, 0, 0x88, 0x13, 0, 0,
    0x98, 0x3a, 0, 0, 0, 0, 0, 0, 0x34, 0x53, 0, 0,
    0x88, 0x2a, 0, 0, 0x98, 0x3a, 0, 0, 0, 0, 0, 0,
    0x34, 0x53, 0, 0, 0x88, 0x2a, 0, 0, 0x98, 0x3a, 0, 0,
    0, 0, 0, 0, 0x34, 0x53, 0, 0, 0x88, 0x2a, 0, 0,
    0x98, 0x3a
};

void upd_ani(void) { if (sprite_instance_count) draw_animated_sprites(); }

/* Advance each sprite animation and append visible frames to the draw list. */
void draw_animated_sprites(void)
{
    sprite_current = sprite_animations;
    for (g_dd88 = 0; g_dd88 < sprite_instance_count; g_dd88++) {
        if (sprite_current->follows_player) {
            sprite_current->x = *(int *)racket_object;
            sprite_current->y = *(int *)(racket_object + 4);
        } else if (sprite_current->animation_delay == 0) {
            sprite_current->x += sprite_current->velocity_x;
            sprite_current->y += sprite_current->velocity_y;
        } else {
            sprite_current->animation_delay--;
        }
        if (--sprite_current->frame_delay <= 0) {
            g_8e20 = (++sprite_current->current_frame)->frame_duration;
            if (g_8e20 < 0) {
                if (sprite_current->signals_bonus) *player_key_flags |= 0x40;
                if (sprite_current->remove_after_animation) {
                    remove_animated_sprite();
                    continue;
                }
                sprite_current->current_frame += g_8e20;
                g_8e20 = sprite_current->current_frame->frame_duration;
            }
            sprite_current->frame_delay = g_8e20;
        }
        g_8db4 = sprite_current->sprite_bank + sprite_current->current_frame->image_offset;
        if (sprite_current->check_screen_bounds) {
            g_e24c = sprite_current->x;
            r_e250 = sprite_current->y;
            get_sprite_bounds(&g_e24c, g_8db4);
            if (sprite_current->x > 0x150 || sprite_current->x < -0x10 ||
                sprite_current->y > 0xd8 || sprite_current->y < -0x10) {
                remove_animated_sprite();
                continue;
            }
        }
        *(int *)image_buffer_cursor = g_8db4;
        *(short *)(image_buffer_cursor + 4) = sprite_current->x;
        *(short *)(image_buffer_cursor + 6) = sprite_current->y;
        *(short *)(image_buffer_cursor + 8) = 0;
        image_buffer_cursor += 10;
        sprite_current++;
    }
}

void remove_animated_sprite(void)
{
    --sprite_instance_count;
    if (g_dd88 != sprite_instance_count)
        memcpy(sprite_current, sprite_current + 1, (sprite_instance_count - g_dd88) * 0x20);
    --g_dd88;
}

void spawn_animated_sprite(int x, int y, int velocity_x, int velocity_y, int sprite_bank, int first_frame, int animation_flags)
{
    if (sprite_instance_count < 0x32) {
        sprite_current = sprite_animations;
        sprite_current += sprite_instance_count;
        sprite_current->x = x;
        sprite_current->y = y;
        sprite_current->velocity_x = velocity_x;
        sprite_current->velocity_y = velocity_y;
        if (animation_flags & 0x10) {
            sprite_current->frame_delay = 0x3e80;
            sprite_current->current_frame = first_frame;
        } else {
            sprite_current->frame_delay = 0;
            sprite_current->current_frame = first_frame - 8;
        }
        sprite_current->sprite_bank = sprite_bank;
        sprite_current->animation_delay = animation_flags >> 4;
        sprite_current->follows_player = animation_flags >> 3;
        sprite_current->signals_bonus = animation_flags >> 2;
        sprite_current->check_screen_bounds = animation_flags >> 1;
        sprite_current->remove_after_animation = animation_flags;
        sprite_instance_count++;
    }
}
