unsigned char g_dd88[8];
int g_ddd0;
int g_ddd4_eoraaik;
unsigned char *g_Ddd8;
/* TU f_7f8a..f_80d8 [0x7f8a, 0x814b): generated by tools/tu.py */
struct Iter24 { int first, second, start, count, step, unused; };
struct Iter48 { int pad0, pad4, box, pad12, pad16, at20; int pad24, pad28, pad32, pad36, pad40, pad44; };
struct DisplayModeInfo { short state; unsigned char plane_addresses[16]; int page_offsets[4]; int page_adjustments[4]; unsigned char page_mode_classes[4]; int buffer_size; int row_stride_bytes; int resolution_height; int width; int height; int left; int top; int right; int bottom; unsigned char mode_flags; unsigned char e37f; unsigned char e380; unsigned char video_mode_low; unsigned char e382; unsigned char e383; unsigned char e384; unsigned char e385; unsigned char e386; unsigned char tail; };
extern struct DisplayModeInfo vga_state;
int g_ddc0;
int g_ddc4;
int g_dDc8;
int g_ddcc;

void save_bios(void);
extern int g_df38;
extern int g_2e9c[];
extern void draw_bob_sprite_entry(unsigned char *, int, int);
extern unsigned char *g_e158_tpotbrbk;
extern short m_E15C;
extern short g_e15e;
extern short g_e160;
extern short g_e162;
extern struct Iter24 *u_e150;
extern int g_e148;
extern int g_e14c;
extern int g_e154;
extern unsigned char *image_buffer_cursor;
void f_95ee(void);
void f_8004(int *rect, unsigned char *info);
void f_8066(int *rect, unsigned char *info);
void f_82cc(void);
void f_8345_wsdytbf(void);
void f_83b1(void);
extern unsigned char g_e13e;
int g_dda0;
int g_dda4;
int g_dDa8;
int c_DDAC;
int g_ddb0;
int g_ddb4;
int g_dDb8;
int g_ddbc;

extern unsigned char g_e13b;
union KeyWord { unsigned short word; struct { unsigned char lo, hi; } bytes; };
extern union KeyWord g_e468[8];
extern unsigned char *x_dd40_xbukycw;
extern void *r_dDDc_uzmlc;
extern int g_8e1c;
extern int g_8e20;
extern int fade_delay;
extern int g_94a0;
extern int g_9490;
extern int g_94a4;
extern int g_94a8;
extern int g_9494;
extern int g_94ac;
extern int g_946c;
extern int g_948c;
extern int g_949c;
extern int g_94b4;
int g_dd90;
int i_DD98;
int g_dd94;
int g_dd9c;

extern int g_9498;
extern int g_9474;
extern int g_6884[];
extern int g_6888[];
extern int g_688c[];
extern int g_6890[];
extern short flip_src;
extern short flip_dst;
extern short g_7b24;
extern short g_7b26;
extern short disp_idx;
extern short draw_idx;
extern short page2;
extern short page3;
extern unsigned short g_7bfe;
extern unsigned short g_7c00;
extern short g_e4a8;
extern short n_e4c2;
extern void submit_audio_request(int);
extern void write_pal(void *);
extern void f_9d40(int);
extern void fade_pal(void *, int, int, int);
extern void f_10369(void);
extern void f_103b9(void);
extern void set_img_buffers();
int f_6e2e(void);
int f_6ee8(void);
void f_7068(void);
void f_843a(void);

void f_7f8a(void)
{
    int x;
    int y;
    unsigned char *p;
    y = 16;
    while (y < vga_state.height) {
        x = 0;
        while (x < vga_state.width) {
            p = g_Ddd8 + g_2e9c[2 * g_df38];
            draw_bob_sprite_entry(p, x, y);
            x += *(short *)(p + 2);
        }
        y += *(short *)(p + 4);
    }
}

void f_8004(int *rect, unsigned char *info)
{
    g_e158_tpotbrbk = info;
    f_95ee();
    rect[0] += m_E15C;
    rect[1] += g_e15e;
    rect[2] = rect[0] + g_e160 - 2;
    rect[3] = rect[1] + g_e162 - 2;
}

void f_8066(int *rect, unsigned char *info)
{
    g_e158_tpotbrbk = info;
    f_95ee();
    rect[0] += m_E15C + 3;
    rect[1] += g_e15e + 3;
    rect[2] = rect[0] - 3 + g_e160 - 5;
    rect[3] = rect[1] - 3 + g_e162 - 5;
}

void f_80d8(void)
{
    if (g_e468[1].bytes.hi & 0x20) {
        if (g_7bfe != g_7c00) {
            if (g_7bfe == 1) {
                f_10369();
                g_e4a8 -= 2;
                n_e4c2 -= 2;
                f_103b9();
            } else if (g_7bfe == 2) {
                f_10369();
                g_e4a8 += 2;
                n_e4c2 += 2;
                f_103b9();
            }
        }
    }
}
