/* TU f_82cc..f_84a0 [0x82cc, 0x8585): generated by tools/tu.py */
struct Iter24 { int first, second, start, count, step, unused; };
struct Iter48 { int pad0, pad4, box, pad12, pad16; char *at20; int pad24, pad28, pad32, pad36, pad40, pad44; };
extern unsigned char *g_e158_tpotbrbk;
extern short m_E15C;
extern short g_e15e;
extern short g_e160;
extern short g_e162;
extern struct Iter24 *u_e150;
extern int g_e148;
extern int g_e14c;
extern int g_e154;
extern unsigned char *image_buffer_cursor;
void read_sprite_frame_bounds(void);
void get_sprite_bounds(int *rect, unsigned char *info);
void get_sprite_collision_bounds(int *rect, unsigned char *info);
void f_82cc(void);
void f_8345_wsdytbf(void);
void f_83b1(void);
extern short disp_idx;
extern short draw_idx;
extern short page2;
extern short page3;
extern short flip_src;
extern short flip_dst;
extern short g_7b24;
extern short g_7b26;
extern unsigned char h_ab40_jbfxrqns[];
extern unsigned char g_bf40_whznxcth[];
extern unsigned char g_d340_schtgisj[];
extern void set_img_buffers(int, int, short, int, int);
extern short hook_flags_word;
extern short space_pressed;
extern unsigned short mouse_btn;
extern unsigned short mouse_btn_old;
extern int g_e1b8;
extern short g_e1bc;
extern short g_e1c0;
extern unsigned char current_scan_code;
extern unsigned char previous_ascii_key_2f;
extern unsigned char current_key_code_01;
extern unsigned char current_ascii;
extern void handle_s_key(void);
extern void f_9d40(unsigned char);
extern void redraw_image_region(int, int);
extern void show_page(void);

void f_82cc(void)
{
    struct Iter24 *p = u_e150;
    int i = 0;
    for (; i < g_e148; i++) {
        p->count = (p->second - p->first) / p->step;
        p->start = p->first - p->count;
        p++;
    }
    g_e14c = 0;
}

void f_8345_wsdytbf(void)
{
    struct Iter24 *p;
    int i;
    ++g_e14c;
    p = u_e150;
    i = 0;
    for (; i < g_e148; i++) {
        if (g_e14c >= p->step)
            p->start = p->second;
        else
            p->start += p->count;
        p++;
    }
}

void f_83b1(void)
{
    struct Iter48 *p = (struct Iter48 *)u_e150;
    int i = 0;
    for (; i < (g_e148 >> 1); i++) {
        *(int *)image_buffer_cursor = (int)(p->at20 + g_e154);
        *(short *)(image_buffer_cursor + 4) = (short)(p->box >> 4);
        *(short *)(image_buffer_cursor + 6) = (short)(p->pad32 >> 4);
        *(short *)(image_buffer_cursor + 8) = 0;
        image_buffer_cursor += 10;
        ++p;
    }
}

void f_843a(void)
{
    set_img_buffers((int)g_d340_schtgisj, 0x100, 4, (int)h_ab40_jbfxrqns, (int)g_bf40_whznxcth);
    disp_idx = flip_src;
    draw_idx = flip_dst;
    page2 = g_7b24;
    page3 = g_7b26;
}

void f_84a0(int a0)
{
    space_pressed = 0;
    hook_flags_word = (hook_flags_word & 0xfffe) & 0xfffd;
    do {
        f_9d40(3);
        g_e1bc = 0;
        g_e1b8 = (int)image_buffer_cursor;
        do {
            image_buffer_cursor = (unsigned char *)g_e1b8;
            handle_s_key();
            f_8345_wsdytbf();
            f_83b1();
            ++g_e1bc;
        } while (g_e1bc < g_e1c0);
        redraw_image_region(0, 0);
        show_page();
    } while ((previous_ascii_key_2f == current_ascii || current_ascii != 0x20) && (mouse_btn == mouse_btn_old || !(*(unsigned char *)&mouse_btn & 7)) && (current_scan_code == current_key_code_01 || current_key_code_01 != 1) && g_e14c < a0);
}
