#define CHEAT_SPELL_KEYS 0x01
#define CHEAT_LEVEL_KEYS 0x02
#define CHEAT_STICKY_RACKET 0x04
#define CHEAT_EXTRA_LIVES 0x08
#define KEY_ASCII_UPPER_A 0x41
#define KEY_ASCII_UPPER_Z 0x5a
#define KEY_ASCII_PERCENT 0x25
#define KEY_ASCII_PERIOD 0x2e
#define KEY_ASCII_SPACE 0x20
#define KEY_ASCII_ASTERISK 0x2a
#define KEY_SCAN_ESCAPE 0x1b
#define KEYBOARD_RELEASE_BIT 0x80
#define CHEAT_LEVEL_NUMBER 0x3c
#define CHEAT_LIFE_BALANCE 0x63
#define CHEAT_LEVEL_SKIP 9
#define CHEAT_SPECIAL_SPELL_ID 0x0f
#define CHEAT_SPELL_SPAWN_X 0xa0
#define CHEAT_SPELL_SPAWN_Y 0x64
#define PLAYER_FLAG_CATCH_BALL 0x08
#define PLAYER_FLAG_BONUS_SIGNAL 0x40
#define PLAYER_FLAG_RACKET_EFFECT 0x80
#define SPELL_FLAG_TEMPORARY 0x04
#define RACKET_STICKY_EFFECT 3

struct Racket {
    int x;
    int y;
    int previous_x;
    int min_x;
    int max_x;
    int min_y;
    int max_y;
    int sprite_frame_index;
    int sprite_height;
    int reward_level;
    int capture_timer;
    int state_2c;
    int state_30;
    int effect_state;
    int horizontal_recenter_timer;
    int vertical_recenter_timer;
    int effect_timer_40;
    int effect_frame_44;
    int animation_timer_48;
    int animation_step_4c;
    int animation_timer_50;
    int animation_step_54;
    int shield_frame_timer;
    int shield_frame_index;
    int spell_anim_timer;
    int spell_anim_index;
    int spell_parameter_68;
    int spell_parameter_6c;
    int spell_parameter_70;
    int previous_x_snapshot;
    unsigned char *sprite_pointer;
};
struct GameProgressState { int progress_marker, life_balance, opaque_08, opaque_0c, opaque_10, score, tail; };
struct PlayerInputFlags { unsigned char control_flags, spell_flags, reserved_2, reserved_3; };

unsigned char *game_art_base;
/* TU handle_keyboard_controls..handle_keyboard_controls [0x814b, 0x82cc): generated by tools/tu.py */
extern unsigned char keyboard_cheat_flags;
extern int remaining_brick_count;
extern int spell_count;
extern struct Racket *racket_object;
struct PlayerInputFlags *player_key_flags;
unsigned char paddle_state_data[124];
struct GameProgressState *score_state;
struct Racket racket_state_storage;
int points;

extern unsigned char level_number;
extern unsigned char prior_key_ascii;
extern unsigned char keyboard_scan_byte;
extern unsigned char current_ascii;
extern void spawn_falling_spell(unsigned char, unsigned char, int, int);
extern void update_racket_movement_bounds(void);

void handle_keyboard_controls(void)
{
    if (keyboard_cheat_flags & CHEAT_SPELL_KEYS) {
        if (current_ascii >= KEY_ASCII_UPPER_A && current_ascii <= KEY_ASCII_UPPER_Z &&
            (keyboard_scan_byte & KEYBOARD_RELEASE_BIT) == 0)
            spawn_falling_spell((unsigned char)(current_ascii - KEY_ASCII_UPPER_A), 0,
                                CHEAT_SPELL_SPAWN_X, CHEAT_SPELL_SPAWN_Y);
        if (current_ascii == KEY_ASCII_PERCENT && (keyboard_scan_byte & KEYBOARD_RELEASE_BIT) == 0)
            spawn_falling_spell(CHEAT_SPECIAL_SPELL_ID, 0, CHEAT_SPELL_SPAWN_X, CHEAT_SPELL_SPAWN_Y);
        if (current_ascii == KEY_ASCII_PERIOD && (keyboard_scan_byte & KEYBOARD_RELEASE_BIT) == 0) {
            player_key_flags->control_flags &= (unsigned char)~PLAYER_FLAG_CATCH_BALL;
            player_key_flags->spell_flags &= (unsigned char)~SPELL_FLAG_TEMPORARY;
            player_key_flags->control_flags &= (unsigned char)~PLAYER_FLAG_BONUS_SIGNAL;
            player_key_flags->control_flags &= (unsigned char)~PLAYER_FLAG_RACKET_EFFECT;
            update_racket_movement_bounds();
        }
    }

    if (keyboard_cheat_flags & CHEAT_LEVEL_KEYS) {
        if (keyboard_scan_byte == KEY_SCAN_ESCAPE) {
            level_number = CHEAT_LEVEL_NUMBER;
            spell_count = 0;
            remaining_brick_count = 0;
            current_ascii = 0;
        }
        if (prior_key_ascii != KEY_ASCII_SPACE && current_ascii == KEY_ASCII_SPACE) {
            spell_count = 0;
            remaining_brick_count = 0;
        }
        if (prior_key_ascii != KEY_ASCII_ASTERISK && current_ascii == KEY_ASCII_ASTERISK) {
            level_number += CHEAT_LEVEL_SKIP;
            spell_count = 0;
            remaining_brick_count = 0;
        }
    }
    if (keyboard_cheat_flags & CHEAT_STICKY_RACKET) {
        player_key_flags->control_flags |= PLAYER_FLAG_CATCH_BALL;
        racket_object->effect_state = RACKET_STICKY_EFFECT;
    }
    if (keyboard_cheat_flags & CHEAT_EXTRA_LIVES)
        score_state->life_balance = CHEAT_LIFE_BALANCE;
}
