int game_art_base;
/* TU handle_keyboard_controls..handle_keyboard_controls [0x814b, 0x82cc): generated by tools/tu.py */
extern unsigned char keyboard_cheat_flags;
extern int remaining_brick_count;
extern int spell_count;
extern unsigned char *racket_object;
unsigned char *player_key_flags;
unsigned char paddle_state_data[124];
unsigned char *racket_state;
unsigned char racket_state_storage[124];
int points;

extern unsigned char level_number;
extern unsigned char prior_key_ascii;
extern unsigned char keyboard_scan_byte;
extern unsigned char current_ascii;
extern void spawn_falling_spell(unsigned char, unsigned char, int, int);
extern void update_racket_movement_bounds(void);

void handle_keyboard_controls(void)
{
    if (keyboard_cheat_flags & 1) {
        if (current_ascii >= 0x41 && current_ascii <= 0x5a && (keyboard_scan_byte & 0x80) == 0)
            spawn_falling_spell((unsigned char)(current_ascii - 0x41), 0, 0xa0, 0x64);
        if (current_ascii == 0x25 && (keyboard_scan_byte & 0x80) == 0)
            spawn_falling_spell(0xf, 0, 0xa0, 0x64);
        if (current_ascii == 0x2e && (keyboard_scan_byte & 0x80) == 0) {
            *player_key_flags &= 0xf7;
            player_key_flags[1] &= 0xfb;
            *player_key_flags &= 0xbf;
            *player_key_flags &= 0x7f;
            update_racket_movement_bounds();
        }
    }

    if (keyboard_cheat_flags & 2) {
        if (keyboard_scan_byte == 0x1b) {
            level_number = 0x3c;
            spell_count = 0;
            remaining_brick_count = 0;
            current_ascii = 0;
        }
        if (prior_key_ascii != 0x20 && current_ascii == 0x20) {
            spell_count = 0;
            remaining_brick_count = 0;
        }
        if (prior_key_ascii != 0x2a && current_ascii == 0x2a) {
            level_number += 9;
            spell_count = 0;
            remaining_brick_count = 0;
        }
    }
    if (keyboard_cheat_flags & 4) {
        *player_key_flags |= 8;
        *(int *)(racket_object + 0x34) = 3;
    }
    if (keyboard_cheat_flags & 8)
        *(int *)(racket_state + 4) = 0x63;
}
