struct TransitionTrack *u_e150;
int g_e154;
unsigned char *g_e158_tpotbrbk;
short g_e162;
/* TU read_sprite_frame_bounds..read_sprite_frame_bounds [0x95ee, 0x963b): generated by tools/tu.py */
struct TransitionTrack { int start_value, end_value, current_value, step_delta, duration, reserved; };
struct TransitionSprite { int pad0, pad4, box, pad12, pad16, at20; int pad24, pad28, pad32, pad36, pad40, pad44; };
extern unsigned char *image_buffer_cursor;
int g_e144;
int g_e148;
int g_e14c;
short m_E15C;
short g_e15e;
short g_e160;

void get_sprite_bounds(int *rect, unsigned char *info);
void get_sprite_collision_bounds(int *rect, unsigned char *info);
void f_82cc(void);
void f_8345_wsdytbf(void);
void f_83b1(void);

void read_sprite_frame_bounds(void)
{
    g_e160 = *(short *)(g_e158_tpotbrbk + 2);
    g_e162 = *(short *)(g_e158_tpotbrbk + 4);
    m_E15C = *(short *)(g_e158_tpotbrbk + 10);
    g_e15e = *(short *)(g_e158_tpotbrbk + 12);
}
