/* TU f_95ee..f_95ee [0x95ee, 0x963b): generated by tools/tu.py */
struct Iter24 { int first, second, start, count, step, unused; };
struct Iter48 { int pad0, pad4, box, pad12, pad16, at20; int pad24, pad28, pad32, pad36, pad40, pad44; };
extern unsigned char *g_e158_tpotbrbk;
extern short g_e15c;
extern short g_e15e;
extern short g_e160;
extern short g_e162;
extern struct Iter24 *g_e150;
extern int g_e148;
extern int g_e14c;
extern int g_e154;
extern unsigned char *g_e2ec;
void f_8004(int *rect, unsigned char *info);
void f_8066(int *rect, unsigned char *info);
void f_82cc(void);
void f_8345_wsdytbf(void);
void f_83b1(void);

void f_95ee(void)
{
    g_e160 = *(short *)(g_e158_tpotbrbk + 2);
    g_e162 = *(short *)(g_e158_tpotbrbk + 4);
    g_e15c = *(short *)(g_e158_tpotbrbk + 10);
    g_e15e = *(short *)(g_e158_tpotbrbk + 12);
}
