/* TU f_acdd..f_b17e [0xacdd, 0xb1df): generated by tools/tu.py */
#include <stdlib.h>
extern int g_7404;
extern int g_7408;
extern int g_740c;
extern int g_7414;
extern int g_7410;
extern signed short g_7b16;
extern float g_e1fc;
extern int f_dd53(int, int);
extern void f_135e8();
extern void f_133f6();
extern void f_ae56();
extern void f_b03c(short, short, short, short, short, short);
extern unsigned char f_13324(short, short);
extern int g_e1f8;
extern int g_e200;
extern int g_e204;
extern unsigned char g_e208;
extern int g_e209;
extern int g_e20d;
extern int g_e219;
extern int g_e21d;
extern int g_e221;
extern int g_e225;

void f_acdd(float factor, int first, int last)
{
    int half;
    g_7404 = first;
    g_7408 = last;
    g_740c = g_7408 - g_7404 + 1;
    if (factor < 0.0f)
        factor = 0.0f;
    if (factor > 1.0f)
        factor = 1.0f;
    half = g_740c / 2;
    g_7414 = (int)(half * factor);
    g_7410 = -g_7414;
}

void f_ad63(float factor, int x1, int y1, int x2, int y2)
{
    g_e1fc = factor;
    f_135e8(g_7b16, x1, y1, x2, y2, g_7404);
    f_133f6(x1, y1, f_dd53(g_7404 + 1, g_7408 - 1));
    f_133f6(x2, y1, f_dd53(g_7404 + 1, g_7408 - 1));
    f_133f6(x2, y2, f_dd53(g_7404 + 1, g_7408 - 1));
    f_133f6(x1, y2, f_dd53(g_7404 + 1, g_7408 - 1));
    f_ae56(x1, y1, x2, y2);
}

void f_ae56(short x1, short y1, short x2, short y2)
{
    short midx, midy;
    if (x2 - x1 >= 2)
        goto subdivide;
    if (y2 - y1 < 2)
        return;
subdivide:
    midx = (x1 + x2) >> 1;
    midy = (y1 + y2) >> 1;
    f_b03c(x1, y1, x2, y1, midx, y1);
    f_b03c(x2, y1, x2, y2, x2, midy);
    f_b03c(x1, y2, x2, y2, midx, y2);
    f_b03c(x1, y1, x1, y2, x1, midy);
    if (f_13324(midx, midy) == g_7404) {
        f_133f6(midx, midy,
                (f_13324(x1, y1) + f_13324(x2, y1) +
                 f_13324(x2, y2) + f_13324(x1, y2)) >> 2);
    }
    f_ae56(x1, y1, midx, midy);
    f_ae56(midx, y1, x2, midy);
    f_ae56(midx, midy, x2, y2);
    f_ae56(x1, midy, midx, y2);
}

void f_b03c(short x1, short y1, short x2, short y2, short x3, short y3)
{
    if (f_13324(x3, y3) != g_7404) return;
    g_e1f8 = f_dd53(g_7410, g_7414) + ((f_13324(x1, y1) + f_13324(x2, y2)) >> 1)
           + (int)(f_dd53(-g_740c >> 1, g_740c >> 1) * g_e1fc * (float)(abs(x1 - x2) + abs(y1 - y2)))
             / (g_740c >> 1);
    if (g_e1f8 < g_7404 + 1) g_e1f8 = g_7404 + 1;
    if (g_e1f8 > g_7408 - 1) g_e1f8 = g_7408 - 1;
    f_133f6(x3, y3, g_e1f8);
}

int f_b17e(int *index, char **cursor)
{
    --*index;
    if (*index <= 0) {
        *cursor += 8;
        if ((*index = *(int *)(*cursor + 4)) < 0) {
            *cursor += *index * 8;
            *index = *(int *)(*cursor + 4);
        }
    }
    return *(int *)*cursor;
}
