/* TU f_b1df..f_b76c [0xb1df, 0xb804): generated by tools/tu.py */
typedef struct { short pad; short dx; short dy; short tail; } FRectPart;
typedef struct { short r0; short w; short h; short r1; short r2; short ox; short oy; short r3; short r4; } Frame;
extern unsigned char *g_e200;
extern unsigned char *g_e204;
extern unsigned char g_e208;
extern int g_e209;
extern int g_e20d;
extern int g_e211;
extern int g_e215;
extern int g_e219;
extern int g_e21d;
extern int g_e225;
extern void f_12cbd_pzyovjt(int, int, int);
int f_b1df(int a0, int a1, int a2);
extern int strcpy(int, int);
extern int ltoa(int, int, int);
extern int strlen(int);
extern int g_e221;

int f_b1df(int a0, int a1, int a2)
{
    unsigned char v_4;
    int v_8;
    int v_c;
    int v_10;
    unsigned char * v_14;
    unsigned char * v_18;
    v_18 = g_e204 + *(int *)(g_e200 + 0x208);
    g_e211 = a0;
    g_e215 = a1;
    if (*(short *)(v_18 + 0xa) >= 0) goto L_b228;
    g_e211 -= *(short *)(v_18 + 0xa);
L_b228:;
    if (*(short *)(v_18 + 0xc) >= 0) goto L_b23f;
    g_e215 -= *(short *)(v_18 + 0xc);
L_b23f:;
    v_4 = *(unsigned char *)(unsigned char *)(a2++);
    switch (v_4) {
        goto L_b32e;
        goto L_b32e;
        case 9:
L_b29a:;
        if (g_e208 != 1) goto L_b2bb;
        g_e211 += (*(short *)(v_18 + 2) + g_e209) << 3;
        goto L_b2c9;
L_b2bb:;
        g_e211 += g_e209 << 3;
L_b2c9:;
        goto L_b46b;
        case 32:
L_b2ce:;
        g_e211 += g_e209;
        if (g_e208 != 1) goto L_b2ef;
        g_e211 += *(short *)(v_18 + 2);
L_b2ef:;
        goto L_b46b;
        case 10:
L_b2f4:;
        g_e211 = g_e219;
        g_e215 += g_e20d;
        if (g_e208 != 1) goto L_b31f;
        g_e215 += *(short *)(v_18 + 4);
L_b31f:;
        goto L_b46b;
        case 18:
L_b324:;
        goto L_b46b;
        case 0:
L_b329:;
        goto L_b46b;
    }
L_b32e:;
    v_8 = a2;
    v_10 = v_4;
    v_c = g_e211;
L_b343:;
    if (v_10 == 0x20) goto L_b34f;
    if (v_10 != 9) goto L_b351;
L_b34f:;
    goto L_b357;
L_b351:;
    if (v_10 != 0xa) goto L_b359;
L_b357:;
    goto L_b35f;
L_b359:;
    if (v_10 != 0x12) goto L_b361;
L_b35f:;
    goto L_b367;
L_b361:;
    if (v_10 != 0) goto L_b369;
L_b367:;
    goto L_b3c1;
L_b369:;
    v_c += g_e209;
    if (g_e208 != 1) goto L_b39e;
    v_14 = g_e204 + *(int *)(g_e200 + (v_10 << 3));
    v_c += *(short *)(v_14 + 2);
L_b39e:;
    if ((v_c - 1) <= g_e21d) goto L_b3b3;
    a2 += -1;
    goto L_b2f4;
L_b3b3:;
    v_10 = *(unsigned char *)(unsigned char *)(v_8++);
    goto L_b343;
L_b3c1:;
    v_14 = g_e204 + *(int *)(g_e200 + (v_4 << 3));
    if (((*(short *)(v_14 + 0xa) + (g_e211 + *(short *)(v_14 + 2))) - 1) > g_e21d) goto L_b43a;
    f_12cbd_pzyovjt((int)v_14, g_e211, g_e215);
    g_e211 += g_e209;
    if (g_e208 != 1) goto L_b438;
    g_e211 += *(short *)(v_14 + 2);
L_b438:;
    goto L_b46b;
L_b43a:;
    g_e211 = g_e219;
    g_e215 += g_e20d;
    if (g_e208 != 1) goto L_b465;
    g_e215 += *(short *)(v_18 + 4);
L_b465:;
    a2--;
L_b46b:;
    if (g_e215 > g_e225) goto L_b47e;
    if (v_4 != 0x12) goto L_b480;
L_b47e:;
    goto L_b48a;
L_b480:;
    if (v_4 != 0) goto L_b23f;
L_b48a:;
    if (v_4 != 0) goto L_b499;
    return 0;
L_b499:;
    return a2;
}

void f_b4a7(int a0, int a1, int a2, int a3, int a4)
{
    int v_4;
    int v_8;
    unsigned char v_28[32];
    ltoa(a2, (int)((v_28 + a4) + 1), a3);
    v_8 = a4 - strlen((int)((v_28 + a4) + 1));
    if (v_8 >= 0) goto L_b4f0;
    v_8 = 0;
L_b4f0:;
    strcpy((int)(v_28 + v_8), (int)((v_28 + a4) + 1));
    v_4 = (int)v_28;
L_b50d:;
    if (v_8 > 0) goto L_b51d;
    goto L_b528;
L_b515:;
    v_8--;
    goto L_b50d;
L_b51d:;
    *(unsigned char *)(unsigned char *)(v_4++) = 0x30;
    goto L_b515;
L_b528:;
    f_b1df(a0, a1, (int)v_28);
}

void f_b541(int a0, int a1, char a2, int a3, int a4)
{
    g_e200 = a0;
    g_e204 = a1;
    g_e208 = a2;
    g_e209 = a3;
    g_e20d = a4;
}

void f_b57a(int a0, int a1, int a2, int a3)
{
    int v_4;
    if (a0 > a2) {
    v_4 = a0;
    a0 = a2;
    a2 = v_4;
    }
L_b5a0:;
    if (a1 > a3) {
    v_4 = a1;
    a1 = a3;
    a3 = v_4;
    }
L_b5ba:;
    g_e219 = a0;
    g_e21d = a2;
    g_e221 = a1;
    g_e225 = a3;
}

int f_b5df(int *r, int *bounds)
{
    if (r[0] > bounds[2]) goto outside;
    if (r[1] > bounds[3]) goto outside;
    if (r[2] < bounds[0]) goto outside;
    if (r[3] < bounds[1]) goto outside;
    return -1;
outside:
    return 0;
}

void f_b639(int *r, FRectPart a, FRectPart b)
{
    r[0] += b.dx;
    r[1] += b.dy;
    r[2] = r[0] + a.dx;
    r[3] = r[1] + a.dy;
}

short f_b680(FRectPart a, FRectPart b, int ignored, int dx, int dy,
           int right, int bottom, int maxx, int maxy)
{
    int xend;
    int yend;
    if ((xend = b.dx + dx) <= maxx)
        if ((yend = b.dy + dy) <= maxy)
            if (a.dx + xend >= right)
                if (a.dy + yend >= bottom)
                    return -1;
    return 0;
}

short f_b6e4(Frame a, int ax0, int ay0, Frame b, int bx0, int by0)
{
    int ax; int ys; int xs; int ay;
    if ((xs = bx0 + b.ox) + b.w < (ax = ax0 + a.ox)) goto outside;
    if ((ys = by0 + b.oy) + b.h < (ay = ay0 + a.oy)) goto outside;
    if (a.w + ax < xs) goto outside;
    if (a.h + ay < ys) goto outside;
    return -1;
outside:
    return 0;
}

short f_b76c(Frame a, int ax0, int ay0, Frame b, int bx0, int by0, int mx, int my, int ix, int iy)
{
    int ys; int ax; int xs; int ay;
    if ((ax = ax0 + a.ox) + mx > (xs = bx0 + b.ox) + b.w) goto outside;
    if ((ay = ay0 + a.oy) + my > (ys = by0 + b.oy) + b.h) goto outside;
    if (a.w + ax - ix < xs) goto outside;
    if (a.h + ay - iy < ys) goto outside;
    return -1;
outside:
    return 0;
}
