int collision_box_a_top;
int sprite_rect_a_right;
int sprite_bounds_a_bottom;
int collision_box_d_left;
unsigned char sprite_bounds_d_top[12];
int collision_box_c_top;
int collision_box_c_right;
int collision_rect_c_bottom;
int collision_box_a_left;
/* TU save_screen_image..save_screen_dump [0xb804, 0xbd24): generated by tools/tu.py */
#include <string.h>
#define SCREENSHOT_FORMAT_IFF_PBM 1
#define SCREENSHOT_FORMAT_COMPACT_BITMAP 5
#define IFF_FORM_ID_BE32 0x464f524d
#define IFF_PBM_FORM_TYPE 0x50424d20
#define IFF_BMHD_CHUNK_ID 0x424d4844
#define IFF_CMAP_CHUNK_ID 0x434d4150
#define IFF_BODY_CHUNK_ID 0x424f4459
#define IFF_CHUNK_HEADER_BYTES 8
#define IFF_BITMAP_HEADER_BYTES 0x14
#define IFF_PALETTE_BYTES 0x300
#define IFF_BMHD_FOLLOWING_DWORD 0x0605ff00
#define COMPACT_BITMAP_HEADER_BYTES 0x20
#define COMPACT_BITMAP_PALETTE_BYTES 0x300
#define COMPACT_BITMAP_PIXELS_OFFSET 0x320
#define COMPACT_BITMAP_PALETTE_MODE 0x01000000
#define VGA_DAC_TO_8BIT_SHIFT 2
#define DIMENSION_WORD_SHIFT 16
#define EVEN_ROW_ROUNDUP 1
#define EVEN_ROW_MASK -2
#define DWORD_ROUNDUP 3
#define DWORD_MASK -4
struct ScreenshotSignature { int first_signature_word; int second_signature_word; unsigned char terminator; };
struct CompactScreenshotPrefixBytes {
    unsigned char magic[6];
    unsigned char terminator;
    unsigned char version;
    unsigned char dimensions_be[4];
};
union CompactScreenshotPrefix {
    struct ScreenshotSignature signature;
    struct CompactScreenshotPrefixBytes fields;
};
union CompactScreenshotModeAndTail {
    int palette_mode;
    struct {
        unsigned short overlapping_word;
        unsigned char reserved[0x12];
    } fields;
};
struct CompactScreenshotHeader {
    union CompactScreenshotPrefix prefix;
    union CompactScreenshotModeAndTail mode_and_tail;
};
/* C89 trailing-byte convention: palette data starts immediately after the 32-byte header. */
struct CompactScreenshotBuffer {
    struct CompactScreenshotHeader header;
    unsigned char palette_and_pixels[1];
};
extern short keyboard_state;
int collision_box_b_right;
int collision_rect_b_bottom;
int sprite_rect_c_left;

extern int dos_memory_error;
struct DisplayModeInfo {
    short render_state;
    unsigned char plane_addresses_or_transform_a[16];
    int page_offsets_or_transform_b[4];
    int page_adjustments_or_transform_c[4];
    unsigned char page_mode_classes[4];
    int buffer_size_or_draw_parameter;
    int row_stride;
    int resolution_height;
    int screen_width;
    int screen_height;
    int viewport_left;
    int viewport_top;
    int viewport_right_or_width;
    int viewport_bottom_or_height;
    unsigned char mode_flags;
    unsigned char sequencer_plane_mask;
    unsigned char graphics_read_map;
    unsigned char reserved_vga_byte;
    unsigned char saved_video_mode;
    unsigned char graphics_controller_mode;
    unsigned char render_cache_60;
    unsigned char render_cache_61;
    unsigned char render_cache_62;
    unsigned char tail;
};
extern struct DisplayModeInfo vga_state;
void save_bios(void);
void restore_bios(void);
void save_vga_state(void);
extern unsigned char read_vga_pixel_entry(int, int);
extern int write_file_buffer(char *, void *, unsigned int);
extern void *alloc_heap_block(int);
extern void free_heap_block(void *);
extern void write_be32(int, int);
extern void read_vga_palette(unsigned char *);
int save_screen_image(char *filename);
extern signed short sound_blaster_detected;
extern unsigned char sound_blaster_irq;
/* picvec is the master PIC vector base; its linker name is retained by its owner. */
extern unsigned char picvec;
extern unsigned char slave_pic_vector_base;
extern unsigned char sndvec;
extern unsigned char sound_system_irq_line;
extern unsigned char sound_callback_interrupt_number;
extern unsigned char sound_callback_irq_line;
extern signed short scbctx;
extern signed short sndirq;
int collision_box_b_left;
int b_box_top;

extern int audio_dma_allocation_bytes;
extern int sound_callback_allocation_size;
extern void stop_audio_stream(void);
extern void stop_protracker_module(void);
/* The defining unit aliases these linker symbols to save/restore interrupt state. */
extern void restore(void *);
extern void free_dpmi_memory(int);
extern void save_irq(void *, void(*)(void));
extern void release_sound_callback(void);

/* _DATA [0x7418,0x7420) */
int screenshot_format = 1;
char *next_screenshot_filename = "\\gfx\\lbm\\dump0001.lbm";

int save_screen_image(char *filename)
{
    int result;
    unsigned char *pixel;
    int x;
    int y;
    int saved_keyboard_state;
    unsigned char *file_data;
    unsigned char *bitmap_header;
    unsigned char *palette_chunk;
    unsigned char *pixel_chunk;
    int chunk_header_bytes;
    int bitmap_header_bytes;
    int palette_bytes;
    int pixel_bytes;
    int file_bytes;
    struct CompactScreenshotBuffer *compact_image_buffer;
    int compact_image_bytes;

    saved_keyboard_state = keyboard_state;
    chunk_header_bytes = 4;
    bitmap_header_bytes = IFF_BITMAP_HEADER_BYTES;
    palette_bytes = IFF_PALETTE_BYTES;
    pixel_bytes = vga_state.screen_height * ((vga_state.screen_width + EVEN_ROW_ROUNDUP) & EVEN_ROW_MASK);
    file_bytes = ((((((pixel_bytes + IFF_CHUNK_HEADER_BYTES) + palette_bytes) + IFF_CHUNK_HEADER_BYTES) + bitmap_header_bytes) + IFF_CHUNK_HEADER_BYTES) + chunk_header_bytes) + IFF_CHUNK_HEADER_BYTES;
    compact_image_bytes = vga_state.screen_width * vga_state.screen_height + COMPACT_BITMAP_PIXELS_OFFSET;
    /* Format 1 writes an IFF PBM; format 5 writes the game's compact bitmap form. */
    switch (screenshot_format) {
    case SCREENSHOT_FORMAT_COMPACT_BITMAP:
        compact_image_buffer = alloc_heap_block(compact_image_bytes);
        if (!compact_image_buffer) {
            return dos_memory_error;
        }
        keyboard_state = -1;
        compact_image_buffer->header.prefix.signature = *(struct ScreenshotSignature *)"mhwanh\0\4";
        compact_image_buffer->header.prefix.fields.terminator = 0;
        compact_image_buffer->header.prefix.fields.version = 4;
        write_be32((int)compact_image_buffer->header.prefix.fields.dimensions_be,
                (vga_state.screen_width << DIMENSION_WORD_SHIFT) | vga_state.screen_height);
        write_be32((int)&compact_image_buffer->header.mode_and_tail.palette_mode, COMPACT_BITMAP_PALETTE_MODE);
        memset((unsigned char *)&compact_image_buffer->header.mode_and_tail + 2, 0,
               COMPACT_BITMAP_HEADER_BYTES - 0xe);
        pixel = compact_image_buffer->palette_and_pixels;
        read_vga_palette(pixel);
        for (x = 0; x < COMPACT_BITMAP_PALETTE_BYTES; x++) {
            pixel[x] = pixel[x] << VGA_DAC_TO_8BIT_SHIFT;
        }
        pixel = compact_image_buffer->palette_and_pixels + COMPACT_BITMAP_PALETTE_BYTES;
        for (y = 0; y < vga_state.screen_height; y++) {
            for (x = 0; x < vga_state.screen_width; x++) {
                *pixel++ = (unsigned char)read_vga_pixel_entry(x, y);
            }
        }
        result = write_file_buffer(filename, compact_image_buffer, compact_image_bytes);
        keyboard_state = (short)saved_keyboard_state;
        free_heap_block(compact_image_buffer);
        break;
    case SCREENSHOT_FORMAT_IFF_PBM:
        file_data = (unsigned char *)alloc_heap_block(file_bytes);
        if (!file_data) {
            return dos_memory_error;
        }
        keyboard_state = -1;
        bitmap_header = file_data + chunk_header_bytes + IFF_CHUNK_HEADER_BYTES;
        palette_chunk = bitmap_header + bitmap_header_bytes + IFF_CHUNK_HEADER_BYTES;
        pixel_chunk = palette_chunk + palette_bytes + IFF_CHUNK_HEADER_BYTES;
        write_be32((int)file_data, IFF_FORM_ID_BE32);
        write_be32((int)(file_data + 4), file_bytes - 8);
        write_be32((int)(file_data + 8), IFF_PBM_FORM_TYPE);
        write_be32((int)bitmap_header, IFF_BMHD_CHUNK_ID);
        write_be32((int)(bitmap_header + 4), bitmap_header_bytes);
        write_be32((int)(bitmap_header + 8), (vga_state.screen_width << 0x10) | vga_state.screen_height);
        *(int *)(bitmap_header + 0xc) = 0;
        bitmap_header[0x11] = 0;
        bitmap_header[0x13] = 0;
        bitmap_header[0x13] = 0;
        bitmap_header[0x10] = 8;
        bitmap_header[0x12] = 0;
        /* The original writes this dword into the eight-byte gap before CMAP. */
        *(int *)(bitmap_header + IFF_BITMAP_HEADER_BYTES) = IFF_BMHD_FOLLOWING_DWORD;
        write_be32((int)(bitmap_header + 0x18), (vga_state.row_stride << 0x10) | vga_state.resolution_height);
        write_be32((int)palette_chunk, IFF_CMAP_CHUNK_ID);
        write_be32((int)(palette_chunk + 4), palette_bytes);
        read_vga_palette(palette_chunk + 8);
        for (x = 8; x < palette_bytes + 8; x++) {
            palette_chunk[x] = palette_chunk[x] << VGA_DAC_TO_8BIT_SHIFT;
        }
        write_be32((int)pixel_chunk, IFF_BODY_CHUNK_ID);
        write_be32((int)(pixel_chunk + 4), pixel_bytes);
        pixel = pixel_chunk + 8;
        for (y = 0; y < vga_state.screen_height; y++) {
            for (x = 0; x < ((vga_state.screen_width + EVEN_ROW_ROUNDUP) & EVEN_ROW_MASK); x++) {
                *pixel++ = (unsigned char)read_vga_pixel_entry(x, y);
            }
        }
        result = write_file_buffer(filename, file_data, (file_bytes + 3) & -4);
        keyboard_state = (short)saved_keyboard_state;
        free_heap_block(file_data);
    }
    return result;
}

void write_be32(int destination, int value)
{
    (*(char *)((destination))) = ((value >> 24) & 255);
    (*(char *)((destination) + 1)) = ((value >> 16) & 255);
    (*(char *)((destination) + 2)) = ((value >> 8) & 255);
    (*(char *)((destination) + 3)) = value;
}

int save_screen_dump(char *filename)
{
    int result;
    char *extension;
    if (!filename)
        filename = next_screenshot_filename;
    result = save_screen_image(filename);
    if (result)
        return result;
    extension = strchr(filename, '.');
    if (extension) {
        if (extension[-1]++ == '9') {
            extension[-1] = '0';
            if (extension[-2]++ == '9') {
                extension[-2] = '0';
                extension[-3]++;
            }
        }
    }
    return 0;
}
