unsigned char gif_decoded_image_state[24];
int screen_page_base;
int render_page_base;
int active_video_page_buffer;
int image_buffer_cursor;
int iff_output_byte_count;
int front_image_page_buffer;
int iff_decoded_pixel_count;
int image_page_back_buffer;
int image_update_list_start;
/* TU rotate_image_buffer..render_image_with_options [0xc886, 0xca51): generated by tools/tu.py */
#include <stdlib.h>
int iff_width_pixels;
int iff_height_pixels;

int rotate_image_buffer(void);
extern void replay_sprite_update_list_entry(int);
void clear_and_rotate_image_buffer(void);
extern void process_sprite_update_list_entry();
void render_image_region(int x, int y);
extern short draw_idx;
extern void draw_bob_sprite_entry();
extern short vga_state;
extern short windows_environment_detected;
extern int windows_mode_code;
void set_img_buffers(int primary_buffer, int frame_limit, int color_depth, int front_buffer, int back_buffer);
void redraw_image_region(int x, int y);
void render_image_with_options(int display_state, int color_depth, int render_arg1, int render_arg2, int render_arg3);
void f_ca51(void);
int detect_windows_environment(void);

/* _DATA [0x746c,0x7474) */
short image_buffer_error_code = 0;
short image_color_depth = 8;
unsigned int image_buffer_record_limit = 0;

int rotate_image_buffer(void) {
    active_video_page_buffer = image_page_back_buffer;
    image_page_back_buffer = front_image_page_buffer;
    front_image_page_buffer = active_video_page_buffer;
    return front_image_page_buffer;
}

/* Keep two image pages available for drawing and display. */
void set_img_buffers(int primary_buffer, int frame_limit, int color_depth, int front_buffer, int back_buffer) {
    image_buffer_record_limit = frame_limit;
    image_update_list_start = primary_buffer;
    image_buffer_cursor = image_update_list_start;
    image_color_depth = color_depth;
    if (image_color_depth == 4) {
        front_image_page_buffer = front_buffer;
        active_video_page_buffer = front_image_page_buffer;
        *(short *)active_video_page_buffer = 0;
        image_page_back_buffer = back_buffer;
        active_video_page_buffer = image_page_back_buffer;
        *(short *)active_video_page_buffer = 0;
    }
}

void clear_and_rotate_image_buffer(void) {
    *(int *)image_buffer_cursor = 0;
    replay_sprite_update_list_entry(rotate_image_buffer());
}

void render_image_region(int x, int y) {
    process_sprite_update_list_entry(x, y, image_update_list_start, active_video_page_buffer);
    *(short *)active_video_page_buffer = 0;
    if ((image_buffer_cursor - image_update_list_start) / 10 > image_buffer_record_limit * 10)
        image_buffer_error_code = 0x407;
    image_buffer_cursor = image_update_list_start;
}

void redraw_image_region(int x, int y) {
    clear_and_rotate_image_buffer();
    render_image_region(x, y);
}

void render_image_with_options(int display_state, int color_depth, int render_arg1, int render_arg2, int render_arg3) {
    int previous_display_state = draw_idx;
    int previous_color_depth = image_color_depth;
    image_color_depth = color_depth;
    draw_idx = display_state;
    draw_bob_sprite_entry(render_arg1, render_arg2, render_arg3);
    draw_idx = previous_display_state;
    image_color_depth = previous_color_depth;
}
