unsigned char g_e2ac[24];
int u_e2E0;
int g_e2e4;
int g_e2e8;
int g_e2ec;
int g_e2cc;
int g_e2d4_o;
int g_e2d0;
int g_e2d8;
int g_e2dc;
/* TU f_c886..f_c9f4 [0xc886, 0xca51): generated by tools/tu.py */
#include <stdlib.h>
int g_e2c4;
int g_e2c8;

int f_c886(void);
extern void f_12b94(int);
void f_c936(void);
extern void f_12a9c();
void f_c960(int a, int b);
extern short g_7b16;
extern void f_12cbd_pzyovjt();
extern short g_e324;
extern short g_7474;
extern int g_7476;
void f_c8c0_pm(int a, int b, int c, int d, int e);
void f_c9ce(int a, int b);
void f_c9f4(int a, int b, int c, int d, int e);
void f_ca51(void);
int f_ca6a(void);

/* _DATA [0x746c,0x7474) */
short g_746c_mmw = 0;
short g_746e = 8;
unsigned int g_7470 = 0;

int f_c886(void) {
    g_e2e8 = g_e2d8;
    g_e2d8 = g_e2d4_o;
    g_e2d4_o = g_e2e8;
    return g_e2d4_o;
}

void f_c8c0_pm(int a, int b, int c, int d, int e) {
    g_7470 = b;
    g_e2dc = a;
    g_e2ec = g_e2dc;
    g_746e = c;
    if (g_746e == 4) {
        g_e2d4_o = d;
        g_e2e8 = g_e2d4_o;
        *(short *)g_e2e8 = 0;
        g_e2d8 = e;
        g_e2e8 = g_e2d8;
        *(short *)g_e2e8 = 0;
    }
}

void f_c936(void) {
    *(int *)g_e2ec = 0;
    f_12b94(f_c886());
}

void f_c960(int a, int b) {
    f_12a9c(a, b, g_e2dc, g_e2e8);
    *(short *)g_e2e8 = 0;
    if ((g_e2ec - g_e2dc) / 10 > g_7470 * 10)
        g_746c_mmw = 0x407;
    g_e2ec = g_e2dc;
}

void f_c9ce(int a, int b) {
    f_c936();
    f_c960(a, b);
}

void f_c9f4(int a, int b, int c, int d, int e) {
    int old_7b16 = g_7b16;
    int old_746e = g_746e;
    g_746e = b;
    g_7b16 = a;
    f_12cbd_pzyovjt(c, d, e);
    g_7b16 = old_7b16;
    g_746e = old_746e;
}
