/* TU f_ca51..f_ca51 [0xca51, 0xca6a): generated by tools/tu.py */
#include <stdlib.h>
extern unsigned char *front_image_page_buffer;
extern unsigned char *image_page_back_buffer;
extern unsigned char *active_video_page_buffer;
int rotate_image_buffer(void);
extern unsigned int image_buffer_record_limit;
extern short image_color_depth;
extern unsigned char *image_update_list_start;
extern unsigned char *image_buffer_cursor;
extern void replay_sprite_update_list_entry(int);
void clear_and_rotate_image_buffer(void);
extern short image_buffer_error_code;
extern void process_sprite_update_list_entry();
void render_image_region(int x, int y);
extern short draw_idx;
extern void draw_bob_sprite_entry();
extern short vga_state;
extern short windows_environment_detected;
extern int windows_mode_code;
void set_image_pages(unsigned char *, int, int, unsigned char *, unsigned char *);
void redraw_image_region(int x, int y);
void render_image_with_options(int display_state, int color_depth, int render_arg1, int render_arg2, int render_arg3);
int detect_windows_environment(void);

/* The matched body only reads vga_state; its original purpose is not established. */
void f_ca51(void) { if (vga_state) {} }
