/* Reserved module-player state words: no source unit reads these locations. */
int module_player_state_hk;
int module_player_state_ie;
int module_player_state_je;
int module_player_state_ke;
int module_player_state_l5;
int module_player_state_d8;
int module_player_state_e5;
int module_player_state_f5;
int module_player_state_g5;
/* TU queue_audio..start_audio_stream_dma [0xc14b, 0xc685): generated by tools/tu.py */
#include <string.h>
/* Level sound-table entries are four dwords; submit_audio_request uses one-based indices. */
struct AudioRequest {
    int source_address;
    int byte_count;
    int sample_rate;
    int playback_mode;
};

/* Typed view over the ordered globals below; other TUs and the IRQ handler import those names. */
struct AudioStreamState {
    short running;
    short stop_requested;
    int buffer_offset;
    int queued_source_address;
    int queued_byte_count;
    int queued_sample_rate;
    int queued_playback_mode;
    int active_source_address;
    int active_bytes_remaining;
    int active_sample_rate;
    int active_playback_mode;
    int dma_buffer_address;
    int dma_half_bytes;
    int last_sample_rate;
    int dma_state;
    int gap_bytes;
    int transfer_mode;
};

#define audio_stream_state (*(struct AudioStreamState *)&audio_stream_flag)
#define SOUND_HOOK_DOS_INTERRUPT_VECTOR 4
#define AUDIO_STREAM_ACTIVE -1
#define AUDIO_STREAM_IDLE 0
#define AUDIO_STREAM_STOP_PENDING -1
#define AUDIO_MODE_CHAIN_QUEUED_REQUEST -1
#define AUDIO_TRANSFER_SOURCE_BYTES -1
#define AUDIO_TRANSFER_CLEAR_BUFFER 0
#define AUDIO_DMA_GUARD_BYTES 0x10

extern short sound_blaster_detected;
/* Remaining module-player words are unreferenced in the available C sources. */
int module_player_state_a5;
char *audio_request_entries;
int module_player_state_b5;
int module_player_state_c5;

extern unsigned char sndirq[];
extern void fatal_exit(unsigned, unsigned);
extern int configure_sound_dma(int);
extern void initialize_audio_stream(void);
extern void stop_audio_stream(void);
void queue_audio(int source, int byte_count, int sample_rate, int playback_mode);
extern int audio_dma_buffer_bytes;
extern short sound_dma_transfer_count;
extern int sound_dma_buffer_address;
extern int random_in_range(int, int);
extern void submit_audio_request(int);
extern void transfer_audio_stream_block(void);
extern void start_audio_stream_dma(void);
extern void configure_sound_dma_input(void);
extern void set_sound_blaster_sample_rate(int);
extern void *alloc_heap_block(int);
extern void free_heap_block(void *);
extern int decode_gif_image();
extern short sound_dma_block_length;
extern void stop_sound_blaster_dma(void);
extern void mask_active_sound_dma_channel(void);
unsigned char *audio_dma_memory;

extern void start_sound_blaster_dma_playback(void);
extern int clear_video_bytes_entry(int, int);
/* Assembly byte-copy helper; call sites use source, destination and byte count. */
extern void mov_mem(int, int, int);

/* _DATA [0x742c,0x746c) */
short audio_stream_flag = 0;
short audio_stream_stop_flag = 0;
int audio_buffer_offset = 0;
int queued_audio_source = 0;
int queued_audio_bytes = 0;
int queued_audio_rate = 0;
int queued_audio_mode = 0;
int active_audio_source = 0;
int active_audio_bytes_remaining = 0;
int active_audio_rate = 0;
int active_audio_mode = 0;
int audio_dma_buffer = 0;
int audio_dma_half_bytes = 0;
int last_audio_sample_rate = 0;
int audio_dma_state = 0;
int audio_dma_gap_bytes = 0;
int audio_transfer_mode = -1;

void queue_audio(int source, int byte_count, int sample_rate, int playback_mode)
{
    int sound_status;
    if (sound_blaster_detected == -1) {
        if (*(short *)sndirq != -1) {
            sound_status = configure_sound_dma(SOUND_HOOK_DOS_INTERRUPT_VECTOR);
            if (sound_status != 0)
                fatal_exit(sound_status, 0);
        }
        if (audio_stream_state.stop_requested == AUDIO_STREAM_STOP_PENDING) {
            if (audio_stream_state.running == AUDIO_STREAM_ACTIVE)
                stop_audio_stream();
        }
        if (audio_stream_state.running == AUDIO_STREAM_IDLE) {
            audio_stream_state.queued_source_address = source;
            audio_stream_state.queued_byte_count = byte_count;
            audio_stream_state.queued_sample_rate = sample_rate;
            audio_stream_state.queued_playback_mode = playback_mode;
            audio_stream_state.active_source_address = audio_stream_state.queued_source_address;
            audio_stream_state.active_bytes_remaining = audio_stream_state.queued_byte_count;
            audio_stream_state.active_sample_rate = audio_stream_state.queued_sample_rate;
            audio_stream_state.active_playback_mode = audio_stream_state.queued_playback_mode;
            initialize_audio_stream();
        }
    }
}

void submit_audio_request(int index)
{
    queue_audio(((struct AudioRequest *)(audio_request_entries + index * 16 - 16))->source_address,
           ((struct AudioRequest *)(audio_request_entries + index * 16 - 16))->byte_count,
           ((struct AudioRequest *)(audio_request_entries + index * 16 - 16))->sample_rate,
           ((struct AudioRequest *)(audio_request_entries + index * 16 - 16))->playback_mode);
}

void play_audio_request_at(int request_x, int request_y)
{
    submit_audio_request(random_in_range(request_x, request_y));
}

void toggle_audio_transfer_mode(void)
{
    if (sound_blaster_detected == -1) {
        if (audio_stream_state.transfer_mode == AUDIO_TRANSFER_SOURCE_BYTES)
            audio_stream_state.transfer_mode = AUDIO_TRANSFER_CLEAR_BUFFER;
        else
            audio_stream_state.transfer_mode = AUDIO_TRANSFER_SOURCE_BYTES;
    }
}

void set_audio_transfer_mode(int value)
{
    if (sound_blaster_detected == -1) {
        if (value == 0) {
            if (audio_stream_state.transfer_mode != 0)
                audio_stream_state.transfer_mode = AUDIO_TRANSFER_CLEAR_BUFFER;
        } else if (value == -1) {
            if (audio_stream_state.transfer_mode != AUDIO_TRANSFER_SOURCE_BYTES)
                audio_stream_state.transfer_mode = AUDIO_TRANSFER_SOURCE_BYTES;
        }
    }
}

void initialize_audio_stream(void)
{
    sound_dma_buffer_address = audio_dma_memory;
    sound_dma_transfer_count = audio_dma_buffer_bytes;
    configure_sound_dma_input();
    audio_stream_state.buffer_offset = 0;
    audio_stream_state.dma_half_bytes = (audio_dma_buffer_bytes >> 1);
    audio_stream_state.gap_bytes = 0;
    audio_stream_state.dma_state = audio_stream_state.active_playback_mode;
    if (audio_stream_state.last_sample_rate != audio_stream_state.active_sample_rate) {
        audio_stream_state.last_sample_rate = audio_stream_state.active_sample_rate;
        set_sound_blaster_sample_rate(audio_stream_state.last_sample_rate);
    }
    /* Alternate DMA halves while feeding queued music or effects. */
    transfer_audio_stream_block();
    start_audio_stream_dma();
    transfer_audio_stream_block();
}

void stop_audio_stream(void)
{
    audio_stream_state.active_bytes_remaining = 0;
    audio_stream_state.dma_half_bytes = 0;
    if ((short)sound_blaster_detected == -1) {
        if ((short)audio_stream_state.running == AUDIO_STREAM_ACTIVE) {
            stop_sound_blaster_dma();
        }
        mask_active_sound_dma_channel();
    }
    audio_stream_state.running = AUDIO_STREAM_IDLE;
}

void transfer_audio_stream_block(void)
{
    int unused_4;
    int unused_8;
    if (sound_blaster_detected == -1) {
        if (audio_stream_state.active_bytes_remaining > 0) {
            audio_stream_state.dma_buffer_address = (int)(audio_dma_memory + audio_stream_state.buffer_offset);
            audio_stream_state.buffer_offset ^= audio_stream_state.dma_half_bytes;
            audio_stream_state.dma_state = audio_stream_state.active_playback_mode;
            if (audio_stream_state.dma_half_bytes <= audio_stream_state.active_bytes_remaining) {
                if (audio_stream_state.transfer_mode == AUDIO_TRANSFER_SOURCE_BYTES) {
                    mov_mem(audio_stream_state.active_source_address, audio_stream_state.dma_buffer_address, audio_stream_state.dma_half_bytes);
                } else {
                    clear_video_bytes_entry(audio_stream_state.dma_buffer_address, audio_stream_state.dma_half_bytes);
                }
                if (audio_stream_state.dma_buffer_address != (int)audio_dma_memory) {
                    memset((void *)(audio_stream_state.dma_buffer_address + audio_stream_state.dma_half_bytes), *(unsigned char *)(unsigned char *)((audio_stream_state.dma_buffer_address + audio_stream_state.dma_half_bytes) + -1), AUDIO_DMA_GUARD_BYTES);
                }
                audio_stream_state.active_source_address += audio_stream_state.dma_half_bytes;
                audio_stream_state.active_bytes_remaining -= audio_stream_state.dma_half_bytes;
            } else {
                if (audio_stream_state.transfer_mode == AUDIO_TRANSFER_SOURCE_BYTES) {
                    mov_mem(audio_stream_state.active_source_address, audio_stream_state.dma_buffer_address, audio_stream_state.active_bytes_remaining);
                } else {
                    clear_video_bytes_entry(audio_stream_state.dma_buffer_address, audio_stream_state.active_bytes_remaining);
                }
                if (audio_stream_state.dma_state == AUDIO_MODE_CHAIN_QUEUED_REQUEST) {
                    audio_stream_state.gap_bytes = audio_stream_state.dma_half_bytes - audio_stream_state.active_bytes_remaining;
                    if (audio_stream_state.transfer_mode == AUDIO_TRANSFER_SOURCE_BYTES) {
                        mov_mem(audio_stream_state.queued_source_address, audio_stream_state.dma_buffer_address + audio_stream_state.active_bytes_remaining, audio_stream_state.gap_bytes);
                    } else {
                        clear_video_bytes_entry(audio_stream_state.dma_buffer_address + audio_stream_state.active_bytes_remaining, audio_stream_state.gap_bytes);
                    }
                } else {
                    memset((void *)(audio_stream_state.dma_buffer_address + audio_stream_state.active_bytes_remaining), *(unsigned char *)(unsigned char *)((audio_stream_state.dma_buffer_address + audio_stream_state.active_bytes_remaining) + -1), audio_stream_state.dma_half_bytes - audio_stream_state.active_bytes_remaining);
                }
                audio_stream_state.active_bytes_remaining = 0;
            }
            return;
        }
        if (audio_stream_state.dma_state == AUDIO_MODE_CHAIN_QUEUED_REQUEST && audio_stream_state.queued_byte_count > 0) {
            audio_stream_state.active_source_address = audio_stream_state.queued_source_address;
            audio_stream_state.active_bytes_remaining = audio_stream_state.queued_byte_count;
            audio_stream_state.active_source_address += audio_stream_state.gap_bytes;
            audio_stream_state.active_bytes_remaining -= audio_stream_state.gap_bytes;
            audio_stream_state.active_sample_rate = audio_stream_state.queued_sample_rate;
            audio_stream_state.active_playback_mode = audio_stream_state.queued_playback_mode;
            transfer_audio_stream_block();
            return;
        }
        audio_stream_state.dma_half_bytes = 0;
    }
}

void start_audio_stream_dma(void)
{
    if (audio_stream_state.dma_half_bytes != 0) {
        if (audio_stream_state.last_sample_rate != audio_stream_state.active_sample_rate) {
            audio_stream_state.last_sample_rate = audio_stream_state.active_sample_rate;
            set_sound_blaster_sample_rate(audio_stream_state.last_sample_rate);
        }
        sound_dma_block_length = (short)audio_stream_state.dma_half_bytes;
        start_sound_blaster_dma_playback();
        audio_stream_state.running = AUDIO_STREAM_ACTIVE;
    } else {
        audio_stream_state.running = AUDIO_STREAM_IDLE;
    }
}
