int g_e290_f9;
int g_e294;
int g_e298;
int g_e29c;
int g_e2a0;
int g_e280_n;
int g_e284;
int g_e288;
int g_e28c;
/* TU queue_audio..start_audio_stream_dma [0xc14b, 0xc685): generated by tools/tu.py */
#include <string.h>
extern short sound_blaster_detected;
int g_e274_d1;
char *audio_request_table_8;
int g_e278;
int g_e27c;

extern unsigned char g_74c4[];
extern void fatal_exit(unsigned, unsigned);
extern int configure_sound_dma(int);
extern void initialize_audio_stream(void);
extern void stop_audio_stream(void);
void queue_audio(int source, int byte_count, int sample_rate, int playback_mode);
extern int audio_dma_buffer_bytes;
extern short sound_dma_transfer_count;
extern int sound_dma_buffer_address;
extern int rand_rng(int, int);
extern void submit_audio_request(int);
extern void transfer_audio_stream_block(void);
extern void start_audio_stream_dma(void);
extern void configure_sound_dma_input(void);
extern void set_sound_blaster_sample_rate(int);
extern void *alloc_heap_block(int);
extern void free_heap_block(void *);
extern int decode_gif_image();
extern short sound_dma_block_length;
extern void stop_sound_blaster_dma(void);
extern void mask_active_sound_dma_channel(void);
unsigned char *audio_dma_memory;

extern void start_sound_blaster_dma_playback(void);
extern int clear_video_bytes_entry(int, int);
extern void f_13889(int, int, int);

/* _DATA [0x742c,0x746c) */
short audio_stream_flag = 0;
short audio_stream_stop_flag = 0;
int audio_buffer_offset = 0;
int queued_audio_source = 0;
int queued_audio_bytes = 0;
int queued_audio_rate = 0;
int queued_audio_mode = 0;
int active_audio_source = 0;
int active_audio_bytes_remaining = 0;
int active_audio_rate = 0;
int active_audio_mode = 0;
int audio_dma_buffer = 0;
int audio_dma_half_bytes = 0;
int last_audio_sample_rate = 0;
int audio_dma_state = 0;
int audio_dma_gap_bytes = 0;
int audio_transfer_mode = -1;

void queue_audio(int source, int byte_count, int sample_rate, int playback_mode)
{
    int sound_status;
    if (sound_blaster_detected == -1) {
        if (*(short *)g_74c4 != -1) {
            sound_status = configure_sound_dma(4);
            if (sound_status != 0)
                fatal_exit(sound_status, 0);
        }
        if (audio_stream_stop_flag == -1) {
            if (audio_stream_flag == -1)
                stop_audio_stream();
        }
        if (audio_stream_flag == 0) {
            queued_audio_source = source;
            queued_audio_bytes = byte_count;
            queued_audio_rate = sample_rate;
            queued_audio_mode = playback_mode;
            active_audio_source = queued_audio_source;
            active_audio_bytes_remaining = queued_audio_bytes;
            active_audio_rate = queued_audio_rate;
            active_audio_mode = queued_audio_mode;
            initialize_audio_stream();
        }
    }
}

void submit_audio_request(int index)
{
    queue_audio(*(int *)(audio_request_table_8 + index * 16 - 16),
           *(int *)(audio_request_table_8 + index * 16 - 12),
           *(int *)(audio_request_table_8 + index * 16 - 8),
           *(int *)(audio_request_table_8 + index * 16 - 4));
}

void play_audio_request_at(int request_x, int request_y)
{
    submit_audio_request(rand_rng(request_x, request_y));
}

void toggle_audio_transfer_mode(void)
{
    if (sound_blaster_detected == -1) {
        if (audio_transfer_mode == -1)
            audio_transfer_mode = 0;
        else
            audio_transfer_mode = -1;
    }
}

void set_audio_transfer_mode(int value)
{
    if (sound_blaster_detected == -1) {
        if (value == 0) {
            if (audio_transfer_mode != 0)
                audio_transfer_mode = 0;
        } else if (value == -1) {
            if (audio_transfer_mode != -1)
                audio_transfer_mode = -1;
        }
    }
}

void initialize_audio_stream(void)
{
    sound_dma_buffer_address = audio_dma_memory;
    sound_dma_transfer_count = audio_dma_buffer_bytes;
    configure_sound_dma_input();
    audio_buffer_offset = 0;
    audio_dma_half_bytes = (audio_dma_buffer_bytes >> 1);
    audio_dma_gap_bytes = 0;
    audio_dma_state = active_audio_mode;
    if (last_audio_sample_rate != active_audio_rate) {
    last_audio_sample_rate = active_audio_rate;
    set_sound_blaster_sample_rate(last_audio_sample_rate);
    }
L_c397:;
    /* Alternate DMA halves while feeding queued music or effects. */
    transfer_audio_stream_block();
    start_audio_stream_dma();
    transfer_audio_stream_block();
}

void stop_audio_stream(void)
{
    active_audio_bytes_remaining = 0;
    audio_dma_half_bytes = 0;
    if ((short)sound_blaster_detected == -1) {
    if ((short)audio_stream_flag == -1) {
    stop_sound_blaster_dma();
    }
L_c3e8:;
    mask_active_sound_dma_channel();
    }
L_c3ed:;
    audio_stream_flag = 0;
}

void transfer_audio_stream_block(void)
{
    int unused_4;
    int unused_8;
    if (sound_blaster_detected != -1) goto L_c61c;
    if (active_audio_bytes_remaining <= 0) goto L_c5b9;
    audio_dma_buffer = (int)(audio_dma_memory + audio_buffer_offset);
    audio_buffer_offset ^= audio_dma_half_bytes;
    audio_dma_state = active_audio_mode;
    if (audio_dma_half_bytes > active_audio_bytes_remaining) goto L_c4e4;
    if (audio_transfer_mode != -1) goto L_c482;
    f_13889(active_audio_source, audio_dma_buffer, audio_dma_half_bytes);
    goto L_c496;
L_c482:;
    clear_video_bytes_entry(audio_dma_buffer, audio_dma_half_bytes);
L_c496:;
    if (audio_dma_buffer == (int)audio_dma_memory) goto L_c4c9;
    memset((void *)(audio_dma_buffer + audio_dma_half_bytes), *(unsigned char *)(unsigned char *)((audio_dma_buffer + audio_dma_half_bytes) + -1), 0x10);
L_c4c9:;
    active_audio_source += audio_dma_half_bytes;
    active_audio_bytes_remaining -= audio_dma_half_bytes;
    goto L_c5b7;
L_c4e4:;
    if (audio_transfer_mode != -1) goto L_c509;
    f_13889(active_audio_source, audio_dma_buffer, active_audio_bytes_remaining);
    goto L_c51d;
L_c509:;
    clear_video_bytes_entry(audio_dma_buffer, active_audio_bytes_remaining);
L_c51d:;
    if (audio_dma_state != -1) goto L_c57d;
    audio_dma_gap_bytes = audio_dma_half_bytes - active_audio_bytes_remaining;
    if (audio_transfer_mode != -1) goto L_c561;
    f_13889(queued_audio_source, audio_dma_buffer + active_audio_bytes_remaining, audio_dma_gap_bytes);
    goto L_c57b;
L_c561:;
    clear_video_bytes_entry(audio_dma_buffer + active_audio_bytes_remaining, audio_dma_gap_bytes);
L_c57b:;
    goto L_c5ad;
L_c57d:;
    memset((void *)(audio_dma_buffer + active_audio_bytes_remaining), *(unsigned char *)(unsigned char *)((audio_dma_buffer + active_audio_bytes_remaining) + -1), audio_dma_half_bytes - active_audio_bytes_remaining);
L_c5ad:;
    active_audio_bytes_remaining = 0;
L_c5b7:;
    return;
L_c5b9:;
    if (audio_dma_state != -1) goto L_c5cb;
    if (queued_audio_bytes > 0) goto L_c5cd;
L_c5cb:;
    goto L_c612;
L_c5cd:;
    active_audio_source = queued_audio_source;
    active_audio_bytes_remaining = queued_audio_bytes;
    active_audio_source += audio_dma_gap_bytes;
    active_audio_bytes_remaining -= audio_dma_gap_bytes;
    active_audio_rate = queued_audio_rate;
    active_audio_mode = queued_audio_mode;
    transfer_audio_stream_block();
    return;
L_c612:;
    audio_dma_half_bytes = 0;
L_c61c:;
}

void start_audio_stream_dma(void)
{
    if (audio_dma_half_bytes != 0) {
        if (last_audio_sample_rate != active_audio_rate) {
            last_audio_sample_rate = active_audio_rate;
            set_sound_blaster_sample_rate(last_audio_sample_rate);
        }
        sound_dma_block_length = (short)audio_dma_half_bytes;
        start_sound_blaster_dma_playback();
        audio_stream_flag = -1;
    } else {
        audio_stream_flag = 0;
    }
}
