/* TU f_ca6a..f_ca6a [0xca6a, 0xcac2): generated by tools/tu.py */
#include <stdlib.h>
extern int g_e2d4_o;
extern int g_e2d8;
extern int g_e2e8;
int f_c886(void);
extern unsigned int g_7470;
extern short g_746e;
extern int g_e2dc;
extern int g_e2ec;
extern void replay_sprite_update_list_entry(int);
void f_c936(void);
extern short g_746c_mmw;
extern void process_sprite_update_list_entry();
void f_c960(int a, int b);
extern short g_7b16;
extern void draw_bob_sprite_entry();
extern short g_e324;
void f_c8c0_pm(int a, int b, int c, int d, int e);
void f_c9ce(int a, int b);
void f_c9f4(int a, int b, int c, int d, int e);
void f_ca51(void);

/* _DATA [0x7474,0x747c) */
short g_7474 = 0;
int g_7476 = -1;

int f_ca6a(void)
{
    if (getenv("WINDIR")) {
        g_7476 = 0x310;
        g_7474 = -1;
        return g_7474;
    } else {
        g_7474 = 0;
        return g_7474;
    }
}
