unsigned char g_e2ac[24];
int u_e2E0;
int g_e2e4;
int active_image_buffer_pointer_2;
int image_buffer_cursor;
int g_e2cc;
int first_image_page_buffer_l;
int g_e2d0;
int second_image_page_buffer_4;
int image_buffer_start_1;
/* TU rotate_image_buffer..render_image_with_options [0xc886, 0xca51): generated by tools/tu.py */
#include <stdlib.h>
int g_e2c4;
int g_e2c8;

int rotate_image_buffer(void);
extern void replay_sprite_update_list_entry(int);
void clear_and_rotate_image_buffer(void);
extern void process_sprite_update_list_entry();
void render_image_region(int x, int y);
extern short g_7b16;
extern void draw_bob_sprite_entry();
extern short g_e324;
extern short windows_environment_detected;
extern int windows_mode_code;
void set_img_buffers(int primary_buffer, int frame_limit, int color_depth, int front_buffer, int back_buffer);
void redraw_image_region(int x, int y);
void render_image_with_options(int display_state, int color_depth, int render_arg1, int render_arg2, int render_arg3);
void f_ca51(void);
int detect_windows_environment(void);

/* _DATA [0x746c,0x7474) */
short image_buffer_error_code = 0;
short image_color_depth = 8;
unsigned int g_7470 = 0;

int rotate_image_buffer(void) {
    active_image_buffer_pointer_2 = second_image_page_buffer_4;
    second_image_page_buffer_4 = first_image_page_buffer_l;
    first_image_page_buffer_l = active_image_buffer_pointer_2;
    return first_image_page_buffer_l;
}

/* Keep two image pages available for drawing and display. */
void set_img_buffers(int primary_buffer, int frame_limit, int color_depth, int front_buffer, int back_buffer) {
    g_7470 = frame_limit;
    image_buffer_start_1 = primary_buffer;
    image_buffer_cursor = image_buffer_start_1;
    image_color_depth = color_depth;
    if (image_color_depth == 4) {
        first_image_page_buffer_l = front_buffer;
        active_image_buffer_pointer_2 = first_image_page_buffer_l;
        *(short *)active_image_buffer_pointer_2 = 0;
        second_image_page_buffer_4 = back_buffer;
        active_image_buffer_pointer_2 = second_image_page_buffer_4;
        *(short *)active_image_buffer_pointer_2 = 0;
    }
}

void clear_and_rotate_image_buffer(void) {
    *(int *)image_buffer_cursor = 0;
    replay_sprite_update_list_entry(rotate_image_buffer());
}

void render_image_region(int x, int y) {
    process_sprite_update_list_entry(x, y, image_buffer_start_1, active_image_buffer_pointer_2);
    *(short *)active_image_buffer_pointer_2 = 0;
    if ((image_buffer_cursor - image_buffer_start_1) / 10 > g_7470 * 10)
        image_buffer_error_code = 0x407;
    image_buffer_cursor = image_buffer_start_1;
}

void redraw_image_region(int x, int y) {
    clear_and_rotate_image_buffer();
    render_image_region(x, y);
}

void render_image_with_options(int display_state, int color_depth, int render_arg1, int render_arg2, int render_arg3) {
    int previous_display_state = g_7b16;
    int previous_color_depth = image_color_depth;
    image_color_depth = color_depth;
    g_7b16 = display_state;
    draw_bob_sprite_entry(render_arg1, render_arg2, render_arg3);
    g_7b16 = previous_display_state;
    image_color_depth = previous_color_depth;
}
