/* TU save_bios..set_video_viewport [0xdfc3, 0xe914): generated by tools/tu.py */
#pragma aux timer_interrupt_record "g_756f";
#include <i86.h>
#include <stdlib.h>
struct VideoMode { int mode_id; short bios_mode; short reserved; union { int dword; short word; unsigned char bytes[4]; } video_mode; unsigned char mode_flags; unsigned char mode_class; int width; int height; int row_bytes; int image_size; int buffer_size; };
struct DisplayModeInfo { short state; unsigned char page_base[16]; int page_start[4]; int page_display[4]; unsigned char page_class[4]; int buffer_size; int scanline_bytes; int page_height; int screen_width; int screen_height; int view_left; int view_top; int view_right; int view_bottom; unsigned char mode_flags; unsigned char saved_reg_1; unsigned char saved_reg_2; unsigned char bios_mode; unsigned char original_mode; unsigned char saved_reg_3; unsigned char current_reg_1; unsigned char current_reg_2; unsigned char current_reg_3; unsigned char tail; };
struct VgaRegisterPreset { unsigned char flags; unsigned char reserved[3]; unsigned char regs[48]; int mode_id; };
struct DisplayModeInfo vga_state;
extern void f_9afc(void);
extern void f_9b44(int);
extern void restore_bios(void);
void save_bios(void);
extern short timer_interrupt_record;
extern int clear_video_bytes_entry(int, int);
extern void set_vga_memory_layout(int);
void restore_vga_register_preset(unsigned char *p);
extern void initialize_vga_map_mask(void);
extern void set_draw_page(short);
extern void clear_pal(void);
extern void _disable(void);
extern void _enable(void);
extern int update_crtc_register(unsigned char, unsigned char, unsigned char);
extern int old_display_mode;
extern int fill_clipped_vga_rectangle();
extern short disp_idx;
extern short draw_idx;
extern void set_vga_display_start(int);
extern void advance_video_page_indices(void);
extern int vga_crtc_offset;
extern int update_attr_register(unsigned char, unsigned char, unsigned char);
extern void outpw(int, int);
extern int fade_start;
extern int fade_end;
extern int fade_delay;
extern void write_dac_palette(void *, int, int, int);
extern void f_9d40(short);
extern short vga_palette_saved;
extern int outp(int, int);
extern int inp(int);
extern void write_pal(void *);
extern void set_pal_rgb(unsigned char, unsigned char, unsigned char, unsigned char);
extern short flip_src;
extern short flip_dst;
int set_display_mode(int requested_mode_id);
/* Preserve the legacy object name while keeping the source routine readable. */
void save_vga_state(void);
void restore_vga_register_state(void);
void set_video_viewport(int left, int top, int right, int bottom);
void set_video_display_address(int a, int b);
void set_vga_horizontal_panning(int pixel_pan);
void set_vga_horizontal_pan_register(unsigned char pixel_pan);
void set_vga_scanline_stride(int scanline_bytes);
void write_vga_mode_register(unsigned char mode_register_value);
void set_vga_line_compare(int scanline);
void set_vga_max_scan_line(unsigned char maximum_scanline);
void fade_pal(void *a, int x, int y, int step);
void read_vga_palette(unsigned char *p);
void apply_saved_palette_once(void *palette_bytes);
void show_page(void);
void display_next_video_page(void);
void draw_page(int page_index);
extern short g_7b12;
extern short page2;
extern short page3;
extern short g_7b1c;
extern short g_7b1e;
extern short video_page_2_index;
extern short vp3idx;

/* _DATA [0x75c8,0x7b00) */
short video_restore_registered = 0;
short bios_video_mode_saved = 0;
short vga_register_state_saved = 0;
/* Game mode IDs pair BIOS requests with geometry and page sizes. */
struct VideoMode video_mode_table[16] = {
    {0, 0, 0, {0x13}, 8, 0, 0x140, 0xc8, 0x140, 0x10000, 0xfa00},
    {1, 0, 0, {0x13}, 8, 1, 0x140, 0xc8, 0x140, 0x10000, 0xfa00},
    {2, 0, 0, {0x13}, 8, 1, 0x140, 0xf0, 0x140, 0x12c00, 0x12c00},
    {3, 0, 0, {0x13}, 8, 1, 0x168, 0xc8, 0x168, 0x11940, 0x11940},
    {4, 0, 0, {0x13}, 8, 1, 0x168, 0xf0, 0x168, 0x15180, 0x15180},
    {5, 0, 0, {0x13}, 8, 1, 0x140, 0x190, 0x140, 0x20000, 0x1f400},
    {6, 0, 0, {0x13}, 8, 1, 0x140, 0x1e0, 0x140, 0, 0x25800},
    {7, 0, 0, {0x13}, 8, 1, 0x168, 0x190, 0x168, 0, 0x23280},
    {8, 0, 0, {0x13}, 8, 1, 0x168, 0x1e0, 0x168, 0, 0x2a300},
    {9, 0, 0, {0x13}, 8, 1, 0x100, 0xc8, 0x100, 0x10000, 0xc800},
    {0xa, 0, 0, {0x13}, 8, 1, 0x100, 0xf0, 0x100, 0x10000, 0xf000},
    {0xb, 0, 0, {0x13}, 8, 1, 0x100, 0x100, 0x100, 0x10000, 0x10000},
    {0xc, 0, 0, {0x13}, 8, 1, 0x140, 0xc0, 0x148, 0x10000, 0xf600},
    {0xd, 0, 0, {0x13}, 8, 8, 0x5a, 0x3c, 0x5a, 0x4000, 0x1518},
    {0xe, 0, 0, {0x13}, 8, 8, 0x50, 0x32, 0x50, 0x4000, 0xfa0},
    {-1, 0, 0, {0}, 0, 0, 0, 0, 0, 0, 0},
};
/* Each mask selects the VGA register groups to restore for a mode. */
struct VgaRegisterPreset vga_register_presets[14] = {
    {0x11, {0}, {0x5f, 0x4f, 0x50, 0x82, 0x54, 0x80, 0xbf, 0x1f, 0, 0x41, 0, 0, 0, 0, 0, 0x31, 0x9c, 0x8e, 0x8f, 0x28, 0x40, 0x96, 0xb9, 0xa3, 0xff, 3, 1, 0xf, 0, 0xe, 0x41, 0, 0xf, 0, 0, 0, 0, 0, 0, 0, 0x40, 5, 0xf, 0xff, 0x63}, 0},
    {0x11, {0}, {0x5f, 0x4f, 0x50, 0x82, 0x54, 0x80, 0xbf, 0x1f, 0, 0x41, 0, 0, 0, 0, 0, 0x31, 0x9c, 0x8e, 0x8f, 0x28, 0x40, 0x96, 0xb9, 0xa3, 0xff, 3, 1, 0xf, 0, 0xe, 0x41, 0, 0xf, 0, 0, 0, 0, 0, 0, 0, 0x40, 5, 0xf, 0xff, 0x63}, 1},
    {0x11, {0}, {0x5f, 0x4f, 0x50, 0x82, 0x54, 0x80, 0xb, 0x3e, 0, 0x41, 0, 0, 0, 0, 0, 0x31, 0xea, 0x8c, 0xdf, 0x28, 0x40, 0xe7, 4, 0xa3, 0xff, 3, 1, 0xf, 0, 0xe, 0x41, 0, 0xf, 0, 0, 0, 0, 0, 0, 0, 0x40, 5, 0xf, 0xff, 0xe3}, 2},
    {0x11, {0}, {0x6a, 0x59, 0x5a, 0x89, 0x61, 0x80, 0xbf, 0x1f, 0, 0x41, 0, 0, 0, 0, 0, 0x31, 0x9c, 0x8e, 0x8f, 0x2d, 0x40, 0x96, 0xb9, 0xa3, 0xff, 3, 1, 0xf, 0, 0xe, 0x41, 0, 0xf, 0, 0, 0, 0, 0, 0, 0, 0x40, 5, 0xf, 0xff, 0x63}, 3},
    {0x11, {0}, {0x6a, 0x59, 0x5a, 0x89, 0x61, 0x8e, 0xd, 0x3e, 0, 0x41, 0, 0, 0, 0, 0, 0x31, 0xea, 0xac, 0xdf, 0x2d, 0x40, 0xe7, 4, 0xa3, 0xff, 3, 1, 0xf, 0, 0xe, 0x41, 0, 0xf, 0, 0, 0, 0, 0, 0, 0, 0x40, 5, 0xf, 0xff, 0xe3}, 4},
    {0x11, {0}, {0x5f, 0x4f, 0x50, 0x82, 0x54, 0x80, 0xbf, 0x1f, 0, 0x40, 0, 0, 0, 0, 0, 0x31, 0x9c, 0x8e, 0x8f, 0x28, 0x40, 0x96, 0xb9, 0xa3, 0xff, 3, 1, 0xf, 0, 0xe, 0x41, 0, 0xf, 0, 0, 0, 0, 0, 0, 0, 0x40, 5, 0xf, 0xff, 0x63}, 5},
    {0x11, {0}, {0x5f, 0x4f, 0x50, 0x82, 0x54, 0x80, 0xb, 0x3e, 0, 0x40, 0, 0, 0, 0, 0, 0x31, 0xea, 0x8c, 0xdf, 0x28, 0x40, 0xe7, 4, 0xa3, 0xff, 3, 1, 0xf, 0, 0xe, 0x41, 0, 0xf, 0, 0, 0, 0, 0, 0, 0, 0x40, 5, 0xf, 0xff, 0xe3}, 6},
    {0x11, {0}, {0x6a, 0x59, 0x5a, 0x89, 0x61, 0x80, 0xbf, 0x1f, 0, 0x40, 0, 0, 0, 0, 0, 0x31, 0x9c, 0x8e, 0x8f, 0x2d, 0x40, 0x96, 0xb9, 0xa3, 0xff, 3, 1, 0xf, 0, 0xe, 0x41, 0, 0xf, 0, 0, 0, 0, 0, 0, 0, 0x40, 5, 0xf, 0xff, 0x63}, 7},
    {0x11, {0}, {0x6a, 0x59, 0x5a, 0x89, 0x61, 0x8e, 0xd, 0x3e, 0, 0x40, 0, 0, 0, 0, 0, 0x31, 0xea, 0xac, 0xdf, 0x2d, 0x40, 0xe7, 4, 0xa3, 0xff, 3, 1, 0xf, 0, 0xe, 0x41, 0, 0xf, 0, 0, 0, 0, 0, 0, 0, 0x40, 5, 0xf, 0xff, 0xe3}, 8},
    {0x11, {0}, {0x5d, 0x3f, 0x40, 0x80, 0x4f, 0x80, 0xbf, 0x1f, 0, 0x41, 0, 0, 0, 0, 0, 0x31, 0x9c, 0x8e, 0x8f, 0x20, 0x40, 0x96, 0xb9, 0xa3, 0xff, 3, 1, 0xf, 0, 0xe, 0x41, 0, 0xf, 0, 0, 0, 0, 0, 0, 0, 0x40, 5, 0xf, 0xff, 0x63}, 9},
    {0x11, {0}, {0x5f, 0x4f, 0x50, 0x82, 0x54, 0x80, 0xbf, 0x1f, 0, 0x41, 0, 0, 0, 0, 0, 0x31, 0x9c, 0x8e, 0x8f, 0x29, 0x40, 0x7f, 0xb9, 0xa3, 0xff, 3, 1, 0xf, 0, 0xe, 0x41, 0, 0xf, 0, 0, 0, 0, 0, 0, 0, 0x40, 5, 0xf, 0xff, 0x63}, 0xc},
    {0x11, {0}, {0x6a, 0x59, 0x5a, 0x89, 0x61, 0x8e, 0xd, 0x3e, 0, 0x47, 0, 0, 0, 0, 0, 0x31, 0xea, 0xac, 0xdf, 0x2d, 0x40, 0xe7, 4, 0xa3, 0xff, 3, 1, 0xf, 0, 0xe, 0x41, 0, 0xf, 0, 0, 0, 0, 0, 0, 0, 0x40, 5, 0xf, 0xff, 0xe3}, 0xd},
    {0x11, {0}, {0x5f, 0x4f, 0x50, 0x82, 0x54, 0x80, 0xbf, 0x1f, 0, 0x47, 0, 0, 0, 0, 0, 0x31, 0x9c, 0x8e, 0x8f, 0x28, 0x40, 0x96, 0xb9, 0xa3, 0xff, 3, 1, 0xf, 0, 0xe, 0x41, 0, 0xf, 0, 0, 0, 0, 0, 0, 0, 0x40, 5, 0xf, 0xff, 0x63}, 0xe},
    {0, {0}, {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0xa, 0xb, 0xc, 0xd, 0xe, 0xf, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0xaa, 0xbb, 0xcc, 0xdd}, -1},
};
short g_7afe = 0;

void save_bios(void) {
    union REGS regs;
    if (bios_video_mode_saved != -1) {
        regs.h.ah = 0x0f;
        int386(0x10, &regs, &regs);
        vga_state.original_mode = regs.h.al;
        if (video_restore_registered == 0) {
            atexit(restore_bios);
            video_restore_registered = -1;
        }
        bios_video_mode_saved = -1;
    }
}

void restore_bios(void) {
    int timer_was_active = timer_interrupt_record;
    union REGS regs;
    if (bios_video_mode_saved == -1) {
        f_9afc();
        regs.h.ah = 0;
        vga_state.bios_mode = vga_state.original_mode;
        regs.h.al = vga_state.bios_mode;
        int386(0x10, &regs, &regs);
        bios_video_mode_saved = 1;
        if (timer_was_active == -1)
            f_9b44(0);
    }
}

int set_display_mode(int requested_mode_id)
{
    int video_memory_limit;
    int previous_timer_state;
    int mode_index;
    int page_index;
    int preset_index;
    int frame_buffer_base;
    int page_offset;
    unsigned char bios_register_block[28];
    previous_timer_state = timer_interrupt_record;
    mode_index = 0;
    if (bios_video_mode_saved != -1) {
        save_bios();
    }
    while (video_mode_table[mode_index].mode_id != requested_mode_id && video_mode_table[mode_index].mode_id != -1) {
        mode_index++;
    }
    if (video_mode_table[mode_index].mode_id != -1) {
        f_9afc();
        clear_pal();
        clear_video_bytes_entry(0xa0000, 0x10000);
        if (vga_state.bios_mode != video_mode_table[mode_index].video_mode.dword) {
            vga_state.bios_mode = video_mode_table[mode_index].video_mode.bytes[0];
            *(short *)bios_register_block = video_mode_table[mode_index].video_mode.word;
            *(short *)(bios_register_block + 4) = video_mode_table[mode_index].bios_mode;
            int386(0x10, (void *)bios_register_block, (void *)bios_register_block);
        }
        clear_video_bytes_entry(0xa0000, 0x10000);
        vga_state.screen_width = video_mode_table[mode_index].width;
        vga_state.screen_height = video_mode_table[mode_index].height;
        vga_state.scanline_bytes = video_mode_table[mode_index].row_bytes;
        vga_state.page_height = vga_state.screen_height;
        vga_state.view_left = 0;
        vga_state.view_top = 0;
        vga_state.view_right = vga_state.screen_width - 1;
        vga_state.view_bottom = vga_state.screen_height - 1;
        vga_state.buffer_size = video_mode_table[mode_index].buffer_size;
        switch (video_mode_table[mode_index].mode_class) {
        case 0:
            video_memory_limit = 0xffff;
            frame_buffer_base = 0xa0000;
            set_vga_memory_layout(0);
            break;
        case 1:
            video_memory_limit = 0x3ffff;
            frame_buffer_base = 0x280000;
            set_vga_memory_layout(1);
            break;
        case 8:
            video_memory_limit = 0xffff;
            frame_buffer_base = 0xa0000;
            set_vga_memory_layout(1);
            vga_state.state = 0;
        }
        vga_state.mode_flags = video_mode_table[mode_index].mode_flags;
        page_offset = 0;
        for (page_index = 0; page_index < 4; page_index++) {
            *(int *)(vga_state.page_base + (page_index << 2)) = frame_buffer_base;
            vga_state.page_start[page_index] = page_offset;
            vga_state.page_display[page_index] = 0;
            *(unsigned char *)(vga_state.page_class + page_index) = video_mode_table[mode_index].mode_class;
            page_offset += video_mode_table[mode_index].image_size;
            if ((page_offset + vga_state.buffer_size) > video_memory_limit) {
                page_offset -= video_mode_table[mode_index].image_size;
            }
            set_draw_page((short)page_index);
        }
        initialize_vga_map_mask();
        preset_index = 0;
        do {
            if (vga_register_presets[preset_index].mode_id == video_mode_table[mode_index].mode_id) {
                restore_vga_register_preset((unsigned char *)&vga_register_presets[preset_index]);
                switch (video_mode_table[mode_index].mode_class) {
                case 0:
                    set_vga_memory_layout(0);
                    break;
                case 1:
                    set_vga_memory_layout(1);
                    break;
                case 8:
                    set_vga_memory_layout(1);
                    vga_state.state = 0;
                }
            }
            ++preset_index;
        } while (vga_register_presets[preset_index].mode_id != -1);
        if (previous_timer_state == -1) {
            f_9b44(0);
        }
        return 0;
    }
    if (requested_mode_id) {
        return 0x503;
    }
    return 0;
}

void save_vga_state(void) {
    vga_state.saved_reg_2 = vga_state.current_reg_3;
    vga_state.saved_reg_1 = vga_state.current_reg_2;
    vga_state.saved_reg_3 = vga_state.current_reg_1;
    vga_register_state_saved = -1;
}

void restore_vga_register_state(void) {
    extern void set_gc_read_map(unsigned int);
    extern void set_seq_plane_mask(unsigned int);
    extern void set_gc_mode(unsigned int);
    if (vga_register_state_saved == -1) {
        set_gc_read_map(vga_state.saved_reg_2);
        set_seq_plane_mask(vga_state.saved_reg_1);
        set_gc_mode(vga_state.saved_reg_3);
        vga_register_state_saved = 1;
    }
}

void set_vga_memory_layout(int chain4_enabled)
{
    extern void set_gc_read_map(short);
    extern void set_seq_plane_mask(short);
    extern void set_gc_mode(short);
    if (chain4_enabled == 1) {
        _disable();
        outp(0x3ce, 5);
        outp(0x3cf, inp(0x3cf) & 0xef);
        outp(0x3ce, 6);
        outp(0x3cf, inp(0x3cf) & 0xfd);
        outp(0x3c4, 4);
        outp(0x3c5, (inp(0x3c5) & 0xf7) | 4);
        outp(0x3d4, 0x14);
        outp(0x3d5, inp(0x3d5) & 0xbf);
        outp(0x3d4, 0x17);
        outp(0x3d5, inp(0x3d5) | 0x40);
        _enable();
    } else if (!chain4_enabled) {
        _disable();
        outp(0x3ce, 5);
        outp(0x3cf, inp(0x3cf) | -0xf0);
        outp(0x3ce, 6);
        outp(0x3cf, inp(0x3cf) | -0xfe);
        outp(0x3c4, 4);
        outp(0x3c5, inp(0x3c5) | -0xf8);
        outp(0x3d4, 0x14);
        outp(0x3d5, inp(0x3d5) | -0xc0);
        outp(0x3d4, 0x17);
        outp(0x3d5, inp(0x3d5) & -0x41);
        _enable();
    }
    set_gc_read_map(0);
    set_seq_plane_mask(0xf);
    set_gc_mode(0x40);
    vga_state.state = (unsigned short)chain4_enabled;
}

void restore_vga_register_preset(unsigned char *preset_bytes) {
    int register_index;
    initialize_vga_map_mask();
    _disable();
    if (preset_bytes[0] & 1) {
        for (register_index = 0; register_index <= 0x18; register_index++)
            outpw(0x3d4, ((unsigned int)preset_bytes[register_index + 4] << 8) | register_index);
    }
    if (preset_bytes[0] & 2) {
        for (register_index = 0; register_index <= 4; register_index++)
            outpw(0x3c4, ((unsigned int)preset_bytes[register_index + 0x1d] << 8) | register_index);
    }
    if (preset_bytes[0] & 4) {
        for (register_index = 0x10; register_index <= 0x14; register_index++) {
            outp(0x3c0, register_index | 0x20);
            outp(0x3c0, preset_bytes[register_index + 0x22]);
        }
    }
    if (preset_bytes[0] & 8) {
        for (register_index = 0; register_index <= 8; register_index++)
            outpw(0x3c4, ((unsigned int)preset_bytes[register_index + 0x27] << 8) | register_index);
    }
    if (preset_bytes[0] & 0x10) {
        outp(0x3c2, preset_bytes[0x30]);
        outp(0x3da, preset_bytes[0x31]);
    }
    _enable();
    initialize_vga_map_mask();
}

void initialize_vga_map_mask(void)
{
    update_crtc_register(3, 0xff, 0x80);
    update_crtc_register(0x11, 0x7f, 0);
}

void set_draw_page(short page_index)
{
    fill_clipped_vga_rectangle((short)page_index, vga_state.view_left, vga_state.view_top, vga_state.view_right, vga_state.view_bottom, 0);
}

void set_video_viewport(int left, int top, int right, int bottom) {
    int t;
    if (left > right) { t = left; left = right; right = t; }
    if (top > bottom) { t = top; top = bottom; bottom = t; }
    vga_state.view_left = left;
    vga_state.view_right = right;
    vga_state.view_top = top;
    vga_state.view_bottom = bottom;
    vga_state.screen_height = vga_state.view_bottom - vga_state.view_top + 1;
    vga_state.screen_width = vga_state.view_right - vga_state.view_left + 1;
}
