/* TU save_bios..set_vga_display_start [0xdfc3, 0xeeac): generated by tools/tu.py */
#pragma aux timer_interrupt_record "g_756f";
#include <i86.h>
#include <stdlib.h>
extern struct DisplayModeInfo vga_state;
struct VideoMode {
    int mode_id;
    short bios_mode;
    short reserved;
    union { int dword; short word; unsigned char bytes[4]; } video_mode;
    unsigned char mode_flags;
    unsigned char mode_class;
    int width;
    int height;
    int row_bytes;
    int image_size;
    int buffer_size;
};

struct DisplayModeInfo {
    short state;
    unsigned char page_base[16];
    int page_start[4];
    int page_display[4];
    unsigned char page_class[4];
    int buffer_size;
    int scanline_bytes;
    int page_height;
    int screen_width;
    int screen_height;
    int view_left;
    int view_top;
    int view_right;
    int view_bottom;
    unsigned char mode_flags;
    unsigned char saved_reg_1;
    unsigned char saved_reg_2;
    unsigned char bios_mode;
    unsigned char original_mode;
    unsigned char saved_reg_3;
    unsigned char current_reg_1;
    unsigned char current_reg_2;
    unsigned char current_reg_3;
    unsigned char tail;
};
struct VgaRegisterPreset {
    unsigned char flags;
    unsigned char reserved[3];
    unsigned char regs[48];
    int mode_id;
};


extern short bios_video_mode_saved;
extern short video_restore_registered;

extern void f_9afc(void);
extern void f_9b44(int);
extern void restore_bios(void);
void save_bios(void);
extern short timer_interrupt_record;

extern struct VideoMode video_mode_table[];









extern struct VgaRegisterPreset vga_register_presets[];
















extern int clear_video_bytes_entry(int, int);
extern void set_vga_memory_layout(int);
void restore_vga_register_preset(unsigned char *p);
extern void initialize_vga_map_mask(void);
extern void set_draw_page(short);
extern void clear_pal(void);






extern short vga_register_state_saved;



extern void _disable(void);
extern void _enable(void);
extern int update_crtc_register(unsigned char, unsigned char, unsigned char);
extern int old_display_mode;
extern int fill_clipped_vga_rectangle();
extern short disp_idx;
extern short draw_idx;
extern void set_vga_display_start(int);
extern void advance_video_page_indices(void);

extern int update_attr_register(unsigned char, unsigned char, unsigned char);
extern void outpw(int, int);
extern int fade_start;
extern int fade_end;
extern int fade_delay;
extern void write_dac_palette(void *, int, int, int);
extern void f_9d40(short);
extern short vga_palette_saved;
extern int outp(int, int);
extern int inp(int);
extern void write_pal(void *);
extern void set_pal_rgb(unsigned char, unsigned char, unsigned char, unsigned char);
extern short flip_src;
extern short flip_dst;

void save_bios(void);

void restore_bios(void);

int set_display_mode(int requested_mode_id);

void save_vga_state(void);

void restore_vga_register_state(void);

void set_vga_memory_layout(int layout);

void restore_vga_register_preset(unsigned char *p);

void initialize_vga_map_mask(void);

void set_draw_page(short page_index);

void set_video_viewport(int left, int top, int right, int bottom);

/* _DATA [0x7b00,0x7b04) */
int vga_crtc_offset = 0;

void set_video_display_address(int screen_x, int screen_y) {
    disp_idx = draw_idx;
    set_vga_display_start(screen_y * vga_state.scanline_bytes + vga_state.page_start[disp_idx] + screen_x);
    advance_video_page_indices();
}

void set_vga_horizontal_panning(int new_panning)
{
    extern void set_vga_horizontal_pan_register();
    set_vga_horizontal_pan_register(vga_crtc_offset);
    vga_crtc_offset = new_panning;
}

void set_vga_horizontal_pan_register(unsigned char pixel_pan) {
    update_attr_register(0x13, 0xf0, (pixel_pan & 3) << 1);
}

void set_vga_scanline_stride(int scanline_bytes) {
    outpw(0x3d4, ((scanline_bytes >> 3) << 8) | 0x13);
}

void write_vga_mode_register(unsigned char mode_register_value);

void set_vga_line_compare(int scanline);

void set_vga_max_scan_line(unsigned char maximum_scanline);

void fade_pal(void *a, int x, int y, int step);

void read_vga_palette(unsigned char *p);

void apply_saved_palette_once(void *palette_bytes);

void write_pal(void *palette_bytes);

void clear_pal(void);

void set_pal_rgb(unsigned char a, unsigned char b, unsigned char c, unsigned char d);

void show_page(void);

void advance_video_page_indices(void);

void display_next_video_page(void);

void draw_page(int page_index);

void set_vga_display_start(int start_address);
/* T14 initialized data reconstructed as mode records and VGA register presets. */
extern short video_restore_registered;
extern short bios_video_mode_saved;
extern short vga_register_state_saved;
extern struct VideoMode video_mode_table[16];
extern struct VgaRegisterPreset vga_register_presets[14];
extern short g_7afe;
extern int fade_start;
extern int fade_end;
extern int fade_delay;
extern short vga_palette_saved;
extern short g_7b12;
extern short disp_idx;
extern short draw_idx;
extern short page2;
extern short page3;
extern short g_7b1c;
extern short g_7b1e;
extern short flip_src;
extern short flip_dst;
extern short video_page_2_index;
extern short vp3idx;
extern struct DisplayModeInfo vga_state;
