/* TU write_vga_mode_register..set_vga_palette_rgb [0xe9dd, 0xed38): generated by tools/tu.py */
#include <i86.h>
#include <stdlib.h>
#define VGA_CRTC_INDEX_PORT 0x3d4
#define VGA_CRTC_MODE_CONTROL 0x17
#define VGA_CRTC_LINE_COMPARE 0x18
#define VGA_CRTC_OVERFLOW 0x07
#define VGA_CRTC_MAX_SCAN_LINE 0x09
#define VGA_DAC_READ_INDEX_PORT 0x3c7
#define VGA_DAC_WRITE_INDEX_PORT 0x3c8
#define VGA_DAC_DATA_PORT 0x3c9
#define VGA_DAC_COLOR_COUNT 0x100
#define VGA_DAC_COMPONENT_COUNT 3
#define VGA_DAC_MAX_COMPONENT 63
struct VideoModeInfo {
    int mode_id;
    short bios_mode_number;
    short reserved;
    union { int raw; short word; unsigned char bytes[4]; } bios_mode_data;
    unsigned char mode_flags;
    unsigned char storage_class;
    int pixel_width;
    int pixel_height;
    int scanline_bytes;
    int image_bytes;
    int page_buffer_bytes;
};
struct DisplayModeInfo {
    short render_state;
    int plane_addresses_or_transform_a[4];
    int page_offsets_or_transform_b[4];
    int page_adjustments_or_transform_c[4];
    unsigned char page_mode_classes[4];
    int buffer_size_or_draw_parameter;
    int row_stride;
    int resolution_height;
    int screen_width;
    int screen_height;
    int viewport_left;
    int viewport_top;
    int viewport_right_or_width;
    int viewport_bottom_or_height;
    unsigned char mode_flags;
    unsigned char sequencer_plane_mask;
    unsigned char graphics_read_map;
    unsigned char reserved_vga_byte;
    unsigned char saved_video_mode;
    unsigned char graphics_controller_mode;
    unsigned char render_cache_60;
    unsigned char render_cache_61;
    unsigned char render_cache_62;
    unsigned char tail;
};
struct VgaRegisterPreset {
    unsigned char restore_groups;
    unsigned char reserved[3];
    unsigned char register_bytes[48];
    int mode_id;
};
extern struct DisplayModeInfo vga_state;
extern short bios_video_mode_saved;
extern short video_restore_registered;
/* Timer callbacks and retrace waits bracket BIOS mode changes. */
extern void reset_timer(void);
extern void start_timer(int);
extern void restore_bios(void);
void save_bios(void);
extern short tmr_rec;
extern struct VideoModeInfo video_mode_table[];
extern struct VgaRegisterPreset vga_register_presets[];
extern int clear_video_bytes_entry(int, int);
extern void set_vga_memory_layout(int);
void restore_vga_register_preset(struct VgaRegisterPreset *preset);
extern void initialize_vga_map_mask(void);
extern void clear_draw_page(short);
extern void clear_vga_palette(void);
extern short vga_register_state_saved;
extern void _disable(void);
extern void _enable(void);
extern int update_crtc_register(unsigned char, unsigned char, unsigned char);
extern int old_display_mode;
extern int fill_clipped_vga_rectangle();
extern short page_idx;
extern short drawpage;
extern void set_vga_display_start(int);
extern void advance_video_page_indices(void);
extern int pending_horizontal_pan;
extern int update_attr_register(unsigned char, unsigned char, unsigned char);
extern void outpw(int, int);
extern void write_dac_palette(void *, int, int, int);
/* Delay through the logical timer tick service. */
extern void wait_for_tick(short);
extern int outp(int, int);
extern int inp(int);
extern void write_vga_palette(void *);
extern void set_vga_palette_rgb(unsigned char, unsigned char, unsigned char, unsigned char);
extern short flip_source_page_index;
extern short flip_destination_page_index;
int set_display_mode(int requested_mode_id);
void save_vga_state(void);
void restore_vga_register_state(void);
void set_video_viewport(int left, int top, int right, int bottom);
void set_video_display_address(int screen_x, int screen_y);
void set_vga_horizontal_panning(int pixel_pan);
void set_vga_horizontal_pan_register(unsigned char pixel_pan);
void set_vga_scanline_stride(int scanline_bytes);
void write_vga_mode_register(unsigned char mode_register_value);
void set_vga_line_compare(int scanline);
void set_vga_max_scan_line(unsigned char maximum_scanline);
void fade_dac(void *palette_bytes, int start_level, int end_level, int fade_step);
void read_vga_palette(unsigned char *palette_bytes);
void apply_saved_palette_once(void *palette_bytes);
void show_page(void);
void display_next_video_page(void);
void draw_page(int page_index);
extern short g_7afe;
extern short page2;
extern short page3;
extern short g_7b1c;
extern short g_7b1e;
extern short stored_page_2_index;
extern short page_3;

/* _DATA [0x7b04,0x7b14) */
int palette_fade_first_index = 0;
int palette_fade_end_index = VGA_DAC_COLOR_COUNT;
int palette_fade_delay_ticks = 1;
short vga_palette_saved = 0;
/* Adjacent initialized video word; its original purpose is unknown. */
short g_7b12 = 0;

void write_vga_mode_register(unsigned char mode_register_value) {
    update_crtc_register(VGA_CRTC_MODE_CONTROL, 0, mode_register_value);
}

void set_vga_line_compare(int scanline) {
    update_crtc_register(VGA_CRTC_LINE_COMPARE, 0, (unsigned char)scanline);
    update_crtc_register(VGA_CRTC_OVERFLOW, 0xef, (scanline & 0x100) >> 4);
    update_crtc_register(VGA_CRTC_MAX_SCAN_LINE, 0xbf, (scanline & 0x200) >> 3);
}

void set_vga_max_scan_line(unsigned char maximum_scanline) {
    update_crtc_register(VGA_CRTC_MAX_SCAN_LINE, 0xe0, maximum_scanline & 0x1f);
}

void fade_dac(void *palette_bytes, int start_level, int end_level, int fade_step) {
    int delay_index;
    if (start_level < -VGA_DAC_MAX_COMPONENT) start_level = -VGA_DAC_MAX_COMPONENT;
    if (start_level > VGA_DAC_MAX_COMPONENT) start_level = VGA_DAC_MAX_COMPONENT;
    if (end_level < -VGA_DAC_MAX_COMPONENT) end_level = -VGA_DAC_MAX_COMPONENT;
    if (end_level > VGA_DAC_MAX_COMPONENT) end_level = VGA_DAC_MAX_COMPONENT;
    if (palette_fade_first_index < 0) palette_fade_first_index = 0;
    if (palette_fade_first_index > VGA_DAC_COLOR_COUNT - 1) palette_fade_first_index = VGA_DAC_COLOR_COUNT - 1;
    if (palette_fade_end_index < 1) palette_fade_end_index = 1;
    if (palette_fade_end_index > VGA_DAC_COLOR_COUNT) palette_fade_end_index = VGA_DAC_COLOR_COUNT;
    if (!fade_step) {
        if (end_level - start_level > 0) fade_step = 1;
        else fade_step = -1;
    }
    do {
        start_level += fade_step;
        if (fade_step > 0) {
            if (start_level > end_level) start_level = end_level;
        } else if (start_level < end_level) start_level = end_level;
        write_dac_palette(palette_bytes, palette_fade_first_index, palette_fade_end_index, start_level);
        for (delay_index = 0; delay_index < palette_fade_delay_ticks; delay_index++) wait_for_tick(0);
    } while (start_level != end_level);
}

void read_vga_palette(unsigned char *palette_bytes) {
    int color_index;
    int component_index;
    for (color_index = 0; color_index < VGA_DAC_COLOR_COUNT; color_index++) {
        outp(VGA_DAC_READ_INDEX_PORT, color_index);
        for (component_index = 0; component_index < VGA_DAC_COMPONENT_COUNT; component_index++) *palette_bytes++ = (unsigned char)inp(VGA_DAC_DATA_PORT);
    }
    vga_palette_saved = -1;
}

void apply_saved_palette_once(void * palette_bytes) {
    if (vga_palette_saved == -1) {
        write_vga_palette(palette_bytes);
        vga_palette_saved = 1;
    }
}

void write_vga_palette(void * palette_bytes) {
    write_dac_palette(palette_bytes, 0, VGA_DAC_COLOR_COUNT, 0);
}

void clear_vga_palette(void) {
    int i;
    for (i = 0; i < VGA_DAC_COLOR_COUNT; i++) set_vga_palette_rgb((unsigned char)i, 0, 0, 0);
}

void set_vga_palette_rgb(unsigned char color_index, unsigned char red, unsigned char green, unsigned char blue) {
    outp(VGA_DAC_WRITE_INDEX_PORT, color_index);
    outp(VGA_DAC_DATA_PORT, red);
    outp(VGA_DAC_DATA_PORT, green);
    outp(VGA_DAC_DATA_PORT, blue);
}
