/* TU write_vga_mode_register..set_pal_rgb [0xe9dd, 0xed38): generated by tools/tu.py */
#pragma aux timer_interrupt_record "g_756f";
#include <i86.h>
#include <stdlib.h>
struct VideoMode { int mode_id; short bios_mode; short reserved; union { int dword; short word; unsigned char bytes[4]; } video_mode; unsigned char mode_flags; unsigned char mode_class; int width; int height; int row_bytes; int image_size; int buffer_size; };
struct DisplayModeInfo { short state; unsigned char page_base[16]; int page_start[4]; int page_display[4]; unsigned char page_class[4]; int buffer_size; int scanline_bytes; int page_height; int screen_width; int screen_height; int view_left; int view_top; int view_right; int view_bottom; unsigned char mode_flags; unsigned char saved_reg_1; unsigned char saved_reg_2; unsigned char bios_mode; unsigned char original_mode; unsigned char saved_reg_3; unsigned char current_reg_1; unsigned char current_reg_2; unsigned char current_reg_3; unsigned char tail; };
struct VgaRegisterPreset { unsigned char flags; unsigned char reserved[3]; unsigned char regs[48]; int mode_id; };
extern struct DisplayModeInfo vga_state;
extern short bios_video_mode_saved;
extern short video_restore_registered;
extern void f_9afc(void);
extern void f_9b44(int);
extern void restore_bios(void);
void save_bios(void);
extern short timer_interrupt_record;
extern struct VideoMode video_mode_table[];
extern struct VgaRegisterPreset vga_register_presets[];
extern int clear_video_bytes_entry(int, int);
extern void set_vga_memory_layout(int);
void restore_vga_register_preset(unsigned char *p);
extern void initialize_vga_map_mask(void);
extern void set_draw_page(short);
extern void clear_pal(void);
extern short vga_register_state_saved;
extern void _disable(void);
extern void _enable(void);
extern int update_crtc_register(unsigned char, unsigned char, unsigned char);
extern int old_display_mode;
extern int fill_clipped_vga_rectangle();
extern short disp_idx;
extern short draw_idx;
extern void set_vga_display_start(int);
extern void advance_video_page_indices(void);
extern int vga_crtc_offset;
extern int update_attr_register(unsigned char, unsigned char, unsigned char);
extern void outpw(int, int);
extern void write_dac_palette(void *, int, int, int);
extern void f_9d40(short);
extern int outp(int, int);
extern int inp(int);
extern void write_pal(void *);
extern void set_pal_rgb(unsigned char, unsigned char, unsigned char, unsigned char);
extern short flip_src;
extern short flip_dst;
int set_display_mode(int requested_mode_id);
void save_vga_state(void);
void restore_vga_register_state(void);
void set_video_viewport(int left, int top, int right, int bottom);
void set_video_display_address(int a, int b);
void set_vga_horizontal_panning(int pixel_pan);
void set_vga_horizontal_pan_register(unsigned char pixel_pan);
void set_vga_scanline_stride(int scanline_bytes);
void write_vga_mode_register(unsigned char mode_register_value);
void set_vga_line_compare(int scanline);
void set_vga_max_scan_line(unsigned char maximum_scanline);
void fade_pal(void *a, int x, int y, int step);
void read_vga_palette(unsigned char *p);
void apply_saved_palette_once(void *palette_bytes);
void show_page(void);
void display_next_video_page(void);
void draw_page(int page_index);
extern short g_7afe;
extern short page2;
extern short page3;
extern short g_7b1c;
extern short g_7b1e;
extern short video_page_2_index;
extern short vp3idx;

/* _DATA [0x7b04,0x7b14) */
int fade_start = 0;
int fade_end = 0x100;
int fade_delay = 1;
short vga_palette_saved = 0;
short g_7b12 = 0;

void write_vga_mode_register(unsigned char mode_register_value) {
    update_crtc_register(0x17, 0, mode_register_value);
}

void set_vga_line_compare(int scanline) {
    update_crtc_register(0x18, 0, (unsigned char)scanline);
    update_crtc_register(7, 0xef, (scanline & 0x100) >> 4);
    update_crtc_register(9, 0xbf, (scanline & 0x200) >> 3);
}

void set_vga_max_scan_line(unsigned char maximum_scanline) {
    update_crtc_register(9, 0xe0, maximum_scanline & 0x1f);
}

void fade_pal(void * palette_bytes, int start_level, int end_level, int fade_step) {
    int delay_index;
    if (start_level < -63) start_level = -63;
    if (start_level > 63) start_level = 63;
    if (end_level < -63) end_level = -63;
    if (end_level > 63) end_level = 63;
    if (fade_start < 0) fade_start = 0;
    if (fade_start > 255) fade_start = 255;
    if (fade_end < 1) fade_end = 1;
    if (fade_end > 256) fade_end = 256;
    if (!fade_step) {
        if (end_level - start_level > 0) fade_step = 1;
        else fade_step = -1;
    }
    do {
        start_level += fade_step;
        if (fade_step > 0) {
            if (start_level > end_level) start_level = end_level;
        } else if (start_level < end_level) start_level = end_level;
        write_dac_palette(palette_bytes, fade_start, fade_end, start_level);
        for (delay_index = 0; delay_index < fade_delay; delay_index++) f_9d40(0);
    } while (start_level != end_level);
}

void read_vga_palette(unsigned char *palette_bytes) {
    int color_index;
    int component_index;
    for (color_index = 0; color_index < 0x100; color_index++) {
        outp(0x3c7, color_index);
        for (component_index = 0; component_index < 3; component_index++) *palette_bytes++ = (unsigned char)inp(0x3c9);
    }
    vga_palette_saved = -1;
}

void apply_saved_palette_once(void * palette_bytes) {
    if (vga_palette_saved == -1) {
        write_pal(palette_bytes);
        vga_palette_saved = 1;
    }
}

void write_pal(void * palette_bytes) {
    write_dac_palette(palette_bytes, 0, 0x100, 0);
}

void clear_pal(void) {
    int i;
    for (i = 0; i < 0x100; i++) set_pal_rgb((unsigned char)i, 0, 0, 0);
}

void set_pal_rgb(unsigned char color_index, unsigned char red, unsigned char green, unsigned char blue) {
    outp(0x3c8, color_index);
    outp(0x3c9, red);
    outp(0x3c9, green);
    outp(0x3c9, blue);
}
